### DISCUSSION TITLE
How to handle multiple sources at once?

### DISCUSSION THREAD

**Discussion by eitsupi** [go-task/task#1009] [Q&A] [answered]
I am using the following Taskfile, but there are several tasks that refer to partially overlapping sources, and I felt it would be useful to be able to specify multiple sources at once.
Do you have any recommendations for such a case?

https://github.com/eitsupi/prqlr/blob/cade3aa1a8cd4c5b1a39b3ea38aea4d95d9e1fdc/Taskfile.yml#L42-L67

```yml
  test-source:
    sources:
      - tests/**/*
      - R/*
      - src/Makevars*
      - src/rust/Cargo.toml
      - src/rust/src/**/*.rs

  test-vignettes:
    sources:
      - vignettes/**/*.Rmd
      - R/*
      - src/Makevars*
      - src/rust/Cargo.toml
      - src/rust/src/**/*.rs
```

I would like to define `R/*`, `src/Makevars*`, `src/rust/Cargo.toml`, `src/rust/src/**/*.rs` somewhere and designate it collectively.
