### DISCUSSION TITLE
executable file not found in $PATH

### DISCUSSION THREAD

**Discussion by Drallas** [go-task/task#1016] [Q&A] [answered]
When I try to run functions I created in my .zshrc 
`task: [test:testfunc] run_test_func`

I see an "executable file not found in $PATH" message.

How can i call those custom functions from Taskfile?

**Comment by pd93** [comment, marked as answer]
Task does not use your local shell to run commands (It uses `gosh` from [mvdan/sh](https://github.com/mvdan/sh)), so your `.profile`, `.bashrc`, `.zshrc` etc files are not being read. This means that your `$PATH` is not being set and your custom functions are not available.

You have a couple of options to make this work. The simplest is probably to invoke your shell (the one your functions are defined in). You can do this by running your command like this:

```yaml
tasks:
  default:
    cmds:
      - zsh -c "my_custom_function" # <--- replace 'zsh` with your shell
```

However, this isn't very portable. If you're writing a project that will be used by other users on different machines, then you might want to include the custom function as a script inside your project and invoke it directly:

```yaml
tasks:
  default:
    cmds:
      - ./scripts/my_custom_script.zsh
```
