### DISCUSSION TITLE
How to do recursive sources?

### DISCUSSION THREAD

**Discussion by GandelXIV** [go-task/task#1017] [Q&A] [answered]
I have been using task as the build system for a project, and i want to create a task that depends on multiple directories and all the files in them. However, listing all the directories requires a lot of work. Another issue with this approach is that if new directories are added and i do not update the task sources, then incorrect builds may happen. In make, i would do something like [this](https://stackoverflow.com/questions/17279220/make-recursive-dependencies).

**Comment by andreynering** [comment, marked as answer]
Hi @GandelXIV,

Can you explain a bit more what you have in mind?

It's already possible to define multiple sources and having full directories as sources using double star (`**`).

```yaml
version: '2'

tasks:
  default:
    sources:
      - src/**/*.js
      - foo/bar/**/*.rb
```
