### DISCUSSION TITLE
How do you check if a command exists on windows?

### DISCUSSION THREAD

**Discussion by sanzoghenzo** [go-task/task#1019] [Q&A] [answered]
Hi there, first of all thanks for this wonderful tool!

I'm mostly a linux user, but some of my colleagues prefer to work on windows, so I'm trying to keep my tools as cross-platform as possible.

I would like to add a `status` check to skip the installation of tools already present (in my specific case they are python packages, but it can be anything).

How do you check if a command already exists on windows/powershell?

I tried to use `Get-Command {{.COMMAND_NAME}}` but it always executes the task.
I also tried something more fancy such as `if(Get-Command {{.COMMAND_NAME}}) {Exit 0} else {Exit 1}`, same result.

Am I missing something here?

Here is a minimal example:

```yaml
version: '3'

tasks:
  install:package:
    label: 'install:{{.PACKAGE_NAME}}'
    vars:
      PACKAGE_NAME: '{{.PACKAGE_NAME}}'
      COMMAND_NAME: '{{default .PACKAGE_NAME .COMMAND_NAME}}'
    cmds:
      - "pip install {{.PACKAGE_NAME}}"
    status:
      - '{{if eq OS "windows"}}if(Get-Command {{.COMMAND_NAME}}) {Exit 0} else {Exit 1}{{else}}command -v {{.COMMAND_NAME}}{{end}}'

  install:pre-commit:
    cmds:
      - task: install:package
        vars:
          PACKAGE_NAME: pre-commit

  init:pre-commit:
    deps:
      - install:pre-commit
    cmds:
      - pre-commit install

  lint:
    deps:
      - init:pre-commit
    cmds:
      - pre-commit run --all
```
