### DISCUSSION TITLE
Interactive variables

### DISCUSSION THREAD

**Discussion by mochja** [go-task/task#1033] [Ideas]
Hello,

was there some though on interactive variables?

Basically after running `task`, user would be prompted for input. I found a solution to use which involves redirection of stdio.

I am trying to use [dialog](https://linux.die.net/man/1/dialog) to let user choose from couple options. Same can be reproduced with read.

```yaml
version: '3'

tasks:
  default:
    cmds:
      - echo "{{.FOO}}"
    vars:
      FOO:
        sh: |
          dialog --clear --default-item 2 --checklist "Select:" 0 0 5 1 "First element" off 2 "Second element" off 3 "Third element" off 2>&1 > /dev/stdout < /dev/stdin
```

Which shows (after running `task`):

![image](https://user-images.githubusercontent.com/1218946/222539009-97beccd4-792a-428f-9825-b05e124a937d.png)

and correctly sets  the value:

![image](https://user-images.githubusercontent.com/1218946/222539082-ba22763b-afd1-4a6a-8fe2-16bfeddc2a81.png)

----

Example with `read`:

```yaml
version: '3'

tasks:
  default:
    cmds:
      - echo "{{.FOO}}"
    vars:
      FOO:
        sh: |
          read -p "Continue? (Y/N): " confirm < /dev/stdin > /dev/stdout
          echo $confirm
```

I could imagine `interactive` attribute for variables too:

```yaml

vars:
  FOO:
    sh: ....
    interactive: true
```

What do you think?

**Comment by pd93** [comment]
@mochja Does something about the examples you've posted not work? I'm not sure what the benefit would be to add this functionality directly into Task when it can already be done by using `read` or `dialog` today.

My general attitude towards this sort of thing is that we should leave jobs like this to the tools that are designed to do it, rather than reimplementing existing code into Task. This has the benefit of allowing the user to chose which tool they want to use rather than us making assumptions about how they want to do it.

**Reply by mochja** [reply]
@pd93 they do work.

I am not looking for dialog or read replacement, I would just like to have the commands (within the variables) interactive without the explicit need to redirect the I/O.

For example:

This does not work.

```yaml
vars:
  FOO:
    sh: |
      read -p "Continue? (Y/N): " confirm; echo $confirm
    # interactive: true # (we could add this to make it work)
```

**Comment by marcaurele** [comment]
How would you do this to use a return value but in the middle of a list of commands to execute sequentially? Like you would need to select a value from a list of values coming from a previous command.

```yml
version: '3'

tasks:
  default:
    cmds:
      - echo "Do something"
      - echo "Fetch all options"
      - echo "Select one of the options"
      - echo "Perform an action with the selected option"
```
