### DISCUSSION TITLE
Problem with includes

### DISCUSSION THREAD

**Discussion by mvuidev** [go-task/task#1069] [Q&A]
Hi,

I have a problem including another taskfile.

The following example is working : 

```yaml
version: '3'

includes:
    init: ./init.yaml

tasks:
    default:
        silent: true
        cmds:
            -   task: init
```

But with this one : 

```yaml
version: '3'

includes:
    init:
        taskfile: ./init.yaml
        internal: true

tasks:
    default:
        silent: true
        cmds:
            -   task: init
```

I get : 

```bash
# task -v
task: "default" started
task: Failed to run task "default": 1:39: & is not a valid word
```

Here is the init.yaml : 

```yaml
version: '3'

tasks:
    default:
        cmds:
            - echo "Hello"
```

Any idea ? Thank you.

Task version: v3.22.0
