### DISCUSSION TITLE
Is there something like automatic variables like gnu make to avoid repetition?

### DISCUSSION THREAD

**Discussion by stephane-archer** [go-task/task#1083] [Q&A]
Is there something like automatic variables like gnu make to avoid repetition like the following task?
```
toto.txt:
    cmds:
      - cp tata.txt toto.txt
    sources:
      - tata.txt
    generates:
      - toto.txt
```
see gnu make doc: https://www.gnu.org/software/make/manual/html_node/Automatic-Variables.html
