### DISCUSSION TITLE
Help with `status` command for a docker container running working, but not command in `preconditions`

### DISCUSSION THREAD

**Discussion by alistaircol** [go-task/task#1159] [Q&A]
I have an issue which I can't figure out.

I want to add a precondition to assert that a docker container is running for a task.

```yaml
---
version: 3

tasks:
  docker_shell:
    desc: Get into a local PHP container
    interactive: true
    silent: false
    preconditions:
    - sh: |
        docker-compose -f "{{.USER_WORKING_DIR}}/docker-compose.yml" exec php true > /dev/null 2>&1
      msg: "php container not running"
    cmds:
    - cmd: |
        docker-compose -f "{{.USER_WORKING_DIR}}/docker-compose.yml" exec php bash
```

I have a `docker-compose.yml` file with a service `php` which has `bash` installed.

The precondition should pass in my tests. The command is output correctly, the [special variable](https://taskfile.dev/api/#special-variables) `{{.USER_WORKING_DIR}}` is interpolated correctly. When I run the command separately, it exits with 0, i.e. success.

```text
$ docker compose ps php --format=json | jq '.[0].State'
"running"
```

```text
$ task docker_shell
task: php container not running
task: precondition not met
```

Changing the `preconditions` to assert the user working directory is usable in the precondition:

```diff
-echo "docker-compose -f "{{.USER_WORKING_DIR}}/docker-compose.yml" exec php true > /dev/null 2>&1" > blah.txt
+echo "docker-compose -f "{{.USER_WORKING_DIR}}/docker-compose.yml" exec php true > /dev/null 2>&1"
```

`blah.txt` has the working directory correctly in the command.

When I run the command from the file

```text
$ docker-compose -f /absolute/path/docker-compose.yml exec php true > /dev/null 2>&1
$ echo $?
0
```

The quotes around the `-f` option are removed, but absolute path in my case doesn't have any whitespace/special characters so that isn't an issue.

---

When I use `status` instead of `preconditions` it will run the task.

```yaml
    status:
    - |
      docker-compose -f "{{.USER_WORKING_DIR}}/docker-compose.yml" exec php true > /dev/null 2>&1
```

My question is why does it not pass with it as an item in the `preconditions`?
