### DISCUSSION TITLE
[Feature Request] Global dependency

### DISCUSSION THREAD

**Discussion by paulo-raca** [go-task/task#1160] [Ideas]
Hello, and thanks for this great project.

My current project has a lot of different tasks, and all of them depend on some common setup action/checks, like "checking that required tools are installed", etc. E.g., 

```
tasks:
  verify_tools:
    preconditions:
      - sh: "command -v docker"
        msg: |
          You don't have docker installed.
          Please check https://docs.docker.com/engine/install/
```

Instead of adding this as a dependency everywhere (easy to forget), It would be nice if we could mark it as global dependency, either using a special task name or a flag.

```
setup_task: verify_tools```

```
tasks:
  _setup_:  # Special task name
    deps: [verify_tools]
```
