### DISCUSSION TITLE
Executing multiple tasks by using wildcard in the task name

### DISCUSSION THREAD

**Discussion by pioio** [go-task/task#1167] [Ideas]
Allow executing the tasks by a wildcard:

```
tasks:
  build:
    cmds:
      - ...

  test-units:
    cmds: 
      - ...
      - ...

  test-integration-a
    cmds:
      - ...
      - ...

  test-integration-b
    cmds:
      - ...
      - ...

  all-tests:
    cmds:
      - task: test-*   # run all tasks matching this wildcard in order in which they are defined
```

This would make it easier to maintain large taskfiles. As adding/removing/renaming a task in one place would not require remembering to update the file in possibly several other places (which is a common error one can make right now).

Also, we should support this on the CLI, e.g.
`$ task build 'test-integration-*'`
