### DISCUSSION TITLE
Looping over tasks with different environment

### DISCUSSION THREAD

**Discussion by ms1331** [go-task/task#1176] [Q&A]
I want to loop over an internal task, setting a different environment every time, but I cannot get it to work. This is my taskfile:

```
version: '3'
vars:
  list: 'one two'

tasks:
  print:
    silent: true
    cmds:
      - |
        echo "{{.VAR}}"
    vars:
      VAR: '{{default "default" .VAR}}'

  works:
    silent: true
    cmds:
      - |
        {{range $i := splitList " " .list}}
        go-task print VAR={{$i}}
        {{end}}

  doesnt-work:
    deps:
      - |
        {{range $i := splitList " " .list}}
        task: print
        vars: { VAR: {{$i}} }
        {{end}
```
and when I run it it produces the following:

```
m93p% go-task print
default
m93p% go-task works
one
two
m93p% go-task doesnt-work
task: Task "\ntask: print \nvars: { VAR: one }\n\ntask: print \nvars: { VAR: two }\n\n" does not exist
task: Task "\ntask: print \nvars: { VAR: one }\n\ntask: print \nvars: { VAR: two }\n\n" does not exist
```

If I set the `print` task to be `internal: true`, the `works` task will stop working. If anyone has ideas on how to implement that, I'd love to see them. Thanks!

EDIT:
I am using this version:
```
m93p% apk info go-task
go-task-3.24.0-r1
```
on Alpine Linux if that matters...
