### DISCUSSION TITLE
Dynamic includes

### DISCUSSION THREAD

**Discussion by Subbeh** [go-task/task#1304] [Q&A]
Hi,

I'm trying to dynamically include taskfiles based on the project directory I'm in.

Let's say I have a directory structure as follows:

```
.
├── pkglist.txt
├── Taskfile.yml
├── test-1
│   ├── pkglist.txt
│   └── .taskfiles
│       └── main.yml
└── test-2
    ├── pkglist.txt
    └── .taskfiles
        └── main.yml
```

If I'm in the `test-1` directory I would like to have only the `main.yml` taskfile from that directory included (and similarly for the `test-2` directory)

I have a Taskfile as follows:

```yaml
---
version: "3"

env:
  DIR: |-
    {{ if ne .USER_WORKING_DIR .ROOT_DIR }}{{ (index (.USER_WORKING_DIR | replace .ROOT_DIR "" | splitList "/") 1) }}{{end}}

includes:
  env:
    taskfile: "{{.DIR}}/.taskfiles/main.yml"
    optional: true
    aliases: ["{{.DIR}}"]

tasks:
  default:
    desc: List tasks
    cmds:
      - go-task --list-all

  init:
    cmds:
      - cat pkglist.txt ${DIR:+$DIR/pkglist.txt} ### just testing using cat

  foo:
    cmds:
      - echo $DIR
```

and the following package files:

```bash
$ cat pkglist.txt
test
$ cat test-1/pkglist.txt
test-1
$ cat test-2/pkglist.txt
test-2
```

In the example above, if I'm anywhere in the `test-1` directory, I would like to only install the packages defined in `pkglist.txt` and `./test-1/pkglist.txt`

This part seems to work as expected:

```bash
./test $ task init
task: [init] cat pkglist.txt ${DIR:+$DIR/pkglist.txt}
test
./test $ cd test-1
./test/test-1 $ task init
task: [init] cat pkglist.txt ${DIR:+$DIR/pkglist.txt}
test
test-1
./test/test-1 $ cd ../test-2
./test/test-2 $ task init
task: [init] cat pkglist.txt ${DIR:+$DIR/pkglist.txt}
test
test-2
```

The problem now is that none of the tasks from `test-2` are included:

```bash
$ cat test-1/.taskfiles/main.yml
---
version: "3"

tasks:
  bar:
    cmds:
      - echo $PWD

$ task
task: [default] go-task --list-all
task: Available tasks for this project:
* default:       List tasks
* foo:
* init:
```

Am I in the right direction, or is this not something that's possible and not designed to be done with go-task?

Please note that this is an oversimplified solution -- the goal is to have project specific taskfiles that share a collection of base tasks from the root.
