### DISCUSSION TITLE
Is there any way to get the name we assign to the included Taskfile?

### DISCUSSION THREAD

**Discussion by Leila-ad** [go-task/task#1320] [Q&A]
for example => 

```
includes:
  first:
    task: Taskfile.yml
  second:
    task: Taskfile-sec.yml
```
    
I am trying to get the names "**first**" and "**second**"
