### DISCUSSION TITLE
Displaying the output of `status`

### DISCUSSION THREAD

**Discussion by dcopso** [go-task/task#1340] [Q&A]
Given the following Taskfile:
```yaml
version: '3'

tasks:
  go:
    cmds:
      - mkdir directory
    status:
      - echo hello
      - test -d directory
```

These are the two output scenarios:
```shell
$ task go
task: [go] mkdir directory
$ task go
task: Task "go" is up to date
```

Notably, unlike other `cmds` specified in a task, the status commands are not printed to the screen. I find this surprising, because often the output is informative.

Is there a way to ask task to display the output of status-check commands?

Thanks!
