### DISCUSSION TITLE
How to run two parallel "watch" type tasks?

### DISCUSSION THREAD

**Discussion by danawoodman** [go-task/task#1353] [Q&A] [answered]
I would like to run two tasks, `npm run dev` (which just runs TailwindCSS in watch mode) and `go run .` in parallel.

The `npm run dev` command automatically watches for changes so I just need it to stay running till exit.

The `go run .` needs to re-run when a `**/*.go` and `templates/**/*.html` have changed (saved). I've played with a few things but I can't grok what the correct approach is after reading the docs/scanning Github.

Is this type of arrangement possible?

Right now I'm running [`gow`](https://github.com/mitranim/gow/) to do `gow run .` which works but I'm wondering if this behavior can be accomplished with just Task?

**Comment by andreynering** [comment, marked as answer]
Hi @danawoodman,

You might want to take a look at #1361 when released. You'll be able to specify specific tasks to be watch, and the `--watch` task can be skipped.

**Reply by danawoodman** [reply]
Perhaps you can point me in the right direction here @andreynering?

It seems the dev-server task isn't being killed when re-running.

I don't see anything in the docs about how to have a running/watched task kill when re-running the task.

```yml
version: "3"

tasks:
  default:
    deps: [dev]

  dev:
    deps: [dev-assets, dev-server]

  dev-server:
    cmds:
      - go run .
    watch: true
    sources: [./**/*.go]
    method: none

  dev-assets:
    cmds:
      - bun dev
    watch: true
```

![image](https://github.com/go-task/task/assets/157695/14ab5fbf-9b73-4a57-a486-d7b6b2ee299f)

**Comment by quinn** [comment]
I'm having trouble getting this to work. For example:

```yaml
version: '3'

tasks:
  one:
    watch: true
    sources:
      - one.txt
    cmds:
      - figlet One
  two:
    watch: true
    sources:
      - two.txt
    cmds:
      - figlet Two
  three:
    cmds:
      - tailwindcss --watch -o test.css
```

I run:
```
task -p one two three
task: [three] tailwindcss --watch -o test.css

Rebuilding...

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration

Done in 93ms.
```

Only tailwind is executed. without three:

```
rm -rfv .task ; task -p one two
```
```
removed '.task/checksum/one'
removed '.task/checksum/two'
removed directory '.task/checksum'
removed directory '.task'
task: Started watching for tasks: one, two
task: [two] figlet Two
task: [one] figlet One
  ___             
 _____               
 / _ \ _ __   ___ 
|_   _|_      _____  
| | | | '_ \ / _ \
  | | \ \ /\ / / _ \ 
| |_| | | | |  __/
  | |  \ V  V / (_) |
 \___/|_| |_|\___|
  |_|   \_/\_/ \___/ 
```

Then, if I modify the sources:

```
echo bump > two.txt
```
```
task: Task "one" is up to date
task: [two] figlet Two
 _____               
|_   _|_      _____  
  | | \ \ /\ / / _ \ 
  | |  \ V  V / (_) |
  |_|   \_/\_/ \___/ 
```
It works more closely to what I would expect.

**Comment by singh-inder** [comment]
You can also use [concurrently](https://www.npmjs.com/package/concurrently)

```yaml
tasks:
  dev:
    cmd: concurrently "air -c .air.toml" "npx tailwindcss -i ./assets/input.css -o ./assets/tw.css --watch"
```
