### DISCUSSION TITLE
How to pass argument and value from the terminal ?

### DISCUSSION THREAD

**Discussion by khanakia** [go-task/task#1392] [Q&A]
```yaml
print:
      cmds:
        - echo "{{.NAME}}"
      vars:
        NAME: Hello!
```

How do i pass the name from the terminal like this or something similar ?
```sh
task print --name=test
```
