### DISCUSSION TITLE
How to make sub-command descriptions in task summary more useful?

### DISCUSSION THREAD

**Discussion by vctls** [go-task/task#1398] [Q&A]
I use `{{.CLI_ARGS}}` and other variables a lot in order to compose tasks while retaining the ability to run parent tasks with custom arguments.  
Sometimes a task will call another task multiple times with different variables. I use `for` loops now and then too.  
But when displaying the summary, the variables are not shown in the commands list. For example:
```yaml
vars:
  DATABASES: main job_processing key_value_store authn
tasks:
  db.dump:
    desc: "Dump the databases to a set of SQL files."
    summary: |-
      Dump the databases to a set of SQL files.
      Use the variable NAME to prefix the dump filenames.
    cmds:
      - for: { var: DATABASES }
        task: db.pg_dump
        vars:
          DB: '{{.ITEM}}'
          # language=sh
          FILE: '> .tmp/{{.NAME | default "db_dump" }}.{{.ITEM}}.sql'
```
results in
```
❯ task --summary db.dump
task: db.dump

Dump the databases to a set of SQL files.
Use the variable NAME to prefix the dump filenames.

commands:
 - Task: db.pg_dump
 - Task: db.pg_dump
 - Task: db.pg_dump
 - Task: db.pg_dump
 ```
Knowing that this tasks call the tasks for `pg_dump` four times is not very useful.
Am I composing my tasks wrong?  
Or should there be some way of printing more context about the commands being called?
