### DISCUSSION TITLE
A before all task type/label

### DISCUSSION THREAD

**Discussion by lc3r** [go-task/task#1409] [Ideas]
Hi and great job!

Apologies if this idea has already been proposed. I looked for it but I could not find any similar reference.

Would it be possible to have a special kind of task that always runs once before all other tasks in the the same taskfile, meaning without being explicitly called or stated as dependency? Similar to what happens with unit-testing frameworks `beforAllClass()`

Example:

```yaml

version: '3'

tasks:
  my-task1:
    desc: Run some dev task
    cmds:
      - ...
  
  my-task2:
    desc: Run some other dev task
    cmds:
      - ...
 
  my-task3:
    desc: Run some other dev task
    deps:
       - task: my-task1
    cmds:
      - ...

  before-all:
    desc: Runs once before any other task in the same taskfile without being explicitly called or stated as deps.
    run: once_before
    cmds:
      - check1
      - check2
      - ...
```

In the example above, `before-all` is like any other task except that it is labelled as `run: once_before` meaning that this will always run once each time one or more tasks in the same file are invoked:

```sh
task my-task1 # runs before-all and then my-task1
task my-task2 # runs before-all and then my-task2
task my-task3 # runs before-all, my-task1 (deps), my-task3 
```

I understand there are ways to achieve this but AFAIK, they lead to a lot more code: constant explicit dependencies, convoluted global dynamic vars.

A valid constrain could be that only one task per taskfile can be labelled as `run: before_all`

Obviously this may pave that way for other similar semantics: `before_any`, `after_all`, `after_any`.

Why this can be useful? Simplifying taskfile development, better standalone taskfiles, concentrating all checks in a single place so to enforce system-wide preconditions without duplicating code.

Happy to discuss more if you think this is useful/doable.
Thank you.
