### DISCUSSION TITLE
Merge environment vars for "wrapped" tasks

### DISCUSSION THREAD

**Discussion by audunmo** [go-task/task#1416] [Ideas]
Say I have a taskfile like:

```yaml
tasks:
  run:
    cmds:
      - env
    env:
      FOO: "bar"
  run:experimental
     cmds:
        - task: run
     env:
       EXPERIMENTAL: true
```

I'd want running `task run:experimental` to give the output:
```
...other env vars
FOO="bar"
EXPERIMENTAL=true
...other env vars
```

This is useful if you have a significant about of env vars, but want to override one or two for a particular case. Right now, the env from `run:experimental` is not inherited by the wrapped task
