### DISCUSSION TITLE
What if `method` is set to `timestamp` without specifying `generates`?

### DISCUSSION THREAD

**Discussion by your-diary** [go-task/task#1425] [Q&A]
According to [the API documentation](https://taskfile.dev/api/), `method` is described as

> Defines which method is used to check the task is up-to-date. `timestamp` will compare the timestamp of the `sources` and `generates` files.

It isn't clear what will happen when you don't explicitly specify `generates`.

**Comment by andreynering** [comment]
Hi @your-diary,

With `method: timestamp`, `generates` is required for it to work, because Task needs to know with files compare `sources` to. If not informed, it is a NO-OP: the task will always run.

**Reply by your-diary** [reply]
Thank you for your comment.

> If not informed, it is a NO-OP: the task will always run.

Really?
I tried the YAML below and the task did NOT always run.

```yaml
version: "3"

tasks:
    build:
        sources:
            - "**/*.go"
        method: timestamp
        cmds:
            - go build
```
