### DISCUSSION TITLE
Run shared dependency only once

### DISCUSSION THREAD

**Discussion by tennox** [go-task/task#1442] [Ideas]
I have this kind of task setup:
```yaml
tasks:
    build:
        deps: [pnpm-install, generate-pwa-icons]
        cmds:
            - pnpm build
    pnpm-install:
        cmds:
            - pnpm install
    generate-pwa-icons:
        deps: [pnpm-install]
        cmds:
            - pnpm pwa-assets-generator
```

I would expect `pnpm-install` to only run once, but it runs in parallel, and breaks because it doesn't support that:
```
❯ task build
task: [pnpm-install] pnpm install
task: [pnpm-install] pnpm install
Scope: all 11 workspace projects
Scope: all 11 workspace projects
 ENOENT  ENOENT: no such file or directory, unlink '/home/manu/dev/tam/wovin/node_modules/.pnpm/node_modules/concurrently'


task: Failed to run task "pnpm-install": exit status 1
task: Failed to run task "pnpm-install": exit status 1
```

I get that running tasks in parallel makes sense, but I think if a dependency depends on the same task, it should only run that one once. :thinking:

**Comment by pd93** [comment]
Hi @tennox, you might want to look into the [`run` keyword](https://taskfile.dev/usage/#limiting-when-tasks-run). This will allow you to limit the number of a times a task can be run:

```yml
  pnpm-install:
    run: once
    cmds:
      - pnpm install
```
