### DISCUSSION TITLE
Clarifying `env` and `var` in Go-Task with Practical Examples

### DISCUSSION THREAD

**Discussion by bayeslearnerold** [go-task/task#1443] [General]
I've been exploring Go-Task and came across some intriguing aspects regarding `var` and `env`. Their usage and impact on task outputs seem nuanced, and I'd appreciate some community insights. Here's a sample YAML file for context:

```yaml
version: '3'

vars:
  CONFIG: '{{.CONFIG | default "Debug"}}'

tasks:
  foo:
    env:
      CONFIG: '{{.CONFIG}}'
    deps:
    - task: bar
    cmds:
    - echo $CONFIG Configuration for task foo
    - task: bar
    silent: true

  bar:
    env:
      CONFIG: '{{.CONFIG}}'
    cmds:
    - echo $CONFIG Configuration for task bar
    silent: true
```
The output: 
```
CONFIG=Release task -t testfile.yml  foo 
Release Configuration for task bar
Release Configuration for task foo
Release Configuration for task bar
```

Alongside understanding the output for this configuration, I have a few more queries:

1. **Are `env` and `var` treated the same in Go-Task, and what are their fundamental differences?**  
   It seems they are not identical and exist in different namespaces, similar to other programming languages.

2. **How does scoping work with Go-Task vars?**  
   Are they dynamically reevaluated like local variables in other languages?

3. **Are there different ways to pass `env`, and do they override global `env`?**  
   Do local `env` variables inherit global `env` values but override them in case of a conflict? So the local env doesn't have to define ALL `env` if you know it exists as a global `env`?

4. **How do we distinguish between `vars` and `env` in the provided script?**  
   What confuses me is that in the global `var` section, `{{.CONFIG}}` seems to be using an `env` for setting a regular `var`. Is this due to the precedence rule where it tries to find a `var` to use, but as a last resort, it will fetch an environment variable of the same name if it exists?

5. **Are local `env` variables reevaluated every time a task runs?**  
   When the task `bar` is invoked, is the `env` variable re-evaluated?

Could someone kindly provide insights or explanations on these points?  There are still many open issues involving env/var interactions such as #1276  #203
