### DISCUSSION TITLE
How can I refer to the last exit status in `defer`?

### DISCUSSION THREAD

**Discussion by your-diary** [go-task/task#1472] [Q&A] [answered]
Currently I have this `Taskfile.yaml`:

```yaml
version: "3"

tasks:
    check:
        cmds:
            - defer: echo 'done'
            - go build
            - go test ./...
```

`check` task does these:

1. Execute `go build`.
2. If success, then execute `go test ./...`.
3. Finally, independent of the success/failure status of `go build` and `go test ./...`, print `"done"`.

This works well but I want to change the body of `echo` according to the success/failure status of `go build` and `go test ./...`:

- If both succeeded, I want to set `"success"` as the body.
- Otherwise, I want to set `"failure"` as the body.

Here's the pseudo configuration:

```yaml
version: "3"

tasks:
    check:
        cmds:
            - defer:
                    - success: echo 'success'
                    - failure: echo 'failure'
            - go build
            - go test ./...
```

Is it possible to achieve that? If so, how?

(By the way, the configuration above is just a minimal example. In my real use-case, I want to execute more complicated commands in `defer`.)
