### DISCUSSION TITLE
How to run included dep only once

### DISCUSSION THREAD

**Discussion by maxmzkrcensys** [go-task/task#1497] [Q&A] [answered]
I'm currently working in a mono repo where we have taskfiles for the various tools/services/libs we have in the repo. At the top level we have a single taskfile that includes each of the taskfiles for the tools/services/libs so that we can run the tasks from the root of the monorepo. Some of the libs have common dependencies that are defined in the other task files. For example, we build a protoc plugin that needs to exist to build the libraries.

Here is an example similar to our setup
```yaml
./tools/input

./tools/taskfile.yml
version: "3"

tasks:
  exe:
    run: once
    sources:
      - ./input
    generates:
      - ./output
    cmds:
      - touch output

./lib/a/taskfile.yml
version: "3"

includes:
  tools:
    taskfile: ../../tools
    dir: ../../tools
    internal: true

tasks:
  lib:
    deps:
      - tools:exe
    cmds:
      - touch a

./lib/b/taskfile.yml
version: "3"

includes:
  tools:
    taskfile: ../../tools
    dir: ../../tools
    internal: true

tasks:
  lib:
    deps:
      - tools:exe
    cmds:
      - touch b

./taskfile.yml
version: "3"

tasks:
  all:
    deps:
      - a:lib
      - b:lib

includes:
  a:
    taskfile: ./lib/a
    dir: ./lib/a

  b:
    taskfile: ./lib/b
    dir: ./lib/b
```

When we want to build all the libraries, we run
```
task all
task: [b:tools:exe] touch output
task: [a:tools:exe] touch output
task: [a:lib] touch a
task: [b:lib] touch b
```

Which we can see builds the tool multiple times.

If I collapse the task files all down to a single file, I can get the single build of the tool
```yaml
version: "3"

tasks:
  tools:exe:
    run: once
    sources:
      - ./tools/input
    generates:
      - ./tools/output
    cmds:
      - touch ./tools/output

  a:lib:
    deps:
      - tools:exe
    cmds:
      - touch lib/a

  b:lib:
    deps:
      - tools:exe
    cmds:
      - touch lib/b

  all:
    deps:
      - a:lib
      - b:lib
```
```
task all                                                                               
task: [tools:exe] touch output
task: [b:lib] touch lib/b
task: [a:lib] touch lib/a
```

Is there a good way for us to get the best of both worlds? (The organization of multiple files but the single run of building the tool?)

**Comment by andreynering** [comment]
Hi @maxmzkrcensys,

Have you tried `run: once` to force tasks to run only once per `task` invocation?

https://taskfile.dev/usage/#limiting-when-tasks-run

**Reply by maxmzkrcensys** [reply]
Yup! The shared task is already including `run: once`
```yaml
tasks:
  exe:
    run: once
    sources:
      - ./input
    generates:
      - ./output
    cmds:
      - touch output
```
