### DISCUSSION TITLE
Transportable Cat?

### DISCUSSION THREAD

**Discussion by WesselAtWork** [go-task/task#1499] [Q&A] [answered]
Is there some kind of command that works on both `DOS` and `Linux` that can extract the contents of a file and put it into `stdout`?
`cat` is a no go as it's not available on DOS.

I needed to do some logic that boils down to: "If file exists, use it's contents, else, invoke one-ish time command to get value"

### Minimal mock

Breaks on `DOS`.

```yaml
some-task:
  desc: "Mock Minimal Cat"
  vars:
    MY_VALUE:
      sh: 'cat backup.txt || echo "my one-ish time command"'
  cmd: 
    - 'echo "{{.MY_VALUE}}" > backup.txt '
    - 'echo "{{.MY_VALUE}} -- command failure sim" && false' 
    - 'rm -f backup.txt'
```

**Comment by WesselAtWork** [comment]
## echo $(<)

`echo "$(<backup.txt)"`

---

Figured it out!

Becuase go-task uses [mvdan/sh](https://github.com/mvdan/sh) as it's command runner I just needed to use bashy contructs to get the file contents.

## My original problem

Sadly I cant do `echo "$(<backup.txt)" || echo "works"`, the bashism fails in the interpreter [  :(  ]

Needed to add a test:
```yaml
some-task:
  desc: "Mock Minimal Cat"
  vars:
    MY_VALUE:
      sh: '[ -f backup.txt ] && echo "$(<backup.txt)" || echo "my one-ish time command"'
  cmd: 
    - 'echo "{{.MY_VALUE}}" > backup.txt '
    - 'echo "{{.MY_VALUE}} -- command failure sim" && false' 
    - 'rm -f backup.txt'
```

**Reply by WesselAtWork** [reply]
Painfully there is no transportable `rm` [  >:(  ]

I'll keep this here for if to need to read a file, but I'm still figuring out if it's even possible to delete in the first place

**Reply by WesselAtWork** [reply]
Not as elegant as the `$(<)` solution but will get you there:
```yml
      - cmd: rm backup.txt
        ignore_error: true
      - cmd: cmd /c del backup.txt
        platform: ["windows"]
```
> `rm` should work on everything else

**Comment by WesselAtWork** [comment, marked as answer]
As of August 2025 we have fake gnu utils in DOS! 
https://taskfile.dev/blog/windows-core-utils
https://github.com/go-task/task/pull/2360

---

You can now just use it directly on DOS
```yaml
some-task:
    desc: "Mock Minimal Cat"
    vars:
      MY_VALUE:
        sh: '[ -f backup.txt ] && cat backup.txt || echo "my one-ish time command"'
    cmds:
      - cmd: 'echo "{{.MY_VALUE}}" > backup.txt '
      - cmd: 'cat backup.txt'
      - cmd: 'rm -f backup.txt'
```

You still need to do the test `[ -f backup.txt ]` because fake `cat` fails fatally when it can't access the file.
See https://github.com/go-task/task/issues/2466
