### DISCUSSION TITLE
Is there an idiomatic way to have a master/root taskfile for a monorepo?

### DISCUSSION THREAD

**Discussion by michaelCTS** [go-task/task#1517] [Q&A]
What I mean with this is having a taskfile that calls other taskfiles. Let's say I want to test an entire monorepo by running the tests in each project the repo contains.

At the moment, the only way I've found to do this is by finding sub directories with taskfiles and running task in those directories like so:

```yaml
tasks:
  run-sub:
    internal: true
    vars:
      args: '{{ default "" .args }}'
      folders: '{{ default "src" .folders }}'
    cmd: find
        {{ .folders }}
        -maxdepth 2
        -name Taskfile.yml
        -print
        -execdir task {{ .args }} \;
  test-sub:
    desc: Test all sub-projects (the project MUST be setup beforehand)
    summary: |
      Available targets are unit, integration, bdd.
      For example `task target=bdd test`
    vars:
      target: unit
    cmds:
      - task: run-sub
        vars:
          folders: src
          args: target={{ .target }} base:test
  test:
    desc: Test all sub-projects (the project MUST be setup beforehand)
    summary: |
      Available targets are unit, integration, bdd.
      For example `task target=bdd test`
    vars:
      target: unit
    cmds:
      - find
        src
        -maxdepth 2
        -name Taskfile.yml
        -print
        -execdir task target={{ .target }} base:test  \;
```

`test` works but copy pasting the cmd is not DRY. Trying to solve that with an internal task doesn't seem to work if vars have to be passed --> `task target=integration test-sub` still runs unit tests instead of integration tests:

```sh
ser@mikes-workstation:~/PycharmProjects/legacy-sync-service$ task target=integration test
task: [run-sub] find src -maxdepth 2 -name Taskfile.yml -print -execdir task target=unit base:test \;
src/subproject/Taskfile.yml
task: [base:test] poetry run pytest tests/unit
```

Have I missed an idiomatic way to do so in the documentation, issues or discussions?

**Comment by andreynering** [comment]
Hi @michaelCTS,

This is exactly what includes are for. Have you taken a look at it?

https://taskfile.dev/usage/#including-other-taskfiles

**Reply by michaelCTS** [reply]
There are multiple issues with that:

**includes get long**

```yaml
includes:
  A:
    taskfile: src/A
    dir: src/A
  B:
    taskfile: src/B
    dir: src/B
  # ...
  N:
    taskfile: src/N
    dir: src/N
```

**`--list` gets very long**

All the included tasks are in the list

**Calling the same task on all includes is explicit**

```yaml
tasks:
  setup:
    cmds:
     - task: "A:setup"
     - task: "B:setup"
     # ....
     - task: "N:setup"
```

---------

Is there some way to include using wildcards or glob? And is there a way to call tasks using a glob?

**Reply by andreynering** [reply]
It's not released yet, but wildcards is already implemented and will be released soon:

https://taskfile.dev/usage/#wildcard-arguments

There's no similar feature for includes, though.

I'd like to remind you that, regarding "`--list` is too long", you can workaround that by running `cd subdir/` and running that specific Taskfile. Included Taskfiles still work in a standalone way.

**Reply by vmaerten** [reply]
Hello @michaelCTS,

I encounter the same issue as you, I've partially resolved by doing this : 

```yml
includes:
  A:
    taskfile: src/A
    dir: src/A
  B:
    taskfile: src/B
    dir: src/B
  # ...
  N:
    taskfile: src/N
    dir: src/N
    
vars:
  ALL_PROJECTS: A B C D N


tasks:
  setup:
    cmds:
      - for: { var: ALL_PROJECTS }
        cmd: task {{.ITEM}}:setup
```

It simplify the tasks' part


@andreynering do you know when the next version will be released ? wildcard's feature is amazing and we can't wait to use it :fire: 
Thanks for your hard work with @pd93 on this project!
