### DISCUSSION TITLE
Support `cmds` in `for` loops

### DISCUSSION THREAD

**Discussion by simonrouse9461** [go-task/task#1543] [Ideas]
Currently, if I want to run multiple commands in a for loop, I have to define a separate task,
```yml
one-task:
  cmd:
    for: [a, b, c]
    var:
      VAR: {{.ITEM}}
    task: another-task

another-task:
  cmds:
    - echo {{.VAR}}
    - echo {{.VAR}}
```

However, sometimes it's not convenient and doesn't worth it to define a separate task for just a few commands. I would prefer something like this,
```yml
one-task:
  cmd:
    for: [a, b, c]
    cmds:
      - echo {{.ITEM}}
      - echo {{.ITEM}}
```

This makes for loops much easier to use. Is there any specific reason why this is not allowed?

**Comment by barrykaplan** [comment]
This would really clean up a lot boilerplate. Even better would be to support nested for. I have typical scenarios where I loop over ENVIRONMENTS, then TENANTS, then SECRETS. It works, but its a lot noise.

**Comment by polarathene** [comment]
You probably should communicate better why you need `cmds`? If you don't want to call other task you can use [`cmd` with your shell commands to run](https://taskfile.dev/usage/#looping-over-a-static-list) with each `for` item:

```yaml
version: '3'

tasks:
  one-task:
    cmd:
      for: [a, b, c]
      cmd: |
        echo {{.ITEM}} 1
        echo {{.ITEM}} 2
```

```console
$ go-task one-task
task: [one-task] echo a 1
echo a 2

a 1
a 2
task: [one-task] echo b 1
echo b 2

b 1
b 2
task: [one-task] echo c 1
echo c 2

c 1
c 2
```

The trick is the [YAML multi-line string feature](https://quickref.me/yaml.html) with `|`, the Task docs have a [similar example demonstrating it's usage for another use-case](https://taskfile.dev/faq/#i-cant-reuse-my-shell-in-a-tasks-commands).
