### DISCUSSION TITLE
Why dotenv files should be listed in reverse order to get expected result?

### DISCUSSION THREAD

**Discussion by vudaltsov** [go-task/task#1559] [Q&A]
```shell
# .env
A=1
```

```shell
# .env.local
A=2
```

```yaml
# Taskfile.yml
version: '3'

dotenv:
  - '.env'
  - '.env.local'

tasks:
  test: echo {{.A}}
```

`task test` outputs `1` instead of `2`. Isn't it counterintuitive that env variables from subsequent files do not override the ones from preceding? For instance, shell itself outputs `2` for `source .env && source .env.local && echo "$A"`.
