### DISCUSSION TITLE
Execute task from sibling task file

### DISCUSSION THREAD

**Discussion by konsalex** [go-task/task#1578] [Q&A] [answered]
Hey folks

I have the following task file
```
.
└── Taskfile.yml/
    ├── ssl/
    │   └── Taskfile.yml
    └── tests/
        └── Taskfile.yml
```

And I want to run `task test:run`

The issue is that this test depends on another task defined in `ssl` folder, called `generate`.

When I try to call this from `tests` it does not work. Is this feasible somehow?

```
# Example tests/Taskfile.yml
version: '3'

tasks:
  run:
    cmds:
      - task ssl:generate
```

```
# Example Taskfile.yml
version: '3'

includes:
  ssl:
    taskfile: ./ssl/Taskfile.yml
    dir: ./ssl
  tests:
    taskfile: ./tests/Taskfile.yml
    dir: ./tests
```

**Comment by konsalex** [comment]
Tried this also with `deps: ["ssl:generate"]` but gives me:

```
task: Task "test:ssl:generate" does not exist
```

**Reply by pd93** [reply, marked as answer]
Hey @konsalex, you can refer to the root Taskfile by prefixing a task name with `:`. From here, you can then give the include path to your SSL task. For example:

```yaml
# Example tests/Taskfile.yml
version: '3'

tasks:
  run:
    cmds:
      - task: :ssl:generate
```

---

This is briefly mentioned as a tip in [our docs](https://taskfile.dev/usage/#calling-another-task).

**Reply by pd93** [reply]
There is also no reason why you can't include the `ssh` Taskfile inside your `tests` Taskfile:

```yaml
# Example tests/Taskfile.yml
version: '3'

includes:
  ssl:
    taskfile: ../ssl/Taskfile.yml
    dir: ../ssl
    internal: true # stops these tasks from being directly callable on the CLI via `tests:ssl:generate`

tasks:
  run:
    cmds:
      - task: ssl:generate
```
