### DISCUSSION TITLE
Call directly a binary program in subdirectory

### DISCUSSION THREAD

**Discussion by GlassGruber** [go-task/task#1632] [Q&A]
I've tried the following but it results just in a "not found" message printed.

```yaml
version: '3'

tasks:
  run_program:
    cmds:
      - relative/path/subdirectory/binary.exe  'some argument'
```

Result
```plain
task.exe run_program
task: [run_program] relative/path/subdirectory/binary.exe  'some argument'
not found
task: Failed to run task "run_program": exit status 127
```

I've also tried editing PATH via env like suggested in https://github.com/go-task/task/issues/482
but no dice

```yaml
version: '3'

env:
  PATH: '{{joinPath .TASKFILE_DIR "relative" "path" "subdirectory"}};{{.PATH}}'


tasks:
  run_program:
    cmds:
       - echo {{.PATH}}
       - binary.exe  'some argument'
```

Result with modified PATH below, looks like it's ignored but the echoed path is correct.

```text
task.exe run_program
task: [run_program] binary.exe  'some argument'
"binary.exe": executable file not found in $PATH
[... big echoed path ...]
```

I'm on a Windows machine.

What am I missing?

I hope it's not a RTFM issue, thank you for your time!

**Comment by trulede** [comment]
First, the error message is correct, so you have a few possibilities: the relative path is wrong, the executable is missing ... so run the command manually, echo the working dir to check its what you think, 'ls' the contents of the directory (you should then see the executable you are trying to run).

Probably, the slashes are wrong? Something like this might work better:

```
tasks:
  run_program:
    cmds:
      - {{fromSlash relative/path/subdirectory/binary.exe}}  'some argument'
```
