### DISCUSSION TITLE
v3.37.0, v3.37.1 breaking mapped variable change

### DISCUSSION THREAD

**Discussion by rotten** [go-task/task#1647] [General]
Since this one tripped us up, I figured I'd mention it here to save others a few minutes of research.

We do not explicitly set the experimental maps variables as described here:  https://taskfile.dev/experiments/map-variables/ and instead rely on the default task behavior.

With earlier versions of `task` this worked:

```
vars:
  REPO_DIR:
    desc: Path to the root of this repository
    sh: git rev-parse --show-toplevel
```

Unfortunately you end up with an error like this with version 3.37.0 and 3.37.1

`task: line 12: maps cannot be assigned to variables`

The fix is fairly simple, remove the description and turn it into a comment:
```
vars:
  REPO_DIR:
     # Path to the root of this repository
    sh: git rev-parse --show-toplevel
```

Setting `TASK_X_MAP_VARIABLES=2` works similarly to the default, but you still have to remove the `desc: ` line with this new version of task.

This change is backwards compatible, so it won't break your colleagues still on v3.36
