### DISCUSSION TITLE
What is the alternative for `yaml` and `json` keys for Map variable

### DISCUSSION THREAD

**Discussion by simonrouse9461** [go-task/task#1700] [General]
I saw in the unreleased changelog that `yaml` and `json` will not be available for Map variable experiment 2 for the next version.
If that's the case what will be the alternative to load yaml and json strings?
I'm asking because I'm currently using experiment 2 `yaml` key to load an external yaml file into a map variable. Is it still possible without using `yaml` key?

**Comment by pd93** [comment]
Hey @simonrouse9461. The `yaml` and `json` keys always felt like they fell outside the scope of the any/map variables experiments to me - This is why they were removed in #1654. In the upcoming version of task, References (using `ref:`) will be generally available and you'll be able to do something like this:

```yaml
tasks:
  default:
    vars:
      JSON: '{"a": 1, "b": 2, "c": 3}'
      FOO:
        ref: "fromJson .JSON"
    cmds:
      - echo {{.FOO}}
```

This actually allows you to create maps without enabling the maps experiment too 😉 

Here are the (WIP) docs for references: https://taskfile.dev/next/usage/#referencing-other-variables
