### DISCUSSION TITLE
Common task using variable "sources" with multiple parent tasks

### DISCUSSION THREAD

**Discussion by ameershira** [go-task/task#1732] [Q&A]
Hi,

This discussion is a continuation of  #494. The goal is to find a better way to handle this case.

The solution to #494 was to set a custom label as shown in the example below:

``` yaml

# https://taskfile.dev

version: '3'

tasks:
  base:
    label: "{{.CALLERTASK}}{{.TASK}}"
    cmds:
      - echo "task ran for file:{{.FILE}}"
    sources:
      - '{{.FILE}}'


  task1:
    cmds:
      - task: base
        vars: {
          CALLERTASK: "{{.TASK}}->",
          FILE: "file1.txt",
        }


  task2:
    cmds:
      - task: base
        vars: {
          CALLERTASK: "{{.TASK}}->",
          FILE: "file2.txt",
        }
```

Doing the above was "okay" for small Taskfiles, however in larger projects with multiple levels of git submodules each including a child Taskfile...

# Things get quite complicated for the following reasons:

1. In contrast to the example above, debugging a **long** chain of tasks is hard. Its not easy to see which tasks are being called with what variables. I also had to add the "->" so that i can **clearly** see the task calling trace and see the chain of tasks when using  the "-v" flag. 
2. Task does not have first class support for what is manually done in the example above, so the tasks are littered with CALLERTASK: "{{.TASK}}->", and if you forget to add this, there is no easy way to know it was not "correct".
3. If you have "sources" is not easy to see what triggered a task to execute. This is needed for debugging/developing a Taskfile.

# Higher level goals:
1. Add more Taskfile developer features to assist with creating and understanding the flow and state of the tasks. This would improve the task traceability.
2. Support the case above an remove the need for the user to add  `CALLERTASK: "{{.TASK}}->"` everywhere.
