### DISCUSSION TITLE
Why {{.CHECKSUM}} variable can't be used in cmds?

### DISCUSSION THREAD

**Discussion by pavetok** [go-task/task#1734] [General]
Hi everyone,

First of all, thanks for the great tool!

I want to build docker image only when sources changed, but `{{.CHECKSUM}}` empty in cmds :(

Why is that?

```yaml
image:
  sources:
    - ./**
  status:
    - docker image inspect my/app:{{.CHECKSUM}}
  cmds:
    - docker build . -t my/app:latest -t my/app:{{.CHECKSUM}}
```
