### DISCUSSION TITLE
How do I use a variable for the generates field of a task

### DISCUSSION THREAD

**Discussion by ibotha** [go-task/task#1737] [Q&A]
Hi all, I would like to do something like this for one of the tasks
```yaml
tasks:
  task:
    sources:
      - main.cpp
    generates:
      - for:
          var: LIST
        {{.ITEM}}
```
My reasoning is that the task can have slightly different outputs based on what arguments it is run with.

This lead to a parsing error however since the for loop expects a key in from of the item (all the docs show `cmd: {{.ITEM}}`), but generates is a list of strings, there is no key.

Any ideas how I can get around this?
