### DISCUSSION TITLE
Blocking/waiting on a task?

### DISCUSSION THREAD

**Discussion by mateothegreat** [go-task/task#1749] [General]
Is there a way to have a "blocking" task so that it waits for it to complete first? (see the first task infra/up below)

```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pkg/rest:
    dir: ../pkg/rest
    taskfile: ../pkg/rest
  pkg/broker:
    dir: ../pkg/broker
    taskfile: ../pkg/broker
  pkg/webrtc:
    dir: ../pkg/webrtc
    taskfile: ../pkg/webrtc/taskfile.yaml
  apps/spa:
    dir: ../apps/spa
    taskfile: ../apps/spa/taskfile.yaml
tasks:
  infra-up:
    cmds:
      - make infra/up
    status:
      - curl -s http://localhost:15672
  stack:
    deps:
      - infra-up # wait for this task <---------
      - pkg/rest:run
      - pkg/broker:run
      - pkg/webrtc:run
      - apps/spa:run
```

**Comment by vmaerten** [comment]
Hello
deeps are run in parallel. If you want to run task sequentially (and wait to complete), you need to use cmds as follow:

```
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  pkg/rest:
    dir: ../pkg/rest
    taskfile: ../pkg/rest
  pkg/broker:
    dir: ../pkg/broker
    taskfile: ../pkg/broker
  pkg/webrtc:
    dir: ../pkg/webrtc
    taskfile: ../pkg/webrtc/taskfile.yaml
  apps/spa:
    dir: ../apps/spa
    taskfile: ../apps/spa/taskfile.yaml
tasks:
  infra-up:
    cmds:
      - make infra/up
    status:
      - curl -s http://localhost:15672
  stack:
    cmds:
      - task: infra-up # wait for this task <---------
      - task: pkg/rest:run
      - task: pkg/broker:run
      - task: pkg/webrtc:run
      - task: apps/spa:run

```
