### DISCUSSION TITLE
Add ability to require wildcards

### DISCUSSION THREAD

**Discussion by Firesphere** [go-task/task#1756] [Ideas]
Say I have this task:
```
 stop:*:
    desc: "Restart a supervisor process"
    summary: |
      A task to start/stop/restart a process, usage:
      `task supervisor:stop:PROCESSNAME`

      Available processes are:
      - admin
      - common
    vars:
      PROCESS: '{{index .MATCH 0}}'
    cmds:
      - docker exec supervisor supervisorctl stop {{.PROCESS}}
```
I would like to be able to add a "require" to this, _requiring_ the wildcard of `*` to be at least _something_.
If the wildcard doesn't match any known supervisor processes, I'm not fuzzed about that, but I'd like to be able to require the end user of my tasks to at least not do `task stop:` and expect that task just does the things they expect.

You'd be surprised how often this has happened in the month-or-two I've migrated to task, it seems that before task, I used make, and people understood that when make said "no such target", they did something wrong. Somehow, they are convinced that with changing to task, it is now all my fault if they don't supply the final argument.
