### DISCUSSION TITLE
Ability for task to self register as a dependency of another task (run before x)

### DISCUSSION THREAD

**Discussion by sirikon** [go-task/task#1772] [Ideas]
I'm using `task` for configuring servers, and a common use case that I'm having is this:

I have a `Taskfile.yaml` for managing `webhook` (https://github.com/adnanh/webhook specifically). `webhook` is configured with a single JSON file containing an array of webhook definitions.

I also have multiple `Taskfile.yaml` for different projects, and each one wants to register its own webhooks, which is done with a different task in each project.

To solve this, I make a script that takes all the `.json` files inside a directory and combines them in a single file in `/etc/webhook.conf`.

**The problem is**, I need a way to tell `task` that all the "create json file with webhook" tasks need to be run **before** the "combine all the json files" task without making the `webhook` tasks know about every single project explicitly. Right now, I can't set a "reverse dependency", saying that a task should always run before another task if the given task is planned to be executed.

Right now, my solution is to manually split the root Taskfile in "phases" to make sure that the "combine all the json files" task is executed last.

This is roughly how it looks now:

```yaml
# Example tasks joined in a single Taskfile and
# ignoring `status`, `sources` and all that stuff for brevity.

tasks:
  default:
    deps: [webhook, project-a, project-b]
    cmds:
      - task: webhook-configure


  webhook:
    deps: [webhook-install]
  
  webhook-install:
    cmds:
      - apt-get install -y webhook

  webhook-configure:
    cmds:
      - ./combine-webhook-jsons.sh


  project-a:
    cmds:
      - ./write-project-a-webhook.sh
  
  project-b:
    cmds:
      - ./write-project-b-webhook.sh
```

And this is how it could look with something like a `before: ` setting implemented.

```yaml
tasks:
  default:
    deps: [webhook, project-a, project-b]


  webhook:
    deps: [webhook-install, webhook-configure]
  
  webhook-install:
    cmds:
      - apt-get install -y webhook

  webhook-configure:
    cmds:
      - ./combine-webhook-jsons.sh


  project-a:
    before: webhook-configure
    cmds:
      - ./write-project-a-webhook.sh
  
  project-b:
    before: webhook-configure
    cmds:
      - ./write-project-b-webhook.sh
```

I've seen the proposal #1409 , but I think it introduces a "before/after arms race", in which you'll eventually need to have tasks running after a task that already has a `run: after` setting. That's why I'm making this proposal instead.
