### DISCUSSION TITLE
Can gotask do "variable variables" / dynamic variables?

### DISCUSSION THREAD

**Discussion by MetalArend** [go-task/task#1773] [Q&A]
Is there any way to print the values of THING1_NAME and THING2_NAME based on the value of INCLUDED?

```yaml
tasks:
  test:
    vars:
      INCLUDED: 'THING1,THING2'
      THING1_NAME: 'foo'
      THING2_NAME: 'bar'
    cmds:
      - for: { var: INCLUDED, split: ',' }
        cmd: echo '{{.ITEM}}_NAME:{{print "." .ITEM "_NAME"}}'
```

Should result in the following output:
```txt
THING1_NAME:foo
THING2_NAME:bar
```

Note: the vars section will eventually be in some .env file.
