### DISCUSSION TITLE
Wildcard arguments and files checksum

### DISCUSSION THREAD

**Discussion by b2broker-yperfilov** [go-task/task#1794] [Q&A] [answered]
```
  wire-*:
    vars:
      SERVICE: '{{index .MATCH 0}}'
    cmds:
      - wire ./cmd/{{.SERVICE}}
    sources:
      - cmd/{{.SERVICE}}/**/*.go
      - exclude: cmd/{{.SERVICE}}/wire_gen.go
      - internal/{{.SERVICE}}/**/*.go
    generates:
      - cmd/{{.SERVICE}}/wire_gen.go
```

Hello! We want to add to the code the job to generate files using `wire` dependency injector generator. We are adding new entrypoints frequently, so want to use wildcard jobs and allow commands like `task wire-accounts` so that `accounts` service di is generated.

However, checksum is stored for a job (file called `wire--`). As a result, if we call it for a service different from previous call, checksum is not used and job anyway executes. Any ideas how to overcome it?
