### DISCUSSION TITLE
Is it possible to "force" run a step by ignoring `status`?

### DISCUSSION THREAD

**Discussion by dbeilin** [go-task/task#1840] [Q&A] [answered]
I have a task that clones a list of repos:

```yaml
version: "3"

vars:
  REPOS:
    - name: repo1
      branch: "main"
    - name: repo2
      branch: "main"
  TMP_DIR: /var/tmp

tasks:
  reusable-checkout-repo:
    desc: "Reusable task to clone a repo"
    internal: true
    label: "checkout-{{.REPO_NAME}}"
    dir: "{{.TMP_DIR}}"
    status:
      - test -d {{.REPO_NAME}}
    cmds:
      - echo "Cloning {{.REPO_NAME}} into {{.TMP_DIR}}"
      - git clone https://github.com/org/{{.REPO_NAME}}.git --depth 1 --branch {{.REPO_BRANCH}}

  checkout-repos:
    desc: "Checkout dev-deps and devops-config repos"
    dir: "{{.TMP_DIR}}"
    cmds:
      - for: { var: REPOS, as: REPO }
        task: reusable-checkout-repo
        vars: { REPO_NAME: "{{.REPO.name}}", REPO_BRANCH: "{{.REPO.branch}}" }
```

The `status` I added enables me to skip this step if those repos already exist on my disk, which is great and generally what I want. 
However, I can see a scenario where I'd like to "force" them to be re-pulled.
I'd hoped to avoid using bash to achieve this, so I was wondering if Taskfile has some native way of achieving this.

For example, If I could run `task checkout-repos --force` or `--ignore-status`.
Any tricks would be appreciated :)
