### DISCUSSION TITLE
Feature Request - Test directory exists

### DISCUSSION THREAD

**Discussion by yonas** [go-task/task#1855] [Ideas]
# Existing workaround

```yaml
version: 3

vars:
  tmpdir: /some/path

tasks:
  default:
    preconditions:
      - sh: test -d "{{ .tmpdir }}"
        msg: "Temp directory must exist"
    requires:
      vars:
        - tmpdir
    dir: '{{.tmpdir}}'
    cmds:
      - echo $PWD
```

## Method #1

The existing workaround would be shortened to:

```yaml
version: 3

vars:
  tmpdir: /some/path

tasks:
  default:
    dir:
      path: '{{.tmpdir}}'
      required: true
    cmds:
      - echo $PWD
```

> [!NOTE]
> - [ ] `requires` is replaced by `dir.required`
> - [ ] `preconditions` check, error message, and program aborting is replaced by `dir.required`

Using `dir` as a simple string would continue to work for existing Taskfiles

`dir.required` defaults to false

## Method #2

The existing workaround would be shortened to:

```yaml
version: 3

vars:
  tmpdir: /some/path

tasks:
  default:
    required-dir: '{{.tmpdir}}'
    cmds:
      - echo $PWD
```

I prefer method #2, as it's more compact.
