### DISCUSSION TITLE
Always execute cmds

### DISCUSSION THREAD

**Discussion by 3sky** [go-task/task#1892] [Ideas]
Hi there,

From time to time I have something like:

```yaml
version: '3'

tasks:
  sts:
    cmds:
      - aws sts get-caller-identity
  network:
    deps:
      - sts
    cmds:
      - cdk deploy network --require-approval never
  clean:
    deps:
      - sts
    cmds:
      - cdk destroy --all --force
  sni24:
    deps:
      - sts
    cmds:
      - cdk deploy sni-24 --require-approval never
```
As you may see I need to specify `sts` every time as a deps.  The idea is to implement keyword that will apply to all steps by default as a prerequisite.  For example:

```yaml
version: '3'

tasks:
  always:
    cmds:
      - aws sts get-caller-identity
  
  network:
    cmds:
      - cdk deploy network --require-approval never
  clean:
    cmds:
      - cdk destroy --all --force
  sni24:
    cmds:
      - cdk deploy sni-24 --require-approval never
 ```
 
 What do you think? Or maybe it's possibly already, but I missed it in documentation? 
 If you like it, I'd love to try implement it.
