### DISCUSSION TITLE
task requires vars

### DISCUSSION THREAD

**Discussion by j0r0** [go-task/task#1919] [Q&A]
Hello,
I see that we can make some vars to be required for a task.
I see :
```
    requires:
      vars:
        - name: ENV
          enum: [ beta, prod ]
```

or 

```
    requires:
      vars: [ENV]
```
 but i don't see anything about combining those together. Something like:

```
    requires:
      vars:
        - name: ENV
          enum: [ beta, prod ]
        - name: VAR2
```
        
The goal here is that the task requires two variables, one that we can validate agains an ENUM, and one that we can not.

Is there any way to achieve this ?

**Comment by vmaerten** [comment]
Hello

This should work : 
```yml
    requires:
      vars:
        - name: ENV
          enum: [ beta, prod ]
        - name: VAR2
```
