### DISCUSSION TITLE
Are there wildcard separators that should be avoided?

### DISCUSSION THREAD

**Discussion by vctls** [go-task/task#1925] [Q&A]
When creating tasks with two or more wildcard arguments, I found that using dashes like in the doc example works well, but using dots leads to a different behaviour:
```yaml
tasks:
  test-*-*:
    vars:
      FOO: |-
        {{index .MATCH 0}}
      BAR: |-
        {{index .MATCH 1}}
      # language=sh
      CLI_ARGS: |-
        {{index .MATCH 0}} {{index .MATCH 1}}
    cmds:
      - cmd: echo "{{.CLI_ARGS}}"
```
```bash
❯ task test-bar-baz
task: [test-*-*] echo "bar baz"
bar baz
```
```yaml
  test.*.*:
    . . .
```
```bash
❯ task test.bar.baz
task: [test.*.*] echo "bar.ba "
bar.ba 
```
I'm guessing that's some regex issue.  Or is it related to YAML paths?
Is it a bug, or are dots just officially not supported?
I don't want to use dashes because sometimes I need to pass arguments such as UUIDs that already have dashes in them. I could use other characters, but some will cause other problems, and some just look weird as separators.
