### DISCUSSION TITLE
Env variable for absolute path of current working directory.

### DISCUSSION THREAD

**Discussion by lesomnus** [go-task/task#1957] [Q&A]
Assume I run following taskfile at `/home/lesomnus/foo`:
```yaml
version: "3"

tasks:
  hello:
    dir: bar
    cmds:
      - echo $(pwd)
```
It will print  `/home/lesomnus/foo/bar` where the cmd's working directory.
However, I believe it can be templated without executing `pwd`.

There was an issue about it at #525 but is closed as duplication of #215 but #215 does not state that.

Maybe I can:
```yaml
version: "3"

tasks:
  hello:
    dir: bar
    vars:
      PWD:
        sh: pwd
    cmds:
      - echo {{.PWD}}
```
but it is too verbose.

Is there already a special variable for this?
