### DISCUSSION TITLE
vars date format

### DISCUSSION THREAD

**Discussion by Dmitriy147** [go-task/task#1968] [General]
Hello! I need to get in my taskfile variable with formatted date but every attempts are with errors!
Only one variant is working fine:
vars: {{ now }}
The output is: 21-12-2024 15:45:56...
I need to get date formatted like: 20241221
 Could anyone help with example string?

**Comment by Dmitriy147** [comment]
..windows11pro..

**Comment by vmaerten** [comment]
Hello ! 
Task is using golang templating, every vars will be parsed using this templating system.
This can do what you want : 

```yml
version: 3
vars:
  DATE: '{{ now.Format "20060102" }}'

tasks:
  default: echo {{.DATE}}
```
