### DISCUSSION TITLE
dependencies to run after a task

### DISCUSSION THREAD

**Discussion by mohsen1** [go-task/task#1995] [Ideas]
`deps` is great for running tasks before running my tasks but sometimes it is more ergonomic to run tasks after success too. similar to npm post* scripts.

For example I have

```yml
  test:e2e:docker:run:internal:
    internal: true
    desc: Run E2E tests in Docker
    cmds:
      - docker compose -f {{.DOCKER_COMPOSE}} up playwright {{.CLI_ARGS}}

  test:e2e:docker:
    desc: Run E2E tests in Docker
    deps:
      - task: test:e2e:docker:run:internal
    prompt: Do you want to open the HTML report?
    cmds:
      - pnpm playwright show-report .next/playwright-report/html
```

It would be nicer if I could specify opening the report as an after task and also allowing to condition it to a flag like `--no-open`
