### DISCUSSION TITLE
Configurable default Taskfile

### DISCUSSION THREAD

**Discussion by HeCorr** [go-task/task#2010] [Ideas]
IMO the default Taskfile (generated with `--init`) is not very useful out-of-the-box:

<details><summary>Taskfile.yml</summary>

```yaml
# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
```

</details> 

I always end up editing it like this to get a good starting point:

<details><summary>Cleaner Taskfile.yml</summary>

```diff
# https://taskfile.dev

version: '3'

-vars:
-  GREETING: Hello, World!
-
tasks:
  default:
    cmds:
-      - echo "{{.GREETING}}"
+      - task --list
    silent: true
```
Now simply calling `task` lists all available tasks that have a description.

</details> 

So it would be very useful to be able to specify a default "template" to use with the `--init` flag, maybe stored in the user's home directory.
