### DISCUSSION TITLE
completions not working on MAC on latest

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2132] [Q&A]
I am using Option 1 as shown here: https://taskfile.dev/installation/#setup-completions

But from my terminal the tabbing does nothing after typing "task " <TAB> ..

any ideas ???

---

OS variables:

```sh
make           

BASE_OS_NAME:         darwin

BASE_SHELL:           /bin/sh
BASE_SHELL_VERSION:   zsh 5.9 (arm64-apple-darwin24.0)

BASE_GO_VERSION:      go version go1.24.1 darwin/arm64

BASE_TASK_VERSION:    Task version: v3.42.1 (h1:HOaFbZGLOrAy2V/dLsX2rGJZVG2Qx6268KUIAIXdNE4=)
BASE_TASK_EXP:        * GENTLE_FORCE:     on (1) * REMOTE_TASKFILES: on (1) * MAP_VARIABLES:    on (1) * ENV_PRECEDENCE:   on (1)
```

---

.zshrc ( at the very top only )

```sh
autoload -Uz compinit
compinit

autoload -U +X compinit && compinit

### Taskfile
eval "$(task --completion zsh)"

echo
echo TASK completions loaded....
echo
```
---

.env

```sh
# .env
# https://taskfile.dev/experiments/env-precedence
TASK_X_ENV_PRECEDENCE=1

# https://taskfile.dev/experiments/gentle-force/
TASK_X_GENTLE_FORCE=1

# https://taskfile.dev/experiments/map-variables/
TASK_X_MAP_VARIABLES=2

# https://taskfile.dev/experiments/remote-taskfiles/
TASK_X_REMOTE_TASKFILES=1
```

---

taskfile:

```yaml

# https://taskfile.dev

version: "3"

interval: 1000ms

includes:
  base: ./mod/base.tf.yaml
  git: ./mod/git.tf.yaml
  remote:
    # binary needed: https://github.com/aquasecurity/trivy/releases/tag/v0.60.0
    taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml
    vars:
      TASK_RUNTIME:
        sh: echo "${TASK_RUNTIME:-devbox}"

vars:
  VERSION:
    sh: cat VERSION

tasks:
  tools:
    platforms: [windows, linux, darwin/arm64, darwin/amd64, openbsd, dragonfly, freebsd, netbsd]
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest

      - platforms: [linux/amd64]
        cmd: test -f site/tailwindcli || wget -O site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-linux-x64

      - platforms: [linux/arm64]
        cmd: test -f site/tailwindcli || wget -O site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-linux-arm64

      - platforms: [darwin/arm64]
        cmd: test -f site/tailwindcli || wget -O site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-macos-arm64

      - platforms: [darwin/amd64]
        cmd: test -f site/tailwindcli || wget -O site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-macos-x64

      - platforms: [windows]
        cmd: test -f site/tailwindcli || wget -O site/tailwindcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.21/tailwindcss-extra-windows-x64.exe

      - platforms: [openbsd, dragonfly, freebsd, netbsd]
        cmd: pnpm add tailwindcss @tailwindcss/container-queries @tailwindcss/typography daisyui

      - platforms: [openbsd, dragonfly, freebsd, netbsd]
        cmd: test -f site/tailwindcli || (echo "#!/bin/sh" > site/tailwindcli  && echo "tailwindcss $@" >> site/tailwindcli)

      - chmod +x site/tailwindcli
      - go install github.com/valyala/quicktemplate/qtc@latest

  version:
    cmds:
      - echo {{.VERSION}}

  qtc:
    sources:
      - "**/*.qtpl"
    generates:
      - "**/*.qtpl.go"
    cmds:
      - qtc

  build:
    deps:
      - qtc
    sources:
      - VERSION
      - "**/*.qtpl"
      - "**/package.json"
      - "**/*.ts"
    generates:
      - "bundles/**/*"
    cmds:
      - go run build/cmd/build/main.go
      - cp -r bundles/* site/static/js/
      - mkdir -p library/dist/
      - cp -r bundles/* library/dist/
      - mkdir -p site/static/librarySource
      - rm -rf site/static/librarySource/*
      - cp -r library/src/* site/static/librarySource/

  library:
    dir: library
    requires:
      vars: [VERSION]
    sources:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.json"
    generates:
      - "dist/**/*"
    cmds:
      - pnpm i
      - pnpm build

  libpub:
    dir: library
    requires:
      vars: [VERSION]
    deps:
      - build
      - library
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      - npm publish --access public
      - curl https://purge.jsdelivr.net/gh/starfederation/datastar/bundles/datastar.js
      - git push origin --tags
      - GOPROXY=proxy.golang.org go list -m github.com/starfederation/datastar@v{{.VERSION}}
      - task: deploy

  sdktspub:
    dir: sdk/typescript
    requires:
      vars: [VERSION]
    cmds:
      - git push origin
      - git tag sdktsv{{.VERSION}}
      - git push origin --tags
      - deno run -A build.ts {{.VERSION}}
      - cd npm && npm publish --access public
      - curl https://purge.jsdelivr.net/gh/starfederation/datastar/sdk/typescript/npm/esm/web/serverSentEventGenerator.js
      - curl https://purge.jsdelivr.net/gh/starfederation/datastar/sdk/typescript/npm/esm/abstractServerSentEventGenerator.js
      - curl https://purge.jsdelivr.net/gh/starfederation/datastar/sdk/typescript/npm/esm/node/serverSentEventGenerator.js
      - git push origin --tags

  idiomorph:
    dir: library/src/vendored
    cmds:
      - wget -O idiomorph.esm.js https://raw.githubusercontent.com/bigskysoftware/idiomorph/refs/heads/main/dist/idiomorph.esm.js
      - npx -p typescript tsc *.js --declaration --allowJs --emitDeclarationOnly --outDir .
  css:
    dir: site
    sources:
      - "**/*.templ"
      - "**/*.md"
      - "**/*.go"
    generates:
      - "static/css/site.css"

    cmds:
      - ./tailwindcli build -i src/css/site.css -o static/css/site.css

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    # deps:
    #   - library
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  kill:
    method: none
    cmds:
      - fuser -k 8080/tcp > /dev/null 2>&1 || true

  support:
    sources:
      - "**/*.templ"
      - "**/*.go"
      - "**/*.md"
      - site/static/**/*
    generates:
      - ./datastar-website
    deps:
      - kill
      - build
      - templ
      - css

  site:
    method: none
    desc: build and run site
    deps:
      - support
    cmds:
      - go mod tidy
      - go build -o ./datastar-website "site/cmd/site/main.go"

  deploy:
    method: none
    deps:
      - support
    cmds:
      - fly deploy --local-only

  test:
    deps:
      - support
    cmds:
      - go test -v github.com/starfederation/datastar/site/smoketests -run '^TestUnit' -count=1 -timeout=1m

  test-all:
    deps:
      - support
    cmds:
      - go test -v github.com/starfederation/datastar/site/smoketests -count=1 -timeout=1m

  default:
    cmds:
      - task: site
      - ./datastar-website
```

---

```sh
task --list-all
task: Available tasks for this project:
* build:                                       
* css:                                         
* default:                                     
* deploy:                                      
* idiomorph:                                   
* kill:                                        
* libpub:                                      
* library:                                     
* qtc:                                         
* sdktspub:                                    
* site:                                        build and run site
* support:                                     
* templ:                                       
* test:                                        
* test-all:                                    
* tools:                                       
* version:                                     
* base:git-print:                              git print
* remote:docker-compose:down:                  Stop and remove containers, networks
* remote:docker-compose:up:                    Create and start containers
* remote:security:sast:checkov:scanner:        Infrastructure as code static analysis
* remote:security:sast:grype:scanner:          A vulnerability scanner for container images, filesystems, and SBOMs
* remote:security:sast:trivy:aws:              [EXPERIMENTAL] Scan AWS account
* remote:security:sast:trivy:config:           Scan config files for misconfigurations
* remote:security:sast:trivy:filesystem:       Scan local filesystem
* remote:security:sast:trivy:image:            Scan a container image
* remote:security:sast:trivy:kubernetes:       [EXPERIMENTAL] Scan kubernetes cluster
* remote:security:sast:trivy:repository:       Scan a repository
* remote:security:sast:trivy:rootfs:           Scan rootfs
* remote:security:sast:trivy:sbom:             Scan SBOM for vulnerabilities and licenses
* remote:security:sast:trivy:vm:               [EXPERIMENTAL] Scan a virtual machine image
* remote:terraform:apply:                      terraform apply -auto-approve
* remote:terraform:destroy:                    terraform destroy
* remote:terraform:doc:                        terraform-docs markdown table
* remote:terraform:fmt:                        terraform fmt
* remote:terraform:init:                       terraform init
* remote:terraform:plan:                       terraform plan
* remote:terraform:terrascan:                  Terrascan static code analyzer
* remote:terraform:tflint:                     tflint
* remote:terraform:validate:                   terraform validate


```
