### DISCUSSION TITLE
Issue with variable type when referencing

### DISCUSSION THREAD

**Discussion by aykhans** [go-task/task#2142] [Q&A]
In the `build-all` task, when I reference the `GLOBAL_ARCHS` variable, it passes the `ARCHS` variable to the `build-platform` task as a `[]interface{}` type.
```yaml
version: "3"

vars:
    PLATFORMS:
        - os: darwin
          archs: [amd64, arm64]
        - os: freebsd
          archs: [386, amd64, arm]
        - os: linux
          archs: [386, amd64, arm, arm64]
        - os: netbsd
          archs: [386, amd64, arm]
        - os: openbsd
          archs: [386, amd64, arm, arm64]
        - os: windows
          archs: [386, amd64, arm64]

    GLOBAL_ARCHS: [386, amd64, arm64]

tasks:
    build-all:
        silent: true
        cmds:
            - for: { var: PLATFORMS, as: PLATFORM }
              vars:
                  OS: '{{ .PLATFORM.os }}'
                  ARCHS:
                      ref: .GLOBAL_ARCHS
              task: build-platform

    build-platform:
        silent: true
        cmds:
            - echo {{typeOf .ARCHS}}
            - for: { var: ARCHS, as: ARCH }
              cmd: echo "Building for {{ .OS }}/{{ .ARCH }}"
```

However, when I reference `PLATFORM.archs` instead, the `ARCHS` variable is passed to the `build-platform` task as a `string` type instead of `[]interface{}`.
```yaml
version: "3"

vars:
    PLATFORMS:
        - os: darwin
          archs: [amd64, arm64]
        - os: freebsd
          archs: [386, amd64, arm]
        - os: linux
          archs: [386, amd64, arm, arm64]
        - os: netbsd
          archs: [386, amd64, arm]
        - os: openbsd
          archs: [386, amd64, arm, arm64]
        - os: windows
          archs: [386, amd64, arm64]

    GLOBAL_ARCHS: [386, amd64, arm64]

tasks:
    build-all:
        silent: true
        cmds:
            - for: { var: PLATFORMS, as: PLATFORM }
              vars:
                  OS: '{{ .PLATFORM.os }}'
                  ARCHS:
                      ref: .PLATFORM.archs
              task: build-platform

    build-platform:
        silent: true
        cmds:
            - echo {{typeOf .ARCHS}}
            - for: { var: ARCHS, as: ARCH }
              cmd: echo "Building for {{ .OS }}/{{ .ARCH }}"
```

Why does referencing `PLATFORM.archs` pass it as a `string` type, while referencing `GLOBAL_ARCHS` pass `ARCHS` as a `[]interface{}` type? And how can I modify it to pass as `[]interface{}`?
