### DISCUSSION TITLE
Thank you go-task team! (April Fools task)

### DISCUSSION THREAD

**Discussion by liiight** [go-task/task#2149] [Show and tell]
I've been an avid user of go-task for a long while now.
It allowed me as a (sort of) DevOps developer in my company to easily control user flows and interaction.
And today it allowed me to deploy the following task to all of my users (you can safely run this, you just need uv)

```yaml
  rick-roll:
    aliases:
      - platform-migration
    vars:
      TEXT: |-
        Happy April fools
              from
          Infra Team!
    cmds:
      - cmd: echo "Preparing platform migration..."
      - cmd: for i in $(seq 100); do echo; sleep 0.1; done | uvx tqdm --total 100 --bar-format '{l_bar}{bar}' > /dev/null
      - cmd: open "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        platforms: [darwin/arm64]
      - cmd: cmd.exe /c start "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        platforms: [amd64]
      - uvx --quiet art text "{{.TEXT}}" xsansb | uvx --quiet --from terminaltexteffects tte beams
 ```

On a serious note, thanks a lot for making this awesome piece of software. I'm working towards getting my company to sponsor several OSS we use, go-task is high up on that list.
