### DISCUSSION TITLE
Build dependencies that are skipped if their dependants are skipped

### DISCUSSION THREAD

**Discussion by couling** [go-task/task#2158] [Ideas]
I'm looking for a way to declare build dependencies.  These have a reversed logic to normal dependencies.

The current logic with dependencies is correct for most cases: tasks can optionally be skipped based on `status` or `sources`, dependencies need to be run before making the decision to skip because they may change the decision 👌

But with build dependencies that sequence is reversed. The build dependencies only need to be run if the task is not skipped. So the decision to skip need to be made before executing the dependancies, and skip the building the dependencies if the dependant is skipped.

That is, build dependencies should be skipped if all of their dependants are skipped.

---------

Example use cases include:
 - building a build tool that is executed in a later step
 - downloading large static reference data. The reference data may not be included in the final artefact, but is needed for the build

---------

As a trivial example I want a way to make something like this, where `build-a` will be skipped on the second run.

```yaml
version: '3'

tasks:
  default:
    silent: true
    deps:
      - build-c

  build-a:
    cmd: echo "a" > 1a

  build-b:
    cmds: 
      - copy 1a 1b
      - echo "b" >> 1b
    status:
      - test -f 1b
    deps:
      - build-a

  build-c:
    cmd: touch 1c
    deps:
      - build-b
```
