### DISCUSSION TITLE
How to EVAL the args passed in ?

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2172] [Q&A]
How to EVAL the args passed on:

```yaml
'{{.TASK_EXE}} base:shell-redress -- {{.TASK_EXE}} base:shell-which {{.TASK_EXE}}'
```

Full example:
https://github.com/joeblew999/pb-stack/blob/main/base.taskfile.yml

task file:

```yaml

shell-redress:
    desc: redress is a cross platform **redress** command. E.G task base:shell-redress -- task
    cmds:
      - '{{.BASE_SHELL_REDRESS_BIN_NAME}} version {{.CLI_ARGS}}'
      - '{{.BASE_SHELL_REDRESS_BIN_NAME}} gomod {{.CLI_ARGS}}'
      - '{{.BASE_SHELL_REDRESS_BIN_NAME}} info {{.CLI_ARGS}}'
      - '{{.BASE_SHELL_REDRESS_BIN_NAME}} packages {{.CLI_ARGS}}'
      - '{{.BASE_SHELL_REDRESS_BIN_NAME}} moduledata {{.CLI_ARGS}}'
      #- '{{.BASE_SHELL_REDRESS_BIN_NAME}} types all {{.CLI_ARGS}}'
      #- '{{.BASE_SHELL_REDRESS_BIN_NAME}} source {{.CLI_ARGS}}'

shell-redress-test:
    cmds:
      # The fully reflective version does not work. How to EVAL the args passed in ?
      - '{{.TASK_EXE}} base:shell-redress -- {{.TASK_EXE}} base:shell-which {{.TASK_EXE}}'
      #- '{{.TASK_EXE}} base:shell-redress -- /Users/apple/workspace/go/bin/task'


  shell-which:
    desc: find binary. E.G task base:shell-which -- which
    cmds:
      - '{{.BASE_SHELL_WHICH_BIN_NAME}} {{.CLI_ARGS}}'
  
```

```sh

pb-stack % task base:shell-redress-test
task: [base:shell-redress-test] task base:shell-redress -- task base:shell-which task
task: [base:shell-redress] shell-redress version task base:shell-which task
______         _                  
| ___ \       | |                 
| |_/ /___  __| |_ __ ___ ___ ___ 
|    // _ \/ _  | '__/ _ / __/ __|
| |\ |  __| (_| | | |  __\__ \__ \
\_| \_\___|\__,_|_|  \___|___|___/
                                 

Version:  
GoRE:     
Go:       
task: [base:shell-redress] shell-redress gomod task base:shell-which task
Error: accepts 1 arg(s), received 3
Usage:
  redress gomod /path/to/go/file [flags]

Aliases:
  gomod, gosum, gm

Flags:
  -h, --help   help for gomod

accepts 1 arg(s), received 3
task: Failed to run task "base:shell-redress": exit status 1
task: Failed to run task "base:shell-redress-test": exit status 201
```.
