### DISCUSSION TITLE
How to remove the need for include prefixes ?

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2182] [Q&A] [answered]
I am still learning, and trying to get things modular for the team.

As you can see in my little example, I have to change the prefix on the task calls, depending on if I am using a local or remote include. 

I think there might be a way to make it so I dont need to ????

```yaml

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # TODO: Can i get rid of the need to swap between base and remote ?
  base: ./../../../remote-taskfile.yml
  #remote:
  #  taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/remote-taskfile.yml
                
vars:
  # MUST have this to work. Maybe can discover it later in base.
  BASE_SRC_NAME: soft_serve
 
tasks:
  default:
    cmds:
      - task --list-all
      - task base:base
      - task base:base:bin
      - task base:go:bin
      - task base:go:run
   
```

**Comment by joeblew999** [comment, marked as answer]
I worked it out and it works really well.

Task is really starting to pay off for me.

```yaml

# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

# MUST have this ONLY in root for env variables to work.
dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # Pick if you want local or remote task file loading.
  # https://taskfile.dev/usage/#flatten-includes makes it all the same either way.
  local: 
    taskfile: ./../../../remote-taskfile.yml
    flatten: true
  #remote: 
  #  taskfile: https://raw.githubusercontent.com/joeblew999/pb-stack/refs/heads/main/remote-taskfile.yml
  #  flatten: true

vars:
  # MUST have this to work. Maybe can discover it later in base.
  BASE_SRC_NAME: soft_serve
 
tasks:
  default:
    cmds:
      - task --list-all
      - task base
      - task base:bin
      - task go:bin
  run:
    cmds:
      - task go:run

```
