### DISCUSSION TITLE
mkdir fails on windows arm64

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2197] [Q&A]
mkdir fails on windows arm64. Passes on all other OS / ARCH.

ci: https://github.com/joeblew999/pb-stack/actions/runs/14592655827/workflow

taskfile:  https://github.com/joeblew999/pb-stack/blob/870301a672997a8eea0a1e15e576afa39ec9434d/_hack/test-paths/taskfile.yml

```yaml

version: '3'

vars:
  UWD: '{{.USER_WORKING_DIR}}'
  FOLDER01_NAME: 'outfolder01'
  FOLDER01_PATH: '{{joinPath .USER_WORKING_DIR .FOLDER01_NAME}}'
  FOLDER02_NAME: "outbar/foo"
  FOLDER02_PATH: '{{joinPath .UWD .FOLDER02_NAME}}'

tasks:
  default:
    cmds:
      - echo 'UWD:' {{.UWD}}
      - echo 'FOLDER01_NAME:' {{.FOLDER01_NAME}}
      - echo 'FOLDER01_PATH:' {{.FOLDER01_PATH}}
      - echo 'FOLDER02_NAME:' {{.FOLDER02_NAME}}
      - echo 'FOLDER02_PATH:' {{.FOLDER02_PATH}}
      - mkdir -p {{.FOLDER01_PATH}}
      - mkdir -p {{.FOLDER02_PATH}}
      - ls -al .
    silent: false
```

manually run on windows arm64:

```sh

 task
task: [default] echo 'UWD:' C:\Users\admin\go\src\github\joeblew99\pb-stack\_hack\test-paths
UWD: C:Usersadmingosrcgithubjoeblew99pb-stack_hacktest-paths
task: [default] echo 'FOLDER01_NAME:' outfolder01
FOLDER01_NAME: outfolder01
task: [default] echo 'FOLDER01_PATH:' C:\Users\admin\go\src\github\joeblew99\pb-stack\_hack\test-paths\outfolder01
FOLDER01_PATH: C:Usersadmingosrcgithubjoeblew99pb-stack_hacktest-pathsoutfolder01
task: [default] echo 'FOLDER02_NAME:' outbar/foo
FOLDER02_NAME: outbar/foo
task: [default] echo 'FOLDER02_PATH:' C:\Users\admin\go\src\github\joeblew99\pb-stack\_hack\test-paths\outbar\foo
FOLDER02_PATH: C:Usersadmingosrcgithubjoeblew99pb-stack_hacktest-pathsoutbarfoo
task: [default] mkdir -p C:\Users\admin\go\src\github\joeblew99\pb-stack\_hack\test-paths\outfolder01
"mkdir": executable file not found in $PATH
task: Failed to run task "default": exit status 127
```
