### DISCUSSION TITLE
go env GOPATH that works in Windows and Unix

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2215] [Q&A]
Stuck trying to get this to work on Windows and Unix.

The Bug is that I get this on windows. 

```sh
- env
GO_ENV_PATH: C:Usersadmingo
GO_ENV_BIN_PATH: C:Usersadmingobin
```

Would appreciate help :) 

```sh
task --version
3.43.3
```

taskfile:

```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json

# go.taskfile.yml 

version: '3'

vars:
  GO_BIN_NAME: go
  #GO_BIN_NAME: 'go{{.BASE_BINARY_EXTENSION}}'
  
  GO_BIN_WHICH:
    #sh: 'command -v {{.GO_BIN_NAME}}'
    #sh: '{{.BASE_TASK_CMD}} base:shell-which -- {{.GO_BIN_NAME}}'
  GO_BIN_VERSION:
    sh: '{{.GO_BIN_NAME}} version'

  ### envs

  GO_ENV_PATH:
    sh: '{{.GO_BIN_NAME}} env GOPATH'
  GO_ENV_BIN_PATH: '{{joinPath .GO_ENV_PATH "bin" }}'

tasks:
  default:
    desc: go print
    cmds:
      - echo ''
      - echo '- bin'
      - echo 'GO_BIN_NAME:'                 {{.GO_BIN_NAME}}
      - echo 'GO_BIN_WHICH:'                {{.GO_BIN_WHICH}}
      - echo 'GO_BIN_VERSION:'              {{.GO_BIN_VERSION}}
      - echo ''
      - echo '- env'
      - echo 'GO_ENV_PATH:'                 {{.GO_ENV_PATH}}
      - echo 'GO_ENV_BIN_PATH:'             {{.GO_ENV_BIN_PATH}}
      - 
```

darwin works: 

```sh

- bin
GO_BIN_NAME: go
GO_BIN_WHICH:
GO_BIN_VERSION: go version go1.24.2 darwin/arm64

- env
GO_ENV_PATH: /Users/apple/workspace/go
GO_ENV_BIN_PATH: /Users/apple/workspace/go/bin
```

windows screws it up:

```sh
- bin
GO_BIN_NAME: go
GO_BIN_WHICH:
GO_BIN_VERSION: go version go1.24.2 windows/arm64

- env
GO_ENV_PATH: C:Usersadmingo
GO_ENV_BIN_PATH: C:Usersadmingobin

```
