### DISCUSSION TITLE
env overrides work but not var overrides

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2229] [Q&A]
The .env overrides work, but not the var ones .

I have a test setup here.

https://github.com/joeblew999/pb-stack/tree/main/mod/_template/source-remote

Can someone please have a look ?

Just git clone and then "task" ...

**Comment by joeblew999** [comment]
@ trulede if you have time would appreciate help. not sure what I am doing wrong :)

**Reply by trulede** [reply]
You might need to specify the variables you want set in the included (and remote) taskfile. So I would first try that:
https://taskfile.dev/usage/#vars-of-included-taskfiles

For instance:

```yaml
includes:
  dse.fmi-v1.1.15:
    taskfile: https://raw.githubusercontent.com/boschglobal/dse.fmi/refs/tags/v1.1.15/Taskfile.yml
    dir: '{{.OUTDIR}}/{{.SIMDIR}}'
    vars:
      FMI_IMAGE: ghcr.io/boschglobal/dse-fmi
      FMI_TAG: 1.1.15
      SIM: '{{.SIMDIR}}'
      ENTRYWORKDIR: '{{.PWD}}/{{.OUTDIR}}'
```

Those vars are then available in the included taskfile. Will that override the env .... I hope so!
