### DISCUSSION TITLE
Is it possible to disable a task?

### DISCUSSION THREAD

**Discussion by your-diary** [go-task/task#2230] [Q&A] [answered]
Like this:

```yaml
healthcheck_prd_env:
    disabled: true # We will enable this task when we have deployed the prd environment.
    cmds:
        - curl https://production.our-server.example.com/healthcheck
```

Workaround:

- comment out the definition

- use `preconditions` (though this doesn't hide the task from `--list/--list-all`):

    ```yaml
    preconditions:
        - echo 'This task is currently disabled. Aborting...'; false
    ```
