### DISCUSSION TITLE
Invoking task from parent directory's Taskfile.yml?

### DISCUSSION THREAD

**Discussion by xaviergmail** [go-task/task#2248] [Q&A] [answered]
Hello, 

Does Task not support walking up the directory tree to find the nearest parent `Taskfile.yml`?

Allow me to explain what I'm trying to achieve.

Consider the following directory tree:
```
repo-root/
├─ api/
│  ├─ src/
│  ├─ cdk/
│  │  ├─ Taskfile.yml
│  ├─ Taskfile.yml
├─ Taskfile.yml
```

Wherein my root `Taskfile.yml` is as follows:
```yaml
version: 3
includes:
  api:
    taskfile: api/Taskfile.yml
    dir: api/

  cdk:
    taskfile: api/cdk/Taskfile.yml
    dir: api/cdk/
```

From the root directory, I can successfully run my nested tasks, such as `task api:lint` or `task cdk:deploy`. However, if I `cd api/`, I have to change my command to `task lint`. This is fine, but our developers get confused (they can't run `task cdk:deploy`, etc)

I have tried naming my included taskfiles as `Taskfile.incl.yml` like so:
```
repo-root/
├─ api/
│  ├─ src/
│  ├─ cdk/
│  │  ├─ Taskfile.incl.yml
│  ├─ Taskfile.incl.yml
├─ Taskfile.yml
```
with
```yaml
version: 3
includes:
  api:
    taskfile: api/Taskfile.incl.yml
    dir: api/

  cdk:
    taskfile: api/cdk/Taskfile.incl.yml
    dir: api/cdk/
```
I was hoping this approach would work but if I `cd api/cdk` and try to run `task api:lint`, I get the following error: 
`stat /Volumes/projects/integrations-api/api/cdk/Taskfile.yml: no such file or directory`

I understand that this is similar to how GNU Make does it, but is there a flag or configuration option I'm unaware of that would allow walking up the path to find the nearest Taskfile.yml?

We are (unfortunately) converting our folks over from `package.json` "scripts" from which they've become accustomed to running `npm run deploy` from whichever directory they please.

---

In my search for similar topics, I've found #289 (and #920), #939 and #903. I was under the impression that #920 solved it but that doesn't seem to be the case? Am I missing something?
