### DISCUSSION TITLE
Is it possible to "group" output in CI only?

### DISCUSSION THREAD

**Discussion by xaviergmail** [go-task/task#2254] [Q&A]
I am leveraging tasks in CI such that my CI/CD pipelines do nothing much more than just invoking tasks. For readability, I have the following:
```yaml
﻿﻿output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::{{.TASK}}"
    error_only: true
```

This works great in GitHub Actions, but I don't like that I can't see error outputs in real-time when running these tasks locally.

I've had the idea of appending that yaml to my top level Taskfile at the start of CI jobs but I was wondering if there was an easier way to do it or if it would be feasible to request such a feature.
