### DISCUSSION TITLE
Define variable in for loop

### DISCUSSION THREAD

**Discussion by yonas** [go-task/task#2269] [Q&A] [answered]
Is this possible?

```yaml
version: 3

tasks:
  default:
    sources:
      - './conf/**/*.rcl'
    cmds:
      - for: sources
        vars:
          FILE:
            sh: basename {{ .ITEM }}
        cmd: 'rcl e --format json {{ .ITEM }} > {{ .FILE }}.json'
```

**Comment by trulede** [comment, marked as answer]
Yes, you can do this:

```yaml
version: '3'

tasks:
  default:
    sources:
      - '*.txt'
    cmds:
      - for: sources
        task: item
        vars:
          FILE: '{{.ITEM}}'

  item:
    cmds:
      - echo '{{.FILE}}'
```

More examples here: https://taskfile.dev/usage/#renaming-variables

**Reply by yonas** [reply]
Thanks @trulede . It'd be convenient to have it all in an one task.

Any reason for designing it this way?

**Reply by trulede** [reply]
That's how you make it work 😄 

What's behind that, well, `cmd:vars` sets variables in the called `cmd:task` (which you don't have), and not the `cmd:cmd` (which you do have). That is described here: https://taskfile.dev/reference/schema#command.

You can set that "item" task to `silent` and/or `internal` to make it "invisible" ... might be nice.

**Comment by vmaerten** [comment]
Hello,
You can do it with go templating (see https://taskfile.dev/reference/templating/#path-and-filepath-functions)

```yml
version: 3

tasks:
  default:
    sources:
      - './conf/**/*.rcl'
    cmds:
      - for: sources
        cmd: 'echo FILE : {{ base  .ITEM }} Full path : {{.ITEM}}'
```

It will print : 

![image](https://github.com/user-attachments/assets/6f4abd91-d6ff-44c3-ac5d-f1da1b838f9e)
