### DISCUSSION TITLE
Prompt for value and use it ?

### DISCUSSION THREAD

**Discussion by joeblew999** [go-task/task#2283] [Q&A]
Trying to work out if I can do a Prompt and get a value from the user:

https://taskfile.dev/usage/#warning-prompts

An easy example being a git commit and push, where you want to get a commit message from the user:

```yaml

push:src:
    desc: 'git push ( eg: COMMIT_MESSAGE=?? task git:push:src )'
    vars:
      COMMIT_MESSAGE: 'all your bases belong to me'
    prompt: Are you sure you want to push? This will commit all changes.
    cmds:
      #- task git:dep
      - echo 'Pushing src ...'
      - cd {{.GIT_VAR_SRC_REPO_PATH}} && {{.GIT_BIN_NAME}} add . 
      - cd {{.GIT_VAR_SRC_REPO_PATH}} && {{.GIT_BIN_NAME}} commit -S -am '{{.COMMIT_MESSAGE}}'
      - cd {{.GIT_VAR_SRC_REPO_PATH}} && {{.GIT_BIN_NAME}} push
   
```
