### DISCUSSION TITLE
Environment variable to disable a task

### DISCUSSION THREAD

**Discussion by valankar** [go-task/task#2292] [Q&A]
I'm wondering what is the proper way to prevent a task running via an environment variable is set. I'm currently doing something like this:

```yaml
tasks:
  some-task:
    cmds:
      - echo blah
    status:
      - test -n "$DISABLE_TASK"
```

Reasonable or is there a better way?
