### DISCUSSION TITLE
How to ZIP files in a cross-platform way?

### DISCUSSION THREAD

**Discussion by novabyte** [go-task/task#2295] [Q&A] [answered]
Is there a way to ZIP a collection of files within Task without multiple platform specific compress commands?

**Comment by vmaerten** [comment, marked as answer]
Hi there!
Task doesn't have a built-in zip function.
You can use the `platform` directive and define a separate command for each platform:
https://taskfile.dev/usage/#platform-specific-tasks-and-commands

**Reply by novabyte** [reply]
Thanks for the quick follow up @vmaerten. Do you think that the project would accept a [Templating Function](https://taskfile.dev/reference/templating/#functions) to perform an archive operation?

It seems strange to me that a tool which describes itself as both a task runner and a **build tool** does not have support for a common operation when build outputs are gathered to be distributed to developers or users. 🤔

**Reply by novabyte** [reply]
To help save time for others who come across this situation with their Taskfile. This is what we used:

```yml
version: '3'

vars:
    SEMVER: '{{.SEMVER | default "v1.25.0-pre"}}'

tasks:
    build-uplugin:
        # $> task -v build-uplugin SEMVER='v1.25.0-pre'
        cmds:
        -   cmd: zip -r ../HiroUnreal-{{.SEMVER}}.zip ./Hiro -x '**/.*' -x '**/__MACOSX'
            platforms: [ darwin, linux ]
        -   cmd: tar.exe --exclude='**/.*' --exclude='Binaries' --exclude='Content' --exclude='Intermediate' --exclude='**/__MACOSX' -acvf "../HiroUnreal-{{.SEMVER}}.zip" Hiro
            platforms: [ windows ]
        deps: [ generate-unreal ]
        desc: 'Build the Unreal plugin from Hiro sources.'
        dir: 'unreal'
        sources:
        - 'Hiro/**/*'
        generates:
        - '../HiroUnreal-{{.SEMVER}}.zip'
```
