### DISCUSSION TITLE
Global variables not accepting types?

### DISCUSSION THREAD

**Discussion by tommyalatalo** [go-task/task#2299] [Q&A] [answered]
I'm not sure what behavior I'm seeing here, I'm just trying to have a top level `vars` definition with a list, like this:
```
vars:
  deps:
    - nfs-server
    - csi-controller
    - csi-node
```
And then use it in a task:
```
tasks:
  test:
    cmds:
      - echo {{ index .deps 3 }}
```
This errors out with this message:
```
❯ task test
task: Failed to parse taskfile.yaml:
yaml: line 14: cannot unmarshal !!seq into variable
```
Why is this failing?

**Comment by vmaerten** [comment, marked as answer]
I think you have some space or tab issues

This is working well : 

```yml
# https://taskfile.dev

version: '3'

vars:
    deps:
      - nfs-server
      - csi-controller
      - csi-node
tasks:
  default:
    cmds:
      - echo {{index .deps 2}}

```

![image](https://github.com/user-attachments/assets/3de1d71f-d038-4ee0-8bdb-80e6cae57762)


Note that you won't be able to access to index 3 because index start at 0. So there are 3 index:  0,1 and 2
