### DISCUSSION TITLE
override PATH variable in `env:`

### DISCUSSION THREAD

**Discussion by ivotron** [go-task/task#449] [Q&A] [answered]
I would like to redefine `PATH` in `env:`, so that I can append paths that are given in `vars:` as well as `.env` files. However, given the following:

```yaml
version: '3'

env:
  PATH: "/some/path/bin:{{.PATH}}"
  OTHER: "/some/path/bin:{{.PATH}}"

tasks:
  test:
  - echo $PATH
  - echo $OTHER
```

and an initial value of `PATH=/usr/bin:/usr/local/bin`, I get the following:

```
$ task test
task: echo $PATH
/usr/bin:/usr/local/bin
task: echo $OTHER
/some/bin:/some/bin:/usr/bin:/usr/local/bin
```

I've tried distinct alternatives such as defining a variable first, then assigning this variables to `PATH` in `env:`, and also doing `sh: "echo ..."`, but nothing seems to work.

I also noticed that this behavior applies to any pre-existing environment variable. Is there a limitation with respect to overriding existing variables? If so, do you have a workaround for this? I would like to avoid having to override PATH inside the bash script itself every time that this is needed.

If this is something that can be fixed, I can volunteer to send a PR for this, but I'd like to kindly ask for your guidance with high-level instructions on how to go about implementing something like this (I'm new to Task in general, so I'm not familiar with the codebase).

thanks a lot for your time!
