### DISCUSSION TITLE
preconditions for internally undefined variables

### DISCUSSION THREAD

**Discussion by klauern** [go-task/task#465] [Q&A]
I have a task file that checks for a set variable as part of a `precondition`. 

```yaml
  run-local:
    desc: Run locally on a single service
    cmds:
      - task: run
    preconditions:
      - sh: test ! "{{.ACCOUNT}}" = "<no value>"
        msg: Must supply an account ID (e.g., `task run-local ACCOUNT=12345678`)
      - sh: test ! "{{.SERVICE}}" = "<no value>"
        msg: Must supply a service name (e.g., `task run-local SERVICE=thing`)
```

I discovered that variables were being set to `<no value>`, but I am not sure if that's a realible means to test for this.  As the precondition is based on a shell command, I am essentially escaping the Taskfile to test for a variable that is set externally, when it **could** be referenced locally.  Is there an equivalent precondition check that I can use to validate that a variable has been set correctly?  Will `<no value>` be reliably set everywhere?

**Comment by dolfelt** [comment]
@klauern Another way to do something like this could be:

```yaml
  run-local:
    desc: Run locally on a single service
    cmds:
      - task: run
    preconditions:
      - sh: '{{ if not .ACCOUNT }}exit 1;{{ end }}'
        msg: Must supply an account ID (e.g., `task run-local ACCOUNT=12345678`)
      - sh: '{{ if not .SERVICE }}exit 1;{{ end }}'
        msg: Must supply a service name (e.g., `task run-local SERVICE=thing`)
```
