### DISCUSSION TITLE
how to set env for deps

### DISCUSSION THREAD

**Discussion by hellojukay** [go-task/task#492] [Q&A]
```
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo $APP_NAME
    silent: true

  template:
    cmds:
      - echo $APP_NAME
    silent: false

  haina:
    env:
      APP_NAME: "haina"
    cmds:
      - echo $APP_NAME
    deps:
      - task: template
        env:
          APP_NAME: haina
```
env `APP_NAME` for deps not work.
