### DISCUSSION TITLE
How do I start two or more web servers within one task

### DISCUSSION THREAD

**Discussion by thesobercoder** [go-task/task#502] [Q&A] [answered]
What is the canonical way to running two web servers with one task? I found a way, but not sure if this is the recommended way of doing it.

```yaml
version: '3'

silent: true

tasks:
  run:
    deps: [a, b] # This command has no run only deps to run both web servers parallelly

  a:
    cmds:
      - go run a/main.go # webserver 1

  b:
    cmds:
      - go run b/main.go # webserver 2
```
