### DISCUSSION TITLE
Checking for adb device

### DISCUSSION THREAD

**Discussion by andersmmg** [go-task/task#504] [Q&A]
I want to have a task that installs the apk to my device if it's plugged in. I've tried a few ways and I've been unable to figure out how to go about this? Any help would be appreciated.
This is what I'm trying currently, but it doesn't seem to work. The task is successful even if there are no devices.
```
android-install:
    cmds:
      - echo "hello"
    preconditions:
      - sh: "test -n `adb devices | awk 'NR>1 {print $1}'`"
        msg: "No ADB Device"
```
