### DISCUSSION TITLE
set vars with another vars

### DISCUSSION THREAD

**Discussion by knsh14** [go-task/task#505] [Q&A] [answered]
I try to make vars like below

```
version: 3

vars:
  FOO: foo
  BAR: bar
  FOOBAR: {{.FOO}}{{.BAR}}

tasks:
  echo:
    cmds:
      - echo {{.FOOBAR}}
```

then executed `task echo` then failed and message is below
```
yaml: line 5: did not find expected key
```

so maybe setting vars.FOOBAR with another var is wrong. 
I want to generate var with other vars like versions. so will this be fixed?
