### DISCUSSION TITLE
Added the ability to change runner and use SSH or a container (Docker)

### DISCUSSION THREAD

**Discussion by JulienBreux** [go-task/task#511] [Ideas]
Hello 👋🏻 

After the proposition of the amazing [import feature](https://github.com/go-task/task/issues/98).

I would to propose an other feature : **The ability to change runner**.

# Proposition

With three possible runners:
- **local**: this is currently used
- **remote**: use the SSH transport
- **container**: use a ~~Docker~~ container image

## Local runner

The local runner is the backward compatible runner currently used in Task.

```
version: '1/2/3'

tasks:
  goVersion:
     cmds:
     - go version
```

## Remote runner

The remote runner use the SSH transport.

```
version: '4'

tasks:
  goVersion:
    remote: ssh://github@github.com:22 # password or key configured via ~/.ssh/config
    cmds:
    - go version
```

## Container runner

```
version: '4'

tasks:
  goVersion:
    image: golang:1.16-alpine
    cmds:
    - go version
```

# Motivation

At @ornikar, all of our tasks files start with `- docker...`

# List of 📌 questions

- ...
- ...
