### DISCUSSION TITLE
what is the difference between the GLOBAL var and env sections?

### DISCUSSION THREAD

**Discussion by amancevice** [go-task/task#537] [Q&A] [answered]
I'm struggling to figure out what the difference between these two GLOBAL sections might be; when to use one over the other, etc.

eg,

```yaml
# Taskfile.yml

version: '3'

env:
  SOME_ENV_NAME: some-env-value

var:
  SOME_VAR_NAME: some-var-value

tasks:
  # …
```
