### DISCUSSION TITLE
Handling a task.status that references another task

### DISCUSSION THREAD

**Discussion by xunholy** [go-task/task#559] [Q&A]
I'm looking for a way to perform a rollback on a deployment that I currently run on kubernetes.

I was anticipating that something like the following would have worked:

```yaml
  rollback:
    cmds:
      - cmd: kubectl rollout undo {{.KIND}}/{{.APP}} -n "{{.NAMESPACE}}"
      - task: status-checks
    status:
      - task: status-checks
```

However, it looks as though the status can't reference another task?

```log
yaml: unmarshal errors:
  line 39: cannot unmarshal !!map into string
```

Is the recommendation to call it as below:

```yaml
  rollback:
    cmds:
      - cmd: kubectl rollout undo {{.KIND}}/{{.APP}} -n "{{.NAMESPACE}}"
      - task: status-checks
    status:
      - task status-checks
```

My main issue with this is that all output captured in the status task are not returned to the caller, I'm guessing maybe because this is running it as a sub-shell or something.
