### DISCUSSION TITLE
Unable to Use Poetry Python Virtualenv

### DISCUSSION THREAD

**Discussion by ProfessorManhattan** [go-task/task#616] [Q&A] [answered]
- Task version: 3.9.0
- Operating System: Ubuntu 20.04

I posted a similar issue before but never really found an answer. I am wondering how people are handling creating/using Python virtualenvs. In the example below, I attempt to source a `bin/activate` but I always get a 127 exit code. In other scenarios where I am successfully getting virtualenvs to source properly, the virtualenv is not maintained since every command seems to be in a new sub-shell and virtualenv requires that it be sourced when a shell first starts. This issue also means that if I have a bash function shared across two tasks, I have to include the function in both tasks since they are different sub-shells. Just wondering what other people are doing to get past these issues..

### Example Taskfile showing the issue

```yaml
---
version: '3'

tasks:
  one:
    cmds:
      - task: two
      - pip3 install ansible

  two:
    interactive: true
    label: three
    desc: Hey
    cmds:
      - poetry env info --path
      - . "/home/hawkz/.cache/pypoetry/virtualenvs/hawkz-iL5HU4tf-py3.9/bin/activate"
```
