### DISCUSSION TITLE
env does not run : may be using vars ?

### DISCUSSION THREAD

**Discussion by patatetom** [go-task/task#639] [Q&A]
hi,
I try for the first time `task` and I can't get it to do what I want.
here is the configuration file I use :
```yaml
version: '3'

env:

  ROOTFS: /tmp/rootfs

tasks:

  default:
    cmds:
      - task --list
    silent: true

  test:
    desc: this is a test
    env:
      PATCH: ./patch.tar.gz
    cmds:
      - tar xvzf $PATCH
    sources:
      - $PATCH
    generates:
      - $ROOTFS/myfile
    method: timestamp
```
`cmds` runs correctly but `sources` (and `generates`) is not taken into account and the task is executed again when it is restarted.
the `.task` folder is not created whatever the `method` used.

I tried `vars` but can't use it afterwards : I always get an error when I run `task`.

the patch being repeated several times (`cmds`, `sources`, etc...) and being able to change in the future, I wish to use a substitute.

thanks for your help, regards, lacsaP.

**Comment by andreynering** [comment]
Hi @patatetom,

Use `vars` and interpolation instead of `env`:

```yaml
version: '3'

vars:
  ROOTFS: /tmp/rootfs

tasks:
  default:
    cmds:
      - task --list
    silent: true

  test:
    desc: this is a test
    vars:
      PATCH: ./patch.tar.gz
    cmds:
      - tar xvzf {{.ROOTFS}}
    sources:
      - '{{.PATCH}}'
    generates:
      - '{{.ROOTFS}}/myfile'
    method: checksum
```

**Comment by patatetom** [comment]
thanks for the quick answer @andreynering.

it works using `vars` as specified, but only when the `checksum` `method` is used.
if I set `method` to `timestamp`, the archive is systematically decompressed even if I use the hard file names (eg. without using `vars`).

here are the three cases : the first one works as expected but not the next two (if I understood the idea of `timestamp`) :
- `vars` and `checksum` is OK :
```yaml
# Taskfile1.OK.yml
version: '3'
vars:
  ROOTFS: ./work/rootfs
tasks:
  default:
    cmds:
      - task --list
    silent: true
  test:
    desc: this is a test
    vars:
      PATCH: ./patch.tar.gz
    cmds:
      - tar xvzf {{.PATCH}}
    sources:
      - '{{.PATCH}}'
    generates:
      - '{{.ROOTFS}}/myfile'
    method: checksum
```
```console
$ rm -rf .task/; rm -rf ./work/; task -t Taskfile1.OK.yml test; task -t Taskfile1.OK.yml test
task: [test] tar xvzf ./patch.tar.gz
./work/
./work/rootfs/
./work/rootfs/myfile
task: Task "test" is up to date
```

- `vars` and `timestamp` is KO :
```yaml
# Taskfile2.KO.yml
version: '3'
vars:
  ROOTFS: ./work/rootfs
tasks:
  default:
    cmds:
      - task --list
    silent: true
  test:
    desc: this is a test
    vars:
      PATCH: ./patch.tar.gz
    cmds:
      - tar xvzf {{.PATCH}}
    sources:
      - '{{.PATCH}}'
    generates:
      - '{{.ROOTFS}}/myfile'
    method: timestamp
```
```console
$ rm -rf .task/; rm -rf ./work/; task -t Taskfile2.KO.yml test; task -t Taskfile2.KO.yml test
task: [test] tar xvzf ./patch.tar.gz
./work/
./work/rootfs/
./work/rootfs/myfile
task: [test] tar xvzf ./patch.tar.gz
./work/
./work/rootfs/
./work/rootfs/myfile
```

- just `timestamp` is KO :
```yaml
# Taskfile3.KO.yml
version: '3'
tasks:
  default:
    cmds:
      - task --list
    silent: true
  test:
    desc: this is a test
    cmds:
      - tar xvzf ./patch.tar.gz
    sources:
      - ./patch.tar.gz
    generates:
      - ./work/rootfs/myfile
    method: timestamp
```
```console
$ rm -rf .task/; rm -rf ./work/; task -t Taskfile3.KO.yml test; task -t Taskfile3.KO.yml test
task: [test] tar xvzf ./patch.tar.gz
./work/
./work/rootfs/
./work/rootfs/myfile
task: [test] tar xvzf ./patch.tar.gz
./work/
./work/rootfs/
./work/rootfs/myfile
```
regards, lacsaP.
