### DISCUSSION TITLE
Interactive CLI choosing mode (interactive task listing with filtering)

### DISCUSSION THREAD

**Discussion by iangregsondev** [go-task/task#641] [Q&A] [answered]
Hi,

It would be really nice to be able to run taskfile in an interactive CLI choice mode.

i.e. A setting for "default" task to show the list of tasks, and using the cursor keys you get to choose and drill down until you find the one you are looking for. so i.e

Show all tasks and drill down into subtasks etc
```
task
```

OR

if I have a list of subtasks under the "exporter" taskfile then running

```
task exporter
```

would display all tasks for "exporter:" (a.k.a filtering)  and allow choosing with the cursor keys or drilling down more i.e.

```
task: Available tasks for this project:
* exporter:build:linux:         Build exporter for Linux
* exporter:build:linux:prod:    Build exporter for Linux (production)
* exporter:build:mac:           Build exporter for Mac
* exporter:build:mac:prod:      Build exporter for Mac (production)
* exporter:release:             Release exporter
* exporter:release:snapshot:    Release exporter
```

exporter is actually a subtask i.e.

```
includes:
  exporter:
    taskfile: ./cmd/exporter/Taskfile.yml
```

Here is an example in the javascript ecosystem. https://www.npmjs.com/package/ntl  , there are many others.

I thought it would be a nice addition.

Great product, by the way, I have dropped makefiles and use this now - everywhere :-)

**Comment by kerma** [comment, marked as answer]
Hello @iangregsondev! You could achieve something like this using fzf:

```
task -l | grep -v 'task: Available' | fzf --prompt="Available tasks: " | awk '{sub(/:$/, "", $2); print $2}' | xargs task
```

It needs a bit more work to get it properly working inside taskfile itself however. 

---
EDIT: Here's a full example that works defined within taskfile itself:

```yaml
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  hello:
    desc: "say hello"
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  default:
    cmds:
      - | 
        selected=$(task -l | grep -v "task: Available" | fzf --prompt="task:")
        echo "$selected" | awk '{sub(/:$/, "", $2); print $2}' | xargs task
    silent: true
```

**Reply by vctls** [reply]
Beautiful :heart: 

You may want to add the flags `-r` and `-o` to `xargs`.
`-r` ensures `xargs` stops if no input is selected, otherwise you may not be able to exit your command if you're using the default task because `xargs` will keep calling `task`, even if you `ctrl-C`.
`-o` opens a TTY, which may be necessary if your selected task expects a terminal.

Also, I replaced `awk` with `sed`: `sed -E 's/\* (.*?):\s.*$/\1/'`
Splitting by column isn't compatible with included files, since the tasks will be prefixed by `include_name:`.

This is my final variation:
```bash
# Fetch the list of all the tasks,
# only keep lines for actual tasks,
# remove initial asterisk and tailing column,
# pipe through fzf for fuzzy matching,
# extract the actual command from the full line,
# send the command to task through xargs.
task -a | grep --color=never '*' \
      | sed 's/\* //;s/: //;s/  //' \
      | fzf --prompt="Available tasks: " \
      | sed -E 's/(\w+)\s.*$/\1/' \
      | xargs -ro task
```

I couldn't make the original colors work though pipes, so I added this to the global variables:
```yaml
vars:
  # ANSI escape sequences
  ESC:
    sh: "printf '\\033'"
  NC: '{{.ESC}}[0m'
  RED: '{{.ESC}}[0;31m'
  BLUE: '{{.ESC}}[0;34m'
```
The variables can be used in `sed` and other commands.  
Complete list of colors, among other sequences: https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
