### DISCUSSION TITLE
defer example doesn't work at all

### DISCUSSION THREAD

**Discussion by psalty** [go-task/task#650] [Q&A] [answered]
Am I missing something?
I copied the defer example from the usage, and it doesn't seem like work.
Anybody tried?

```
version: '3'

tasks:
  default:
    cmds:
      - mkdir -p tmpdir/
      - defer: rm -rf tmpdir/
      - echo 'Do work on tmpdir/
```
