### DISCUSSION TITLE
Is it possible to set an OS environment variable and use it in a different task?

### DISCUSSION THREAD

**Discussion by ezerw** [go-task/task#660] [Q&A] [answered]
Hi, I'm trying to run some commands in a task that should set some environment variables and then use those in another task. e.g

```yaml
tasks:
  task_a:
      cmds:
          - sh: export TESTING=something
  task_b:
      cmds:
          - sh: `command that assumes $TESTING is set`
 ```
But it doesn't seem to set it. I'm assuming tasks runs in a different subshells? any workaround?
Basically its for authenticate with AWS, first task will do the login and the second needs to see `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` are available

**Comment by kerma** [comment, marked as answer]
Environment handling is a bit of a weak point of task. However there are various ways how to achieve what you're after.

1. Login in the same shell

```yaml
task_b:
  cmds:
    - |
      test ! -z "$AWS_ACCESS_KEY_ID" && login.sh
      real_command
```

2. Use https://github.com/99designs/aws-vault (which is probably what you should do)

There is some background reading on this topic in various issues, like
* https://github.com/go-task/task/issues/277
* https://github.com/go-task/task/issues/593
* https://github.com/go-task/task/issues/630
