### DISCUSSION TITLE
Shouldn't an out-of-date dependency trigger an otherwise up-to-date task?

### DISCUSSION THREAD

**Discussion by ConX** [go-task/task#669] [Q&A] [answered]
Hi everyone,

First of all, thanks for the great tool!

I just noticed that when a dependency is out-of-date, that doesn't necessarily trigger the target task. The scenario that I have is that of a target task (T) that generates some files and requires a file generated by another task (A). The way I tried to implement that was by listing the task (A) as a dependency of (T) and also listing sources and generates for the task (T). I expected that if task (A) is out-of-date, that will trigger task (T) as well, but that isn't the case.

I assume that I can list the file generated by task (A) in the sources of (T), and that will fix the issue, but I am curious why this isn't implied, given that (A) is a dependency of (T). What is a scenario for which the current approach is desired?

Here is a minimal reproducible example that uses `status`  instead of files:

```
version: "3"

tasks:
  first-dep:
    cmds:
      - echo First
    status:
      - "exit 1"

  second-dep:
    cmds:
      - echo Second
    status:
      - "exit 0"

  target:
    cmds:
      - "echo Target"
    deps:
      - first-dep
      - second-dep
    status:
      - "exit 0"
```

and here is the output that I get:

```
$task target
task: Task "second-dep" is up to date
task: [first-dep] echo First
First
task: Task "target" is up to date
```

**Comment by ConX** [comment]
I forgot to mention that I would work on a PR if allowing for such behavior (other by default or through an option) is something others find useful.

**Reply by ghostsquad** [reply]
I believe that whether or not a dependency changes is irrelevant unless you specify that it is relevant. The default behavior is to run a task everytime unless you tell go-task that it shouldn't run via status. The example provided is unfortunately not very useful to me to really dig deeper into this use case.

Here's an example that may be useful:

TaskA generates fileA
TaskB consumes fileA and generates fileB

In this case, taskB does in fact depend on the output of taskA via fileA.

TaskB should then use FileA as a way to determine if it should run.

Do you have another scenario that we can explore together?

**Reply by ghostsquad** [reply]
Maybe the issue is that 99% of the time, if a dependency changes, the current task needs to run? I'm not sure that's true.

If it is true, then setting up status/sources/generates becomes tedious boilerplate.

I am very curious about the specific situation you are trying to optimize.

**Reply by ConX** [reply]
I agree that when all tasks generate a single output file and have a list of file sources it's usually not unreasonable to write a chain of `sources` and `generates` statements to achieve the dependencies. Though, having to do that manually, especially in long chains of tasks, I believe diminishes the power of the `deps` which can serve as an abstraction mechanism, that does not require tracking file names (to populate `sources` and `generates`), but rather using the user-friendly custom task aliases.

Where it starts becoming tedious is when tasks use programmatic checks to determine if they should run or not and do not generate files.  

Here is a three-task pseudo-code example for demonstration:
```
task archive:
  cmd: tar to archive files
  sources: src_file1, src_file2
  generates target.tar.gz
task build-cloud-instance-image:
  cmd: <cloud image builder>
  sources target.tar.gz
task cloud-deploy:
  cmd: <deploy cloud instance with latest image>
  status: check if an instance already exists
  deps: build-cloud-instance-image
```

In this case above, the first time when `task cloud-deploy` is invoked everything will run as expected. Now, let's assume that we update the file `src_file1` and invoke `task cloud-deploy` again. This would make tasks `archive` and `build-cloud-instance-image` run but since the instance already exists task `cloud-deploy` will be skipped. With the current implementation, this can be fixed by adding the `target.tar.gz` file in the sources of `cloud-deploy` or by programmatically tracking if the image has been updated since the last run. My original expectation of `deps` was that since one or more dependencies had to be executed so should the current task.

> Maybe the issue is that 99% of the time, if a dependency changes, the current task needs to run? I'm not sure that's true.

I am also not sure! I just can't think of a scenario where it would be desired for the current task to be skipped when a dependency has changed. Moreover, there is a already mechanism to support this behavior that better reflects the use of the terms "current task" and "dependency." For example, in the case above, if I didn't want the `cloud-deploy` to run, and I only wanted to rebuild the cloud instance image, I would simply invoke `task build-cloud-instance-image` instead.

**Reply by ghostsquad** [reply]
Right, so I think you got the nail on the head, but maybe didn't realize it. `cloud-deploy` should be an idempotent operation.

Meaning, I would explicitly _not_ give this a `status`. The script that deploys the instance should have all the logic in place to do the following:

1. If the instance does not exist, create it
2. If the instance already exists, check if the relevant source files have changed.
2a. If the source files or other attributes have changed, perform an operation to bring the deployed instance in line with new desired state.
2b. If desired state (source files) match what has been deployed, exit with code 0 (and a helpful message that everything is up-to-date)

If you are familiar with Terraform or Pulumi, this is what they do when you run `apply` or `up`, respectively.

Kubernetes also does this operation continuously. The manifests applied represent the desired state. Kubernetes is a reconciliation engine that is constantly evaluating the current state and trying to converge it to the desired state.

You _could_ use go-task in a similar way, by decoupling the scripts to check if an update is needed, from the scripts that update the instance, but I don't think that's actually the best idea. There will likely be duplication in that, and the result would be the same anyways.

TLDR: make `cloud-deploy` idempotent.

**Reply by ConX** [reply]
That's why I initially tried to avoid giving a specific example, as my goal wasn't to find a solution to my specific case.

You must agree that all of what you describe above can be more easily resolved by having a change in one of the dependencies, trigger the dependent tasks.

The reason I started this discussion topic, is to understand why this isn't the current behavior and what are the downsides of making that change, if any. Could you provide an equivalent real-life example where the current behavior of skipping the target task is desired despite the execution of its dependencies?

**Reply by ConX** [reply]
@ghostsquad Expanding from the example you gave in your first comment, below is another code that I hope better illustrates the point I am trying to make.

```
version: "3"

tasks:
  create-dummy-files:
    cmds:
      - |
        for i in `seq 5`; do
          echo "${i}" >> "file${i}"
        done;

  modify-file1:
    cmds:
      - echo {{.RANDOM}} > file1
    vars:
      RANDOM:
        sh: date +%N|sed s/...$//

  task1:
    cmds:
      - cat file1 file2 > file6
    sources:
      - file1
      - file2
    generates:
      - file6

  task2:
    cmds:
      - cat file3 file4 > file7
    sources:
      - file3
      - file4
    generates:
      - file7

  task3:
    cmds:
      - cat file5 file6 file7 > file8
    sources:
      - file5
    deps:
      - task1
      - task2
```

The first two tasks are there just for convenience generating the files. The demo would be something like this:

1. `task create-dummy-files`
2. `task task3` (Should run everything as expected)
3. `task task3` (Everything gets skipped as it's up-to-date)
4. `task modify-file1`
5. `task task3` (Should run `task1` and `task3`)

My question is why does `task3` require both the `deps` and the `sources` to be defined to achieve this?  I understand that `deps` is necessary in order for `task1` and `task2` to be evaluated and run if needed. But doesn't that alone infer _"in order to run `task3` you need whatever `task1` and `task2` are generating/doing?"_ If so, why the redundancy of having to specify the sources? If not, what is an example of where the dependencies would need to be executed, but the target task should be skipped?
