### DISCUSSION TITLE
Equivalent to pattern rules?

### DISCUSSION THREAD

**Discussion by mohamed--abdel-maksoud** [go-task/task#686] [Q&A]
I tried to find this in the documentation to no avail. What is Task's equivalent to pattern rules? e.g.
```
%.dat : books/%.txt countwords.py
	python countwords.py $< $*.dat

```

**Comment by andreynering** [comment]
Hi @mohamed--abdel-maksoud,

This is still missing in Task. One of the oldest issues at the repository contains a proposal to address something similar:

https://github.com/go-task/task/issues/82#issuecomment-353057649

Let me know if you have thoughts about the proposal.

**Reply by mohamed--abdel-maksoud** [reply]
Hi @andreynering 
Thanks for the answer (and for the amazing tool that is Task!)
My 2c: the `foreach` syntax is quite elegant, the only issue I see is that it doesn't expose its targets (i.e. what it generates). If it supports the special wildcard `%` like Make does, it'd solve the issue. E.g.
```yaml
create_pdf:
  sources: print/%.ps    # e.g. print/magazine.ps
  generates: print/%.pdf
  foreach: true
  cmds:
    ps2pdf "{{.SOURCE}}"
publish:
  deps: ["print/magazine.pdf"]
  cmds:
    sftp put print/magazine.pdf <some server>
```
