### DISCUSSION TITLE
Complex task string having VARS ENV vars and CLI_ARGS in the same command

### DISCUSSION THREAD

**Discussion by a1exk-dev** [go-task/task#690] [Q&A]
Hi, all!
Part of my `.env` file:
```
###< DOCKER ENV SETUP ###
# general ###
APP_NAME=app_name
APP_DIR=project_folder
APP_USERNAME=a1ex-k
CONTAINER_PREFIX=project_name
```

I have a main task file which is mostly used for including other task files:
```yaml
version: '3'

output: prefixed

env:
  ENV: dev

vars:
  DOCKER: docker
  POSTGRES: postgres

dotenv: ['.env', '.env.{{ENV}}']

includes:
  docker: ./taskfiles/DockerTasks.yaml
  app: ./taskfiles/SymfonyTasks.yaml

tasks:
```
one of included files:

```yaml
version: '3'

vars:
  APP: app

tasks:
  exec:
    desc: description here
    cmds:
      - "{{.DOCKER}} exec -it $CONTAINER_PREFIX.{{.APP}} {{.CLI_ARGS}}"
```

When I run this task `$CONTAINER_PREFIX` env var is not parsed from `.env` file:

```bash
task app:exec -- /bin/bash
task: [app:exec] docker exec -it $CONTAINER_PREFIX.app /bin/bash
```

Can I do something to make `$CONTAINER_PREFIX` parsed from `.env` file?
