### DISCUSSION TITLE
{{.CLI_ARGS}} passed to dependencies

### DISCUSSION THREAD

**Discussion by AntoinePrv** [go-task/task#692] [General]
Hello and thank you for this project!

Right now, `{{.CLI_ARGS}}` are passed to dependencies, for example with two tasks:

```yaml
tasks:
  foo:
    cmds:
      - echo from foo {{.CLI_ARGS}}
  bar:
    deps:
      - foo
    cmds:
      - echo from bar {{.CLI_ARGS}}
```
```shell
$ task bar -- Hello
task: [foo] echo from foo Hello
from foo Hello
task: [bar] echo from bar Hello
from bar Hello
```

Is this default on purpose? I think in most cases dependencies would be a different command and it would not make sense to share CLI args.

**Context:**
```
Task version: v3.11.0 (h1:eCcCe1cKyta4YnGQYLo2FriPS9h7fFS8XBVW6QvWEV4=)
````
