### DISCUSSION TITLE
Overriding A Task Variable From Within A Task

### DISCUSSION THREAD

**Discussion by prodigy-byron-jones** [go-task/task#731] [Q&A] [answered]
This may be a silly question, but I can't seem to glean the answer from the docs and would greatly appreciate the clarity.

I find myself not understanding how to programmatically update a Task variable from within a Task. This results in scenarios where I have to cast the variable to an ordinary bash variable. Is there a right way to do this?

Given a root Task variable of:
```
vars:
  PARAMETER_NAME: "/{{.SYSTEM_NAME}}/${TERRAFORM_VARIABLE}"
```

Below is an example of me having to introduce a new local bash variable. 
```
  example:
    cmds:
      - |
        if [ -z "{{.TERRAFORM_VARIABLE}}" ]
        then
          PARAMETER_NAME="{{.OTHER_PARAMETER_NAME}}"
        else
          PARAMETER_NAME="{{.PARAMETER_NAME}}"
        fi
        echo "${PARAMETER_NAME}" 
        echo "{{.PARAMETER_NAME}}"
```

Thank you,

**Comment by ghostsquad** [comment, marked as answer]
Vars cannot be updated per se, they can only be overwritten. Unfortunately, the way vars currently work is that you don't actually get access to the value as it is declared in a higher scope, if you declare a var in a child scope with the same name.

The recommended approach is to declare a new var (different name) and then reference the global var.

Here's an example:

```yaml
vars:
  PARAMETER_NAME: "/{{.SYSTEM_NAME}}/${TERRAFORM_VARIABLE}"

tasks:
   example:
      vars:
        DERIVED_PARAMETER: |
           {{if (eq .TERRAFORM_VARIABLE "")}}{{.OTHER_PARAMETER_NAME}}{{else}}{{.PARAMETER_NAME}}{{end}}
      cmds:
      - echo '{{.DERIVED_PARAMETER}}'
```
