### DISCUSSION TITLE
Q: Does a Taskfile permit inline subtasks?

### DISCUSSION THREAD

**Discussion by fj** [go-task/task#739] [Q&A] [answered]
Is something like the following possible:

```yaml
tasks:
  sync:
    tasks:
      up: "rsync a b"
      down: "rsync b a"
```

with the aim of being able to do, e.g., `task sync:up` or `task sync:down`? In other words, are _inline_ sub-tasks permitted? I see references to "sub-tasks" in the documentation but no documentation about how to create one directly -- it seems like you generally have to have separate files.

**Comment by ghostsquad** [comment]
In short, yes. Check out the document for more information.

```yaml
tasks:
  up:
     cmds:
     - echo "up"
  down:
     cmds:
     - echo "down"
  sync:
     cmds:
     - task: up
     - task: down
```

**Reply by fj** [reply]
I don't think this is the same thing. This would create three tasks:

  * a task called `up`
  * a task called `down`
  * a task called `sync` which calls `up` and `down`.

What I want is actually:

  * a task called `sync:up`
  * a task called `sync:down`

Including tasks from another file does this automatically; I was wondering if there's a way to do this inline.

**Comment by andreynering** [comment, marked as answer]
I'm not sure what you mean by "sub-tasks", but you can declare tasks with names like `docker:start` / `docker:stop` / etc (including an external Taskfile also does this automatically).

Also, it's possible to forward extra arguments to a command by doing this: https://taskfile.dev/#/usage?id=forwarding-cli-arguments-to-commands

**Reply by fj** [reply]
> I'm not sure what you mean by "sub-tasks"

This is by analogy to subcommands (e.g. `git commit`) or other task managers which have similar features. For example, Ruby's `rake` has a similar idea:

```ruby
namespace "main" do
  task :build do
    # Build the main program
  end

  # other main-specific tasks
end

namespace "samples" do
  task :build do
    # Build the sample programs
  end

  # other sample-specific tasks
end

namespace "docs" do
  task :build do
    # Build the sample programs
  end

  # ... other doc-specific tasks
end
```

This produces three tasks, `main:build`, `samples:build`, and `docs:build`. You could then have, say, `task build-all: "main:build", "samples:build", "docs:build"`. Does that make sense?

**Comment by fj** [comment]
I think @andreynering's suggestion about just naming the tasks that way and hardcoding it is probably the most sensible approach for now. Thank you!

**Comment by slava-nikulin** [comment]
Including external task files is fine because the vscode extension displays the task list as a tree, but it's not very convenient because of the need to split tasks into folders. Especially if tasks are small
![image](https://github.com/user-attachments/assets/f88f9336-6673-4185-801d-e70cf449fa42)

**Comment by kennylajara** [comment]
Had the same issue: "I want to have namespaces but I don't want to create more files".

I found a workaround:

```
tasks:
  "test:all":
    desc: Run all tests
    dir: '{{.PROJECT_DIR}}'
    cmds:
      - poetry run pytest tests/ -v {{.CLI_ARGS}}

  "test:unit":
    desc: Run unit tests only
    dir: '{{.PROJECT_DIR}}'
    cmds:
      - poetry run pytest tests/unit/ -v {{.CLI_ARGS}}

  "test:integration":
    desc: Run integration tests only
    dir: '{{.PROJECT_DIR}}'
    cmds:
      - poetry run pytest tests/integration/ -v {{.CLI_ARGS}}
```
      
> The only "caveat" is that you cannot have a "test"-only task, you'll always need a suffix
