### DISCUSSION TITLE
`sh` in `vars` is inconsistently chomping linebreaks compared to `cmds`?

### DISCUSSION THREAD

**Discussion by fj** [go-task/task#761] [Q&A]
I'd like to write this:

```yaml
vars:
  ASSETS_SYNC_SESSION_KEY:
    sh:
      >
        AWS_SECRET_ACCESS_KEY={{.AWS_SECRET_ACCESS_KEY}} \
        AWS_ACCESS_KEY_ID={{.AWS_ACCESS_KEY_ID}} \
        aws sts get-session-token
```

but instead I get:

```
" AWS_ACCESS_KEY_ID=not-implemented": executable file not found in $PATH
task: Command "AWS_SECRET_ACCESS_KEY=not-implemented \ AWS_ACCESS_KEY_ID=not-implemented \ aws sts get-session-token
" failed: exit status 127
# fails, treated as one line with no line breaks
```

This seems to happen because the parsing of `sh:` is deleting the linebreaks. I expected that the multiline YAML here would work the same way as it does with `cmds` -- this works, for example:

```yaml
tasks:
  example:
    cmds:
      - >
        AWS_SECRET_ACCESS_KEY={{.AWS_SECRET_ACCESS_KEY}} \
        AWS_ACCESS_KEY_ID={{.AWS_ACCESS_KEY_ID}} \
        aws sts get-session-token
        # above works as expected, treated as three lines
```

Is this a bug or is this the expected behavior?
