### DISCUSSION TITLE
Documenting use with tools like virtualenv, rvm or nvm that modify path

### DISCUSSION THREAD

**Discussion by ssbarnea** [go-task/task#773] [Ideas]
There are tools like python `virtualenv/venv` or node `nvm` which do not magically work with taskfile by default because they require a shell, and because they modify various environment variables when run, especially PATH.

I use both virtualenv and nvm and I have tasks where I need to use particular versions of either nvm or virtualenv, basically activating them at start.

With python virtualenv is relatively ok but with nvm is becomes far more complex, especially as nvm itself is a shell function and not an on disk executable.

I opened this thread so we can investigate how these tools can be used with taskfile and document them, making easier for others to use them. Maybe in the longer run we can even think about what changes we can to to taskfile itself to make it easier to use virtual environment managers (the category of these tools).

Usage examples found so far:

* virtualenv/venv:
  * ~100 users of venv listed at https://sourcegraph.com/search?q=context:global+file:Taskfile.yml+venv&patternType=literal - i need to look at more to pick the version that i find most flexible.
* nvm:
  * Only 1 listed by https://sourcegraph.com/search?q=context:global+file:Taskfile.yml+nvm&patternType=literal - nead use of vars but is buggy as it not portable. At least on M1 macos, nvm install path is different so the hardcoded values would not work. Also current example does only activate the local node version from repository `.nvmrc` file and does not allow taskfile to decide which version to activate.

**Comment by ghostsquad** [comment]
I would suggest ASDF. It is far superior to nvm and others.

**Comment by ayasechan** [comment]
this is the way how i work with venv

```yaml
version: '3'

vars:
  printpy: python -c "import sys; print(sys.executable)"

tasks:
  default:
    cmds:
      - pdm run {{.printpy}}
      - task: venv
        vars:
          content: '{{.printpy}}'

  venv:
    silent: true
    cmds:
      - |-
        bash << 'eof'
        eval $(pdm venv activate)
        {{.content}}
        eof
```

**Comment by apastuhov** [comment]
Just if someone will end-up here. For venv I come up with pretty simple solution:

```
# Define a precondition to check if the virtual environment is activated
venv-precondition: &venv
  - sh: test $(whereis -q pip) -ef ./venv/bin/pip
    msg: "You forgot to run\n. ./venv/bin/activate\n"


tasks:
  setup-venv:
    desc: "Setup python virtual environment"
    cmds:
      - rm -rf ./venv
      - python3 -m venv ./venv
      - echo "Don't forget to run\n. ./venv/bin/activate"

  setup:
    # Assign a precondition to specific task
    # so if you accidentally forgot to activate venv - task will fail
    preconditions: *venv
    cmds:
      - pip install -r requirements.tx
```
