### DISCUSSION TITLE
Is there any way to run task w/o running its dependencies?

### DISCUSSION THREAD

**Discussion by mbergal** [go-task/task#787] [General]
Will be very useful when writing Taskfiles where deps are very heave and long to run

**Comment by ghostsquad** [comment]
The general pattern is to encode logic in your dependent tasks that will indicate whether or not that task needs to run. This is done through `sources` and `generates` and/or `status`.

https://taskfile.dev/usage/#using-programmatic-checks-to-indicate-a-task-is-up-to-date

https://taskfile.dev/usage/#by-fingerprinting-locally-generated-files-and-their-sources

Related #788

**Reply by mbergal** [reply]
I guess I wasn't clear enough in my original posting. Suppose I have `Taskfile` like:

```
clean:
 ....
clone:
   deps: clean
   ...
build:
   deps: clone
   
```

I am debugging cmds for task `build`. I don't want `clean` and `clone` to be run on `task build`. I just want to `task --only build` to run my `build` step w/o running `clean` and `clone`. This is for `Taskfile` development purposes only, I am not intending to use it in any other circumstances.

**Reply by ghostsquad** [reply]
Make a task with no deps. Make another task that uses this one in `cmds` and has deps.

```yaml
tasks:
  clean: ...
  build-only: ...
  build:
    deps: 
    - clean
    cmds:
    - task: build-only
```
