### DISCUSSION TITLE
Staged parallel runs

### DISCUSSION THREAD

**Discussion by misuzu** [go-task/task#821] [Q&A] [answered]
I want something weird.

I have `A.yml`, `B.yml` and `C.yml` files with following content:
```yml
version: '3'

output: 'prefixed'

tasks:
  build:
    cmds:
      - build command

  deploy:
    cmds:
      - deploy command
```

I'm using these files in main taskfile:
```yml
version: '3'

includes:
  a:
    taskfile: ./A.yml
  b:
    taskfile: ./B.yml
  c:
    taskfile: ./C.yml

tasks:
  a:
    cmds:
      - task: a:build
      - task: a:deploy

  b:
    cmds:
      - task: b:build
      - task: b:deploy

  c:
    cmds:
      - task: c:build
      - task: c:deploy

  all:
    deps:
      - task: a
      - task: b
      - task: c
```

Is it possible to first run `a:build` `b:build` and `c:build` in parallel and if there is no errors run `a: deploy` `b: deploy` and `c: deploy` also in parallel when I'm starting task `all`?

**Comment by andreynering** [comment, marked as answer]
Hi @misuzu,

I hope all is well with you and your family in Ukraine!

You need to declare extra tasks to achieve that:

```yaml
tasks:
  build-all:
    deps: [a:build, b:build, c:build]

  deploy-all:
    deps: [a:deploy, b:deploy, c:deploy]

  all:
    - task: build-all
    - task: deploy-all
```

A bit of duplication if you also need the old tasks, but it does the trick.
