### DISCUSSION TITLE
Precondition on empty CLI argument

### DISCUSSION THREAD

**Discussion by rtubio** [go-task/task#849] [Q&A] [answered]
I am trying to avoid running a task whenever the parameter required to be passed on form the command line is not given.
In order to do this, I am currently trying to use a precondition with a string test in shell as follows:

```
task:
  summary: |
    My awesome task, required arguments:
    * name : gimme an awesome name, please!
  preconditions:
    - sh: "[ -z {{.name}} ]"
      msg: "Need to provide the branch name as an argument"
  cmds:
    - echo {{.name}}
```

I am currently using "shell" evaluation since trying to use "len" to evalute the length of the string did not work either.
My current understanding is that the usage of the Go template inside the definition of the sh command might not be working well; however, I have no way to check what is the output of the execution of that shell command.

- Any suggestions about how to do this?
- Is there an standard way of doing argument checking for a given task?
