### DISCUSSION TITLE
How to run the same task with different vars?

### DISCUSSION THREAD

**Discussion by Kludex** [go-task/task#916] [Q&A]
Hi there :wave: 

I have the following `Taskfile.yml`:

```yml
version: "3"

tasks:
    run-server:
        cmds:
            - /venv/bin/uvicorn src.cases.{{.case}}.main:app

    load-test:
        desc: Load test the server, and output the results to a file.
        cmds:
            - mkdir -p reports/{{.case}}
            - /venv/bin/locust --headless --users 20 --spawn-rate 2 -H http://127.0.0.1:8000 -t 60s --csv reports/{{.case}}/report.csv --html reports/{{.case}}/report.html
            - kill $(lsof -t -i:8000)

    benchmark:
        deps:
            - task: run-server
              vars: { case: '{{.case | default "simple"}}' }
            - task: load-test
              vars: { case: '{{.case | default "simple"}}' }

    all:
        cmds:
            - task: benchmark
              vars: { case: "simple" }
            - task: benchmark
              vars: { case: "add_uvloop" }
            - task: benchmark
              vars: { case: "add_httptools" }
            - task: benchmark
              vars: { case: "uvloop_and_httptools" }
```

Is there a way, on the `all` task, to make it more cute? I will have to add many more to this list, and I was wondering if there's a better way to do it. :eyes: 

Thanks in advance! :pray:

**Comment by andreynering** [comment]
Hi @Kludex,

I think you've done the right thing. Don't really have suggestions on how to improve that.

Other than syntax, maybe. Our [styleguide](https://taskfile.dev/styleguide/#use-upper-case-variable-names) suggests `UPPER_CASE` variable names instead of `lower_case`. We suggest 2-space indentation as well.

Also, if you prefer, you could indent like this (but that's personal opinion and there's no right answer):

```yaml
all:
  cmds:
    - task: benchmark
      vars:
        CASE: simple
    - task: benchmark
      vars:
        CASE: add_uvloop
    - task: benchmark
      vars:
        CASE: add_httptools
    - task: benchmark
      vars:
        CASE: uvloop_and_httptools
```
