### DISCUSSION TITLE
Is it possible to use a task to set a dynamic variable?

### DISCUSSION THREAD

**Discussion by pietro** [go-task/task#925] [Q&A]
I have a few tasks that use a similar command to set a dynamic variable. I would like to abstract that command into an internal task instead of repeating it. 

Example:

```yaml
version: "3"

tasks:
  one:
    cmds:
      - task one command "{{.Some_VAR}}"
    vars:
      SOME_VAR:
        sh: some var command --argument task-one-example

  two:
    cmds:
      - task two command "{{.Some_VAR}}"
    vars:
      SOME_VAR:
        sh: some var command --argument task-two-example
```

I'd to either use a task to set `SOME_VAR` or call a task in my `cmds` or as in my `deps` and have that set `SOME_VAR`. Is this possible?

Thanks.

**Comment by wtfzambo** [comment]
I don't think it's possible yet.
The only workaround I found was to either:

- Make the task public and define the variable calling it as if you were using the CLI, e.g.:
```
SOME_VAR:
  sh: 'task my_task`
```
- Use an internal task and output the value to a temporary file, keeping track of the temp file path (probably useful only in certain cases).

**Comment by pd93** [comment]
I could be missing something here, but can you not just define the `var` globally and reuse it in both tasks?

```yaml
version: "3"

vars:
  SOME_VAR:
    sh: some var command --argument task-one-example

tasks:
  one:
    cmds:
      - task one command "{{.Some_VAR}}"

  two:
    cmds:
      - task two command "{{.Some_VAR}}"
```
