### DISCUSSION TITLE
Command-level dir (or cd)?

### DISCUSSION THREAD

**Discussion by MadL1me** [go-task/task#940] [Q&A] [answered]
Hi.

Today faced a problem with directory changing. I didn't found any docs examples or github issues, so sorry if I mistaken something.
Very often, then I use task, I need to switch folders, in which is task performed. For example, do 3-4 command in one directory, then change directory and do another 2-3 command relative to the new directory. Currently, I accomplish this logic this way:

```yaml
tasks:
  create:
    cmds:
      - |
        cd 'Level X\nupkg\'
        pwd
        rm *.nupkg
        cd '..'
        dotnet pack
```

But I dont like it, because I'm basically smash all commands together into one. Is there a way to do something like this:

```yaml
tasks:
  create:
    cmds:
        - cd 'Level X\nupkg\'
        - pwd
        - rm *.nupkg
        - cd '..'
        - dotnet pack
```

or

```yaml
tasks:
  create:
    cmds:
        - dir: 'Level X\nupkg\' 
        - pwd
        - rm *.nupkg
        - dir: '..'
        - dotnet pack
```

Thank you for your attention

**Comment by pd93** [comment, marked as answer]
Each Task command is executed in isolation (i.e. its own shell) and so a `cd` in one command will not affect the directory of any subsequent commands. This isolation is by design and cannot be changed.

Unfortunately, there is no `dir` keyword at a `cmd` level either, so you also can't currently do anything like your second suggestion. However, I think this would be a valid feature request and would probably look something like this:

```yaml
# Does not work in 3.18
tasks:
  create:
    cmds:
      - cmd: pwd
        dir: 'Level X\nupkg\'
      ...
```

The `dir` keyword _is_ available at a task level though, so you could do something like this today:

```yaml
tasks:
  remove-and-create:
    cmds:
      - task: remove
      - task: create
   
  remove:
    dir: 'Level X\nupkg\'
    cmds:
      - pwd
      - rm *.nupkg
  
  create:
    dir: 'Level X'
    cmds:
      - dotnet pack
```
