### DISCUSSION TITLE
Serial calling and deps task

### DISCUSSION THREAD

**Discussion by aweseeker** [go-task/task#954] [Q&A]
Hi Team,

In Taskfile, serial calling and deps both not calling other task with their respective sequence, that is serial task not calling next task serially instead concurrently and deps defined task starts running before completing the deps task. Kindly advice here.
Attached both examples.

In my case the task I am going to run for satisfying deps are bit time consuming task takes around 60 secs, but before finishing this task the dependent caller task starts executing, same scenrio applies for serial call, task 1 is time consuming, so before completing task 1 task 2 get called. I expect task2 should start after finishing task1. Any chance we can mention kind of wait time or sleep?

Taskfile.yaml - for serial ex
Taskfile.yml - for deps ex.
[ExFiles.zip](https://github.com/go-task/task/files/10239312/ExFiles.zip)

**Comment by aweseeker** [comment]
In my case the task I am going to run for satisfying deps are bit time consuming task takes around 60 secs, but before finishing this task the dependent caller task starts executing, same scenrio applies for serial call, task 1 is time consuming, so before completing task 1 task 2 get called. I expect task2 should start after finishing task1. Any chance we can mention kind of wait time or sleep?

**Comment by theunrepentantgeek** [comment]
Burying your examples in a zip file makes it harder for anyone to review them. For other readers, here they are:

Taskfile.yml
```
version: '3'

tasks:
  main:
    cmds:
      - task: buildGRA
      - task : copyGRA
  copyGRA:
    deps: [buildGRA]
    cmds:
      - robocopy C:/Users/release/tomcat/ C:/Users/psankara/GRA/Docker/gra gra.war
      
  buildGRA:
    dir: C:/Users/GRA/Docker/gra/src/production
    cmds:
      - C:/Users/GRA/Docker/gra/src/production/build_brgui.bat
```

Taskfile.yaml
```
version: '3'

tasks:
  copyGRA:
    deps: [buildGRA]
    cmds:
      - robocopy C:/Users/release/tomcat/ C:/Users/psankara/GRS/Docker/gra gra.war
      
  buildGRAT:
    dir: C:/Users/GRA/Docker/gra/src51/production
    cmds:
      - C:/Users/GRA/Docker/gra/src51/production/build_brgui.bat
```

My guess would be that your batch file `build-brgui.bat` is exiting before the launched programs are complete.

Add `echo Done` to the end of the batch file; my guess is that you'll see that `echo` command show up well before the build finishes.
