### DISCUSSION TITLE
Is there any way to define a file scoped variable?

### DISCUSSION THREAD

**Discussion by mythay** [go-task/task#981] [Q&A] [answered]
I want to define a variable only can be seen in a Taskfile scope, then the variable can be shared by different task in the single Taskfile, and other Taskfile can also use the same name to refer a different variable. Is there any way to do this?

The initiate is that I have a project that need to build multiple packages, the folder structure looks like:

topdir/Taskfile.yaml
      |----package1/Taskfile.yaml
      |----package2/Taskfile.yaml

I found if I write the taskfile in the following style:
```yaml
version: '3'
vars:
  NAME: 'package1'

tasks:
  default: 
    cmds: 
      - echo deploy {{.NAME}}
  build: 
    cmds: 
      - echo build {{.NAME}}
```

The variable `NAME` become a global variable, and they override each other if I include these two files in the top level taskfile.
