### ISSUE TITLE
Incorrect type error in schema.json when using the `output` mode

### ISSUE THREAD

**Issue by nik-steinebrunner** [go-task/task#1005]
Hi,
This line [(click here)](https://github.com/go-task/task/blob/master/docs/static/schema.json#L339) in schema.json causes an "incorrect type" error in Visual Studio Code when we use this output configuration as described in the [documentation](https://taskfile.dev/usage/#output-syntax):
```yaml
output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'
```
![grafik](https://user-images.githubusercontent.com/105271666/217622577-8a53b1da-10ef-40e4-9246-c1f01eeac512.png)
