### ISSUE TITLE
How can I allow task execution only in docker container?

### ISSUE THREAD

**Issue by harobed** [go-task/task#101]
How can I allow task execution only in docker container?

In my Makefile, I have this:

```
.PHONY: tests
tests:
	@if [ ! -f /.dockerenv ]; then echo "Execute it in docker app container"; false; fi
	pytest -v demo_polls/
```

Can I add condition check on tasks?

**Comment by andreynering** [comment]
Hi @harobed,

Did you try?

```yml
version: '2'

tasks:
  tests:
    cmds:
      - cmd: if [ ! -f /.dockerenv ]; then echo "Execute it in docker app container"; false; fi
        silent: true
      - pytest -v demo_polls/
```
