### ISSUE TITLE
Specifying a dotenv breaks special variables

### ISSUE THREAD

**Issue by bergercookie** [go-task/task#1011]
- Task version: 3.20
- Operating System: Ubuntu 20.04

Hi there,

Thanks for this great software, and apologies if the following issue is somehow already mentioned.

I have the following taskfile

```
version: "3"

# dotenv:
#   - taskfile_config.env

vars:
  THIS_REPONAME:
    sh: echo $(basename {{.ROOT_DIR}})

tasks:
  hello:
    cmds:
      - echo "Kalimera {{.ROOT_DIR}}"
```

This works fine and when running `task hello` I indeed get the string with the ROOT_DIR appended.

```
at 16:33:10 ➜ go-task hello -v
task: dynamic variable: 'echo $(basename /home/berger/a)' result: 'a'
task: "hello" started
task: [hello] echo "Kalimera /home/berger/a"
Kalimera /home/berger/a
task: "hello" finished
```

However, uncommenting the `dotenv` section breaks this:

```
version: "3"

dotenv:
  - taskfile_config.env

vars:
  THIS_REPONAME:
    sh: echo $(basename {{.ROOT_DIR}})

tasks:
  hello:
    cmds:
      - echo "Kalimera {{.ROOT_DIR}}"
```

Execution output:

```
berger in spitfire in ~/a took 8ms
at 16:33:10 ➜ go-task hello -v
task: dynamic variable: 'echo $(basename /home/berger/a)' result: 'a'
task: "hello" started
task: [hello] echo "Kalimera /home/berger/a"
Kalimera /home/berger/a
task: "hello" finished
```

Any hints as to what's going wrong there?

Thanks,
Nikos
