### ISSUE TITLE
Possibility to run internal task from `sh` in dynamic variables or as part of a larger command

### ISSUE THREAD

**Issue by wtfzambo** [go-task/task#1028]
> Describe in detail what feature do you want to see in Task.
> Give examples if possible.
>
> Please, search if this wasn't proposed before, and if this is more like an idea
> than a strong feature request, consider opening a
> [discussion](https://github.com/go-task/task/discussions) instead.

Hello,
first of all thanks for this amazing software.

Secondly, I think it would be neat if it was possible to run a task inside an `sh` command when defining a dynamic variable, or as part of a larger command.

I know it's possible to currently run them as if it was a shell command, eg:

```yaml
my_task:
  cmds:
    - do-some-stuff && task my-other-task
  vars:
    MY_VAR:
      sh: >
        task my-other-task
```

But it is impossible for tasks flagged as "internal".

Example usage:

```yaml
do-something-with-file:
  vars:
    FILE_PATH:
      sh: >
        task: find-file
        vars: {FILE_NAME: '{{.FILE_NAME}}'}
  cmds:
    - echo {{.FILE_PATH}}
    # or
    - echo $(task: find-file ...)

find-file:
  internal: true
  cmds:
    - dirname $(find . -name {{.FILE_NAME}}.* || (echo 'File not found' && exit 1)
```

Alternatively, and probably much easier to implement, add a flag in the API that can override the `internal=true` flag, eg.
```bash
task -O find-file FILE_NAME=foo
```
