### ISSUE TITLE
Add task section to describe its input arguments

### ISSUE THREAD

**Issue by nicomeunier** [go-task/task#1063]
It could be nice to have a dedicated section from task section to describe explicitly which are the arguments of the task.

**Current issues:**
- Doing that by variables is a problem because the variables cannot be overwritten.  
- So without the predefined variable, is not obvious an input argument is required without noticing it from its description. It's so error-prone.  
- Using go's template to check if a variable exist or fails otherwise is cumbersome and not readable at all. Example:  
  ```yaml
  my_task:
    vars:
      MY_TASK_ARG: '{{if .MY_TASK_ARG}}{{.MY_TASK_ARG}}{{else}}{{fail "Missing argument MY_TASK_ARG"}}{{end}}'
  ```
- Using go's template to check if a variable exist or use a default value is also cumbersome. Example:
  ```yaml
  my_task:
    vars:
      MY_TASK_ARG: '{{.MY_TASK_ARG | default "my_default_value"}}'
  ```

**Suggestion:**

Having a dedicated `args` section in task section like this:
```yaml
  my_task:
    args:
      MY_ARG_WITH_DEFAULT_VALUE: my_default_value # short-way to define the variable with just a default value
      MY_ARG_REQUIRED:
        required: true
      MY_ARG_WITH_DESCRIPTION:
        desc: argument description that could be printed with `--list`
        default: my_default_value
      MY_ARG_WITH_PREDEFINED_VALIDATOR_INT:
        assert_int: true
      MY_ARG_WITH_PREDEFINED_VALIDATOR_EXISTING_FILE:
        assert_existing_file: true
      MY_ARG_WITH_PREDEFINED_VALIDATOR_ENUM:
        assert_enum: [ option1, option2 ]
        default: option1
      MY_ARG_WITH_CUSTOM_VALIDATOR:
        assert: '{{has . (list "option1" "option2" "option3")}}'
      MY_ARG_WITH_CUSTOM_RANGE:
        assert_int: true
        assert: '{{ and (gt . 0) (lt . 10) }}'
```
Then these arguments could be accessible like variables or environments. But they should be evaluated before variables and environments.
