### ISSUE TITLE
Idea: Consider having functions to access variables and envs

### ISSUE THREAD

**Issue by andreynering** [go-task/task#1065]
This is an idea for the next major version, and would be a breaking change.

Nowadays both variables and envs are accessed as Go template values, like this:

```yaml
{{.MY_VARIABLE}}
{{.MY_ENV}}
```

This have a couple of drawbacks:

1) Variables need to be declared in an specific order if you want to include one into another:

```yaml
FOO: foo
FOOBAR: '{{.FOO}}bar'
FOOBARBAZ: '{{.FOOBAR}}baz'
```

2) Variables and envs are mixed, and this often generate a bit of confusion to users.

3) Shell variables are always computed, even when they are not being used.
    - We also currently cache them, which can be annoying if the user want to calculate it again on every call. On the current implementation removing the cache would not be a good idea, though, because it would calculate these multiple times unnecessarily.

This proposal to have two template functions called `var` and `env` to access these values:

```yaml
MY_VARIABLE: '{{var "MY_VARIABLE"}}'
MY_ENV: '{{env "MY_ENV"}}'
```

As part of these proposal, environment variables would stop being added to variables, so you need to really call `env` if you want an env.

**Comment by andreynering** [comment]
To make this clear: this is an idea, but needs experimentation to see if it would really work as expected.

Also, opinion from users are welcome, specially considering that this is a breaking change and would add work to users that will want to upgrade to the next version.

**Comment by ghostsquad** [comment]
I think this is a great idea. Changing variable access from being a field to a function call enables lazy variables, which is a big pain point right now.

**Comment by ghostsquad** [comment]
> @andreynering what are the problems with:
> 
> > Variables need to be declared in an specific order if you want to include one into another
> 
> This keeps things simple, readable, and maintainable for the user.

I too am interested in this answer. I mentioned in a different issue that task uses a "map" for storing variables, where it really should be using a list/array. Maps inherently don't have an order. Golang even explicitly randomizes map access in loops to discourage any reliance on order. Yet in Task, order of declared keys in variables matters.

**Comment by andreynering** [comment]
@ghostsquad It's not true that Task store vars in a map. It's stored in a ordered map implementation. That's why we're able to make it work correctly.

**Comment by ghostsquad** [comment]
> @ghostsquad It's not true that Task store vars in a map. It's stored in an ordered map implementation. That's why we're able to make it work correctly.

I'm referring to how it's stored in yaml.

**Comment by shakfu** [comment]
As a recent newcomer to `task`, I can confirm that after a few days, I was confused about the differences between `var` and `env` variables and their interpolation and scoping rules, whether they could be used together, and when to use which, and why both are needed...

Concretely, I was translating a part of a Makefile in use to `task` syntax, and was testing what worked and what didn't:

```make
DEPS = build/deps
VCPKG_ROOT = $(DEPS)/vcpkg
VCPKG = $(VCPKG_ROOT)/vcpkg
```
to

```yaml
version: '3'

vars:
  DEPS: build/deps
  VCPKG_ROOT: '{{.DEPS}}/vcpkg'
  VCPKG: '{{.VCPKG_ROOT}}/vcpkg'

env:
  GREETING: Hey, there!
  GREETING2: $GREETING! Friend! 
  # GOODBYE: {{.VCPKG_ROOT}} # this doesn't work: cannot unmarshal !!map into string

tasks:
  default:
    cmds:
      - echo $GREETING
      - echo ${GREETING}
      - echo {{.GREETING}}

      - echo $GREETING2

      - echo $VCPKG_ROOT
      - echo ${VCPKG_ROOT}
      - echo {{.VCPKG_ROOT}}
```
and then running `task`:

```bash
$ task
task: [default] echo $GREETING
Hey, there!
task: [default] echo ${GREETING}
Hey, there!
task: [default] echo Hey, there!
Hey, there!
task: [default] echo $GREETING2
$GREETING! Friend!
task: [default] echo $VCPKG_ROOT

task: [default] echo ${VCPKG_ROOT}

task: [default] echo build/deps/vcpkg
build/deps/vcpkg
```

I initially got bitten with following: 

- The requirement to quote interpolated `var` but not required to do so in the case of an`env`;

- That I could not use a `var` to define to an `env` variable;

- That I should only use `{{.<name>}}` syntax for vars in a `cmd`, 

- That `env` variables can also do interpolation of previously defined `env` variables in a list. 

So in summary, I agree that these small differences of use and inter-use can be confusing for a newcomer, and even now after a few days with the docs, and some testing behind me, I'm still looking for some further clarity on this subject.

I think a big step would be improving the docs and ensuring that both are discussed together at the same time and to highlight what problem each solves, what are the differences, when to use one vs the other, etc. 

With the respect to the solution above, I kind of understand it, but I am slighly confused by the example given to demonstrate its utility:

> This proposal to have two template functions called var and env to access these values:

> ```
> MY_VARIABLE: '{{var "MY_VARIABLE"}}'
> MY_ENV: '{{env "MY_ENV"}}'
> ```

Does the above mean this would be norm?:

```yml
vars:
  a: abc
  b: '{{var "a"}}'

env:
  c: def
  d: '{{env "c"}}'
  e: '{{var "a"}}'
```

While this would certainly eliminate confusion, it makes the interpolation syntax more verbose than that of Makefiles and regular shell interpolation syntax.

May I suggest better docs, a table of differences, an advisory on usage, as a first step...
