### ISSUE TITLE
Watch of Taskfile.yml (reload file)

### ISSUE THREAD

**Issue by misery** [go-task/task#1095]
I like to watch the Taskfile.yml itself. It works that it react on changes but the file won't be reload with the new content of that file.

Maybe Taskfile.yml could be watched by default?

```
version: '3'

interval: 5s

tasks:
  default:
    deps: [first, second]
    sources:
      - Taskfile.yml

  first:
    cmds:
      - echo "First"

  second:
    cmds:
      - echo "Second"
```
