### ISSUE TITLE
Feature: Would be nice to have a more dynamic Taskvar file

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#11]
I think the following would be really nice:

```yaml
GIT_USER: git config user.name
GIT_EMAIL: git config user.email
STATIC_VAR: echo static
```

Also if #7 will be implemented, OS specific Taskvar would be nice.

What do you think?

**Comment by andreynering** [comment]
You can have that currently with:

```yml
setgituser:
  set: GIT_USER
  cmds:
    - git config user.name
```

But I also like your idea. Would be also welcome `vars` attribute of a task. 🤔

**Comment by zbindenren** [comment]
Yes, I am already doing it :-). But it is more verbose and I have to set the dependencies. If you have a lot of vars that means a lot of dependencies.

**Comment by sascha-andres** [comment]
@andreynering I would keep env properties as they are - you can fill in variables there. I think that would complicate stuff.

Regarding vars we could go for a fallback scenario like trying to execute and when it fails assign the text. One thing that comes into my mind is, that even for a short Taskfile the number of processes spawned might be very high.

**Comment by sascha-andres** [comment]
After thinking a whole on this, I had an idea of a different approach. Let's assume a Taskvar like this:

```
SIMPLE_VAR: content
EXEC_VAR:
  cmd: echo a
```

The former is just an assignment, the latter one an executed one. This would make reading the Taskvar harder but the syntax cleaner

**Comment by andreynering** [comment]
Both ideas are valid.

I just had an idea for having it in a clear and backward compatible way. We could have a special syntax like prefixing commands with `@`.

```yml
# Taskvars.yml
STATIC: foobar
DYNAMIC: @git config user.name
```

```yml
# Taskfile.yml
build:
  cmds:
    - go build main.go
  vars:
    STATIC: foobar
    DYNAMIC: @git config user.name
```
