### ISSUE TITLE
Bug/problem to put a variable in an include

### ISSUE THREAD

**Issue by Antoine-Sevec** [go-task/task#1109]
Hi !
I need help because I can't put the **TASKFILE_DIR** variable in my includes in v3.23.0 (ubuntu 22.10), here is my code:

```
---
version: "3"

includes:
  main: 
    taskfile: '{{.TASKFILE_DIR}}/test/Taskfile.yml'
```

Thanks for your help

**Comment by pd93** [comment]
This works as expected in the latest version.

Note that you need to start your path with `./` to make it relative:

```yaml
version: "3"

includes:
  main:
    taskfile: './{{.TASKFILE_DIR}}/test/Taskfile.yml'
```
