### ISSUE TITLE
How to declare variables with multiple value and expend them properly?

### ISSUE THREAD

**Issue by stephane-archer** [go-task/task#1117]
```
version: '3'

vars:
  GOSRC: main.go module1/module1.go module2/module2.go

tasks:
  default:
    cmds:
      - go build 
    sources:
       - "{{.GOSRC}}"
    generates:
      - MyApp
```
I'm quite sure I use and declare the variable GOSRC not the right way

**Comment by pd93** [comment]
Unfortunately, this is not currently possible. #948 tracks this functionality. Please feel free to upvote that issue so that we can prioritise accordingly.

In the meantime, you will need to manually define your list of files in the `sources` array:

```yml
version: '3'

tasks:
  default:
    cmds:
      - go build 
    sources:
       - main.go
       - module1/module1.go
       - module2/module2.go
    generates:
      - MyApp
```

Note that you are able to use globbing in `sources` if this helps?
