### ISSUE TITLE
Dynamic summary

### ISSUE THREAD

**Issue by Zebradil** [go-task/task#1120]
I have a use case in which interpolation in the `summary` field would be quite helpful.

I often use Taskfile as an interface to run shell scripts, which might require arguments or environment variables set. Requirements are usually described in a script's help/usage message. However, I can't provide it natively in a summary when a Taskfile is used instead of using the script directly. This leads to an inconvenience when a help message should be changed — it has to be changed in several places.

Here is an example (executable `hi.sh` and `Taskfile.yaml`):

```shell
#!/usr/bin/env bash

USAGE="./hi.sh NAME
Args:
  NAME : Username to greet

Env:
  GREETING : How to greet the user, default: HI"

GREETING=${GREETING:-HI}

if [[ $# -eq 0 ]]; then
    echo "$USAGE"
    exit 1
fi

# Check help flag
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "$USAGE"
    exit 0
fi

echo "$GREETING $*"
```

```yaml
version: '3'

silent: true

tasks:
  hi:
    desc: Say hi to someone
    summary: |
      Says hi to the user
      
      Args:
        NAME : Username to greet
      
      Env:
        GREETING : How to greet the user, default: HI

    cmds:
      - ./hi.sh {{.CLI_ARGS}}

  nice-hi:
    desc: Say hi to someone
    summary: |
      {{.USAGE}}
    vars:
      USAGE:
        sh: ./hi.sh --help
    cmds:
      - ./hi.sh {{.CLI_ARGS}}
```

Currently, I have to duplicate the `USAGE` text in the script and in the task summary (`hi` task).

I want to be able to form the `summary` text dynamically as it is shown in the `nice-hi` task definition.

Would it be an option to have a way to inject dynamic variables into the `summary` field?
