### ISSUE TITLE
variable cycle dependencies

### ISSUE THREAD

**Issue by ayasechan** [go-task/task#1124]
- Task version: v3.23.0
- Operating System: Microsoft Windows [Version 10.0.22621.1413]

task does not report an error when there is a cyclic dependency , but initializes the relevant variable to a null value.

This may lead to some unpredictable bugs that are difficult to debug.

I think task shuold exit with an error when a cyclic dependency is detected or at least output some warning message.

example file

```yaml
# https://taskfile.dev

version: '3'

vars:
  a: '{{.b}}'
  b: '{{.a}}'

tasks:
  default:
    cmds:
      - echo {{.a}} {{.b}}
```
