### ISSUE TITLE
The behavior of env is not consistent

### ISSUE THREAD

**Issue by ayasechan** [go-task/task#1125]
- Task version: v3.23.0
- Operating System: Microsoft Windows [Version 10.0.22621.1413]

example 

```yaml
version: '3'

env:
  foo: global

tasks:
  default:
    env:
      foo: task
    cmds:
      - echo {{.foo}} # output: global
      - echo $foo # output: task
```

**Comment by trulede** [comment]
This is working correctly. The `task:env:foo` is injected to the `cmds `environment ($foo) and the template reference resolves to the global `env:foo`. To get the behaviour you expect, do this:

```yaml
version: '3'

env:
  foo: global

tasks:
  default:
    vars:
      foo: task
    env:
      foo: '{{.foo}}'
    cmds:
      - echo {{.foo}} # output: task (was global)
      - echo $foo # output: task      
```
