### ISSUE TITLE
how to split line when cmd too long

### ISSUE THREAD

**Issue by wangduanduan** [go-task/task#1129]
if the cmd is too long, how to make line break ?

in taskfile
```
# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    cmds:
      - echo "{{.GREETING}}"  "{{.GREETING}}" "{{.GREETING}}" "{{.GREETING}}" "{{.GREETING}}" "{{.GREETING}}" Hello
    silent: true
```

in makefile,  `\` for split line, 

```
run:
    echo "{{.GREETING}}"  "{{.GREETING}}"  \
    "{{.GREETING}}" "{{.GREETING}}" \
    "{{.GREETING}}" "{{.GREETING}}"  hello
```
