### ISSUE TITLE
deps should be completed before vars are attempt

### ISSUE THREAD

**Issue by mgale** [go-task/task#1139]
The shell calls in vars should be executed after all the deps tasks are completed.

- Task version: 3.24.0
- Operating System: Ubuntu 22.04

In this example a stat error is raised because ./helloword does not exist.
```
version: '3'

tasks:
  # Get helloworld tool
  get-binary:
    cmds:
      - wget -nv https://<download-path>/helloworld
      - chmod +x helloworld
    status:
      - test -f helloworld

  do-stuff:
    deps: [get-binary]
    vars:
      FOO_BAR:
        sh: ./helloworld {{.ENV_FOO}}
    cmds:
      - echo "foo bar"
```

Output
```
stat /home/mgale/workspace/helloword: no such file or directory
task: Command "./helloworld ... " failed: exit status 127
```
