### ISSUE TITLE
double error output

### ISSUE THREAD

**Issue by mdigger** [go-task/task#1141]
- Task version: 3.24.0
- Operating System: Mac OS

```shell
$ task test3
task: Available tasks for this project:
* test1:        Test 1
* test2:        Test 2
task: Task "test3" does not exist
task: Task "test3" does not exist
```

```yaml
version: '3'
tasks:
  test1:
    desc: Test 1
    cmds:
      - echo "test 1"
  test2:
    desc: Test 2
    cmds:
      - echo "test 2"
```
