### ISSUE TITLE
[Feature Request] Detect infinite recursion when using 'sh' to call 'task' in a dynamic global variable

### ISSUE THREAD

**Issue by NiceGuyIT** [go-task/task#1158]
This is related to [issue #178][] and specifically to [this comment][]. It's nice being able to assign the output of a task to variable. The problem comes when assigning the task output to a global variable because `task` will enter a recursive loop trying to resolve the global dependency before executing the actual task. This feature request is in the hopes that `task` can detect if a dynamic global variable is calling `task` and exit with a friendly error message.

Here's an example of infinite recursion.

```yaml
---
version: '3'

vars:
  DEFAULT_USER:
    sh: |
      task --silent config-get-value

tasks:

  user-exists:
    desc: Check if the system (OS) user exists.
    summary: |
      This task will check if the given user exists.
    platforms: [linux]
    cmds:
      - cmd: |
          id {{ quote .CHECK_USER }} >/dev/null && echo {{ quote .CHECK_USER }}

  config-get-value:
    desc: Get the value of a config key.
    summary: |
      This task will get a config key.
    platforms: [linux]
    cmds:
      - cmd: |
          echo "Some value"
```

The workaround is to move the variable definition inside each task that needs it.

```yaml
---
version: '3'

tasks:

  user-exists:
    desc: Check if the system (OS) user exists.
    summary: |
      This task will check if the given user exists.
    platforms: [linux]
    vars:
      DEFAULT_USER:
        sh: |
          task --silent config-get-value
      CHECK_USER: {{.CHECK_USER | default .DEFAULT_USER}}
    cmds:
      - cmd: |
          id {{ quote .CHECK_USER }} >/dev/null && echo {{ quote .CHECK_USER }}

  config-get-value:
    desc: Get the value of a config key.
    summary: |
      This task will get a config key.
    platforms: [linux]
    cmds:
      - cmd: |
          echo "Some value"
```

[issue #178]: https://github.com/go-task/task/issues/178
[this comment]: https://github.com/go-task/task/issues/178#issuecomment-469042672

**Comment by trulede** [comment]
Hi, you can do this to solve your problem:

```yaml
---
version: '3'

vars:
  DEFAULT_USER:
    sh: |
      {{if eq .TASK "config-get-value"}}{{else}}task --silent config-get-value{{end}}
      
tasks:

  default:
    cmds:
      - cmd: |
          echo User is: {{ .DEFAULT_USER }}

  config-get-value:
    silent: true
    cmds:
      - cmd: |
          echo "FOO"
```
