### ISSUE TITLE
Task is not getting re-executed after addition/deletion of files when used with --watch argument. 

### ISSUE THREAD

**Issue by PaulisMatrix** [go-task/task#1179]
> Please describe the bug you're facing. Consider pasting example

Task is not getting re-executed after addition/deletion of files when used with `--watch` argument. 
Below is the sample taskfile for it. 

```yaml
version: '3'

tasks:
  go-runs:
    desc: Task for building a new binary
    cmds:
      - go build -o main
      - go install 
      - echo 'new binary available'
    sources:
      - '**/*.go
```
Works fine without `--watch` arg when the command `task go-runs` is ran but have to do that manually every time which can be avoided by using `--watch` arg but its not working for it as explained above. 

- Task version: 3.0 
- Operating System: MacOS 12.4

It seems to be an issue from the watcher pkg itself. 
https://github.com/radovskyb/watcher/issues/120
