### ISSUE TITLE
Skip / warn about empty tasks

### ISSUE THREAD

**Issue by Eun** [go-task/task#120]
I use golang's template conditions in `cmds` like this:

```yaml
 task1:
    cmds:
      - cmd: "{{if .RUN_TASK1}}echo Running Task 1{{end}}"
```
> `RUN_TASK1` is a environment variable

If `RUN_TASK1` is not set I will get following message:
```
task: Failed to run task "task1": task: Task "" not found
```

So it might be useful to give out a warning about empty tasks, or skip them directly?

---
For completeness:
The current workaround is using this syntax:
```yaml
 task1:
    cmds:
      - cmd: "{{if .RUN_TASK1}}echo Running Task 1{{else}}true{{end}}"
```

**Comment by smyrman** [comment]
There is another workaround:
```yaml
task1:
    cmds:
    - |
      set -e
      "{{if .RUN_TASK1}}echo Running Task 1{{end}}"
```
