### ISSUE TITLE
Grouped output is mixed with Task output

### ISSUE THREAD

**Issue by mochja** [go-task/task#1208]
Hello, when using grouped output for the tasks, it seems like the Tasks' logs are mixed within the output, in the example below you can see that `task: Task "one" is up to date` is being printed within the task group and the output is different with every run, sometimes this statement is printed is before the group statement, sometimes it is after the closing group statement. I would expect this to be consistent across the runs or atleast outside of the group output.

Please run the Taskfile below multiple times to reproduce.

```
::group::two
task: Task "one" is up to date
2
::endgroup::
```

- Task version: 3.25.0
- Operating system: MacOS
- Experiments enabled: 0

```yaml
version: '3'

output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'

tasks:
  default:
    deps: [one,two]
    cmds:
    - task: one
    - task: two
    - task: one

  one:
    sources: [Taskfile.yml]
    cmds: [sleep 1]
  two: echo 2
```

```
~/sandbox/task-test ❯ task
task: [two] echo 2
::group::two
task: Task "one" is up to date
2
::endgroup::
task: Task "one" is up to date
task: [two] echo 2
::group::two
2
::endgroup::
task: Task "one" is up to date

~/sandbox/task-test ❯ task
task: [two] echo 2
::group::two
2
::endgroup::
task: Task "one" is up to date
task: Task "one" is up to date
task: [two] echo 2
::group::two
2
::endgroup::
task: Task "one" is up to date

~/sandbox/task-test ❯ task
task: [two] echo 2
task: Task "one" is up to date
::group::two
2
::endgroup::
task: Task "one" is up to date
task: [two] echo 2
::group::two
2
::endgroup::
task: Task "one" is up to date
```
