### ISSUE TITLE
Implement notifier for tasks

### ISSUE THREAD

**Issue by vitonsky** [go-task/task#1213]
I need task runner for long time tasks on server, that will notify me about tasks status.

Your project looks suit for me by features, but i don't see any notifier feature in docs. Can you implement it?

See example in [replicator repository](https://github.com/vitonsky/replicator) - my own task runner with notifications
```yaml
# Notifications config
notifications:
    telegram:
        # Define should notifications been sent
        enabled: true
        # Token for bot who will sent notifications
        # How to: https://core.telegram.org/bots/tutorial#getting-ready
        botToken: '123:token'
        # User IDs to receive notifications
        userIds:
            - 123456

# Replicate backup from main storage
tasks:
    - run: rclone s3Replica:backups s3Mirror1:backups
    - run: rclone s3Replica:backups s3Mirror2:backups
    - run: rclone s3Replica:backups s3Mirror3:backups
```

Replicator will notify me when task will end with success or fail, so i can track progress and call alerts if task fails.

It would great to use this feature with task files. I suggest to implement few notifiers:
- telegram
- web hook
- call any command provided by user like that `command message type?`
