### ISSUE TITLE
Fail if variable isn't set

### ISSUE THREAD

**Issue by jaxxstorm** [go-task/task#122]
Is there a way to stop a task running if a variable isn't defined via the environment variables?

**Comment by smyrman** [comment]
Using shell logic, you can.
```yaml
version: "2"
tasks:
  some-task:
    cmds:
    - |
      if [ -z "MYVAR" ]; then
        echo "Need to set MYVAR"
        exit 1
      fi
   - echo "OK"
```
OR:
```yaml
version: "2"
tasks:
  some-task:
    deps:
     - hasMYVAR
    cmds:
    - echo "OK"
  hasMYVAR:
    silent: true
    cmds:
    - |
      if [ -z "MYVAR" ]; then
        echo "Need to set MYVAR"
        exit 1
      fi
```

**Comment by smyrman** [comment]
Not to pretty perhaps, but it works.

**Comment by jaxxstorm** [comment]
Thanks!

**Comment by andreynering** [comment]
If you do that a lot, you can create a generic task to do that for:

```yml
version: '2'

tasks:
  some-task:
    deps:
      - task: has-env
        vars: {ENV: MY_VARIABLE}
    cmds:
      - echo OK

  has-env:
    silent: true
    cmds:
      - |
        if [ -z "{{.ENV}}" ]; then
          echo "Need to set {{.ENV}}"
          exit 1
        fi
```

Maybe that's not common enough to be worth adding a feature to Task itself to do that. If someone disagree, feel free to comment.

**Comment by DanielGeryousFares** [comment]
This might be a bit late to share here, but as they say, sharing is caring. Here's how I did it on my system using bash:

```
version: "3"

tasks:
  print-var:
    cmds:
      - |
        set -u
        echo ${SOMEVAR}
```
