### ISSUE TITLE
Forwarding CLI arguments not working

### ISSUE THREAD

**Issue by usersina** [go-task/task#1238]
- Task version: `v3.24.0`
- Operating system: `Windows 10 Pro 21H2`

I have a `Taskfile.yml` file to build and run docker images using different compose files depending on the environment.
It is more complex but I simplify it below for the sake of this report:
```yml
version: "3"

env:
  # Compose file ("dev" | "local" | "prod")
  ENVIRONMENT: dev

tasks:
  up:
    cmds:
      - docker compose -f docker-compose.${ENVIRONMENT}.yml up

  down:
    cmds:
      - docker compose -f docker-compose.${ENVIRONMENT}.yml down
```

I can run my task without problems doing `task up`. However, when running `task up -- -d` expecting my containers to run in detached mode, that does not work, neither does anything else passed after `--` gets forwarded.

```bash
$ task up -- -d
task: [up] docker compose -f docker-compose.${ENVIRONMENT}.yml up
```

I know full well that I can do a conditional

```yml
tasks:
  up:
    summary: |
      Start the containers in the background using the appropriate
      docker-compose file.
    cmds:
      - |
        if [ "${ENVIRONMENT}" = "prod" ]; then
          docker compose -f docker-compose.${ENVIRONMENT}.yml up --detach
        else
          docker compose -f docker-compose.${ENVIRONMENT}.yml up
        fi
```

Or create other tasks but that does scale very well. Especially since I have other plans in mind for other complex commands. (For example `ENVIRONMENT=local task down -- --volumes`, `ENVIRONMENT=prod task up -- --pull --no-build -d`)

**Comment by st0le** [comment]
FWIW I use `{{.CLI_ARGS}}` to forward the extra parameters

**Comment by usersina** [comment]
@st0le - that's exactly so. It was [already documented](https://taskfile.dev/usage/#forwarding-cli-arguments-to-commands) but I miraculously missed it...

```yml
version: "3"

env:
  # Compose file ("dev" | "local" | "prod")
  ENVIRONMENT: dev

tasks:
  up:
    cmds:
      - docker compose -f docker-compose.${ENVIRONMENT}.yml up {{.CLI_ARGS}} # added here

  down:
    cmds:
      - docker compose -f docker-compose.${ENVIRONMENT}.yml down {{.CLI_ARGS}} # added here
```
