### ISSUE TITLE
preconditions doesn't respect `task` keyword

### ISSUE THREAD

**Issue by Gleland** [go-task/task#1255]
Hi team, thanks for the awesome tool! I'm not sure if it's intentional, but currently go-task doesn't support `task` within a `precondition` block. With the following example Taskfile.yml:

```yml
version: '3'

tasks:
  default:
    preconditions:
      - task first
    cmds:
      - echo 'should print second'
  first:
    cmds:
      - echo 'should print first'
  ```
  
 I'd expect that invoking `task default` would print out two lines, but instead only prints one:
```
$ task --version
Task version: v3.27.1 (h1:cftsoOqUo7/pCdtO7fDa4HreXKDvbrRhfhhha8bH9xc=)
$ task default
task: [default] echo 'should print second'
should print second
$ task --dry
task: [default] echo 'should print second'
```
This is reproducible on macOS Ventura 13.4.1 and on Debian 6.1.27-1. Thanks for your time!

**Comment by pd93** [comment]
@Gleland Are you sure you're not looking for `deps` instead? e.g.

```yaml
version: '3'

tasks:
  default:
    deps:
      - first
    cmds:
      - echo 'should print second'
  first:
    cmds:
      - echo 'should print first'
```

This should do what you're expecting in your example. I'm not sure if your real-world scenario has slightly different requirements though?

- [`preconditions`](https://taskfile.dev/usage/#using-programmatic-checks-to-cancel-the-execution-of-a-task-and-its-dependencies) are a set of commands that will be run in order to determine if we should run a task (depending on the exit code of the commands). As @pasman1 eluded to, these commands are executed internally to gather an exit code. Nothing will be output to the terminal. A good example of this would be to check if a binary that is required by the task is installed.
- [`deps`](https://taskfile.dev/usage/#task-dependencies) are dependent tasks that will always run before a task is executed.
