### ISSUE TITLE
Requires not working?

### ISSUE THREAD

**Issue by TheOddler** [go-task/task#1264]
- Task version: 3.24.0
- Operating system: NixOS (23.05)
- Experiments enabled: None

I was trying out Task with a simple taskfile:

```
version: "3"

tasks:
  default:
    cmds:
      - task --list-all

  hello:
    cmds:
      - echo 'Hello World from Task! {{.NAME}} - {{.MATCH}}'
    requires:
      vars: [NAME, MATCH]
```

However, when I run `task hello` it just works, rather than give me an error I didn't set the `NAME` nor `MATCH` variable:

```
❯ task hello
task: [hello] echo 'Hello World from Task!  - '
Hello World from Task!  - 
```
