### ISSUE TITLE
Variable interpolation on commands

### ISSUE THREAD

**Issue by titpetric** [go-task/task#1269]
## Variable interpolation and yaml gotchas

```
---
version: "3"

tasks:
  default:
    desc: "Test interpolation"
    vars:
      cli: go
      args: version
    cmds:
      - go {{.args}}
      - |
        {{.cli}} version
      - "{{.cli}} {{.args}}"
```

Ultimately, I would have expected `- {{.cli}} {{.args}}` to work, as `- go {{.args}}` work, but it seems that's not valid yaml.

We could use yaml anchors, albeit it looks ugly, for example:

```
---
version: "3"

tasks:
  default:
    desc: "Test interpolation"
    vars:
      cli: &cli go
    cmds:
      - *cli
```

This however doesn't let us pass arguments. An `args` extension to the command schema would be needed to enable:

```
cmds:
  - cmd: *cli
    args: *args
```

However, my original point was the expectation - how do we evaluate the command with a reasonably nice definition.

Weirdly, this is the cleanest way I came up with:

```
- \{{.cli}} {{.version}}
```

This works, but only works because task invokes `\go` in this case, and that just happens to work. Bash thinks we're trying to escape `g` (`\g`), while the yaml parser considers it the usual string literal when parsing, leaving it as part of the string.

References:

https://taskfile.dev/api/#command 
https://stackoverflow.com/questions/40631913/concatenation-of-yaml-anchors-with-another-string-in-keys

**Comment by Allaman** [comment]
Currently, I am in the process of migrating a Makefile to Task and stumbled over this. 

In my Makefile, I define common commands to keep things dry:

```
BUILD:=kustomize build
APPLY:=kubectl apply -f -

deploy-ingress:   ## Only deploy the ingress controller
	@$(BUILD) deployments/overlay/ingress | $(APPLY)
```

The trick with prefixing `\` works, thanks @titpetric!

```
vars:
  BUILD: kustomize build
  APPLY: kubectl apply -f -

tasks:
    desc: Deploy
    cmds:
      - \{{.BUILD}} . | {{.APPLY}}
```

Nevertheless, a proper solution would be cool :)

**Comment by vmaerten** [comment]
The recommanded way to do it is to wrap in quote : 

```yml
version: "3"

tasks:
  default:
    desc: "Test interpolation"
    vars:
      cli: go
      args: version
    cmds:
      - '{{.cli}} {{.args}}'
```
This works as expected
