### ISSUE TITLE
`CGO_ENABLED` cannot be set to `1`

### ISSUE THREAD

**Issue by JamieEdge** [go-task/task#1272]
When Task is invoked with `CGO_ENABLED=0`, the environment variable cannot be set to `1` in the `env` section of a task declaration.

This is reproducible using the following Taskfile.

```yaml
version: 3

tasks:
  default:
    env:
      CGO_ENABLED: 1
    cmds:
      - go env CGO_ENABLED
```

The issue is shown in the following output. `go` should report the value as `1`, but instead reports `0`.

```
$ CGO_ENABLED=0 task
task: [default] go env CGO_ENABLED
0
```

The same behaviour is *not* observed when Task is invoked with `CGO_ENABLED=1` and the task attempts to set the value to `0`.

Setting the environment variable within the command string itself (e.g. `CGO_ENABLED=1 go env CGO_ENABLED`) results in the expected behaviour.

- Task version: v3.27.1 (h1:cftsoOqUo7/pCdtO7fDa4HreXKDvbrRhfhhha8bH9xc=)
- Operating system: macOS 13.4.1 (22F82)
- Experiments enabled: None

**Comment by pd93** [comment]
@JamieEdge Your Taskfile works as intended for me with v3.28.0 on MacOS and Linux.

![image](https://github.com/go-task/task/assets/9294862/8dfb43a7-0952-4822-b499-1a1f9b4da0f6)

**Comment by JamieEdge** [comment]
Thanks for testing this @pd93.

Do you have `CGO_ENABLED` set to `0` in your environment? The default value is `1`, so it needs to be explicitly set prior to executing the Taskfile.

**Comment by pd93** [comment]
@JamieEdge I'm getting the same result either way

<img width="569" alt="image" src="https://github.com/go-task/task/assets/9294862/eac8c5c2-2b03-4316-9ce0-e534f130818e">

**Comment by JamieEdge** [comment]
The variable needs to be exported for it to be provided to `task` (i.e. `export CGO_ENABLED=0`).

**Comment by UninspiredNickname** [comment]
> The variable needs to be exported for it to be provided to `task` (i.e. `export CGO_ENABLED=0`).

So what would be an idiomatic way to set CGO_ENABLED? And is that a bug, or a feature?

**Comment by UninspiredNickname** [comment]
> > The variable needs to be exported for it to be provided to `task` (i.e. `export CGO_ENABLED=0`).
> 
> So what would be an idiomatic way to set CGO_ENABLED? Something like this?:
> 
> ```yaml
> cmds:
>   - export CGO_ENABLED=0 && go build .
> ```
> 
> And is that a bug, or a feature?

Ok - for anyone who finds this issue - it's actually documented in [docs](https://taskfile.dev/faq/#why-wont-my-task-update-my-shell-environment) and idiomatic way seems to be to create task that prints `export ...` and then something like this:

```yaml
cmds:
  - eval $(task my-shell-env) &&  go build .
```

**Comment by trulede** [comment]
AFAICS this works with the latest Task.

```yaml
version: 3

tasks:
  cgo-default:
   cmds:
      - go env CGO_ENABLED
  default:
    deps: [cgo-default]
    env:
      CGO_ENABLED: 0
    cmds:
      - echo $CGO_ENABLED
      - go env CGO_ENABLED
```

```bash
$ task 
task: [cgo-default] go env CGO_ENABLED
1
task: [default] echo $CGO_ENABLED
0
task: [default] go env CGO_ENABLED
0
```

I will close the issue, please, reopen it if you are unable to resolve your issue.
