### ISSUE TITLE
Variables should be inherited

### ISSUE THREAD

**Issue by bluebrown** [go-task/task#1277]
I think it would be good if variables would be inherited from the calling task

For example, if I have the below taskfile, I would expect the sub tasks, build and image, to have the version set by the default task.

```yaml
version: "3"

tasks:
  default:
    vars:
      VERSION:
        sh: echo v1
    cmds:
      - task: build
      - task: image

  build:
    cmd: echo build {{.VERSION}}

  image:
    cmd: echo image {{.VERSION}}
```

Instead, one needs to pass them explicitly down, which makes it verbose and hard to track 

```yaml
version: "3"

tasks:
  default:
    vars:
      VERSION:
        sh: echo v1
    cmds:
      - task: build
        # vars:
        # VERSION: '{{.VERSION}}'
      - task: image
        # vars:
        # VERSION: '{{.VERSION}}'

  build:
    cmd: echo build {{.VERSION}}

  image:
    cmd: echo image {{.VERSION}}
```

That makes it in my opinion not feasible to use such a dynamic variable in the task file. It seems much easier to run that dynamic command outside the taskfile and pass it as environment variable, as this will lead to all task seeing that value.

**Comment by atishnazir** [comment]
+1.  I bumped into this yesterday and crafted the following unergonomic workaround using dynamic variables:

```
  docker:build:
    desc: Execute build target within a container
    vars:
      BUILD_OUTPUT:
        sh: mktemp --tmpdir --directory "{{.DOCKER_BUILDER}}.XXX"

    cmds:
      - task: docker:compile
        vars:
          BUILD_OUTPUT:
            sh: echo {{.BUILD_OUTPUT}}
      - task: docker:runtime
        vars:
          BUILD_OUTPUT:
            sh: echo {{.BUILD_OUTPUT}}
      - rm -rf "{{.BUILD_OUTPUT}}"

  docker:compile:
    internal: true
    requires:
      vars:
        - BUILD_OUTPUT
    cmds:
      - echo "{{.BUILD_OUTPUT}}"
...
```

**Comment by JonZeolla** [comment]
@bluebrown If this is all in one file, why not use a global `vars`?

```bash
$ task default
task: [build] echo build v1
build v1
task: [image] echo image v1
image v1
```

```yaml
version: "3"

vars:
  VERSION: v1

tasks:
  default:
    cmds:
      - task: build
      - task: image

  build:
    cmd: echo build {{.VERSION}}

  image:
    cmd: echo image {{.VERSION}}
```

**Comment by ameergituser** [comment]
Variables should be expicitly parsed. Just like functions in programming lauguages allow variables as inputs to achieve abstraction. It actually makes it easy to track and maintain what affects the state of a task. Imagine chaining tasks multiple levels down, and you share state/variables implicitly accros the entire chain. This is nightmare as the higher level task needs to know the logic and variables used by the entire chain just so that he does not affect the lower tasks accidentally.

Global variables should be enough if this is the desired affect.

**Comment by sedyh** [comment]
Can we revisit this? I would like to have a flag like `vars: all` instead of referencing each variable one-by-one. It becomes messy very quick.

```yaml
format:
  vars:
    SRC: 'cmd/format'
    BIN: 'bin/tool/format'
  sources:
    - '{{.SRC}}/*'
  generates:
    - '{{.BIN}}'
  cmds:
    - task: build
      vars:
        SRC: '{{.SRC}}'
        BIN: '{{.BIN}}'
imports:
  vars:
    SRC: 'cmd/imports'
    BIN: 'bin/tool/imports'
  sources:
    - '{{.SRC}}/*'
  generates:
    - '{{.BIN}}'
  cmds:
    - task: build
      vars:
        SRC: '{{.SRC}}'
        BIN: '{{.BIN}}'
build:
  internal: true
  cmd: go build {{.OPT}} -o ./{{.BIN}} ./{{.SRC}}
  generates:
    - '{{.BIN}}'

```
