### ISSUE TITLE
Merge elements accordingly based on the order of priority that Task uses to look for configuration files

### ISSUE THREAD

**Issue by x80486** [go-task/task#1289]
I started using `Task` recently. I find it really useful :1st_place_medal:

I always use two files: `Taskfile.dist.yaml` (committed) and `Taskfile.yaml` (ignored by `Git`). Problem is that all the tasks from `Taskfile.yaml` are the ones that will be available, when what I really expect (regardless of what the documentation says :rofl:) is to have a single set of tasks/variables/etc. where each one will get overwritten based on the algorithm `Task` look for configuration files.

For instance, consider these two files:

```yaml
# Taskfile.dist.yaml

vars:
  BINARY_NAME: "superapp"

tasks:
  build:
    cmds:
      - go build -o build/{{.BINARY_NAME}}
    generates:
      - build/{{.BINARY_NAME}}

  # 9 other task definitions
```

```yaml
# Taskfile.yaml

vars:
  BINARY_NAME: "superapp-local"

tasks:
  build:
    cmds:
      - rm --force --recursive build/
      - go build -o build/{{.BINARY_NAME}}
    generates:
      - build/{{.BINARY_NAME}}

  additional-only-for-me:
    ...

  # No other task(s) defined
```

Based on this logic, I would expect `11` tasks, `BINARY_NAME` bound to `superapp-local`, and `build` should have the behavior from `Taskfile.yaml`.

I'm aware there is a way to include a file from another, but that changes all the task names :neutral_face: and really variables and such are not taken into consideration if declared again.
