### ISSUE TITLE
Document importance of specifying version in Taskfile

### ISSUE THREAD

**Issue by jpwhite3** [go-task/task#129]
As a new user I misunderstood "version" to mean the version of the Taskfile, and that would be used as part of the orchestration of the override files. When I attempted to implement "Global Variables" using a Taskfile like below, I couldn't get things working... 

```
version: '1'

vars:
    EXAMPLE: Arbitrary global string variable

tasks:
    default:
        cmds:
            - task --list
    work:
        desc: This example works.
        vars:
            EXAMPLE: Arbitrary local string variable
        cmds:
            - echo "{{.EXAMPLE}}"
    no-work:
        desc: This example does not work.
        cmds:
            - echo "{{.EXAMPLE}}"
```

Output on macOS terminal:

```
$ task work
echo "Arbitrary local string variable"
Arbitrary local string variable

$ task no-work
echo "<no value>"
<no value>
```

On a hunch, I updated the "version" to "2" as in all of the examples. A that indeed resolved my issues with the global variables. So I now take it to understand the "version" refers to the version of the API. Is that correct?

Updating documentation would really provide clarity here, as well as a list of what features are supported by what version.
