### ISSUE TITLE
Option to specify a custom interpreter

### ISSUE THREAD

**Issue by aucampia** [go-task/task#1292]
I have had a couple of situations where I wanted to run commands with a different interpreter than `mvdan.cc/sh/v3/cmd/gosh`. Two examples are:

Small python snippets that I want executed with the python interpreter:

```yaml
tasks:
  _rimraf:
    # This task is a utility task for recursively removing directories, it is
    # similar to rm -rf but not identical and it should work wherever there is
    # a python interpreter. The name is inspired by
    # <https://www.npmjs.com/package/rimraf>.
    - cmd: |
        {{.PYTHON}} -c '
        from pathlib import Path;
        import sys, shutil;
        for path in sys.argv[1:]:
          if Path(path).exists():
            sys.stderr.write(f"removing {path}\n")
            shutil.rmtree(path, ignore_errors=True)
        ' {{.RIMRAF_TARGET}}
```

Commands I want to execute on a LXD container:

```yaml
tasks:
  nomad:clean:jobs:
    desc: Delete all Nomad jobs
    cmds:
      - cmd: lxc exec -t kron-cluster-sandbox -- bash -l -c {{ .CMD | shellQuote }}
        ignore_error: true
    vars:
      CMD: |
        set -x -euo pipefail

        nomad job inspect -json | jq -r ".[].ID" | xargs -I{} -t nomad job stop -yes {}
        nomad system gc
```

I feel these two cases would be a bit more elegant if I could specify the interpreter separately from the command without having to pass the command as either an environment variable or a shell escaped string.

This is a rather minor request though, clearly there are serviceable workarounds that get the job done, but having something similar to the [interpreter setting from poethepoet](https://poethepoet.natn.io/tasks/task_types/shell.html#using-a-different-shell-interpreter) may help.
