### ISSUE TITLE
Conditional assigned env at task level does not work.

### ISSUE THREAD

**Issue by Thomy90** [go-task/task#1294]
Hi guys,
great work, keep going =)

I found an issue for conditional assigned vars at task level.

Here is my simplified taskfile for reproduction:
```
version: '3'

vars:
  FOO_GLOBAL: 'foo-global'
  BAZ_GLOABL: '{{ if eq .FOO_GLOBAL "foo-global"}}baz-global{{end}}'

tasks:
  default:
    vars:
      FOO_TASK: 'foo-task'
      BAZ_TASK: '{{ if eq .FOO_TASK "foo"}}baz-task{{end}}'
    cmds:
      - echo {{.BAZ_GLOABL}}
      - echo {{.BAZ_TASK}}
```

Expected output:
```
task: [default] echo baz-global
baz-global
task: [default] echo baz-task
baz-task
```

Actual output:
```
task: [default] echo baz-global
baz-global
task: [default] echo 

```

The evaluation only works on global level. Same for env keyword.

- Task version: v3.28.0
- Operating system: Ubuntu 20.04.6
- Experiments enabled: false

**Comment by JonZeolla** [comment]
I think you just have a mistake in your conditional, this works as expected:
```yml
version: '3'

vars:
  FOO_GLOBAL: 'foo-global'
  BAZ_GLOABL: '{{ if eq .FOO_GLOBAL "foo-global"}}baz-global{{end}}'

tasks:
  default:
    vars:
      FOO_TASK: 'foo-task'
      BAZ_TASK: '{{ if eq .FOO_TASK "foo-task"}}baz-task{{end}}'
    cmds:
      - echo {{.BAZ_GLOABL}}
      - echo {{.BAZ_TASK}}
```

**Comment by Thomy90** [comment]
@JonZeolla thanks for your comment. You are right, that was a mistake from my side. The issue occurs only for env keyword. 
Here this time a correct issue description =)

```
version: '3'

env:
  FOO_GLOBAL: 'foo-global'
  BAZ_GLOABL: '{{ if eq .FOO_GLOBAL "foo-global"}}baz-global{{end}}'

tasks:
  default:
    env:
      FOO_TASK: 'foo-task'
      BAZ_TASK: '{{ if eq .FOO_TASK "foo-task"}}baz-task{{end}}'
    cmds:
      - echo {{.BAZ_GLOABL}}
      - echo {{.BAZ_TASK}}
```
Expected output
```
task: [default] echo baz-global
baz-global
task: [default] echo baz-task
baz-task
```

Actual output
```
task: [default] echo baz-global
baz-global
task: [default] echo 

```
