### ISSUE TITLE
Included taskfiles don’t use provided vars while evaluating their vars

### ISSUE THREAD

**Issue by JonZeolla** [go-task/task#1295]
I expected the included taskfile to exit 1 because it uses the passed `CODE` var that was passed to it, but it seems to be unset and uses the `default` instead.

`Taskfile.yml`:
```yml
version: '3'

includes:
  example:
    taskfile: ./Taskfile.included.yml
    vars:
      CODE: '{{.CODE | default 2}}'

vars:
  CODE: 1

tasks:
  echo-code:
    cmds:
      - 'echo {{.CODE | default 4}}'
```

`Taskfile.included.yml`:
```yml
version: '3'

vars:
  CODE:
    sh: 'exit {{.CODE | default 3}}'
```

## Expected output

```bash
$ task echo-code
task: Command "exit 1" failed: exit status 1
```

## Actual output

```bash
$ task echo-code
task: Command "exit 3" failed: exit status 3
```

- Task version: v3.28.0 (h1:PGYGwevlGQdYrqhO6lLCYylC7YuGoQLlVwHkO42gf0I=)
- Operating system: darwin arm64 (macOS 13.4.1 M1 Max)
- Experiments enabled: None

**Comment by JonZeolla** [comment]
I was hopeful that reordering the `Taskfile.yml` to put `vars` before the `includes` section but that didn't work either.

**Comment by JonZeolla** [comment]
In doing more testing, it seems that the problem is that `includes` may be running before `vars`.  Here's a test diff which shows the issue:

```yaml
diff --git a/testdata/include_with_vars/Taskfile.yml b/testdata/include_with_vars/Taskfile.yml
index aee8f51..96c799a 100644
--- a/testdata/include_with_vars/Taskfile.yml
+++ b/testdata/include_with_vars/Taskfile.yml
@@ -1,5 +1,8 @@
 version: "3"

+vars:
+  VAR_2: included2-var2
+
 includes:
   included1:
     taskfile: include/Taskfile.include.yml
@@ -9,6 +12,7 @@ includes:
     taskfile: include/Taskfile.include.yml
     vars:
       VAR_1: included2-var1
+      VAR_2: '{{.VAR_2}}'
   included3:
     taskfile: include/Taskfile.include.yml

diff --git a/testdata/include_with_vars/include/Taskfile.include.yml b/testdata/include_with_vars/include/Taskfile.include.yml
index 3bb7a68..f902f91 100644
--- a/testdata/include_with_vars/include/Taskfile.include.yml
+++ b/testdata/include_with_vars/include/Taskfile.include.yml
@@ -2,7 +2,8 @@ version: "3"

 vars:
   VAR_1: '{{.VAR_1 | default "included-default-var1"}}'
-  VAR_2: '{{.VAR_2 | default "included-default-var2"}}'
+  VAR_2:
+    sh: 'echo {{.VAR_2 | default "included-default-var2"}}'

 tasks:
   task1:
```

And this one works as expected:

```yaml
diff --git a/testdata/include_with_vars/Taskfile.yml b/testdata/include_with_vars/Taskfile.yml
index aee8f51..aa3ecb4 100644
--- a/testdata/include_with_vars/Taskfile.yml
+++ b/testdata/include_with_vars/Taskfile.yml
@@ -9,6 +9,7 @@ includes:
     taskfile: include/Taskfile.include.yml
     vars:
       VAR_1: included2-var1
+      VAR_2: included2-var2
   included3:
     taskfile: include/Taskfile.include.yml

diff --git a/testdata/include_with_vars/include/Taskfile.include.yml b/testdata/include_with_vars/include/Taskfile.include.yml
index 3bb7a68..f902f91 100644
--- a/testdata/include_with_vars/include/Taskfile.include.yml
+++ b/testdata/include_with_vars/include/Taskfile.include.yml
@@ -2,7 +2,8 @@ version: "3"

 vars:
   VAR_1: '{{.VAR_1 | default "included-default-var1"}}'
-  VAR_2: '{{.VAR_2 | default "included-default-var2"}}'
+  VAR_2:
+    sh: 'echo {{.VAR_2 | default "included-default-var2"}}'

 tasks:
   task1:
```

**Comment by JonZeolla** [comment]
This was also unexpected (with the below patch):

```bash
$ go run ./cmd/task --dir ./testdata/include_with_vars_multi_level default
task: [lib:greet] echo 'Hello world'
Hello world
task: [foo:lib:greet] echo 'Hello foo'
Hello foo
task: [bar:lib:greet] echo 'Hello world'
Hello world
```

```yaml
diff --git a/testdata/include_with_vars_multi_level/bar/Taskfile.yml b/testdata/include_with_vars_multi_level/bar/Taskfile.yml
index f280f3f..b2495bb 100644
--- a/testdata/include_with_vars_multi_level/bar/Taskfile.yml
+++ b/testdata/include_with_vars_multi_level/bar/Taskfile.yml
@@ -1,7 +1,10 @@
 version: "3"

+vars:
+  RECEIVER: 'bar_global'
+
 includes:
   lib:
     taskfile: ../lib/Taskfile.yml
     vars:
-      RECEIVER: "bar"
+      RECEIVER: '{{.RECEIVER | default "bar_local"}}'
```

**Comment by JonZeolla** [comment]
Still an issue as of 3.36.0

**Comment by trulede** [comment]
@JonZeolla OK, this is what's happening:

> Vars declared in the included Taskfile have preference over the variables in the including Taskfile! If you want a variable in an included Taskfile to be overridable, use the [default function](https://sprig.taskfile.dev/defaults.html): MY_VAR: '{{.MY_VAR | default "my-default-value"}}'.

First: the order of evaluation is: imported taskfile var, importing taskfile. That means you global var is set immediately in the imported taskfile because it has a default clause.

Second: imports vars have precedence over global vars in the _imported_ taskfile. But, since you are referring to the global variable that is _already_ set by the imported taskfile, this has no noticeable effect.

So, what you can do is use an "indirect variable" to push a value into the imported taskfile via the imports var. The following is an example of that.

Taskfile.yml
```
version: '3'

includes:
  example:
    taskfile: ./Taskfile.included.yml
    flatten: true
    vars:
      # CODE: '{{.CODE | default 2}}'
      CODE: '{{.FOO | default 2}}'

vars:
  FOO: 6
  CODE: 3

tasks:
  echo-code:
    cmds:
      - echo CODE {{.CODE}}
      - task: echo-code-inc
```

Taskfile.included.yml
```
version: '3'

vars:
  CODE: '{{.CODE | default 4}}'

tasks:
  echo-code-inc:
    cmds:
      - 'echo CODE {{.CODE}}'
```

Produces the output, as expected
```
$ task echo-code
task: [echo-code] echo CODE 4
CODE 4
task: [echo-code-inc] echo CODE 6
CODE 6
```

I will close the issue. There are other issues tracking planed changes in how variables are scoped, where you may wish to participate with your ideas.
