### ISSUE TITLE
Feature: non-string variables

### ISSUE THREAD

**Issue by smyrman** [go-task/task#130]
Hi, we got a use-case for non-string variables. Imagine two files:

Taskvars.yml:
```yml
parent:
  one: "hello"
  two: "world"
```

Taskfile.yml
```yml
version: "2"

tasks:
  default:
    cmds:
    - echo "{{.parent.one}}"
    - echo "{{.parent.two}}"
```

If we try to run this, we get:
```sh
$ task default                                         
template: :1:15: executing "" at <.master.child>: can't evaluate field child in type string
```

# Use-cases
- Increase readabilty/grouping for somewhat large taskfiels with many taskvars.
- Allow looping over members in a map or array.
- Allow easier programatic parsing and updates of Taskvars.yml

Our own use-case happen to be the latter one.

**Comment by smyrman** [comment]
PS! I am happy to do a PR for this if it's wanted. If it's not really wanted, I can work-aroud it for our own use-case, e.g. by variable prefixes or something like that.

**Comment by smyrman** [comment]
Had a stab at it. I realize it is in conflict with the "sh:" syntax. I think I will resolve to a work-around.

It could be this is still relevant to try for "v3", but I suggest we close it for now.

**Comment by andreynering** [comment]
Something similar may be needed by #82

This discussion is interesting, even I don't know how to deal with the conflict with `sh:`

Feel free to keep this open for future reference if you want

**Comment by smyrman** [comment]
Alright. let's reopen it for future references.

**Comment by andreynering** [comment]
Since I'm cleaning up a bit the issue list, let's close this for now since we have other features on the queue

We can still revisit this in the future, though

**Comment by themanifold** [comment]
FYI, I've just hit this too, as I'm trying to assign a `list` to a var and it gets automagically converted to a `string`. I was tearing my hair out until I noticed this behaviour.

For example, 

```
some_task:
    vars:
        foo: '{{ list 1 2 3 4 }}'
    cmds:
        - echo {{ typeOf .foo}}
```
which comes back as `string`. At the very least, this should be documented I think.
