### ISSUE TITLE
Task reported as not up-to-date but not executed

### ISSUE THREAD

**Issue by visciang** [go-task/task#1305]
- Task version: 3.28.0
- Operating system: MacOs
- Experiments enabled: no

Taskfile:

```yaml
version: "3"

tasks:
  test:
    cmds:
      - cp source.txt generate.txt
    sources:
      - source.txt
    generates:
      - generate.txt
```

Test:

```
touch source.txt

task test
# task run

task --status test
# task is up-to-date

echo "change" > source.txt

task --status test
# task is not up-to-date

task test
#  >>>  task does not run and is reported as up-to-date  <<<

```

Do I miss something in the task file definition?
