### ISSUE TITLE
Global vars evaluation doesn't work when calling task from another task.

### ISSUE THREAD

**Issue by Thomy90** [go-task/task#1310]
Hi guys,
I found another bug.

After calling call-default task in example below.

```yaml
version: '3'

vars:
  FOO: '{{ default "foo" .FOO}}'
  BAZ: '{{.FOO}}'

tasks:
  default:
    cmds:
      - echo {{.BAZ}}

  call-default:
    cmds:
      - task: default
        vars:
          FOO: 'new-foo'

```
Expected output:

```
task: [default] echo foo
new-foo
```

Actual output:

```
task: [default] echo foo
foo
```

- Task version: 3.28.0
- Operating system: Ubuntu 20.04.6
- Experiments enabled: no

**Comment by trulede** [comment]
Hi, you need to do something like this:

```
version: '3'

vars:
  FOO: '{{ default "foo" .FOO}}'
  BAZ: '{{.FOO}}'

tasks:
  default:
    cmds:
      - echo {{.BAZ}}
    vars:
      BAZ: '{{.FOO}}'

  call-default:
    cmds:
      - task: default
        vars:
          FOO: 'new-foo'
```
