### ISSUE TITLE
file-global silent:true not respected when in included file

### ISSUE THREAD

**Issue by ambis** [go-task/task#1319]
- Task version: Task version: v3.29.1 (h1:q4mqGSR40qTOf9XZp2ySY3cM6enb2d+AqaxI/pEBiLk=)
- Operating system: Ventura 13.5
- Experiments enabled: none I guess

```yaml
# taskfile.yml
version: "3"
includes:
  silent: taskfile.silent.yml
```

```yaml
# taskfile.silent.yml
version: "3"
silent: true # <- look here 
tasks:
  me-not-silent:
    desc: "hello"
    cmds:
      - echo hello
 ```

```sh
$ task silent:me-not-silent
task: [silent:me-not-silent] echo hello # <- not very silent :(
hello
```

When silent set to the included job directly, then it works as expected.

**Comment by vmaerten** [comment]
hi @ambis 
As a workaround we can specify `silent: true` in the task itself : 

```yml
# taskfile.silent.yml
version: "3"

tasks:
  me-not-silent:
    silent: true
    desc: "hello"
    cmds:
      - echo hello

```
