### ISSUE TITLE
Prefix --summary output by task description if description and summary available

### ISSUE THREAD

**Issue by ypid-work** [go-task/task#1333]
`task --summary build` should probably include the short task description if available. The [example given in the docs](https://taskfile.dev/usage/#display-summary-of-task) also highlights this need. What description would that build task have? Probably "Release your project to github" that was included in the summary. But then we have redundantly. I see the following options:

## 1. Add special variable "DESC" to be used in summary

Would be most flexible and allow something like this:

```yaml
tasks:
  release:
    # deps: [build]
    desc: Release your project to github
    summary: |
      {{ .DESC }}

      It will build your project before starting the release.
      Please make sure that you have set GITHUB_TOKEN before starting.
    cmds:
      - your-release-tool
```

## 3. Add `include_desc_in_summary` option into Taskfile schema

Add to https://taskfile.dev/api/#taskfile-schema

Less flexible. Should probably default to true.

## 4. special variable "DESC" from 1 and `include_desc_in_summary` from 3
