### ISSUE TITLE
False positive precondition fails if context is aborted

### ISSUE THREAD

**Issue by sylv-io** [go-task/task#1337]
I have a bug similar to #597 where you can see precondition false positives error print that can be reproduced with the following tasks:
```
version: '3'

tasks:
  default:
    deps:
      - fail-0s
      - pass-1s
    cmds:
      - "true"
  fail-0s:
    run: always
    preconditions:
      - sh: 'false'
        msg: "precondition should fail"

  pass-1s:
    run: always
    preconditions:
      - sh: 'sleep 1; true'
        msg: "precondition should never fail"
```

output:
```
$ task
task: precondition should fail
task: precondition should never fail
task: precondition not met
```

Context abort due to a failed context causes other conditions to print the error message as well.
I already found the reason, so a PR will follow soon :+1:

- Task version: main (72d77eb)
- Operating system: Arch Linux
- Experiments enabled: no
