### ISSUE TITLE
`vars` available for `cmd` inside `cmds`

### ISSUE THREAD

**Issue by davinkevin** [go-task/task#1339]
Hello 👋 , 

First, thank you for this wonderful tool I use all the time, and do a lot of promotion for it, it's a must have now in a system for me, good job on it! 

I open this issue because I think this could be a bit better to have `vars` object available in each `cmd` of `cmds`. An example is better than a full paragraph, so see:

```
  release:publish:
    cmds:
      - vars:
          FOO: bar
        cmd: echo {{.FOO}}
      - vars:
          X: "Y"
        cmd: echo {{.X}}
```

This is not working, even if the syntax is valid. It could be, for me, a good alternative to the lack of variable sharing between each command. So I can use `vars.*.sh` to extract value from a subcommand and then use it in the last one. 

At the moment, I have to create an extra task just for this… which is painful for the exact same result.
