### ISSUE TITLE
Add option to ignore status checks when running with --list --json options

### ISSUE THREAD

**Issue by amancevice** [go-task/task#1348]
When running `task --list --json` it would be useful to have an additional `--no-status` option to disable running the status checks for each task.

For example, given the following taskfile:

```yaml
---
version: "3"

tasks:
  init:
    desc: Inititalize project
    status:
      - brew bundle check
    cmds:
      - brew bundle
```

if I run `task --list` the task(s) are listed almost instantly, but if I run `task --list --json` it takes about 3.5s because it's calculating the status of the `init` task. It would be useful to have another flag, eg `--no-status` to disable this check to make listing the tasks easier.
