### ISSUE TITLE
Version > 3.28 not working with include from different Taskfiles

### ISSUE THREAD

**Issue by almeida-allan** [go-task/task#1360]
- Task version: 3.30
- Operating system: Ubuntu
- Experiments enabled:

Say I have following folder structure:

.
├── Taskfile.yaml
└── foo/
    └── Taskfile.yaml
    
So in root `Taskfile.yaml` I have

```yaml
version: '3'

includes:
  foo:
    taskfile: ./foo/Taskfile.yaml
    dir: './foo'

tasks:

  run:
    deps:
      - task: foo:run
```

An in `foo/Taskfile.yaml` I have:

```yaml
version: '3'

tasks:

  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - npm start
```

This works just fine in version 3.28 and below, but 3.30 does not work anymore. It gives error

```bash
npm ERR! npmcode ENOENT
npm ERR!  syscall open
ERR! npmcode  ENOENT
ERR!npm  ERR!path /home/myuser/root/package.json
 syscall open
npm ERR! path /home/myuser/root/package.json
npm ERR! errno -2
npm ERR! errno -2
npm npmERR!  ERR! enoentenoent ENOENT: no such file or directory, open '/home/myuser/root/package.json'
```

It's like it is trying to run the commands in the root directory even If I'm specifying the `dir` when I include `foo/Taskfile.yaml`
