### ISSUE TITLE
Change to sources triggers all tasks when using watch

### ISSUE THREAD

**Issue by kasperg** [go-task/task#1380]
- Task version: 3.31.0
- Operating system: OSX Sonoma 14.0
- Experiments enabled: No

I am not sure whether this is a bug or a feature but `watch` behaves differently than I expected. If I enable watching for a task (parent) which depends on or runs other tasks where one (`watcher`) specifies `sources´/`generates` and the other (`simple`) does not, and the sources for `watcher` is updated then both `watcher` and `simple` are executed

I had expected that only `watcher` (and potentially any dependencies) would be executed as this is the task for which the sources are updated.

I have tried to demonstrate this with the following `Taskfile.yml`:

```yaml
version: '3'

tasks:
  simple:
    cmds:
      - echo "Simple triggered"

  watcher:
    generates:
      - generated.txt
    sources:
      - source.txt
    cmds:
      - echo "Watcher triggered"
      - cp source.txt generated.txt

  parent:
    deps:
      - simple
      - watcher
```

In this case if I create a `sources.txt`  and run ` task parent --watch` I see 

```sh
$: task parent --watch
task: Started watching for tasks: parent
task: [simple] echo "Simple triggered"
Simple triggered
task: [watcher] echo "Watcher triggered"
Watcher triggered
task: [watcher] cp source.txt generated.txt
```

If I change the contents of `sources.txt` I see:

```
task: [simple] echo "Simple triggered"
task: [watcher] echo "Watcher triggered"
Watcher triggered
task: [watcher] cp source.txt generated.txt
Simple triggered
```

I had only expected to see:

```
task: [watcher] echo "Watcher triggered"
Watcher triggered
task: [watcher] cp source.txt generated.txt
```
