### ISSUE TITLE
Strange results of task --status 

### ISSUE THREAD

**Issue by antonmarin** [go-task/task#139]
If relevant, include the following information:
- Task version: 2.1.0
- OS: MacOS 10.13
- Example Taskfile showing the issue
```
deploy-dev:
    cmds:
      - smth here
    status:
      - if [ -z $(helm ls -q {{ printf "%s-dev" "plc-frontend" }}) ]; then exit 1; else exit 0; fi
```

```
▶ task --status deploy-dev
task: Task "deploy-dev" is not up-to-date

▶ task deploy-dev         
task: Task "deploy-dev" is up to date
```
