### ISSUE TITLE
Environment inheritance not working as expected when invoking subtasks

### ISSUE THREAD

**Issue by titpetric** [go-task/task#1391]
When invoking subtasks, the environment settings of the parent task are not propagated.

```
---
version: "3"

tasks:
  e2e:
    desc: "Run e2e/integration tests"
    env:
      TASK_ENV_VAR: "env-value"
    cmds:
      - task: test-repository

  test-repository:
    internal: true
    desc: "Test repository"
    cmds:
      - env | grep TASK
```

Running `task e2e` produces no output, while I would expected it to print the TASK_ENV_VAR value.
