### ISSUE TITLE
Recent taskfile doesn't take vars from env or args

### ISSUE THREAD

**Issue by titpetric** [go-task/task#1393]
I reinstalled task today from latest:

```
Task version: v3.31.0 (h1:o6iyj9gPJXxvxPi/u/l8e025PmM2BqKgtLNPS2i7hV4=)
```

Following the docs example:

```
version: '3'

tasks:
  print-var:
    cmds:
      - echo "{{.VAR}}"
    vars:
      VAR: Hello!
```

None of the suggested methods seem to allow to override the variable value:

```
# VAR=foo task print-var
task: [print-var] echo "Hello!"
Hello!
# task print-var VAR=foo
task: [print-var] echo "Hello!"
Hello!
# task VAR=foo print-var
task: [print-var] echo "Hello!"
Hello!
```

If i move the `vars` definition into global scope:

```
# task VAR=foo print-var
task: [print-var] echo "foo"
foo
# task print-var VAR=foo
task: [print-var] echo "foo"
foo
# VAR=foo task print-var
task: [print-var] echo "Hello!"
Hello!
```

https://taskfile.dev/usage/#variables says overriding by env should be possible, and I remember the first case (explicit args per task target) working, as I have taskfiles and docs in place that rely on that behaviour.

**Comment by andreynering** [comment]
Hi @titpetric,

As the documentation says, `Variables declared in the task definition` has the highest importance, so they aren't overridable by default.

Use the `default` template function to allow that:

```yaml
version: '3'

tasks:
  print-var:
    cmds:
      - echo "{{.VAR}}"
    vars:
      VAR: '{{.VAR | default "Hello!"}}'
```
