### ISSUE TITLE
Feature request: Allow taskfile schema to use options related to remote taskfiles

### ISSUE THREAD

**Issue by c-ameron** [go-task/task#1403]
As discussed [here](https://github.com/go-task/task/pull/1345#issuecomment-1791296189), I'd like to see options for the remote taskfiles to be included in taskfile schema.

Having them as a key in the .yml would make it easier to manage the options and a less clunky CLI invocation (especially in the context of sourcing/sharing different remote taskfiles).

As an example
``` yaml
includes:
  my-remote-namespace: https://raw.githubusercontent.com/my-org/my-repo/main/Taskfile.yml
  offline: true
  auto-update-ttl: weekly
```

I understand that you don't want to do schema changes while the remote taskfiles are still an experiment, but something to track/think about if it makes it to GA.

Thanks again for your work!
