### ISSUE TITLE
Inadequate Propagation of SIGTERM and SIGINT to Task Subprocesses

### ISSUE THREAD

**Issue by cake-monotone** [go-task/task#1408]
Script: `signal-test.sh`
```sh
#!/bin/sh

# Set up signal traps
trap 'echo "Received SIGINT"' SIGINT
trap 'echo "Received SIGTERM"' SIGTERM

# Infinite loop to keep the script running
while true; do
    sleep 1
done

```

Task Configuration: `Taskfile.yml`
```
version: "3"

tasks:
  signal-test:
    cmds:
      - sh ./signal-test.sh

```

Given the process structure:
```
# ps output for reference
PID   PPID  CMD
2       1    task signal-test
3       2    sh ./signal-test.sh

```

When executing kill -INT 2, the following output is observed:
```sh
kill -INT 2
# task: Signal received: "interrupt"
# However, the signal is not propagated to `signal-test.sh`
```

It is critical to note that the SIGINT signal fails to reach the subprocess. This issue is particularly problematic when using Taskfile within a Docker container. Both `docker stop` and CTRL-C interruption during `docker run` attempt to send SIGINT or SIGTERM to the Taskfile process directly. The described problem prevents Docker from achieving a 'graceful exit'.

- Task version: Task version: v3.31.0 (h1:o6iyj9gPJXxvxPi/u/l8e025PmM2BqKgtLNPS2i7hV4=)
- Operating system: Mac
- Experiments enabled:

**Comment by cake-monotone** [comment]
How about this flows?

1. Propagate SIGINT or SIGTERM signals directly to the currently running command.
2. Allow the command to complete its process.
3. If the command finishes, the taskfile should stop without triggering any further commands.

What do you think of this idea?

**Comment by Elijas** [comment]
+1 Same here - the described problem prevents Docker from achieving a 'graceful exit'. 
Any solutions?

**Comment by lookitsatravis** [comment]
I'm also experiencing this issue with Docker. My work around is to start the container with `-d` and then I have a stop task which I run at the beginning of the stop task to try and kill the container. It's fine, but it would be better if signals propagated.

Here's what I do for anyone who is dealing with this for Docker:

```yml
# https://taskfile.dev

version: "3"

vars:
  IMAGE_NAME: my-app
  IMAGE_TAG: latest
  IMAGE: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all

  build:
    desc: Build the app
    cmds:
      - docker build . -t {{.IMAGE}}

  start:
    desc: Start the app
    deps:
      - build
    cmds:
      - cmd: task stop
        ignore_error: true
      - docker run -d --rm -p 8080:8080 --name my-app {{.IMAGE}}
      - cmd: docker logs --follow my-app
        ignore_error: true

  stop:
    desc: Stop the app
    cmds:
      - docker stop my-app
```
