### ISSUE TITLE
Global `vars:` & `env:` are not interpolated in `tasks:` `desc:` fields

### ISSUE THREAD

**Issue by itnok** [go-task/task#1410]
- Task version: 3
- Operating system: darwin / macOS
- Experiments enabled: No
- Example `Taskfile.yaml` to reproduce the issue:

```yaml
---
version: "3"

env:
  SOME_STATIC_ENV: "ful"
  SOME_DYNAMIC_ENV:
    sh: echo "beauti"

vars:
  SOME_STATIC_VAR: "o "
  SOME_DYNAMIC_VAR:
    sh: echo "hell"

tasks:
  not-helpful:
    desc: {{ .SOME_DYNAMIC_VAR }}{{ .SOME_STATIC_VAR }}{{ .SOME_DYNAMIC_ENV }}{{ .SOME_STATIC_ENV }} {{ OS }} world
    cmds:
      - true
```

Expected output:

```txt
hello beautiful darwin world
```

Output:

```txt
hellful darwin world
```

Variable interpolation works well, but it seems that `desc:` does not support interpolation for neither `vars:` or `env:` variables that are _"dynamically"_ generated _(or more likely `vars:` and `env:` are not computed before `desc:` interpolation happens?)_. I am looking for this to try to make my tasks a little more generic... _(similar to #276 but not limited to Golang templates)_

**Comment by clarson99** [comment]
This same issue exists with both the `desc:` and `prompt:` fields.  I'd like to be able to run something like:

`ENVIROMENT=prod task deploy`

But the prompt comes back looking like:

`You are about to deploy to ${ENVIROMENT}, continue? [y/N]`

Instead of the desired:

`You are about to deploy to prod, continue? [y/N]`

**Comment by vmaerten** [comment]
@itnok in desc (and prompt), you can interpolate static variables but not dynamic variables. This is intentional, mainly for better performance, as this command is used for autocomplete.

@clarson99 this is working actually : 

```yml
version: "3"

tasks:
  deploy
    prompt: 'You are about to deploy to {{.ENV}}'
    cmds:
      - true
```
