### ISSUE TITLE
Support labels for commands

### ISSUE THREAD

**Issue by Chi-teck** [go-task/task#1411]
## Motivation
When running multiple commands it sometimes difficult to distinguish their ouput.
```yml
cmds:
  - some/script.sh
  - task: some_task
  - another/script.sh
  - task: another_task
```

## Proposed solution

Add `label`  property to [cmd difinition](https://taskfile.dev/api/#command) so the above example could be modified as follows.
```yml
cmds:
  - label: Step 1
    cmd: ./some/script.sh
  - label: Step 2
    task: some_task
  - label: Step 3
    cmd: another/script.sh
  - label: Step 4
    task: another_task
```

Currently it requires adding extra commands like follows
```
- echo -e "\e[0;32mStep 1\e[0m"
``` 
This doesn't look well. Also the color scheme may not be consistent with the colors used by Task itself.
