### ISSUE TITLE
Bug: In watch mode, when sources are present in another task, defer statements run after re-running the task

### ISSUE THREAD

**Issue by 20manas** [go-task/task#1413]
Expected Behavior: Regardless of where the sources are, if files are being watched and a file among them changes, defer statements should always run before running the task again.

Taskfile:
```yaml
version: '3'

tasks:
  server:
    watch: true
    sources: 
      - '**/*.go'
    generates:
      - './tmp/main'
    cmds:
      - go build -o ./tmp/main ./cmd/something/
      - ./tmp/main

  
  abc:
    watch: true
    cmds:
      - echo "started"
      - defer: echo "ended"
      - task: server
```
Output:

![image](https://github.com/go-task/task/assets/14952218/4463b49d-cb1f-4332-959e-0cf3742c73d4)

- Task version: v3.31.0
- Operating system: Linux
- Experiments enabled: no

**Comment by 20manas** [comment]
@pd93 @andreynering could you please look into this issue

**Comment by trulede** [comment]
This might be resolved by adding a waitgroup to the watcher

```
func (e *Executor) watchTasks(calls ...*Call) error {
    ...	
    var wg sync.WaitGroup
    ctx, cancel := context.WithCancel(context.Background())

    wg.Add(1)
    go func() {
        defer wg.Done()
        ..... 
        for {
            select {
            case <-ctx.Done():
                return
            default:
            }
        }
    }()

    cancel()
    wg.Wait()
```

A similar solution was mentioned in #160, although for different reasons where it would not have been effective (i.e. process management .. which is more complicated than it first appears).

**Comment by trulede** [comment]
As the issue is described, the behaviour is normal. The task `abc` appears to call task server, but actually, the watcher code takes over running these tasks (it collects and then runs the "calls"), and so task `abc` exits rather promptly, and runs its defer statement. To get the behaviour you want, you need to have `abc` block, and when a watched file is changed, both will restart.

However, even with that change ... defers may, and often will, run _after_ the tasks are restarted (by the watcher). So there is a bug there. I have tested a solution for that, it can be solved, and I have a PR in progress for that.

A taskfile you can use to experiment:

```
version: '3'

tasks:
  server:
    watch: true
    sources: 
      - 'foo.txt'
    cmds:
      - echo "server start"
      - defer: sleep 0.5; echo "server end"
      - sleep 1000

  client:
    watch: true
    cmds:
      - echo "client start"
      - defer: sleep 0.5; echo "client end"
      - task: server
      - sleep 1000

  default:
    watch: true
    deps:
      - client 
      - server
```
 
task -v -d ISSUES/1413 client server
or
task -v -d ISSUES/1413 default
