### ISSUE TITLE
Using summary with a for loop using tasks is not very descriptive.

### ISSUE THREAD

**Issue by hans-d** [go-task/task#1414]
Using summary with a for loop using tasks is not very descriptive.
```
vars:
  FROM_DIRS: a,b
tasks:
  example:
    desc: Something
    cmds:
      - for: { var: FROM_DIRS, split: ',' }
        task: next-task
        vars:
          DIR: '{{.ITEM}}'
```
`task --summary example`

```
task: example

Something

commands:
 - Task: next-task
 - Task: next-task
```

Might need vars or 
```
      - for: { var: FROM_DIRS, split: ',' }
        task: next-task
        desc: '{{.task}} {{.ITEM}}'
        vars:
          DIR: '{{.ITEM}}'
```

- Task version:  v3.31.0
- Operating system: Debian
- Experiments enabled: false
