### ISSUE TITLE
Variables don't work at the beginning of a command

### ISSUE THREAD

**Issue by fschoell** [go-task/task#1417]
See this example Taskfile.yaml

```yaml
version: '3'

vars:
  BUILD_FLAGS: 'GOOS=linux GOARCH=amd64'

tasks:
  build:
    cmds:
      - {{.BUILD_FLAGS}} go build
```

Result: Running `task build ` fails with the following error: 

```
task: Failed to parse Taskfile.yaml:
yaml: line 8: did not find expected '-' indicator
```

Expected behaviour: `task build` properly executing `GOOS=linux GOARCH=amd64 go build`

- Task version: 3.32.0
- Operating system: MacOS 14.1.1
- Experiments enabled: no

**Comment by pd93** [comment]
You need to quote your command string:

```yaml
version: '3'

vars:
  BUILD_FLAGS: 'GOOS=linux GOARCH=amd64'

tasks:
  build:
    cmds:
      - '{{.BUILD_FLAGS}} go build'
```
