### ISSUE TITLE
Propagation of variables fails since the v3.33.0 release.

### ISSUE THREAD

**Issue by ZCube** [go-task/task#1435]
- Task version: v3.33.0
- Operating system: Linux
- Experiments enabled:

* Example
```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GIT_URL:
    sh: git ls-remote --get-url
  GIT_GROUP: '{{first (slice (splitList "/" .GIT_URL) 3 4)}}'
  GIT_PROJECT: '{{first (slice (splitList ".git" (first (slice (splitList "/" .GIT_URL) 4 5))) 0)}}'

tasks:
  test:
    desc: update tasks
    cmds:
      - echo {{.GIT_URL}}
      - echo {{.GIT_GROUP}}
      - echo {{.GIT_PROJECT}}
```

* v3.33.0 (Fail)
```bash
root@a577eb48cc8f:/work# TASK_X_ANY_VARIABLES=1 task test
template: :1:30: executing "" at <.GIT_URL>: wrong type for value; expected string; got map[string]interface {}
root@a577eb48cc8f:/work# TASK_X_ANY_VARIABLES=0 task test
template: :1:9: executing "" at <slice (splitList "/" .GIT_URL) 3 4>: error calling slice: reflect.Value.Slice: slice index out of bounds
```

* v3.32.0 (Success)
```bash
root@a577eb48cc8f:/work# TASK_X_ANY_VARIABLES=1 task test
task: [test] echo ssh://git@nas.dev.opnd.io:2222/d2e/backend
ssh://git@******/some/backend
task: [test] echo some
some
task: [test] echo backend
backend
root@a577eb48cc8f:/work# TASK_X_ANY_VARIABLES=0 task test
task: [test] echo ssh://git@nas.dev.opnd.io:2222/d2e/backend
ssh://git@******/some/backend
task: [test] echo some
some
task: [test] echo backend
backend
```
