### ISSUE TITLE
Dynamic vars with tasks

### ISSUE THREAD

**Issue by hans-d** [go-task/task#1439]
Allow vars/envs to be dynamic with output from another task, not just shell commands.

```
vars:
   BLAH:
      task: :some:other:task
   FOO:
      sh: echo {{.BLAH}} | grep x
   BAR:
      task: :yet:some:other:task
      var:
         TARGET: '{{.FOO}}'
```

**Comment by mgbowman** [comment]
Any chance we could triage this issue? I could really use this feature and would like to try and implement it.

**Comment by victor-ufg** [comment]
I also ran into this, I actually tried this first because it kind of felt "natural", to only find out in the docs it isn't supported :/

Also, I find that the "workaround" (running `sh: task some:other:task`) is tricky to execute well when you're including the task in another Taskfile (you end up having to make the tasks "public" rather than internal, and knowing the included Taskfile namespace).

**Comment by trulede** [comment]
You can do this

```
version: '3'

tasks:
  default:
    cmds:
      - cmd: echo "FOO_ENVAR=foo" > tdotenv
      - task: dotenv
  dotenv:
    dotenv: [tdotenv]
    cmds: 
      - cmd: echo "  var FOO_ENVAR = $FOO_ENVAR"
```

I think it covers most use cases. You can also simply source files (on Linux), and use multiline cmds to collect/redirect/consolidate ouput.
