### ISSUE TITLE
Add ability to register output of a task and make it available in templates context

### ISSUE THREAD

**Issue by iilyak** [go-task/task#1449]
`rash-sh` allows passing arbitrary values from one task from another one via register (see [here](https://rash-sh.github.io/docs/rash/v1.10/tasks.html))

```
tasks:
  sources:
    cmds:
      - sh: find . -type f -name '*.c'
  mytask:
    cmds:
      - task: sources
         register: sources_result
      - echo discovered files {{ .sources.output }}
      - echo stderr {{ .sources.extra.stderr }}
      - echo return code {{ .sources.extra.return_code }}
```

Starting from the above we can go further and allow multiple named returns

```
  sources:
    cmds:
      - sh: find . -type f -name '*.c'
         register: c_sources
      - sh: find . -type f -name '*.cpp'
         register: cpp_sources
      - sh: find . -type f -name '*.h'
         register: h_sources
    register:
         sources: # the result would be flattened (concatenation of lists) 
            - c_sources
            - cpp_sources
         headers: h_sources
      
  mytask:
    cmds:
      - task: sources
         register:
            inputs: sources
            headers: headers
            rc: _rc # assume we always register return code in `_rc` output
            sterr: _stderr # assume we always register return code in `_stderr` output
      - echo discovered files {{ .inputs }}
      - echo header files {{ .headers }}
      - echo stderr {{ .stderr }}
      - echo return code {{ .rc }}
```

This design has sufficient level of indirection to avoid any name collisions. Also it doesn't pollute the global namespace.

**Comment by thetanil** [comment]
register is also supported in Ansible. you use it not just for templates context, but for conditionals in the task itself using ```when:``` and probably others.

[example from ansible docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#registering-variables)
```
- hosts: web_servers

  tasks:

     - name: Run a shell command and register its output as a variable
       ansible.builtin.shell: /usr/bin/foo
       register: foo_result
       ignore_errors: true

     - name: Run a shell command using output of the previous task
       ansible.builtin.shell: /usr/bin/bar
       when: foo_result.rc == 5
``` 

The struct for vars created with register are kind of complex in a way which I'm not a huge fan of, but exit status (registered_var.rc) and stdout separate from stderr is very useful.
