### ISSUE TITLE
task requires vars doesnt exit if var is not there

### ISSUE THREAD

**Issue by xsteadfastx** [go-task/task#1453]
i try to check for a variable to be set before running the task. this doesnt work

example (the only Taskfile in that directory and with just that content):

```yaml
version: "3"

tasks:
  foo:
    cmds:
      - echo before {{.BLA}} after
    run: once
    requires:
      vars:
        - BLA
```
if i run it it will just echos the blank variable

```sh
$ task foo
task: [foo] echo before  after
before after
```

- Task version: `Task version: v3.23.0 (h1:egOOrya0biMnrV1W8RSEo2pviHMGTtBmy4VqxUYfcyk=)`
- Operating system: linux ubuntu
- Experiments enabled: -
