### ISSUE TITLE
After the v3.32.0 release, variable propagation to environment variables fails.

### ISSUE THREAD

**Issue by ZCube** [go-task/task#1463]
- Task version: v3.33.1
- Operating system: Linux
- Experiments enabled:

* Example
```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  test:
    vars:
      GIT_URL:
        sh: git ls-remote --get-url
      GIT_GROUP: '{{first (slice (splitList "/" .GIT_URL) 3 4)}}'
      GIT_PROJECT: '{{first (slice (splitList ".git" (first (slice (splitList "/" .GIT_URL) 4 5))) 0)}}'
    env:
      GIT_URL_ENV: "{{.GIT_URL}}"
      GIT_GROUP_ENV: '{{first (slice (splitList "/" .GIT_URL) 3 4)}}'
      GIT_PROJECT_ENV: '{{first (slice (splitList ".git" (first (slice (splitList "/" .GIT_URL) 4 5))) 0)}}'
    desc: test task
    cmds:
      - echo {{.GIT_URL}}
      - echo {{.GIT_GROUP}}
      - echo {{.GIT_PROJECT}}
      - echo ${GIT_URL_ENV}
      - echo ${GIT_GROUP_ENV}
      - echo ${GIT_PROJECT_ENV}
```

* v3.32.0 (Fail)
```bash
task test
template: :1:9: executing "" at <slice (splitList "/" .GIT_URL) 3 4>: error calling slice: reflect.Value.Slice: slice index out of bounds
```

* v3.31.0 (Success)
```bash
task: [test] echo https://github.com/go-task/task/
https://github.com/go-task/task/
task: [test] echo go-task
go-task
task: [test] echo task
task
task: [test] echo ${GIT_URL_ENV}
https://github.com/go-task/task/
task: [test] echo ${GIT_GROUP_ENV}
go-task
task: [test] echo ${GIT_PROJECT_ENV}
task
```
