### ISSUE TITLE
Allow generates to be a command

### ISSUE THREAD

**Issue by jaxxstorm** [go-task/task#147]
The sources and generates functions are awesome. I'm using task to build dockerfiles now, and it'd be nice to be able to set the `generates` directive to be a command that runs with exit codes.

Example:

```
docker:
    desc: "Build docker image"
    cmds:
      - docker build -t jaxxstorm/rpmbuild:{{ .DOCKER_IMAGE_VERSION }} .
    sources:
      - Dockerfile
    generates:
       - docker images jaxxstorm/rpmbuild | grep 0.0.2 # exits with 1, fails
```

**Comment by andreynering** [comment]
Hi @jaxxstorm,

We have `status`, that replaces the whole `sources`/`generates` thing with a list of commands:

```yaml
version: '2'

tasks:
  generate-files:
    cmds:
      - mkdir directory
      - touch directory/file1.txt
      - touch directory/file2.txt
    # test existence of files
    status:
      - test -d directory
      - test -f directory/file1.txt
      - test -f directory/file2.txt
```

If all task returns status 0, the task is considered up-to-date.

Example taken from: https://taskfile.org/#/usage?id=prevent-unnecessary-work

Would that work for you?
