### ISSUE TITLE
Cannot execute task for each item in a list

### ISSUE THREAD

**Issue by jakubledl** [go-task/task#1485]
- Task version: `Task version: 3.33.1` (installed via homebrew)
- Operating system: macos 14.2.1
- Experiments enabled: none

Following the documentation sample at https://taskfile.dev/usage/#looping-over-tasks.

Given the following `Taskfile.yml`:

```yaml
version: 3

tasks:
  install-bins:
    cmds:
      - for:
          - google.golang.org/protobuf/cmd/protoc-gen-go
          - google.golang.org/grpc/cmd/protoc-gen-go-grpc
        task: install-bin
        # cmd: echo {{.ITEM}}
        vars:
          BIN: {{.ITEM}}

  install-bin:
    internal: true
    cmds:
      - echo {{.BIN}}
```

running `task install-bins` gives the following:

```
task: Failed to parse Taskfile.yml:
yaml: line 6: invalid keys in command
[1]    8230 exit 102   task install-bins
```

Modyfing the file as follows (not touching line 6 at all):

```yaml
version: 3

tasks:
  install-bins:
    cmds:
      - for:
          - google.golang.org/protobuf/cmd/protoc-gen-go
          - google.golang.org/grpc/cmd/protoc-gen-go-grpc
        # task: install-bin
        cmd: echo {{.ITEM}}
        vars:
          BIN: {{.ITEM}}

  install-bin:
    internal: true
    cmds:
      - echo {{.BIN}}
```

gives the expected result:

```
task: [install-bins] echo google.golang.org/protobuf/cmd/protoc-gen-go
google.golang.org/protobuf/cmd/protoc-gen-go
task: [install-bins] echo google.golang.org/grpc/cmd/protoc-gen-go-grpc
google.golang.org/grpc/cmd/protoc-gen-go-grpc
```

**Comment by pd93** [comment]
Hi @jakubledl. Looks like a quotation issue to me. YAML is sensitive to strings when values begin or contain certain characters. In general, it's best to quote them to stop this issue:

```yaml
version: 3

tasks:
  install-bins:
    cmds:
      - for:
          - google.golang.org/protobuf/cmd/protoc-gen-go
          - google.golang.org/grpc/cmd/protoc-gen-go-grpc
        task: install-bin
        vars:
          BIN: "{{.ITEM}}" # <-- Quoting this value fixes the issue

  install-bin:
    internal: true
    cmds:
      - echo {{.BIN}}
```

There is some more detailed information on YAML strings and when you should quote them in this [StackOverflow post](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml).
