### ISSUE TITLE
GOARCH incorrect on Mac M2

### ISSUE THREAD

**Issue by p0ll3n** [go-task/task#1488]
The ARCH variable contains amd64 when I expect to have arm64, like reported by the 'uname -m' command.
This prevent me to run task on specific platform like [ darwin/arm64 ]

example task file:

```
# https://taskfile.dev

version: '3'
  foo:
    cmds:
      - cmd: echo "Running command on {{OS}} ({{ARCH}})"

```
will output:

```
task: [foo] echo "Running command on darwin (amd64)"
Running command on darwin (amd64)

```

- Task version: v3.32.0 (h1:K3NsqVLjkWGO5rbCw8AF2ImDc7/M/SVoFF1fFTvCDEA=)
- Operating system: MacOs 14.2.1 (23C71)
- Experiments enabled: false
