### ISSUE TITLE
strange syntax error, only difference is a space. 

### ISSUE THREAD

**Issue by bayeslearner** [go-task/task#1493]
```
  switch_context:
    desc: "Switch to a different context."
    vars:
      NEW_CONTEXT_NAME: "{{.NEW_CONTEXT_NAME | default ``}}"
    cmds:
      - echo 'Switching to context:' '{{.NEW_CONTEXT_NAME}}' 
      - echo 'Switching to context:{{.NEW_CONTEXT_NAME}}'  
      - echo 'Switching to context: {{.NEW_CONTEXT_NAME}}'  
      - sed -i.bak 's/^export CONTEXT_NAME=.*/export CONTEXT_NAME="{{.NEW_CONTEXT_NAME}}"/' "{{.ROOT_DIR}}/.envrc.context"
      - rm "{{.ROOT_DIR}}/.envrc.context.bak"
      - direnv allow "{{.ROOT_DIR}}"
   ```
   The third echo will cause syntax errors.  Why?
