### ISSUE TITLE
Variables Passed to Included Taskfile Is Unavilable During Global Variables Expansion

### ISSUE THREAD

**Issue by liblaf** [go-task/task#1503]
- Task version: v3.34.1 (h1:yAAxUM54zoaHv+OtDnGgkWSVeiRuaOCn1lPUXPQQA0o=)
- Operating system: Arch Linux
- Experiments enabled: None

## Reproduction

```yaml
# Taskfile.yaml
version: "3"

includes:
  hello:
    taskfile: taskfiles/hello.yaml
    vars:
      NAME: world

tasks:
  default:
    deps:
      - hello:default
```

```yaml
# taskfiles/hello.yaml
version: "3"

vars:
  MESSAGE: "Hello, {{.NAME}}!"

tasks:
  default:
    cmds:
      - echo "{{.MESSAGE}}"
    requires:
      vars:
        - MESSAGE
```

## Actual Output

```console
$ task
task: [hello:default] echo "Hello, !"
Hello, !
```

## Expected Output

```console
$ task
task: [hello:default] echo "Hello, world!"
Hello, world!
```
