### ISSUE TITLE
When I set watch for a task that uses deps from includes, then the wrong watchlist is set

### ISSUE THREAD

**Issue by sirenkovladd** [go-task/task#1504]
example:
```yml
version: '3'

tasks:
  build:
    cmds:
      - echo subtask
    sources:
      - list.json
```
```yml
version: '3'

includes:
  sub:
    taskfile: ./sub
    internal: true

tasks:
  dev:
    deps: [sub:build]
    watch: true
    cmds:
      - node index.js
    method: none
    sources:
      - index.js
```

- Task version: v3.34.1
- Operating system: Darwin arm64
- Experiments enabled: false

what i see
the sub:build command is never called, even after restarting the task
after editing json, the dev task is not reload (although when editing index.js it is reload)

**Comment by sirenkovladd** [comment]
list.json has been modified and here is the run result after
```sh
task: Started watching for tasks: dev
task: Watching for changes every 5s
task: "dev" started
task: watching new file: /var/folders/36/nhtbdyy51gg2n2snnk7c7gnr0000gn/T/tmp.eXNSAjpqGg/index.js
task: "sub:build" started
task: Task "sub:build" is up to date
task: [dev] node index.js
{ q: 1 }
task: "dev" finished
```

**Comment by sirenkovladd** [comment]
workaround

```yml
includes:
  sub:
    dir: ./sub
    taskfile: ./sub
    internal: true
```
