### ISSUE TITLE
Any variables: Template strings in nested map variables aren't executed

### ISSUE THREAD

**Issue by pd93** [go-task/task#1511]
When you create a map variable using the any variables experiment, any strings that contain templating are not evaluated by the templating engine. Instead, the raw, unevaluated string is returned.

```yaml
version: '3'

vars:
  IMAGE_TAG: 'latest'

tasks:
  default:
    vars:
      works: '{{.IMAGE_TAG}}'
      # TASK_X_ANY_VARIABLES=1
      does:
        not:
          work: '{{.IMAGE_TAG}}'
      # TASK_X_ANY_VARIABLES=2
      does:
        map:
          not:
            work: '{{.IMAGE_TAG}}'
    cmds:
      - 'echo {{.works}}'
      - 'echo {{.does.not.work}}'
```

_Originally posted by @cwrau in https://github.com/go-task/task/issues/1415#issuecomment-1953012547_
            
- Task version: v1.34.1
- Operating system: Linux
- Experiments enabled: Any Variables 1/2
