### ISSUE TITLE
Wildcards not working

### ISSUE THREAD

**Issue by iPenguin** [go-task/task#1519]
Hi I'm trying to use the wildcard arguments as [listed in the documentation](https://taskfile.dev/usage/#wildcard-arguments). I've updated to the latest version of taskfile but it's not working.

I also tried to copy the example in the docs and that isn't working either.

Am I missing something obvious?

```
---
version: '3'

tasks:
  echo-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - echo {{.TEXT}}

  run-*-*:
    vars:
      ARG_1: '{{index .MATCH 0}}'
      ARG_2: '{{index .MATCH 1}}'
    cmds:
      - echo {{.ARG_1}} {{.ARG_2}}
```

Thanks,
Brian

- Task version: v3.34.1
- Operating system: Linux
- Experiments enabled: no
