### ISSUE TITLE
Wildcard issues

### ISSUE THREAD

**Issue by stelcheck** [go-task/task#153]
- Task version: latest
- OS: Linux

> Taskfile.yml

```yaml
    test:unit:
        desc: "Run unit test suite"
        silent: true
        cmds:
            - go test ./pkg/tests/* -bench=.
        sources: *sources
```

This does not seem to work - I think the './' prefix gets truncated for each file, thus causing an issue:

> Output

```plaintext
can't load package: package pkg/tests/game: cannot find package "pkg/tests/game" in any of:
        /usr/lib/go/src/pkg/tests/game (from $GOROOT)
        /home/stelcheck/go/src/pkg/tests/game (from $GOPATH)
can't load package: package pkg/tests/pitch: cannot find package "pkg/tests/pitch" in any of:
        /usr/lib/go/src/pkg/tests/pitch (from $GOROOT)
        /home/stelcheck/go/src/pkg/tests/pitch (from $GOPATH)
can't load package: package pkg/tests/statemachine: cannot find package "pkg/tests/statemachine" in any of:
        /usr/lib/go/src/pkg/tests/statemachine (from $GOROOT)
        /home/stelcheck/go/src/pkg/tests/statemachine (from $GOPATH)
task: Failed to run task "test": task: Failed to run task "test:unit": exit status 1
```

Fun fact, `$(pwd)` as a prefix makes the glob not work:

> Taskfile.yml

```yaml
    test:unit:
        desc: "Run unit test suite"
        silent: true
        cmds:
            - go test $(pwd)/pkg/tests/* -bench=.
        sources: *sources
```

> Output 

```plaintext
can't load package: package ***censored***/pkg/tests/*: cannot find package "***censored***/pkg/tests/*" in any of:
        /usr/lib/go/src/***censored***/pkg/tests/* (from $GOROOT)
        /home/stelcheck/go/src/***censored***/pkg/tests/* (from $GOPATH)
task: Failed to run task "test": task: Failed to run task "test:unit": exit status 1
```
