### ISSUE TITLE
Computed environment variables have started happening in the task directory.

### ISSUE THREAD

**Issue by PaulPopat** [go-task/task#1536]
- Task version: v3.35.1
- Operating system: Ubuntu Server
- Experiments enabled: None
- Last working version: v3.34.1

When running a computed environment at the top of a task file, the working directory used to be the task file directory. Now it is the directory specified in the specific task. This means that referencing setup files is breaking.

```
version: '3'

env:
  ACCESS_KEY:
    sh: ./scripts/login.sh

tasks:
  broken-task:
    # Looks for "{{.TASKFILE_DIR}}/test/scripts/login.sh" for the value of "ACCESS_KEY" as opposed to "{{.TASKFILE_DIR}}/scripts/login.sh"
    dir: "{{.TASKFILE_DIR}}/test"
    cmds:
      - echo "$ACCESS_KEY"

  working-task:
    cmds:
      - echo "$ACCESS_KEY"
```

**Comment by pd93** [comment]
@PaulPopat I'm not able to reproduce this. Results on my machine with the following content in `./scripts/login.sh`:

```
#!/bin/bash
pwd
```

v3.34.1

```
❯ task --version                   
Task version: v3.34.1 (h1:yAAxUM54zoaHv+OtDnGgkWSVeiRuaOCn1lPUXPQQA0o=)
❯ task working-task
task: [working-task] echo "$ACCESS_KEY"
/home/pete/dev/github.com/go-task/task/tmp/1536
❯ task broken-task 
task: [broken-task] echo "$ACCESS_KEY"
/home/pete/dev/github.com/go-task/task/tmp/1536
```

v3.35.1

```
❯ task --version                                        
Task version: v3.35.1 (h1:zjQ3tLv+LIStDDTzOQx8F97NE/8FSTanjZuwgy/hwro=)
❯ task working-task                                     
task: [working-task] echo "$ACCESS_KEY"
/home/pete/dev/github.com/go-task/task/tmp/1536
❯ task broken-task                                      
task: [broken-task] echo "$ACCESS_KEY"
/home/pete/dev/github.com/go-task/task/tmp/1536
```

What is inside your `./scripts/login.sh`? and what directory/command are you using to run the task?

**Comment by PaulPopat** [comment]
Hi @pd93 Sorry it appears I miss a critical step in trying to make a minimal reproduction. It must be a sub task and it must be called without the `- task: task:name` syntax. We are doing this in our live example because we are running a task as background and piping it into a log file for running integration tests.

In Taskfile.yml
```YAML
version: '3'

env:
  TEST_STRING:
    sh: ./scripts/get-data.sh

tasks:
  test:working:
    cmds:
      - echo "$TEST_STRING"

  test:broken:
    cmds:
      - task test:working
    dir: "{{.TASKFILE_DIR}}/test/other"
```

In `scripts/get-data.sh`
```SHELL
#!/bin/bash

echo "TEST: $(pwd)"
```

Console output
```
ubuntu in 🌐 ip-10-200-9-185 in ~/task-file-test via  v18.19.0 on ☁️  (eu-west-2) 
❯ npm install -g @go-task/cli@v3.34.1

changed 2 packages in 1s

ubuntu in 🌐 ip-10-200-9-185 in ~/task-file-test via  v18.19.0 on ☁️  (eu-west-2) 
❯ task test:broken
task: [test:broken] task test:working
task: [test:working] echo "$TEST_STRING"
TEST: /workspace/ubuntu/task-file-test

ubuntu in 🌐 ip-10-200-9-185 in ~/task-file-test via  v18.19.0 on ☁️  (eu-west-2) 
❯ npm install -g @go-task/cli@v3.35.0

changed 2 packages in 1s

ubuntu in 🌐 ip-10-200-9-185 in ~/task-file-test via  v18.19.0 on ☁️  (eu-west-2) 
❯ task test:broken
task: [test:broken] task test:working
stat /workspace/ubuntu/task-file-test/test/other/scripts/get-data.sh: no such file or directory
task: Command "./scripts/get-data.sh" failed: exit status 127
task: Failed to run task "test:broken": exit status 1
```

A snippet to better demonstrate our use case
```YAML
version: '3'

env:
  AWS_ACCESS_KEY_ID:
    sh: ./utilities/assume.sh AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    sh: ./utilities/assume.sh AWS_SECRET_ACCESS_KEY
  AWS_SESSION_TOKEN:
    sh: ./utilities/assume.sh AWS_SESSION_TOKEN

tasks:
  test:browser:project:
    dir: "{{.TASKFILE_DIR}}/packages/tests"
    cmds:
      - rm -f ../../artifacts/ui-tests-app.log
      - task launch:app > ../../artifacts/ui-tests-app.log && sleep 2 &
      - task: utils:wait-for-ports
        vars:
          PORTS: '8888,7654,5432'
      - yarn run test --all=true
```
