### ISSUE TITLE
Allow values inside collection-type variables to reference one another

### ISSUE THREAD

**Issue by pd93** [go-task/task#1544]
Relates to:

- #1477
- #1511

The issues above were fixed in #1526. However, this still left the issue described in https://github.com/go-task/task/issues/1415#issuecomment-1978366328 unresolved. This issue is to track the functionality described here.

---

It is possible to use variables inside other collection-type variables. However, you are not currently able to refer to a key within the same collection-type variable in another key. For example:
 
```yaml
version: '3'

vars:
  foo: "foo"
  bar:
    works: "{{.foo}}" # Refers to a value in a different variable
  baz:
    qux: "qux"
    works: "{{.bar.works}}" # Refers to a nested value in a different variable
    fails: "{{.baz.qux}}" # Refers to a nested value in THE SAME variable

tasks:
  works:
    cmds:
      - echo {{.bar.works}}
      - echo {{.baz.works}}
  fails:
    cmds:
      - echo {{.baz.fails}}
```

```shell
❯ TASK_X_ANY_VARIABLES=1 taskd --dir ./tmp/foo works
task: [works] echo foo
foo
task: [works] echo foo
foo
```

```shell
❯ TASK_X_ANY_VARIABLES=1 taskd --dir ./tmp/foo fails
task: [fails] echo 
# Prints nothing
```
