### ISSUE TITLE
Feature request: Allow specifying env vars at the command level

### ISSUE THREAD

**Issue by justinrixx** [go-task/task#1550]
It would be nice to be able to specify an `env` key on a `command` object ([docs](https://taskfile.dev/api/#command)). This specifically enables specifying env vars in a loop, but it could have other uses.

Example I'm trying to accomplish:

```yaml
tasks:
  ci:image:build:
    desc: build a docker image for foo
    cmds:
      - for: ['386', 'amd64', 'arm', 'mips', 'ppc', 'riscv', 'sparc64', 'wasm']
        task: go:ci:build
        env: # NOT ALLOWED
          GOARCH: {{ .ITEM }}
        vars:
          APP_ID: foo
          GO_BUILD_PACKAGE: ./cmd/foo
          TEAM_ID: justinr
          GO_ENV_VARS: |-
            GOARCH
```

Instead I have to do something like this:

```yaml
tasks:
      ci:image:build:386:
    desc: build a docker image for foo on 386
    env:
      GOARCH: 386
    cmds:
      - task: go:ci:build
        vars:
          APP_ID: foo
          GO_BUILD_PACKAGE: ./cmd/foo
          TEAM_ID: justinr
          GO_ENV_VARS: |-
            GOARCH
  ci:image:build:amd64:
    desc: build a docker image for foo on amd64
    env:
      GOARCH: amd64
    cmds:
      - task: go:ci:build
        vars:
          APP_ID: foo
          GO_BUILD_PACKAGE: ./cmd/foo
          TEAM_ID: justinr
          GO_ENV_VARS: |-
            GOARCH
    ...
```
