### ISSUE TITLE
Var containing var to be replaced later?

### ISSUE THREAD

**Issue by leobenkel** [go-task/task#1552]
so imagine the main Taskfile and a child `child.Taskfile.yml`: 

`child.Taskfile.yml`: 
```yml
version: '3'
#...

tasks:
#...
   vars:
        FOO: "{{.FOO | default '' }}"
   cmds:
      - {{DO_SOMETHING}}
```

so the parent might want to do something like:

`Taskfile.yml`
```
#...

includes:
  utils:
    taskfile: child.Taskfile.yml
    vars:
       DO_SOMETHING: echo "{{.FOO}}"
#...
```

That way when the child task is called, it can leverage the locally available variable.

Is that possible today? 

specifically useful to handle utilities for `aws` queries that might have dynamic arguments
