### ISSUE TITLE
Required vars not required when calling tasks

### ISSUE THREAD

**Issue by mvhatch** [go-task/task#1557]
I tried looking to see if this was already an issue but did not find anything. Also, wasn't sure if this is a bug or a feature request. 
```
  helm-diff:
    desc: Show the diff between the current and previous helm release
    cmds:
      - task: common:helm-diff
        vars:
          HELM_ARGS: "-f=./helm/{{.PROJ}}.yaml --set image.tag={{.DOCKER_IMAGE_TAG}}"
          K8S_REGION: '{{dig .PROJ "region" .DEFAULT_K8S_REGION (mustFromJson .K8S_CONFIG)}}'
          K8S_CLUSTER: '{{dig .PROJ "cluster" .DEFAULT_K8S_CLUSTER (mustFromJson .K8S_CONFIG)}}'
    requires:
      vars: [PROJ]
```
**Expected** running `task helm-diff` fails with: `task: Task "helm-diff" cancelled because it is missing required variables: PROJ`

**Actual** task runs successfully. 
Note: `PROJ` has no default value. For comparison, this works as expected.

```
  helm-diff:
    desc: Show the diff between the current and previous helm release
    cmds:
      - cmd: echo "helm diff"
        vars:
          HELM_ARGS: "-f=./helm/{{.PROJ}}.yaml --set image.tag={{.DOCKER_IMAGE_TAG}}"
          K8S_REGION: '{{dig .PROJ "region" .DEFAULT_K8S_REGION (mustFromJson .K8S_CONFIG)}}'
          K8S_CLUSTER: '{{dig .PROJ "cluster" .DEFAULT_K8S_CLUSTER (mustFromJson .K8S_CONFIG)}}'
    requires:
      vars: [PROJ]
```
- Task version: `v3.35.1`
- Operating system: MacOS arm64
- Experiments enabled: none

**Comment by trulede** [comment]
Tried this:

```
version: '3'
tasks:
  foo:
    vars:
      BAR: '{{.BAR | default "who"}}'  # also works without this line
    cmds:
      - echo {{.BAR}}
  bar:
    cmds:
      - task: foo
        vars:
          BAR: "{{.PROJ}}"
    requires:
      vars: [PROJ]
```

which yields:

```
$ task foo
task: [foo] echo who
who
$ task bar
task: Task "bar" cancelled because it is missing required variables: PROJ
$ task bar PROJ=fubar
task: [foo] echo fubar
fubar
```

Can you provide a more complete example that causes the problem? Is it possible that ".PROJ" was defined somewhere in "common:helm-diff" and so was actually considered not missing?

**Comment by neriaad** [comment]
Happened to me as well, here is a minimal example:
```  
  docker-build:
    cmds:
      - echo "Building {{.IMAGE_NAME}}"
    requires:
      vars: [IMAGE_NAME]
```

Now running:
`task docker-build`

Should fail, but instead prints:
`Building `

**Comment by vmaerten** [comment]
@neriaad Your example is working as expected cf : 
![image](https://github.com/user-attachments/assets/60739215-11f9-4ae5-a4fb-2cc024b4d89b)

@mvhatch Can you provide the full example (that I can copy / past) ?

**Comment by NorbertHauriel** [comment]
I have another example on v3.40.0:

```
version: 3
tasks:
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range .MY_VAR | splitList " " }}
      {{end}}
```

Expected: "requires" prevents task execution
Result: task's template is resolved first, causing a fail-late situation: the root cause for the failure is hidden (required variable not provided)


The bug is caused by the function call in the template. If the loop is a simple range, the expected behavior happens, "requires" stops the task's execution:

```
version: 3
tasks:
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range .MY_VAR }}
      {{end}}
```
