### ISSUE TITLE
prefix is overiden by label

### ISSUE THREAD

**Issue by barrykaplan** [go-task/task#1560]
When label is used the prefix has no effect.

OVERLAY is passed in from the calling task.
```
  update-cluster-secret:
    label: overlay-update-secret-{{.SECRET}}
    sources:
      - "{{.ROOT_DIR}}/base/.env"
    cmds:
      - create-sealedsecret --secret={{.SECRET}}.yaml
    prefix: '{{.OVERLAY}} update {{.SECRET}}'
```

The prefix that is emitted is the label value, not the prefix value.

I need to specify label because I need for the SECRET value distinguish the task checksum.
But I am still trying to have a different prefix value.

Maybe related to https://github.com/go-task/task/issues/933

- Task version: 3.35.1
- Operating system: linux mint 21.3
- Experiments enabled: none
