### ISSUE TITLE
On error / on exit / on (event) tasks

### ISSUE THREAD

**Issue by tulilirockz** [go-task/task#1573]
There currently (apparently) is no way to run a task or command whenever a task (or command) fails in a native Taskfile way. It would be awesome to have a event handler for tasks or commands, something like this:

```yaml
version: '3'

tasks:
  test:
    cmds:
      - wget {{.URL}} -O {{.CACHE_FILE}}
    on:
       error: 
         - cmd: rm {{.CACHE_FILE}}
           silent: true
       exit: # on CTRL+C
         - cmd: rm -i {{.CACHE_FILE}}
           silent: true
    vars:
      URL: test_url
      CACHE_FILE:
         sh: echo /tmp/$(mktemp)
```
