### ISSUE TITLE
It doesn't recognize powershell or windows pipes command.

### ISSUE THREAD

**Issue by frederikhors** [go-task/task#158]
I'm trying to use this code on Windows:

```
tasks:
  exit:
      silent: true
      cmds:
        - if [ {{OS}} = "windows" ]; then netstat -ano | select -skip 4 | and so on with more pipes...; fi
```

But it says:

`task: Failed to run task "exit": 1:49: "select foo" must be followed by "in", "do", ;, or a newline`

It doesn't recognize `netstat -ano | select -skip 4 | and so on with more pipes...` as Windows Powershell command.

How can I do?

I'm trying this because I need an `exit` to close server on `watch` tasks. Is there some other way to close command line servers (like Rails, Go and so on...)?
