### ISSUE TITLE
Taskfile doesn't expand env vars in global variable section

### ISSUE THREAD

**Issue by sdmitriev1** [go-task/task#1580]
- Task version: 3.33.1
- Operating system: MacOS 14.4.1
- Experiments enabled: none

Taskfile.yml:
```
---
version: "3"

vars:
  PATH: /tmp/{{ .NAME }}/.tmp

tasks:
  print:
    cmds:
      - echo {{ .NAME }}
      - echo {{ .PATH }}
```
the result of the task:
```
[]$ task print NAME="test"
task: [print] echo test
test
task: [print] echo /tmp//.tmp
/tmp//.tmp
```

I didn't find any reference to it in the documentation, but it looks like Taskfile does not expand the environmental variable properly, variable `NAME` is expanded in the task section, but when it's assigned to another var in global section (`PATH: /tmp/{{ .NAME }}/.tmp` it's just empty string instead
