### ISSUE TITLE
Map variables experiment

### ISSUE THREAD

**Issue by pd93** [go-task/task#1585]
> [!WARNING]
> All experimental features are subject to breaking changes and/or removal at any time. We strongly recommend that you do not use these features in a production environment. They are intended for testing and feedback only.

## Context

This experiment attempts to solve the problems originally described by #140. It is a follow-up to the "Any Variables" experiment (#1415) which was merged without support for maps.

Currently, all variable types are allowed except for maps. This is because there is some debate around the syntax that should be used to define them. The proposals for these syntaxes are described below.

## Proposal 1

> [!WARNING]
> This experiment proposal breaks the following functionality:
> 
> - Dynamically defined variables (using the `sh` keyword)

> [!NOTE]
>
> To enable this experiment, set the environment variable: `TASK_X_MAP_VARIABLES=1`. Check out [our guide to enabling experiments][enabling-experiments] for more information.

This proposal removes support for the `sh` keyword in favour of a new syntax for
dynamically defined variables, This allows you to define a map directly as you
would for any other type:

```yaml
version: 3

tasks:
  foo:
    vars:
      FOO: {a: 1, b: 2, c: 3} # <-- Directly defined map on the `FOO` key
    cmds:
      - 'echo {{.FOO.a}}'
```

### Migration

Taskfiles with dynamically defined variables via the `sh` subkey will no longer
work with this experiment enabled. In order to keep using dynamically defined
variables, you will need to migrate your Taskfile to use the new syntax.

Previously, you might have defined a dynamic variable like this:

```yaml
version: 3

tasks:
  foo:
    vars:
      CALCULATED_VAR:
        sh: 'echo hello'
    cmds:
      - 'echo {{.CALCULATED_VAR}}'
```

With this experiment enabled, you will need to remove the `sh` subkey and define
your command as a string that begins with a `$`. This will instruct Task to
interpret the string as a command instead of a literal value and the variable
will be populated with the output of the command. For example:

```yaml
version: 3

tasks:
  foo:
    vars:
      CALCULATED_VAR: '$echo hello'
    cmds:
      - 'echo {{.CALCULATED_VAR}}'
```

If your current Taskfile contains a string variable that begins with a `$`, you
will now need to escape the `$` with a backslash (`\`) to stop Task from
executing it as a command.

## Proposal 2

> [!NOTE]
>
> To enable this experiment, set the environment variable: `TASK_X_MAP_VARIABLES=2`. Check out [our guide to enabling experiments][enabling-experiments] for more information.

This proposal maintains backwards-compatibility and the `sh` subkey and adds another new `map` subkey for defining map variables:

```yaml
version: 3

tasks:
  foo:
    vars:
      FOO:
        map: {a: 1, b: 2, c: 3} # <-- Defined using the `map' subkey instead of directly on 'FOO'
      BAR: true # <-- Other types of variables are still defined directly on the key
      BAZ:
        sh: 'echo Hello Task' # <-- The `sh` subkey is still supported
    cmds:
      - 'echo {{.FOO.a}}'
```

### Parsing JSON and YAML

> [!NOTE]
> This part of the proposal has been removed as the same functionality is achievable using the `ref` keyword 
> See https://github.com/go-task/task/issues/1585#issuecomment-2467792423.

~~In addition to the new `map` keyword, this proposal also adds support for the `json` and `yaml` keywords for parsing JSON and YAML strings into real objects/arrays. This is similar to the `fromJSON` template function, but means that you only have to parse the JSON/YAML once when you declare the variable, instead of every time you want to access a value.~~

~~Before:~~

```yaml
version: 3

tasks:
  foo:
    vars:
      FOO: '{"a": 1, "b": 2, "c": 3}' # <-- JSON string
    cmds:
      - 'echo {{(fromJSON .FOO).a}}' # <-- Parse JSON string every time you want to access a value
      - 'echo {{(fromJSON .FOO).b}}'
```

~~After:~~

```yaml
version: 3

tasks:
  foo:
    vars:
      FOO:
        json: '{"a": 1, "b": 2, "c": 3}' # <-- JSON string parsed once
    cmds:
      - 'echo {{.FOO.a}}' # <-- Access values directly
      - 'echo {{.FOO.b}}'
```

## Looping over maps (Both proposals)

This experiment also adds support for looping over maps using the `for` keyword, just like arrays. In addition to the `{{.ITEM}}` variable being populated when looping over a map, we also make an additional `{{.KEY}}` variable available that holds the string value of the map key.

### Proposal 1

```yaml
version: 3

tasks:
  foo:
    vars:
      MAP: {a: 1, b: 2, c: 3}
    cmds:
      - for:
          var: MAP
        cmd: 'echo "{{.KEY}}: {{.ITEM}}"'
```

### Proposal 2

```yaml
version: 3

tasks:
  foo:
    vars:
      map:
        MAP: {a: 1, b: 2, c: 3}
    cmds:
      - for:
          var: MAP
        cmd: 'echo "{{.KEY}}: {{.ITEM}}"'
```

> [!NOTE]
> Remember that maps are unordered, so the order in which the items are looped over is random.

[enabling-experiments]: https://taskfile.dev/experiments/#enabling-experiments

**Comment by simonrouse9461** [comment]
Is there a way to do templating in map variables?
For example,
```yaml
version: 3

tasks:
  foo:
    vars:
      PREFIX: prefix_
      MAP:
        map: 
          a: '{{.PREFIX}}1'
          b: '{{.PREFIX}}2'
          c: '{{.PREFIX}}3'
    cmds:
      - echo {{index .MAP "a"}}
```
This will print `{{.PREFIX}}1` instead of ‘prefix_1’.

**Comment by pd93** [comment]
@simonrouse9461 See #1526 and #1544. Your example works in the latest release. Also worth noting that `TASK_X_MAP_VARIABLES` won't replace `TASK_X_ANY_VARIABLES` until the next release.

![image](https://github.com/go-task/task/assets/9294862/0769ad68-d7a0-48ed-ac47-1a64362bd583)

**Comment by simonrouse9461** [comment]
@pd93 Thanks! Upgrading to the latest release solved the problem.

**Comment by simonrouse9461** [comment]
Suggestion:
For the ref variables, is it possible to reuse the template engine syntax? For example,
```yaml
version: 3

tasks:
  foo:
    requires:
      vars: [VAR_NAME]
    vars:
      VAR_MAP: 
        map:
          FOO: [1, 2, 3]
          BAR: [4, 5, 6]
    cmds:
      - task: bar
        vars:
          VAR:
            ref: index .VAR_MAP .VAR_NAME
  bar:
    cmds:
      - echo {{index .VAR 0}}
```
Then,
- `task bar VAR_NAME=FOO` will print `1`
- `task bar VAR_NAME=BAR` will print `4`

**Comment by pd93** [comment]
> is it possible to reuse the template engine syntax

@simonrouse9461 I was initially going to reply saying that this is quite difficult as the `text/template` package doesn't surface the ability to resolve references without converting the result to a string. However, after some thought, I have created #1612 to solve this.

**Comment by steffans** [comment]
Suggestion:

Like proposal 1 but use YAML custom tags in order to define `sh` or `ref`, instead of prefixes `$` or `#`. See example here: 

```yml
version: 3

tasks:
  foo:
    vars:
      FOO: {a: 1, b: 2, c: 3} # <-- Directly defined map on the `FOO` key
      BAR: !sh 'echo Hello Task' # <-- Use a custom tag for a sh
      BAZ: !ref '.BAR' # <-- Use a custom tag for a ref
    cmds:
      - 'echo {{.FOO.a}}'
```

As an alternative to maintain backwards-compatibility also use YAML custom tags to define data types like `map`. This would still support tags like `sh` or `ref` see example here: 

```yml
version: 3

tasks:
  foo:
    vars:
      FOO: !map {a: 1, b: 2, c: 3} # <-- Use a custom tag for map data type
      BAR: !sh 'echo Hello Task' # <-- Use a custom tag for a sh
      BAZ: !ref '.BAR' # <-- Use a custom tag for a ref
    cmds:
      - 'echo {{.FOO.a}}'
```

See also:

- https://github.com/eemeli/yaml/blob/main/docs/06_custom_tags.md
- https://symfony.com/doc/current/components/yaml.html#handling-invalid-types

For example Symfony YAML uses custom tags to add native PHP types like `!php/object`, `!php/const`, `!php/enum`, etc.

**Comment by simonrouse9461** [comment]
@pd93 I really like @steffans's idea. Is there a chance to have a Proposal 3 for this?

**Comment by pd93** [comment]
@steffans, @simonrouse9461, I took a look at this today. It's an interesting proposal. It definitely has some clear advantages over the other 2 proposals. However after some (very limited) research, I can see some drawbacks too:

1. Lack of familiarity with the syntax (This is the first time I've used it after many years of handling YAML files). YAML has a very low bar to entry. It's one of the giant benefits of using Task over `make` and other task tools IMO. Does this increase that bar?
2. JSON schema (also used by the very popular YAML VS Code extension) doesn't support custom tags as far as I can see - this leads to confusing errors in the Taskfile. To solve this users are required to add the custom tags to their VS Code settings.
4. `!map` is extremely similar to the already defined `!!map` (which we can't use for the same reason that we can't directly define a map in proposal 1). I don't fancy repeatedly trying to explain the difference to confused users.

**Comment by JonZeolla** [comment]
I've been taking a poke at this very briefly but it made me wonder if there would be interest in something that would support using the output of a `sh:` into a map (proposal 2). This would allow me to create complex tasks or scripts that generate valid JSON for consumption by `task` (something I already do regularly for GitHub Actions matrixes).

For instance:

```yaml
---
version: 3

tasks:
  foo:
    vars:
      BAZ:
        sh: 'echo "{a: 1, b: 2, c: 3}"'
      FOO:
        map: '{{.BAZ}}'
    cmds:
      - 'echo {{.FOO.a}}'
```

Or, a more streamlined:

```yaml
---
version: 3

tasks:
  foo:
    vars:
      FOO:
        map:
          sh: 'echo "{a: 1, b: 2, c: 3}"'
    cmds:
      - 'echo {{.FOO.a}}'
```

**Comment by quirin-buechner-mdctec** [comment]
I have another Suggestion:
Introduce a new string-template function named "sh" like:
```yaml
version: 3
tasks:
  git:tag:package-version:
    cmd: git tag '{{.PACKAGE_VERSION_TAG}}'
    vars:
      vars:
        PACKAGE_VERSION_TAG: 'v{{sh "pwsh -C"}}(gc ./package.json | ConvertFrom-Json -AsHashtable).version{{end}}' 
```

Advantages:
 - Allows to specify the exact shell executable including parameters.
 - The output value can be used anywhere inside nested strings. (In the example above, the string from stdout is easily prepended with `v`)
 - No need for extra 'sh' key in a var entry. Map variables can be defined in yaml directly like in proposal 1.
 - Only uses familiar syntax. (No extra `!map` or `$...` expansion)

**Comment by pd93** [comment]
@JonZeolla What you propose in your comment is actually already possible today by using `ref` and `fromJson`:

```yaml
version: 3

tasks:
  foo:
    vars:
      FOO: '{"a": 1, "b": 2, "c": 3}'
      BAR:
        ref: 'fromJson .FOO'
    cmds:
      - 'echo {{.BAR.a}}'
```

I don't think we need a new keyword to deal with this.

@quirin-buechner-mdctec the same thing applies to your comment but it is worth noting that it is impossible to output anything other than a string from a template. If your var contains `{{}}` the output will always be a string. This is why `ref` was created (so you could preserve the type of a templated variable).

Most of the time, users will want to define maps statically, not dynamically. As such, any new proposal for defining maps would need to allow a user to define a static map object in YAML or its not worth having IMO. Converting strings to a map dynamically is already possible as shown above.
