### ISSUE TITLE
Cannot override global variables in included Taskfiles since 3.36.0

### ISSUE THREAD

**Issue by MarioSchwalbe** [go-task/task#1588]
- Task version: 3.36.0
- Operating system: Linux (probably others)
- Experiments enabled: none

We need 2 task files (see https://taskfile.dev/usage/#vars-of-included-taskfiles):

`Taskfile.yml`:
```yml
version: '3'

includes:
  subA:
    taskfile: DockerBuild.yml

  subB:
    taskfile: DockerBuild.yml
    vars:
      DOCKER_IMAGE: imageOfB

tasks:
  default:
    cmds:
      - task: subA:show   # Uses the default value.
      - task: subB:show   # Used to be `imageOfB`. Now is `default_image`.
```

and `DockerBuild.yml`:
```yml
version: '3'

vars:
  DOCKER_IMAGE: default_image

tasks:
  show:
    cmds:
      - echo "DOCKER_IMAGE = {{.DOCKER_IMAGE}}"
```

Since version 3.36.0 I get:
```bash
$ task
task: [subA:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
task: [subB:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
```

In previous versions it was possible to override variables when including taskfiles changing the second case to:
```bash
$ task
task: [subA:show] echo "DOCKER_IMAGE = default_image"
DOCKER_IMAGE = default_image
task: [subB:show] echo "DOCKER_IMAGE = imageOfB"
DOCKER_IMAGE = imageOfB
```

Is this an intended change? And if yes, how would we implement something like that instead?

**Comment by glenvan** [comment]
Same issue here.

Passing in a variable with the intention of overriding a variable that is defined in the top-level `vars:` object of the included file no longer replaces the variable's value.

The workaround is to use the [`default` function](https://go-task.github.io/slim-sprig/defaults.html), as in the test data for (the possible cause) #1533:

```yaml
vars:
  DOCKER_IMAGE: {{ .DOCKER_IMAGE | default "default_image" }}
```

**Comment by jclasley** [comment]
FWIW, using an anchor in the vars works:
```yaml
# taskfile A

version: 3

vars:
  VAR: "bar"

tasks:
  echo:
    cmds:
      - echo {{ .VAR }}
---
# taskfile B
version: 3

def: &var
  VAR: "foo"

includes: 
  A: 
    taskfile: Taskfile.A.yaml

tasks:
  echo:
    cmds:
      - task: A:echo
        vars:
          *var
```
which outputs `"foo"`
but that same command with a merge override is then overridden
```yaml
# ...
 echo:
    cmds:
      - task: A:echo
        vars:
           <<: *var
```
echos `"bar"`

-----------
If you're like me and have a bunch of variables that you don't want to hardcode over and over, the anchors proved to be a sufficient workaround.

**Comment by jclasley** [comment]
This bug also occurs if the included Taskfile is given a variable at the time of inclusion. It randomly picks a variable. Example:

parent taskfile
```yaml
version: 3

includes:
  a:
    taskfile: ./a
    vars:
       PREFIX: a
  b:
    taskfile: ./b
    vars:
       PREFIX: b
  c:
    taskfile: ./c
    vars:
       PREFIX: c
```

internal taskfile:
```yaml
version: 3

tasks:
   echo: echo {{ .PREFIX }}
```

then from `./a`
```yaml
version: 3

includes:
  internal:
    taskfile: ./internal

tasks:
   echo:
     cmds:
        - task: internal:echo
          vars:
            PREFIX: {{ .PREFIX }}
```

`task -d ./a echo` may print `a` or `b` or `c`. Across my department we have had different results, though I personally have repeatedly gotten the same (incorrect) result on my machine.
