### ISSUE TITLE
can't disable color in taskfile.yml

### ISSUE THREAD

**Issue by taylormonacelli** [go-task/task#1589]
I'd like to instruct task to not use colored output within the Taskfile if possible.

This doesn't work:
```
cat >Taskfile.yml <<EOF
version: "3"
vars:
  NO_COLOR: 1
env:
  NO_COLOR: 1
tasks:
  default:
    env:
      NO_COLOR: 1
    cmds:
    - echo foo
EOF
task 
```

These work fine:
```bash
NO_COLOR=1 task
task --color=false
```

Not sure if i'm getting syntax wrong or its not supported.
