### ISSUE TITLE
When calling a subtask, the passed variable cannot directly overwrite the value in the subtask, which is inconsistent with the document description.

### ISSUE THREAD

**Issue by QianChenglong** [go-task/task#1597]
<img width="2545" alt="image" src="https://github.com/go-task/task/assets/1881126/61d35282-22c0-4fcf-ab84-7f7681451fdf">
<img width="1728" alt="image" src="https://github.com/go-task/task/assets/1881126/dfeeb84b-68cd-4f2f-b614-c9d1bce70f1f">

If use the template default method, cannot use shell commands to obtain the default value.

**Comment by MarioSchwalbe** [comment]
Hi, this is because point 1 (`variables declared in the task definition`) has precedence. You can use the `default` function in something like this:

```yml
build:
  vars:
    PARAM: '{{ .PARAM | default "foo" }}'
    GOARCH_DEFAULT: { sh: go env GOARCH }
    GOARCH: '{{ .GOARCH | default .GOARCH_DEFAULT }}'
  cmds:
    - echo {{.GOARCH}} {{.PARAM}}
```

In case of `GOARCH`, you would need a helper variable, because this cannot be combined with `sh:`.
