### ISSUE TITLE
for loop does not take effect in deps

### ISSUE THREAD

**Issue by QianChenglong** [go-task/task#1598]
<img width="2545" alt="image" src="https://github.com/go-task/task/assets/1881126/c2e62f39-2b54-4a7e-b2ac-aea1f55bfef1">

**Comment by pd93** [comment]
@QianChenglong When opening issues, could you please provide the following information:

- Task version
- Operating system
- Experiments enabled

Also, it would help us to track down the cause of your problem if you posted samples of your code rather than screenshots. Otherwise, we have to manually copy your Taskfiles from the image.

---

With the Taskfile below, looping over dependencies works fine in v3.36.0. Please note that this functionality was only added in v3.36.0, so if you are running a version prior to that, then this will not work.

```yaml
version: 3

tasks:
  build:
    cmds:
      - echo {{.GOOS}} {{.GOARCH}}

  default:
    deps:
      - for: ["amd64", "arm64"]
        task: build
        vars:
          GOOS: linux
          GOARCH: "{{.ITEM}}"
    cmds:
      - for: ["amd64", "arm64"]
        task: build
        vars:
          GOOS: linux
          GOARCH: "{{.ITEM}}"
```

![image](https://github.com/go-task/task/assets/9294862/e351f9d5-5b01-4c01-8961-652db760ff7f)
