### ISSUE TITLE
Exclude doesn't support globbing

### ISSUE THREAD

**Issue by polds** [go-task/task#1602]
- Task version: v3.36.0 (h1:XVJ5hQ5hdzTAulHpAGzbUMUuYr9MUOEQFOFazI3hUsY=)
- Operating system: macOS
- Experiments enabled: None

It looks like exclude does not support globbing, the docs don't explicitly mention that it does (or doesn't), so maybe this is by-design? But I would expect to be able to declare globbed exclusions (generated files, whole directories, etc)

You can see a small example here by utilizing a loop over sources:

```bash
# directory structure
for d in "1" "2" "3"; do mkdir $d; done
# files
for f in "a.txt" "a.go" "1/b_gen.go" "2/c.go" "3/d.go"; do touch $f; done
```

`Taskfile.yaml`
```yaml
version: '3'

tasks:
  default:
    sources:
      - "**/*.go"
      - "exclude: **/*_gen.go" # Try to exclude all files ending with _gen.go
      - "exclude: 3/**/*.go"   # Try to exclude an entire directory
    cmds:
      - for: sources
        cmd: echo {{.ITEM}}
```

Result
```bash
$ task --force
task: [default] echo 1/b_gen.go
1/b_gen.go
task: [default] echo 2/c.go
2/c.go
task: [default] echo 3/d.go
3/d.go
task: [default] echo a.go
a.go
```

What I would expect based on the excludes:
 - `task: [default] echo 1/b_gen.go` is not executed due to `exclude: **/*_gen.go`
 - `task: [default] echo 3/d.go` is not executed due to `exclude: 3/**/*.go`

If I add `exclude: 3/d.go` it _does_ correctly exclude it from the output.

**Comment by pd93** [comment]
Hey @polds. Thanks for the excellent repro steps. Took me a second to figure out what was wrong, but it's as simple as unquoting `"exclude: ..."`. `exclude` should be an actual YAML key rather than a part of the glob string.

Working example below:

```yaml
version: '3'

tasks:
  default:
    sources:
      - "**/*.go"
      - exclude: "**/*_gen.go" # Try to exclude all files ending with _gen.go
      - exclude: "3/**/*.go"   # Try to exclude an entire directory
    cmds:
      - for: sources
        cmd: echo {{.ITEM}}
```
