### ISSUE TITLE
Vars can be included in other vars, but env vars not in other env vars

### ISSUE THREAD

**Issue by lostkamp** [go-task/task#1615]
- Task version: Task version: v3.36.0 (h1:XVJ5hQ5hdzTAulHpAGzbUMUuYr9MUOEQFOFazI3hUsY=)
- Operating system: Linux/Kubuntu
- Experiments enabled: no

#### Vars can be included in other vars
```yaml
version: '3'

vars:
  SECRET_NAME: MySecret
  AZURE_APPLICATION_CLIENT_ID:
    sh: aws secretsmanager get-secret-value --secret-id {{.SECRET_NAME}} --query SecretString --output text | jq -r .client_id

tasks:
  test:
    cmds:
      - echo {{.AZURE_APPLICATION_CLIENT_ID}}
```

```
$ task -v test
task: [/home/lutz/Schreibtisch/test] Not found - Using alternative (Taskfile.yml)
task: dynamic variable: "aws secretsmanager get-secret-value --secret-id MySecret --query SecretString --output text | jq -r .client_id" result: "e01eb3c2-fb2f-47f7-a574-8a8db607796e"
task: "test" started
task: [test] echo e01eb3c2-fb2f-47f7-a574-8a8db607796e
e01eb3c2-fb2f-47f7-a574-8a8db607796e
task: "test" finished
```

#### Env vars can not be included in other env vars
```yaml
version: '3'

env:
  SECRET_NAME: MySecret
  AZURE_APPLICATION_CLIENT_ID:
    sh: aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text | jq -r .client_id

tasks:
  test:
    cmds:
      - echo $AZURE_APPLICATION_CLIENT_ID
```

```
$ task -v test
task: [/home/lutz/Schreibtisch/test] Not found - Using alternative (Taskfile.yml)

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --secret-id: expected one argument

task: dynamic variable: "aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text | jq -r .client_id" result: ""
task: "test" started
task: [test] echo $AZURE_APPLICATION_CLIENT_ID

task: "test" finished
```

#### Vars can kind of be included in env vars
```yaml
version: '3'

vars:
  SECRET_NAME: MySecret

env:
  AZURE_APPLICATION_CLIENT_ID:
    sh: aws secretsmanager get-secret-value --secret-id {{.SECRET_NAME}} --query SecretString --output text | jq -r .client_id

tasks:
  test:
    cmds:
      - echo $AZURE_APPLICATION_CLIENT_ID
```

This does not work on the first try, but is executed twice and works on the second try:

```
$ task -v test
task: [/home/lutz/Schreibtisch/test] Not found - Using alternative (Taskfile.yml)

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: argument --secret-id: expected one argument

task: dynamic variable: "aws secretsmanager get-secret-value --secret-id  --query SecretString --output text | jq -r .client_id" result: ""
task: dynamic variable: "aws secretsmanager get-secret-value --secret-id MySecret --query SecretString --output text | jq -r .client_id" result: "e01eb3c2-fb2f-47f7-a574-8a8db607796e"
task: "test" started
task: [test] echo $AZURE_APPLICATION_CLIENT_ID
e01eb3c2-fb2f-47f7-a574-8a8db607796e
task: "test" finished

```

I guess that this behavior is intended? If so, it would be great to document this on the "Usage" web page (and maybe discourage people from doing the third thing).

I could provie a PR if you'd like.
