### ISSUE TITLE
Running 'background' task hangs

### ISSUE THREAD

**Issue by orthomind** [go-task/task#162]
Hi,

I'm trying to create a task to start up a cockroachdb instance.  One of the commands I use is the actual running of the instance:

```
cockroach start --background --host=localhost --http-host=localhost --certs-dir="$(echo ~)/.cmswww/data/testnet3/cockroachdb"
```

The --background flag is described as follows:

```
      --background                                  
        Start the server in the background. This is similar to appending "&"
        to the command line, but when the server is started with --background,
        control is not returned to the shell until the server is ready to
        accept requests.
```

Unfortunately, when I use this flag, Task does not seem to progress beyond this step.  It's as though the cockroachdb instance never returns to shell.  However, when I run this command in the shell manually, it works as expected.

Do you know why this may not work when I use it in task, while it works as expected outside of that?

Thanks!

**Comment by andreynering** [comment]
Hi @orthomind,

Maybe `--background` messes with more obscure OS stuff, and something in between isn't cooperating.

This can either be a bug on CockroachDB, on mvdan/sh or Task itself.

Can you please try running this command on Make and [Gosh](https://github.com/mvdan/sh)? You'd be helping me debug this issue.

Also, what's your Task version and OS?

**Comment by andreynering** [comment]
Ping @orthomind

**Comment by SwitchedToGitlab** [comment]
Hey @orthomind I'm attempting to assist @andreynering in clearing out some bugs. Is this still and issue with the current version? If so, can you include the Taskfile.yml that you're using, as well as the operating system that you're on so I can attempt to replicate it?

If not, can we close this issue?

**Comment by andreynering** [comment]
Closing for lack of feedback.

If you still have updates, feel free to comment and we may reopen the issue.

**Comment by cr1cr1** [comment]
I'm having this issue.

Trying to start a server process in background.

1. `cat bin/nats-server.sh`
```bash
#!/bin/bash
nats-server --log bin/nats-server.log& echo "PID $!"
```

2. `bin/nats-server.sh`
PID 3439

```
ps -fp 3439
UID     PID    PPID  TTY        STIME COMMAND
cri    3439       1 cons1    11:35:33 /c/tools/scoop/shims/nats-server
```

3. `gosh -c bin/nats-server.sh` or `gosh -c bash -c bin/nats-server.sh`
fork/exec x:\bin\nats-server.sh: %1 is not a valid Win32 application.

4. `gosh -c 'bash -c bin/nats-server.sh'`
PID 3468

```
ps -fp 3491
UID     PID    PPID  TTY        STIME COMMAND
cri    3491       1 cons1    11:38:56 /c/tools/scoop/shims/nats-server
```

5. Taskfile:
```yaml
  run_nats_server:
    deps:
      - install_nats
      - install_nats_server
    status:
      - nats server check connection
    cmds:
      - echo "Starting nats-server"
      - |
        PATH="bin{{.PD}}$PATH"
        echo '#!/bin/bash
        nats-server --log bin/nats-server.log& echo "PID $!"' > bin/nats-server.sh
        chmod +x bin/nats-server.sh
        bash -c 'bin/nats-server.sh'
```

```
task run_nats_server
[run_nats_server] Starting nats-server
[run_nats_server] PID 3525
```

hangs.
