### ISSUE TITLE
Suppress signal received message

### ISSUE THREAD

**Issue by sedyh** [go-task/task#1621]
Hello,  I would like to be able to turn off stdout for a task using an option in the taskfile, I have not found such functionality or existing proposals.

It would be nice if silent not only did not output the command, but also did not write about received signals until it is stderr.

```
version: "3"

silent: true

tasks:
  app:
    cmds:
      - cmd: go build -ldflags="-X main.Version={{.VERSION}}" -o app ./cmd/app && ./app
        ignore_error: true
      - defer: rm -rf app
```
```
started
log
log
...
log
task: Signal received: "interrupt"
stopped
```
