### ISSUE TITLE
Add support for faint colors

### ISSUE THREAD

**Issue by sedyh** [go-task/task#1622]
Hello, I noticed that cmd output from task does not support faint colors, as far as I know they work on most major platforms.
It would be great if they worked the same as without task.

![image](https://github.com/go-task/task/assets/19890545/05a48a8f-e142-42ee-9c37-9fe60b78b890)

![image](https://github.com/go-task/task/assets/19890545/fe984fd1-5a4a-48c0-9cde-ff908089ac13)

**Comment by pd93** [comment]
@sedyh Do you have a reproducible example? Perhaps my attempt below is a bit naive, but it works so I'm unable to work out what the issue is:

```yaml
version: 3

tasks:
  default:
    cmds:
      - echo -e "\e[2m16:48:50 \e[22;32mINF \e[0mheader ...\e[0m"
```

![image](https://github.com/go-task/task/assets/9294862/1f1b9bd0-160a-4054-850d-71ee544eaced)
