### ISSUE TITLE
Multiline commands for dynamic vars

### ISSUE THREAD

**Issue by sedyh** [go-task/task#1625]
Hello, I would like to separate the flags for assembling my program into different lines.
I can’t figure out how to do this correctly with the tools that taskfile provides.

```yaml
version: "3"

tasks:
  app:
    cmds:
      - cmd: go build {{.FLAGS}} -o app ./cmd/app && ./app
vars:
  FLAGS:
    sh:
      - |
        list=(
          -X main.Debug=true
          -X main.Dirty=false
          ...
          -X main.Version={{.VERSION}}
        )
        echo "-ldflags="${list[@]}""
  VERSION:
    sh: git rev-parse HEAD

```

**Comment by pd93** [comment]
How I would do this today:

```yaml
version: "3"

vars:
  VERSION:
    sh: git rev-parse HEAD
  FLAGS: |
    -X main.Debug=true
    -X main.Dirty=false
    -X main.Version={{.VERSION}}
  LDFLAGS: '{{ splitList "\n" .FLAGS | compact | join " " }}'

tasks:
  app:
    cmds:
      - cmd: go build -ldflags="{{.LDFLAGS}}" -o app ./cmd/app && ./app
```

How I would do this after the next Task release (v3.37.0) which will add the ability to define list variables:

```yaml
version: "3"

vars:
  VERSION:
    sh: git rev-parse HEAD
  FLAGS:
    - -X main.Debug=true
    - -X main.Dirty=false
    - -X main.Version={{.VERSION}}
  LDFLAGS: '{{ .FLAGS | join " " }}'

tasks:
  app:
    cmds:
      - cmd: go build -ldflags="{{.LDFLAGS}}" -o app ./cmd/app && ./app
```

Both of these result in:

```
go build -ldflags="-X main.Debug=true -X main.Dirty=false -X main.Version=..." -o app ./cmd/app && ./app
```
