### ISSUE TITLE
Declaration order matters when nesting dynamic vars

### ISSUE THREAD

**Issue by sedyh** [go-task/task#1626]
As far as I know you can nest dynamic variables in each other, but this behavior is depends on declaration order.
Looks like a bit confusing. I didn't find this info in docs.

```yaml
vars:
  A:
    sh: echo "a {{.B}}"
  B:
    sh: echo "b {{.C}}"
  C:
    sh: echo "c"
```
```shell
cmd
```
```yaml
vars:
  C:
    sh: echo "c"
  B:
    sh: echo "b {{.C}}"
  A:
    sh: echo "a {{.B}}"
```
```shell
cmd a b c
```
