### ISSUE TITLE
[Bug] Global Taskfile with local dotenv file not load variables using `USER_WORKING_DIR` path reference

### ISSUE THREAD

**Issue by rrmistry** [go-task/task#1629]
With this Taskfile:

```YAML
# Global Taskfile: ~/Taskfile.yaml
version: "3"
dotenv:
  # - "{{.USER_WORKING_DIR}}/.env" # <<<< Does not work (but it should)
  - "~/repos/my-project/.env"      # <<<< Works
tasks:
  build:
    dir: '{{.USER_WORKING_DIR}}'
    dotenv: ["{{.USER_WORKING_DIR}}/.env"] # <<<< Does not load Taskfile Variable either but it does load env variable
    cmds:
      # Should print: "value = testABC123"
      - echo value = {{.DOT_ENV_VAR}}
```

And `.env` file:

```.env
# Local .env file: ~/repos/my-project/.env
DOT_ENV_VAR=testABC123
```

Then running this:

```shell
mkdir -p ~/repos/my-project
cd ~/repos/my-project
echo "DOT_ENV_VAR=testABC123" > .env
task -g build
```

Should print:

```shell
task: [build] echo value = testABC123
value = testABC123
```

But prints:

```shell
task: [build] echo value = 
value = 
```

_____

This is not a blocker as we can still use script variables (instead of Taskfile variables):

```YAML
# Global Taskfile: ~/Taskfile.yaml
version: "3"
tasks:
  build:
    dir: '{{.USER_WORKING_DIR}}'
    dotenv: ["{{.USER_WORKING_DIR}}/.env"] # <<<< Workaround loads env variables but not as Taskfile variables
    cmds:
      # Will print: "value = testABC123"
      - echo value = $DOT_ENV_VAR # Workaround
```

But it is not ideal as it prints:

```shell
task: [build] echo value = $DOT_ENV_VAR 
value = testABC123
```

We would like to see task output with variable values replaced in the script like below:

```shell
task: [build] echo value = testABC123
value = testABC123
```

_____

Task Version Output:

```shell
 task --version
Task version: v3.36.0 (h1:XVJ5hQ5hdzTAulHpAGzbUMUuYr9MUOEQFOFazI3hUsY=)
```
