### ISSUE TITLE
Define ENV vars not static

### ISSUE THREAD

**Issue by wburningham** [go-task/task#1630]
Given the current taskfile:

```
version: 3

tasks:
  default:
    env:
      EFOO: "little env foo"
      EBAR: "little env bar"
    vars:
      VFOO: "little var foo"
      VBAR: "little var bar"
    cmds:
      - cmd: echo $EFOO
      - cmd: echo $EBAR
      - cmd: echo {{.VFOO}}
      - cmd: echo {{.VBAR}}
 ```

With the given invocation:

```
EBAR="BIG ENV BAR" VBAR="BIG VAR BAR" task
```

Outputs:

```
task: [default] echo $EFOO
little env foo
task: [default] echo $EBAR
BIG ENV BAR
task: [default] echo little var foo
little var foo
task: [default] echo little var bar
little var bar
```

Since the ENV defined in the taskfile are static AND they are not using the `{{ default ...}}` pattern I would expect that all output says "little...". Am I mistaken? Also shouldn't `vars` and `env` behave the same?

Thanks for clarifying this case.

- Task version: v3.36.0 (h1:XVJ5hQ5hdzTAulHpAGzbUMUuYr9MUOEQFOFazI3hUsY=)
- Operating system: macOS 14.4.1 
- Experiments enabled: remote taskfiles (but it should not affect this case)

**Comment by vmaerten** [comment]
Hello !
I think it's related to : 
- https://github.com/go-task/task/issues/1038
Env variable from the shell takes precedence over env defined in the Taskfile.

**Comment by wburningham** [comment]
Thanks for the link. It looks like the issue I just created is a duplicate. I'm going to close this issue.

**Comment by vmaerten** [comment]
Even if it won't resolve your issue but you can use templating system and default pipe, and you can also define dynamic env variable like this : 
```yml
version: 3

tasks:
  default:
    env:
        EBAR: "big env bar"
        EBAZ:
          sh: echo "big env baz"
    vars:
      VFOO: "little var foo"
      VBAR: "little var bar"
    cmds:
      - cmd: echo {{.EFOO | default "little env foo"}}
      - cmd: echo $EBAR
      - cmd: echo $EBAZ
      - cmd: echo {{.VFOO}}
      - cmd: echo {{.VBAR}}
```
