### ISSUE TITLE
unable to use ( or ) when calling powershell

### ISSUE THREAD

**Issue by hahn-kev** [go-task/task#1635]
Simple task defined like this:
```yaml
cmd: powershell if (test-path {{.HG_REPO_DIR}}/sena-4) { rm -r {{.HG_REPO_DIR}}/sena-4 }
```

however when I try to run it I get this error: 
> task: Failed to run task "setup-win": 1:15: a command can only contain words and redirects; encountered (

So I tried various ways of escaping the `(`, the last one being this:
```yaml
vars: 
  TEST: "(test-path {{.HG_REPO_DIR}}/sena-4)"
cmds:
  - cmd: powershell if {{.TEST}} { rm -r {{.HG_REPO_DIR}}/sena-4 }
```

using task --dry shows this:
> task: [setup-win] powershell if (test-path ./hgweb/repos/sena-4) { rm -r ./hgweb/repos/sena-4 }

which is exactly what I want, but then when I try to run it I get the same error again
> task: [setup-win] powershell if (test-path ./hgweb/repos/sena-4) { rm -r ./hgweb/repos/sena-4 }
> task: Failed to run task "setup-win": 1:15: a command can only contain words and redirects; encountered (

The only related [issue](https://github.com/go-task/task/issues/206) I found was not helpful. It said this was an escaping issue, and ended with the user changing the syntax of their command, however I can't change the syntax powershell expects, it must be `if ( test )` for an if block.

- Task version: 3.36
- Operating system: windows
- Experiments enabled: none

**Comment by trulede** [comment]
@hahn-kev a command like this works:

```
version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds: 
      - cmd: powershell 'if (test-path Music) { Write-Host "foo" }'
```

Thanks.
