### ISSUE TITLE
align target hints by column

### ISSUE THREAD

**Issue by dmitry-mightydevops** [go-task/task#1637]
- Task version:
```sh
➜ task --version
Task version: v3.36.0 (h1:XVJ5hQ5hdzTAulHpAGzbUMUuYr9MUOEQFOFazI3hUsY=)
```
- Operating system:

```sh
➜ uname -a          
Linux dmitry-desktop 6.8.5-101.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 11 19:59:26 UTC 2024 x86_64 GNU/Linux
```
- Experiments enabled:
N/A

### Problem

![image](https://github.com/go-task/task/assets/70822710/cae38f6b-4bf3-4daa-9124-6a6e176b0fff)

would like to align the hints on the right side by the same column and remove unnecessary empty space lines between targets listed in the output

**Comment by dmitry-mightydevops** [comment]
here is the taskfile

```yaml
version: '3'

tasks:
  check-file-existence:
    desc: "Check if the specified file exists"
    vars:
      file: '{{.file}}'
    cmds:
      - test -f "{{.file}}" || (echo "The file {{.file}} does not exist" && exit 1)
    silent: true

  encrypt-string:
    desc: |
      Encrypt secret string with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-string -- secret-text-here`
    vars:
      secret: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - |
        echo :OK"
    silent: true

  decrypt-string:
    desc: |
      Decrypt string with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-string -- encrypted-text-here`
    vars:
      secret: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - |
        echo :OK"
    silent: true

  encrypt-file:
    desc: |
      Encrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-file -- apps/spiderkeeper/envs/prod.secrets.yaml`
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
      - |
        echo :OK"
    silent: true

  decrypt-file:
    desc: |
      Decrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:decrypt-file -- apps/spiderkeeper/envs/prod.secrets.yaml.encrypted`
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
      - |
        echo :OK"
    silent: true

  edit-encrypted-file:
    desc: |
      Encrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:edit-encrypted-file VAR=sentry_slack_webhook_url VAL=https://example.com -- ../secret.yaml.encrypted`
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV, VAR, VAL]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
        output: decrypted_output
      - |
        echo :OK"
    silent: true

```

so if desc is multiline, i.e. this then the formatting is off

```yaml
target:
  desc: |
    Then we have issues
```

If I change it to a single line

```
version: '3'

tasks:
  check-file-existence:
    desc: "Check if the specified file exists"
    vars:
      file: '{{.file}}'
    cmds:
      - test -f "{{.file}}" || (echo "The file {{.file}} does not exist" && exit 1)
    silent: true

  encrypt-string:
    desc: "Encrypt secret string with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-string -- secret-text-here`"
    vars:
      secret: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - |
        echo :OK"
    silent: true

  decrypt-string:
    desc: "Decrypt string with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-string -- encrypted-text-here`"
    vars:
      secret: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - |
        echo :OK"
    silent: true

  encrypt-file:
    desc: "Encrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:encrypt-file -- apps/spiderkeeper/envs/prod.secrets.yaml`"
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
      - |
        echo :OK"
    silent: true

  decrypt-file:
    desc: "Decrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:decrypt-file -- apps/spiderkeeper/envs/prod.secrets.yaml.encrypted`"
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
      - |
        echo :OK"
    silent: true

  edit-encrypted-file:
    desc: "Encrypt secret with AWS KMS keys to be used in terraform, example: `task secrets:edit-encrypted-file VAR=sentry_slack_webhook_url VAL=https://example.com -- ../secret.yaml.encrypted`"
    vars:
      file: '{{ index ($x:=splitArgs .CLI_ARGS) 0 }}'
    requires:
      vars: [ENV, VAR, VAL]
    cmds:
      - task: check-file-existence
        vars: {file: "{{.file}}"}
        output: decrypted_output
      - |
        echo :OK"
    silent: true
```

then all is good:

![image](https://github.com/go-task/task/assets/70822710/e49de01e-03db-4c53-9d2a-8d748ca87c57)
