### ISSUE TITLE
Regression - env var yaml integer no longer exported to enviroment

### ISSUE THREAD

**Issue by ameergituser** [go-task/task#1640]
**input**
```
version: '3'

tasks:
  default:
    env:
      CC: x86_64-w64-mingw32-gcc
      CGO_ENABLED: 1
      GOOS: windows
      GOARCH: amd64
    cmds:
      - echo CC=$CC CGO_ENABLED=$CGO_ENABLED GOOS=$GOOS GOARCH=$GOARCH

```
**output: Task version: v3.36.0**
```
CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64
```

**output: Task version: v3.37.0**
```
CC=x86_64-w64-mingw32-gcc CGO_ENABLED= GOOS=windows GOARCH=amd64
```

**Comment:**
Note `CGO_ENABLED` env var was not set for v3.37.0
Converting the integer var into a string works around this issue.

- Operating system: Linux dev 5.15.0-106-generic 116-Ubuntu 
- Experiments enabled: No
