### ISSUE TITLE
 When includes are used, the value of the variable is not constant and changes randomly.

### ISSUE THREAD

**Issue by ZCube** [go-task/task#1646]
- Task version: 3.37.1
- Operating system: Linux
- Experiments enabled:

When includes are used, the value of the variable is not constant and changes randomly.

* env/a/Taskfile.yaml
```yaml
version: "3"

vars:
  Target: "a"

includes:
  c:
    taskfile: ../c/Taskfile.yaml
    vars:
      Target: "{{.Target}}"
```
* env/b/Taskfile.yaml
```yaml
version: "3"

vars:
  Target: "b"

includes:
  c:
    taskfile: ../c/Taskfile.yaml
    vars:
      Target: "{{.Target}}"
```
* env/c/Taskfile.yaml
```yaml
version: "3"

tasks:
  c:
    desc: "Task c"
    cmds:
      - echo "Task {{.Target}}"
```
* Taskfile.yaml
```yaml
version: "3"

includes:
  a:
    taskfile: ./env/a/Taskfile.yaml
  b:
    taskfile: ./env/b/Taskfile.yaml
```
* test.sh
```bash
#!/bin/bash

for i in {1..1000}; do
    task b:c:c
done
```

Test
```bash
# ./test.sh | grep "Task a"

...

task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task b"
task: [b:c:c] echo "Task a"
Task a
task: [b:c:c] echo "Task a"
Task a
...
```
[test.tar.gz](https://github.com/go-task/task/files/15272985/test.tar.gz)
