### ISSUE TITLE
Long number string variables are now converted to scientific notation, breaking existing tasks that expect the number as is

### ISSUE THREAD

**Issue by manzamor-cs** [go-task/task#1658]
Existing commands that utilize a long number variable as a string are now broken by conversion to scientific notation.

Given this task:
```yaml
  long-number:
    desc: Print a long number variable
    vars:
      LONG_NUMBER: 123456789012345678901234567890
    cmds:
      - echo "{{.LONG_NUMBER}}"
```
Using task version 3.36.0:
```shell
❯ task long-number      
task: [long-number] echo "123456789012345678901234567890"
123456789012345678901234567890
```
Using task version 3.37.2:
```shell
❯ task long-number 
task: [long-number] echo "1.2345678901234568e+29"
1.2345678901234568e+29
```
The issue can fixed by just quoting the variable that is meant to be interpreted as a string, but this does break previously existing tasks that utilize unquoted long numbers.

- Task version: 3.37.2
- Operating system: Mac OS/Linux
- Experiments enabled: Nope

**Comment by pd93** [comment]
This is behaving as intended. Since Task now supports any scalar variable type, if you give it a number, it will be interpreted as one (rather than the previous behaviour which automatically converted it to a string). Since the number you used far exceeds the maximum signed and unsigned 64 bit integer size, it is converted to a float approximation instead and when printed it will be displayed using scientific notation.

If you want your variable to be a string then you should wrap it with quotes and it will be interpreted as expected:

```yaml
  long-number:
    desc: Print a long number variable
    vars:
      LONG_NUMBER: "123456789012345678901234567890"
    cmds:
      - echo "{{.LONG_NUMBER}}"
```
