### ISSUE TITLE
Allow using tasks in `preconditions` (possibly `status`)

### ISSUE THREAD

**Issue by DerpgonCz** [go-task/task#1667]
This feature requests aims to allow using `task: ...` property in `preconditions` array of a task.

Currently, `preconditions` is an array of either string (interpreted as shell commands) or an array of objects with `sh` (also interpreted as a shell command) and `msg` (interpreted as a string) being printed when given shell command exits with a return code != 0.

Example:
```yaml
version: '3'

tasks:
  positive:
    cmd: exit 0

  negative:
    cmd: exit 2

  test-positive:
    preconditions:
      - task: positive
    cmd: echo "I am OK"

  test-negative:
    preconditions:
      - task: negative
        msg: Precondition negative failed
    cmd: echo "I am not ok"

  test-invalid:
    preconditions:
      - task: positive
        sh: exit 1
```

Acceptance criteria:
- ✅ Running `task positive` should not do anything
- ✅ Running `task negative` should fail with exit code 2
- ❌ Running `task test-positive` should check the precondition
- ✅ Running `task test-positive` should print `I am OK`
- ❌ Running `task test-negative` should check the precondition
- ❌ Running `task test-negative` should print `Precondition negative failed` exit with an error code 1
  - not sure if it should inherit the error code or not
- ❌ Running `task test-negative` should not print `I am not OK`
- ❌ Running `task test-invalid` should not be valid
  - or throw a validation error on running any task, as the file is technically not valid

Backwards compatibility is assured, as this is just an expansion to the existing object used as an array item in `preconditions`. Using both `sh` and `task` should not be valid declaration of a precondition.

**Comment by trulede** [comment]
Perhaps look at #1200 which seems like it would solve your problem (with the `--force` flag).

https://taskfile.dev/experiments/gentle-force/

**Comment by DerpgonCz** [comment]
> Perhaps look at #1200 which seems like it would solve your problem (with the `--force` flag).
> 
> https://taskfile.dev/experiments/gentle-force/

This is different, this is an expansion to existing logic where you can call tasks in preconditions and status, and has nothing to do with the `--force` flag.

I have a few preconditions and status-es that I would like to run, but have to either use YAML anchors (if I do not want to duplicate logic) or run other tasks with `task xxx` (which does not work in included Taskfiles). The logic is basically the same as with `deps`, where the strings are tasks by default.

This keeps the default logic of running shell command when only a string is provided, but can be expanded to run tasks (similarly to `cmds`/`cmds` attribute in tasks) where if you supply an object with `{ task: xxx }` it will run that task, capture the response code, and behave the same way as if it was a regular shell command.

**Comment by ChrisPbb** [comment]
I found a workaround for this but I can't say I'm proud of it 😅.  You can call the task CLI from `status` and `preconditions` 👼 

```yaml
version: "3"

tasks:
  random-fail:
    cmds:
      - exit {{randInt 0 2}}

  default:
    status:
      - task random-fail
    cmds:
      - echo Not skipped.
```
