### ISSUE TITLE
Wildcard-include tasks from a dir

### ISSUE THREAD

**Issue by pentago** [go-task/task#1678]
I was thinking about a possibility of having a directory full of individual task files and just including the entire directory of tasks without having to specify all of them one by one.

This way, one would be able to make compositions from predefined tasks suitable for a need.
For example, in large teams working on various projects, one person might have different needs than the other (e.g. OS or tooling-wise).

My proposal is mostly aimed at working in an environment with multiple people to be able to share tasks.

For example, consider this definition:

```
version: '3'

includes_dir:
  - dir: tasks/*
  - dir: os/mac/*

tasks:
  setup-mac-infra:
    cmds:
      - task: setup-cluster
      - task: setup-metrics-server
      - task: setup-cilium
      - task: setup-coredns
      - task: setup-cert-manager
      - task: setup-gateway-api
      - task: setup-workload
      - task: setup-netpols
      - task: run-hubble

  mac-cleanup:
    cmds:
      - task: cleanup
```

Or something along those lines - just being able to include all (we have hundreds) of tasks and be able to share across the teams.

Thoughts?
