### ISSUE TITLE
Add an option to allow multiple wildcard matches and only run the first match 

### ISSUE THREAD

**Issue by simonrouse9461** [go-task/task#1688]
Consider this case:
```yml
tasks:
  '*:*':
    vars:
      JOB_TYPE: {ref: index .MATCH 0}
      OPTION: {ref: index .MATCH 1}
    cmd: <some logic to generate the command with JOB_TYPE and OPTION>

  '*':
    vars:
      JOB_TYPE: {ref: index .MATCH 0}
    cmd:
      task: '{{.JOB_TYPE}}:default_option'
```
If I run `task some_job:some_opt`, it will throw an error:
```
task: Failed to run task "some_job:some_opt": task: Found multiple tasks (*:*, *) that match "some_job:some_opt"
```
Essentially, by using '*', I want to match things that does not contain a `:` instead of matching everything. I don't think this is possible under current taskfile's mechanism.

I need to do this since both `some_job` and `some_opt` are dynamic in my case. I can't statically list all the available choices. Even if I can, there will be too many of them, which requires a lot of boilerplate tasks. A worse thing is that the list might be dynamically updating. One possible choice is to override vars: `task JOB_TYPE=some_job OPTION=some_opt`, but this makes the syntax too cumbersome and almost defies the purpose of using task.

Is it possible to add a top-level option, for example `use_first_wildcard_match: true`, to allow this behavior?
