### ISSUE TITLE
Dynamic variables not working inside includes

### ISSUE THREAD

**Issue by simonrouse9461** [go-task/task#1690]
- Task version: 3.37.2
- Operating system: MacOS
- Experiments enabled: TASK_X_MAP_VARIABLES=2

Taskfile:
```yml
version: '3'

vars:
  ENV_NAME: 
    sh: echo $(hostname)_$(users)

includes:
  test_import: 
    taskfile: '{{.ENV_NAME}}.yml'

tasks:
  test:
    cmds:
      - echo {{.ENV_NAME}}
```

This will fail with:
```
stat /path/to/my/workspace/.yml: no such file or directory
```

It seems that `ENV_NAME` evaluates to an empty string inside test_import.

**Comment by simonrouse9461** [comment]
This won't work either:
```yml
version: '3'

dotenv:
  - .env

includes:
  test_import: 
    taskfile: '{{.ENV_NAME}}.yml'

tasks:
  test:
    cmds:
      - echo {{.ENV_NAME}}
```

where .env file contains:
```
ENV_NAME=my_env
```
