### ISSUE TITLE
YAML merge key `<<` doesn't work

### ISSUE THREAD

**Issue by simonrouse9461** [go-task/task#1705]
I'm trying to use yaml anchors with merge key in the taskfile:
```yaml
version: '3'
 
anchors: &vars
  A: 1
  B: 2

vars:
  << : *vars

tasks:
  default:
    cmd: echo {{.A}} {{.B}}
```

Here's the error message:
```
err:  "A" is not a valid variable type. Try "sh", "ref", "map" or using a scalar value
file: .../Taskfile.yml:3:10
  1 | version: '3'
  2 |  
> 3 | anchors: &vars
    |          ^
  4 |   A: 1
  5 |   B: 2
```

It looks like the anchor works but the merge key doesn't. It treated the merge key as an actual key.

- Task version: 3.38.0
- Operating system: MacOS Sonoma
