### ISSUE TITLE
Adding `silent: true`when using wildcard produces extra output

### ISSUE THREAD

**Issue by stephenpope** [go-task/task#1718]
- Task version: `3.38.0`
- Operating system: `OSX`
- Experiments enabled: `false`

Issue: Adding `silent: true` to a task when using wildcards creates extra output. It seems to append the wildcard to the end of the `cmd` output.

*without* `silent: true`

```yaml
  my:thing-*:
    desc: Do a thing
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - echo wat
      - echo wat-{{.TEXT}}
```
Command + output = All good !
```
task my:thing-hello
task: [my:thing-*] echo wat
[my:thing-*] wat
task: [my:thing-*] echo wat-hello
[my:thing-*] wat-hello

```
----

*with* `silent: true`

```yaml
  my:thing-*:
    desc: Do a thing
    silent: true
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - echo wat
      - echo wat-{{.TEXT}}
```

Command & output = I have an extra `-hello` on the end.
```
 task my:thing-hello
[my:thing-*] wat-hello
[my:thing-*] wat-hello
```
----
Most simple repro:
```yaml
  my:thing-*:
    desc: Do a thing
    silent: true
    cmds:
      - echo wat
```

```
task my:thing-hello
[my:thing-*] wat-hello
```

If you need any more info please let me know :)
