### ISSUE TITLE
Remote file not working

### ISSUE THREAD

**Issue by romanzdk** [go-task/task#1727]
I am trying to use remote files.

I have remote file:

```yaml
version: "3"

tasks:
  type:
    cmds:
      - mypy .
    desc: "Run mypy"

  lint:
    cmds:
      - ruff check --fix --unsafe-fixes .
    desc: "Run ruff lint"

  fmt:
    cmds:
      - ruff format .
    desc: "Run ruff format"

  cq:
    desc: "Run mypy, ruff lint, and ruff format"
    deps:
      - fmt
      - type
      - lint
```

and local file:
```yaml
version: '3'

includes:
  abb: https://gitlab.our.company.com/some-group/some-repo/-/raw/main/Taskfile.yml
```

The remote file is stored in the root of the Gitlab repository.

When I run `TASK_X_REMOTE_TASKFILES=1 task abb:cq` I get:
```
The task you are attempting to run depends on the remote Taskfile at "https://gitlab.our.company.com/some-group/some-repo/-/raw/main/Taskfile.yml/Taskfile.yml".
--- Make sure you trust the source of this Taskfile before continuing ---
Continue? [y/N]
y
task: Failed to parse https://gitlab.our.company.com/some-group/some-repo/-/raw/main/Taskfile.yml/Taskfile.yml:
yaml: line 3: mapping values are not allowed in this context
```

So it appears `task` automatically adds `/Taskfile.yml`. However, when I delete the `/Taskfile.yml` from the URL definition I still get an error:
```
The Taskfile at "https://gitlab.our.company.com/some-group/some-repo/-/raw/main/Taskfile.yml" has changed since you last used it!
--- Make sure you trust the source of this Taskfile before continuing ---
Continue? [y/N]
y
task: Failed to parse https://gitlab.our.company.com/some-group/some-repo/-/raw/main/Taskfile.yml:
yaml: line 3: mapping values are not allowed in this context
```

When I copy content of the remote file to the local file it runs perfectly.

- Task version: 3.37.2
- Operating system: `macOS 14.3`
- Experiments enabled: `TASK_X_REMOTE_TASKFILES=1`
