### ISSUE TITLE
Task label not reflected in logs when using output prefixed

### ISSUE THREAD

**Issue by nathanperkins** [go-task/task#1750]
- Task version: v3.38.0 (h1:O7kgA6BfwktXHPrheByQO46p3teKtRuq1EpGnFxNzbo=)
- Operating system: Linux
- Experiments enabled: None

With task:

```
...

output: prefixed

tasks:
  build-image:
    label: build-image-{{.IMAGE_NAME}}
    requires:
      vars:
        - IMAGE_NAME
  ...
```

I expected the logging output to include the image name in the prefixed output, but it does not.

```
...
task: [build-image-foo] docker build \
...

...
[docker:build-image] #8 CACHED
[docker:build-image]
[docker:build-image] #9 exporting to image
[docker:build-image] #9 exporting layers done
...
```
