### ISSUE TITLE
`TASKFILE_DIR` with incorrect value

### ISSUE THREAD

**Issue by yz89122** [go-task/task#1755]
```yaml
# /Users/user/includes/Taskfile.yml
version: '3'

envs:
  PROJECT_ROOT: '{{.TASKFILE_DIR}}'

tasks:
  test:
    cmds:
      - cmd: echo '{{.PROJECT_ROOT}}'
```

```yaml
# /Users/user/Taskfile.yml
version: '3'

includes:
  included:
    taskfile: 'includes'

output: prefixed

tasks:
  test:
    deps: ['included:test']
    cmds:
     - cmd: echo '{{.PROJECT_ROOT}}'
```

```bash
cd /Users/user && task test
```

output:

```
task: [included:test] echo '/Users/user/includes'
[included:test] /Users/user/includes
task: [test] echo '/Users/user'
[test] /Users/user
```

expected output:

```
task: [included:test] echo '/Users/user/includes'
[included:test] /Users/user/includes
task: [test] echo '/Users/user/includes'
[test] /Users/user/includes
```

- Task version: `Task version: 3.38.0 ()`
- Operating system: macOS
- Experiments enabled: false
