### ISSUE TITLE
Vars passed from the CLI don't seem to work

### ISSUE THREAD

**Issue by Thiht** [go-task/task#1759]
I want to override a task variable from the CLI following this documentation: https://taskfile.dev/usage/#variables and I can't make it work

I'm assuming I'm doing something wrong but I can't figure it out so I guess it's a bug?

Here's an example:

```yml
version: "3"
tasks:
  example:
    vars:
      FILE: "*.yml"
    cmds:
      - "echo '{{.FILE}}'"
```

```
$ task example
task: [example] echo '*.yml'
*.yml

$ task example FILE=foo
task: [example] echo '*.yml'
*.yml

$ FILE=foo task example
task: [example] echo '*.yml'
*.yml
```

- Task version: v3.38.0 (h1:O7kgA6BfwktXHPrheByQO46p3teKtRuq1EpGnFxNzbo=)
- Operating system: macOS Sonoma 14.6.1
- Experiments enabled: no

**Comment by vmaerten** [comment]
Hello
You need to use  the default function (https://taskfile.dev/next/reference/templating/#default-functions) as follow : 

```
version: "3"
tasks:
  example:
    vars:
      FILE: '{{.FILE | default "*.yml"}}'
    cmds:
      - "echo '{{.FILE}}'"
```
