### ISSUE TITLE
Escape Colon in Cmds

### ISSUE THREAD

**Issue by tommyknows** [go-task/task#177]
- Task Version: Built on master

Pretty simple setup:
A `cmds` section that contains something like this:
```yaml
version: '2'

tasks:
  default:
    cmds:
      - echo "1"
      - echo "Hello: World"
      - echo "2"

```

It prints 1 and 2, but completely ignores the command with the colon in the echo string.
How can I escape this?
I know I can use 
```yaml
cmds:
  - >
    echo "Hello: World"
```
But this is not really beautiful...any other way?

**Comment by andreynering** [comment]
Hi @tommyknows,

This is an YAML issue. You should probably quote strings when they have a colon in it:

```yaml
version: '2'

tasks:
  default:
    cmds:
      - echo "1"
      - 'echo "Hello: World"'
      - echo "2"
```
