### ISSUE TITLE
Multi-line python commands fail with IndentationError

### ISSUE THREAD

**Issue by tonnydourado** [go-task/task#1770]
I could swear that multi-line python commands used to work, but now I can't make one work in any way, shape, or form. This is the simplest example of what I'm trying to do:

```yaml
# https://taskfile.dev
version: '3'
tasks:
  wat:
    cmds:
      - |
        python -c '
        import sys
        print(sys.executable)
        '
```

I have similar commands in older projects, that I haven't touched in a while, so I'm quite sure it used to work. But now I always get an indentation error:

```console
$ task wat
task: [wat] python -c '
import sys
print(sys.executable)
'

  File "<string>", line 1
    ||  goto :error
IndentationError: unexpected indent
task: Failed to run task "wat": exit status 1
```

I tried changing the block style indicator, running under different shells (Git Bash, PowerShell), using different task versions (v3.38.0, v3.29.1, v3.28.0), opening new shells, nothing works. 

Any ideas what else could have changed?

- Task version: v3.38.0, v3.29.1, v3.28.0
- Operating system: Windows
- Experiments enabled: None
