### ISSUE TITLE
`fish` completions don't report `aliases`

### ISSUE THREAD

**Issue by davinkevin** [go-task/task#1781]
Hey team, 👋 

A small feature request, because I use (and love) task for a long time, and I leverage completions a lot in my day to day work.

However, I'm not able to use `aliases` the same way, because they are ignored completly from `completions` script for my `shell` (that is `fish`). 

See, with this following file: 

```
version: 3

tasks:

  foo:
    aliases:
      - bar
    cmd: echo bar

  another: echo another
```

I have the following result: 

<img width="458" alt="image" src="https://github.com/user-attachments/assets/d828be13-a921-4013-9d78-d994e98a30cf">

The `bar` task, even if available, is totally ignored. 

Can we do something about it?
