### ISSUE TITLE
Feature: Dynamically added env variables

### ISSUE THREAD

**Issue by michaszcz** [go-task/task#1786]
I'd like to have some option to set env variables dynamically for all steps of the task.

Example 1:
```yaml
version: '3'

tasks:
  greet:
    cmds:
      - export GREETING=Hello
      - echo $GREETING  # Currently it'll print an empty string, I'd like to receive the value `Hello`
```

Example 2:
```yaml
version: '3'

tasks:
  task_name:
    dynamic_env:  # Currently not possible
      sh: python script_that_exports_env_variables.py
    cmds:
      - echo $DYNAMIC_VAR1 $DYNAMIC_VAR2  # Env vars set by the script
```

Without the feature I have to export variables and use them in one step - example:
Example 2:
```yaml
version: '3'

tasks:
  task_name:
    cmds:
      - ./export_vars.sh && echo $DYNAMIC_VAR1 $DYNAMIC_VAR2
      - echo $DYNAMIC_VAR1 $DYNAMIC_VAR2  # Currently vars are not available in this step
```

**Comment by vmaerten** [comment]
This is possible to set dynamic env variable but only one at the same time : 

```yml
version: '3'

tasks:
  greet:
    env:
      GREETING: {sh: echo 'hello'}
      FOO: bar
    cmds:
      - echo $GREETING
```

If you want to add multiple env variable at the same time, I would use `dotenv` files and follow this issue : https://github.com/go-task/task/issues/1381

**Comment by michaszcz** [comment]
Even if `dotenv` were available, it would still have a few issues:
1. It would require generating a dotenv file and removing it after task execution, which could cause issues in parallel execution.
2. Environment variables must remain the same throughout the task's execution.

**Comment by Madgvox** [comment]
+1

My use case is that I'd like to dynamically define $A or $B from a script depending on what's available in the environment. I implemented this logic as well as a bunch of other checks as an internal task and exported the appropriate variable for use in subsequent commands. Obviously, this didn't end up working as exported variables aren't visible to other commands. It would be nice to be able to affect the 'global task environment' in some way from within tasks. There are other methods to achieve what I'm doing, but they subvert Task's features rather than synergize with them.

**Comment by trulede** [comment]
@michaszcz hi, you solve this with a multi-line command:

```
version: '3'

tasks:
  task_name:
    cmds:
      - |
        ./export_vars.sh && echo $DYNAMIC_VAR1 $DYNAMIC_VAR2
        echo $DYNAMIC_VAR1 $DYNAMIC_VAR2
```

More info: https://taskfile.dev/docs/faq#i-can-t-reuse-my-shell-in-a-task-s-commands

It can also be used to exchange values between tasks, for instance, if export_vars.sh was generated be a dependency of task_name.
