### ISSUE TITLE
Architecture is incorrectly reported

### ISSUE THREAD

**Issue by punkfairie** [go-task/task#1787]
- Task version: v3.38
- Operating system: macOS 15 beta on arm64
- Experiments enabled: none

Task incorrectly reports my computer's architecture as x86_64 when I am actually on arm64. This makes Homebrew throw all kinds of errors when trying to install packages with Task.

Task output:
```yaml
tasks:
  config: brew config

# output - macOS: 15.0-x86_64
```

Shell output:
```bash
brew config
# output - macOS: 15.0-arm64
```

**Comment by andreynering** [comment]
Hi @punkfairie,

I could not reproduce this on my machine. I get `macOS: 14.6.1-arm64` no matter if I call it directly or inside a Taskfile.

Can you tell me which architecture of the `task` binary you have installed? You can check that by running a task like:

```yaml
version: '3'

tasks:
  arch: 'echo {{ARCH}}'
```
