### ISSUE TITLE
vars no longer run `sh`

### ISSUE THREAD

**Issue by Firesphere** [go-task/task#1825]
- Task version: 3.39.2
- Operating system: MacOS 15 & MacOS 14.latest
- Experiments enabled: TASK_X_MAP_VARIABLES=1

Vars, such as this:
```
version: '3'

tasks:
  test:
    cmds:
      - echo {{.GIT_COMMIT}}
    vars:
      GIT_COMMIT:
        sh: git log -n 1 --format=%h
```
Now return
```
$ task test
map[sh:git log -n 1 --format=%h]
```
instead of the expected evaluated value.
