### ISSUE TITLE
[Bug:] Custom task directory (set with `dir`) is not created before initializing dynamic variable

### ISSUE THREAD

**Issue by ColorfulRhino** [go-task/task#1841]
Consider the following task using a custom `dir`:

```YAML
version: '3'

tasks:
  test:
    dir: test-dir
    vars:
      TEST_VAR: "This is a test"
    cmds:
      - echo "This is a test. Using TEST_VAR with value: ${TEST_VAR}"
```

The above task will create the directory `test-dir` before executing the command if it is not already created.

However, when using a dynamic variable instead, like this:

```YAML
version: '3'

tasks:
  test:
    dir: test-dir
    vars:
      TEST_VAR:
        sh: curl https://taskfile.dev
    cmds:
      - echo "This is a test. Using TEST_VAR with value: ${TEST_VAR}"
```

It fails to execute when the directory `test-dir` does not yet exist:
`task: Command "curl https://taskfile.dev" failed: chdir /home/user/test-dir: no such file or directory`

**Expected behaviour:**
The directory should be created *before* trying to execute the dynamic variable initialization command.

---

- Task version: v3.39.2
- Operating system: Ubuntu 24.04
- Experiments enabled: no

**Comment by trulede** [comment]
Why can't the curl command be the first of the task cmds? I guess this is just an example, is there a real use-case?

```
version: '3'

tasks:
  test:
    dir: test-dir
    vars:
      TEST_VAR: https://taskfile.dev
    cmds:
      - curl ${TEST_VAR}"
      - echo "This is a test. Using TEST_VAR with value: ${TEST_VAR}"
```
