### ISSUE TITLE
String interpolation and home dir (including ~)

### ISSUE THREAD

**Issue by Ilyes512** [go-task/task#185]
Task version: 2.4.0    OS: Darwin (MacOS)

This project really looks promising, and I would really like to use this instead of `Make` except I am running into some problems.

I have the fallowing example task file. For the below test I ran this first to have a test file: `$ echo 'hello world' > ~/testfile.txt`:

```yaml
version: "2"

env:
  WORLD: world!!!!!
  HW: hello_${WORLD}
  TEST_FILE: ~/testfile.txt

tasks:
  test:
    cmds:
      - echo $HOME
      - echo ~
      - echo $WORLD
      - echo $HW
      - echo $TEST_FILE
      - echo ~/testfile.txt
      - cat ~/testfile.txt
      - echo ${TEST_FILE}
      - cat ${TEST_FILE}
```

I get the fallowing output (minus the `-----> expected` appended) when I run `$ task test`:

```bash
echo $HOME
/Users/ilyes512
echo ~
/Users/ilyes512
echo $WORLD
world!!!!!
echo $HW
hello_${WORLD} -----> expected: hello_world!!!!!
echo $TEST_FILE
~/testfile.txt
echo ~/testfile.txt
/Users/ilyes512/testfile.txt
cat ~/testfile.txt
hello world
echo ${TEST_FILE}
~/testfile.txt -----> expected: /Users/ilyes512/testfile.txt
cat ${TEST_FILE}
cat: ~/testfile.txt: No such file or directory -----> expected: hello world
```

When I set an env variable like this (and I don't even use it):

```yaml
env:
  EXAMPLE: ${HOME}/foobar
```

It will error with:

```bash
"{HOME}/foobar": executable file not found in $PATH
task: Command "{HOME}/foobar" in taskvars file failed: exit status 127
```

- So should I be able to use a earlier set env variable in another env?
- Does the `~` and `${HOME}` behave correctly?

Another issue I saw about almost the same thing: #74 It also mentions a "chat". Is this still in use, and if so, it should be documented somewhere? (would expect the readme to mention it).

BTW I have tried variables as both `${FOOBAR}` as well as `$FOOBAR` (so minus the `{` and `}`).

Thanks in advance :)

**Comment by andreynering** [comment]
Hi @Ilyes512,

We had a chat room in the past [here](https://gophers.slack.com/messages/C5E8GGHU2/) (you'd need to sign up on https://gophers.slack.com first). It's still there, but I removed the links from the GitHub repo and site because I not always had time to answer questions quickly, and also it's not very searchable. GitHub issues suits better, IMHO.

About the issues you've being having... that's happening because Task isn't currently expanding values on `env:` at all. Expanding are only happening for `dir:` and `sources:` and `generates:`, so stuff like `~` will work there. But I think it makes sense to also expand `env:`, so I'll look into fixing this soon.

Even then, you still won't be able to reference other environment variables add to `env:`, though. Unless it's a previously set one, like `PATH`, etc.

**Comment by andreynering** [comment]
Keep in mind [variable expansion](https://taskfile.dev/#/usage?id=variables-expansion) works for `env:`, too. That is likely to solve your use case already.

**Comment by Ilyes512** [comment]
Yes, I was just now playing with vars instead and I realise I wouldn't actually use env variables that much.

I also noticed I can use vars to "build" env variables when needed ie:

```yaml
vars:
  HOME: {sh: "echo $HOME"}

env:
  HOME: "{{.HOME}}/foobar"
```

BTW I am already am a member of gophers :)

**Comment by Ilyes512** [comment]
This might be it's own issue but I was wondering what your thought is about adding this:

```
vars:
  MINIKUBE_IP: {sh: "minikube ip", ignore_error: true}
```

If [Minikube](https://kubernetes.io/docs/setup/minikube/) is not running it would stop execution with: `💣  Error getting IP: Host is not running` which is fine, but would be nicer to do this in the task explicitly. Another great addition might be something like a `condition` key. A sort of check if the task deps are met:

```
tasks:
  foobar:
    condition:
      - node --version
    cmds:
      - <node stuff>
```

hmm, but then again, having an easy to understand, not bloated task runner, is very nice as well. Could probably come up with 10's of idea's. A more generic way would maybe be a `before_cmds` and `after_cmds` (with the last one always beging run even when `cmds` errors, but not if `before_cmds` errored).
