### ISSUE TITLE
Allow option to populate prompt response to sub tasks

### ISSUE THREAD

**Issue by onedr0p** [go-task/task#1870]
## Current issue

```yaml
---
version: '3'
tasks:
  task-1:
    prompt: Task 1?
    cmds:
      - task: task-2
  task-2:
    prompt: Task 2?
    cmd: echo hello
```

With the above example if I run `task task-1 --yes` the `task-2` will not ask for a prompt and run. However if I run `task task-1` and answer `y` I still get prompted on `task-2`.

It would be great if there was a way to enable passing down the prompt response to sub-tasks. I am aware of work-arounds like instead of using `- task: task-2` just use `- task task-2 --yes` but it doesn't seem very native and defeats the purpose of having the `task:` option in certain cases like this. If that is actually the suggested way to do it, that's fine.

## Purposed solution

```yaml
---
version: '3'
tasks:
  task-1:
    prompt: Task 1?
    cmds:
      - task: task-2
        propagate:
          prompt: true
          force: true # Could also be used to propagate `--force` to sub-tasks
  task-2:
    prompt: Task 2?
    cmd: echo hello
```

or allow the sub task to inherit the task calling it prompt reaponse

```yaml
---
version: '3'
tasks:
  task-1:
    prompt: Task 1?
    cmds:
      - task: task-2
  task-2:
    prompt: Task 2?
    cmd: echo hello
    inherit_prompt_response: true
```

**Comment by trulede** [comment]
Hi, really this is a task design issue (your task design). You can, for instance, do this:

```
version: '3'
tasks:
  task-1:
    prompt: Task 1?
    cmds:
      - task: task-2-real
  task-2:
    prompt: Task 2?
    cmds:
      - task: task-2-real
  task-2-real:
    internal: true
    cmd: echo hello
```

And that solves the problem.
