### ISSUE TITLE
override dist taskfile

### ISSUE THREAD

**Issue by lrob** [go-task/task#1873]
If not already possible, and I missed it, it would be very useful to be able to override only certain fields of a taskfile.dist.yml with a local taskfile.yml. Just like in docker compose with docker-compose.override.yml. [Here](docker-compose.override.yml) is the documentation for it.

This would have several advantages: the most important, I think, are:
1) The taskfile.yml would usually be very short, because the fields to be overridden are usually only a few.
2) if any part of the dist file is modified, this is automatically inherited by the local taskfile.yml.

**Comment by trulede** [comment]
@lrob You could use the existing include mechanism to achieve the same effect. 

The specification of the included taskfile name uses a template mechanism, so it would even be possible to select which file to include at runtime. For example:

```yaml
version: '3'

includes:
  lib:
    taskfile: ./Taskfile.{{REL}}.yml    //resolves to a taskfile containing task 'do_stuff'
    flatten: true                              // no namespace, just call task'do_stuff' directly
```

Then run task: `REL=debug task do_stuff` ... or similar. There is a lot of possibility from there.

https://taskfile.dev/usage/#flatten-includes

**Comment by lrob** [comment]
Hi, thanks for your answer.
I think that I cannot achieve what I need with the `include` feature. I provide an example of what I would like to achieve. 
Let's say that this is the content of the taskfile.dist.yml:
```
version: '3'

tasks:
  greet:
    cmds:
      - echo $GREETING
    env:
      GREETING: Hey, there!
```

if we locally want a different greeting, so far, we need to copy the tasfkile.dist.yml in a new file named taskfile.yaml with this content:
```
version: '3'

tasks:
  greet:
    cmds:
      - echo $GREETING
    env:
      GREETING: Hello!
```

what I would like to have is a mechanism that allow to override only some fields of the tasfile.dist.yml by creating a file named (for example) taskfile.override.yaml with the following content:

version: '3'

tasks:
  greet:
    env:
      GREETING: Hello!
```
