### ISSUE TITLE
Calling parent task with templating bug

### ISSUE THREAD

**Issue by ameergituser** [go-task/task#1876]
- Task version: v3.39.2
- Operating system: Ubuntu 24.04.1 LTS
- Experiments enabled: No

### Use case
A child task (included taskfile task) which can either call its task or a parent task. The behavior is determined based on a variable using template conditional logic.

### Example Taskfiles
.
├── child
│   └── Taskfile.yml
└── Taskfile.yml

#### Child Taskfile
``` yaml
# https://taskfile.dev

version: '3'

tasks:
  hello:
    cmds:
      - task: work
      - task: :work
      - task: '{{if .CALL_PARENT_TASK}}:work{{else}}work{{end}}'


  work:
    cmds:
      - echo "hello from child!"

``` 
#### Parent Taskfile
``` yaml
# https://taskfile.dev

version: '3'

includes:
  child:
    taskfile: ./child/Taskfile.yml
    dir: ./child
    internal: true

tasks:
  test1:
    cmds:
      - task: child:hello


  test2:
    cmds:
      - task: child:hello
        vars: {CALL_PARENT_TASK: true}


  work:
    cmds:
      - echo "hello from parent!"

```
 ### Output
 Running the parent Taskfile `task test1` always works as expected:
 
 ``` shell
task test1
task: [child:work] echo "hello from child!"
hello from child!
task: [work] echo "hello from parent!"
hello from parent!
task: [child:work] echo "hello from child!"
hello from child!

```
However, running the parent task `task test2` always fails:
``` shell
task test2
task: [child:work] echo "hello from child!"
hello from child!
task: [work] echo "hello from parent!"
hello from parent!
task: Failed to run task "test2": task: Task "child::work" does not exist
```
It seems that the templating has an effect on calling parent tasks.

**Comment by vmaerten** [comment]
Indeed this syntax is not compatible with templating. As workaround you can do this : 

```yml
# https://taskfile.dev

version: '3'

tasks:
  hello:
    cmds:
      - task: '{{if .CALL_PARENT_TASK}}parent_work{{else}}work{{end}}'

  parent_work:
    cmds:
      - task: :work
  work:
    cmds:
      - echo "hello from child!"

```
