### ISSUE TITLE
Incorrect/confusing `include cycle detected` error message after a silly mistake

### ISSUE THREAD

**Issue by VinGarcia** [go-task/task#1881]
- Task version: v3.38.0 (h1:O7kgA6BfwktXHPrheByQO46p3teKtRuq1EpGnFxNzbo=)
- Operating system: MacOS M1 Sonoma

I did a silly mistake on a Taskfile and got a misleading message as a response, so it took me a while to figure out exactly what the issue was. 

### Minimum Reproducible example

I create two taskfiles in the same directory with the following names:

```yaml
# Taskfile.yml
version: '3'

includes:
  common: ./TaskfileCommon.yml

tasks:
  test:
    cmds:
      - task: common:test
```

And

```yaml
# TaskfileCommon.yml
version: '3'

includes: # This was the silly mistake, this should be `vars` not `includes`
  GOBIN:
    sh: echo $(go env GOPATH)/bin

tasks:
  test:
    cmds:
      - "{{.GOBIN}}/richgo test ./..."
```

Then I tried running:

```
task common:test
```

And the error message I got back was this:

> task: include cycle detected between /Users/vingarcia/temp/tfile/Taskfile.yml <--> /Users/vingarcia/temp/tfile/TaskfileCommon.yml

I am not sure how easy it is to fix this issue and I understand this might not be a high priority bug, but I thought it would be worth mentioning anyway.

Great tool, thanks for making it and keeping it open source =]

**Comment by semihbkgr** [comment]
I'm not sure if this is an issue that needs to be fixed, but perhaps we could consider preventing empty strings and null values in the path of includes if there’s no use case for them.

**Comment by pd93** [comment]
```yaml
includes: # This was the silly mistake, this should be `vars` not `includes`
  GOBIN:
    sh: echo $(go env GOPATH)/bin
```

This should absolutely be generating an error when no `taskfile:` or `directory:` is specified on an include.
