### ISSUE TITLE
Set Variable not working with equal sign

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#19]
Taskvars.yml:

```yaml
CONTEXT: /
```

Taskfile.yaml:

```yml
set-vars-notworking:
  cmds:
    - echo git.pnet.ch/mule/mule/pkg/http/api.context={{.CONTEXT}}
  set: NOT_WORKING

set-vars-working:
 cmds:
   - echo git.pnet.ch/mule/mule/pkg/http/api.context{{.CONTEXT}}
 set: WORKING

view:
  deps:
    - set-vars-notworking
    - set-vars-working
  cmds:
    - echo 'notworking {{.NOT_WORKING}}'
    - echo 'working {{.WORKING}}'
    - echo 'context {{.CONTEXT}}'
```

Produces the following output:

```bash
$ task view
notworking git.pnet.ch/mule/mule/pkg/http/api.context
working git.pnet.ch/mule/mule/pkg/http/api.context/
context /
```

The notworking value should be:
```bash
notworking git.pnet.ch/mule/mule/pkg/http/api.context=/
```

not

```bash
notworking git.pnet.ch/mule/mule/pkg/http/api.context
```
