### ISSUE TITLE
Internal task should inherit prefix from caller task

### ISSUE THREAD

**Issue by TLG-Gildas** [go-task/task#1906]
In case of `output: prefixed`, if we have a task calling an internal task (see ex taskfile above), prefix used for internal task should be caller task's prefix to completely hide internal task.

taskfile.yml : 
```yaml
version: 3

output: prefixed

tasks:
  .internal:
    internal: true
    cmds:
      - echo "internal"

  external2:
    cmds:
      - echo "external2"
      - task: .internal

  external:
    cmds:
      - echo "external"
      - task: external2
```

actual output of : `task external`
```
[external] external
[external2] external2
[internal] internal
```

expected output : 
```
[external] external
[external2] external2
[external2] internal
```

I have put two levels of calling in this exemple to explicitly see that prefix should be inherited from direct caller only.

If prefix is customized on caller, then internal callee should use this one.
If prefix is customized on internal task, then there shouldn't have inheritance.

**Comment by trulede** [comment]
A different perspective: 

We have Taskfile's which represent fairly complex workflows, most of the Tasks themselves are internal, and we have a fair amount of inheritance, and also deps (and everywhere else a Task might reside). If all of our internal tasks would have the same prefix as the "external" ones then it becomes very difficult to understand what is happening as a task/workflow executes, and consequently, difficult to debug.

**Comment by trulede** [comment]
@TLG-Gildas Can you try this, it should solve your problem. Please reopen the issue if not.

```
version: 3

output: prefixed

tasks:
  .internal:
    vars:
       PREFIX: '{{.PREFIX | default .TASK}}'
    prefix: '{{.PREFIX}}'
    internal: true
    cmds:
      - echo "internal"

  external2:
    cmds:
      - echo "external2"
      - task: .internal
         vars:
           PREFIX: '{{.TASK}}'

  external:
    cmds:
      - echo "external"
      - task: external2
        vars:
           PREFIX: '{{.TASK}}'

```
