### ISSUE TITLE
Dynamic variables are logged incorrectly in verbose mode

### ISSUE THREAD

**Issue by mgbowman** [go-task/task#1920]
Dynamic variables are logged incorrectly when running in `--verbose` mode. It looks like a regression introduced in #1904 when `v.Sh` was refactored to a pointer. 

`Taskfile.yml` to reproduce (standard `task --init` where `GREETING` is a dynamic var)
```yaml
# https://taskfile.dev

version: '3'

vars:
  GREETING: 
    sh: echo "Hello, World!"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

```

**Actual Output**

```
$ task --verbose
task: [/workspaces/personal/go-task/taskfiles/dynamic-vars] Not found - Using alternative (Taskfile.yml)
task: dynamic variable: %!q(*string=0xc000146cf0) result: "Hello, World!"
task: "default" started
task: [default] echo "Hello, World!"
Hello, World!
task: "default" finished
```

**Expected Output**

```
$ task --verbose
task: [/workspaces/personal/go-task/taskfiles/dynamic-vars] Not found - Using alternative (Taskfile.yml)
task: dynamic variable: "echo \"Hello, World!\"" result: "Hello, World!"
task: "default" started
task: [default] echo "Hello, World!"
Hello, World!
task: "default" finished
```

- Task version: `v3.40.0 (h1:1gKx+2UDz06Jtm0MBiN+EqVN87wWEyspuEze4LRGusk=)`
- Operating system: `Linux colima 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Experiments enabled:
```
* GENTLE_FORCE:     off
* REMOTE_TASKFILES: off
* MAP_VARIABLES:    off
```
