### ISSUE TITLE
Allow shorter syntax for tasks with default configuration

### ISSUE THREAD

**Issue by andreynering** [go-task/task#194]
Instead of requiring tasks to be declared as:

```yaml
version: '2'

tasks:
  foobar:
    cmds:
      - echo "something"
```

We could allow:

```yaml
version: '3'

tasks:
  foobar:
    - echo "some"
    - echo "thing"
```

Or even:

```yaml
version: '3'

tasks:
  foobar: echo "something"
```

If users want to change any task configuration, they'd have to use the original form.
