### ISSUE TITLE
`generates` work avoidance does not seem to work

### ISSUE THREAD

**Issue by alexec** [go-task/task#1945]
- Task version: v3.40.1 
- Operating system: Linux
- Experiments enabled: None

```yaml
version: '3'

tasks:
  install-kind:
    cmds:
      - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      - chmod +x ./kind
    generates:
      - kind
```

This always runs. It should only run once.

**Comment by alexec** [comment]
```yaml
tasks:
  install-kind:
    cmds:
      - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      - chmod +x ./kind
      - sudo mv ./kind /usr/local/bin/kind
    status:
      - test -f /usr/local/bin/kind
```
