### ISSUE TITLE
Dependency run twice

### ISSUE THREAD

**Issue by alexec** [go-task/task#1946]
- Task version: v3.40.1
- Operating system: Linux
- Experiments enabled: None

```yaml
# https://taskfile.dev

version: '3'

tasks:
  install-kind:
    cmds:
      - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
      - chmod +x ./kind
      - sudo mv ./kind /usr/local/bin/kind
    status:
      - test -f /usr/local/bin/kind

  config-kubectl-completion:
    deps: [ install-kind ]
    cmds:
      - kubectl completion bash > sudo tee /etc/bash_completion.d/kubectl
    status:
      - test -f /etc/bash_completion.d/kubectl

  install-helm:
    cmds:
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    status:
      - test -f /usr/local/bin/helm

  install-eiamcli:
    cmds:
      - wget -O /tmp/eiamcli.zip https://artifactory.a.intuit.com/nexus/content/repositories/IBP.Intuit-Releases/com/intuit/ebs/eiam/eiamCli-linux/3.0.5/eiamCli-linux-3.0.5.zip
      - cd /tmp && unzip -o eiamcli.zip && cd eiamCli-linux && sudo sh install.sh
    status:
      - test -f /usr/local/bin/eiamCli

  default:
    deps:
      - install-kind
      - config-kubectl-completion
      - install-helm
      - install-eiamcli
```

Note how `config-kubectl-completion` depends on `install-kind`, this is the output:

```
task: Task "install-eiamcli" is up to date
task: Task "install-helm" is up to date
task: Task "install-kind" is up to date
task: Task "install-kind" is up to date
task: Task "config-kubectl-completion" is up to date
```

Why is `install-kind` run twice. Should only be run once.
