### ISSUE TITLE
Template function breaks the "requires" feature

### ISSUE THREAD

**Issue by NorbertHauriel** [go-task/task#1950]
This could be the exact same, or similar issue as #1557, but there is no reproduction happening there, so I decided to make a new issue, because I found a way to reproduce the "requires" breakage. The required variable is not enforced in the below example.

**Expected:** "task: Task "default" cancelled because it is missing required variables: MY_VAR"
**Result:** "template: :1:28: executing "" at <" ">: invalid value; expected string"
**Taskfile:**
```
version: 3
tasks:
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range .MY_VAR | splitList " " }}
      {{end}}
```

When not using the template function, the required variable feature works as expected.
Result: "task: Task "default" cancelled because it is missing required variables: MY_VAR"
```
version: 3
tasks:
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range .MY_VAR }}
      {{end}}
```

- Task version: v3.40.0
- Operating system: Linux, macOS
- Experiments enabled: no

**Comment by vmaerten** [comment]
Hello
This is not linked to the require feature. This is because there is a template error.

```yml
version: 3
tasks:
  default:
    cmd: |
      {{range .MY_VAR | splitList " " }}
      {{end}}
```

The above still results in an error.

Your template seems incorrect, and I'm not sure what you're trying to achieve.
For reference, here’s a valid template:

```yml
cmd: '{{range .MY_VAR}}{{range splitList . " "}}{{.}}{{end}}{{end}}'
```

**Comment by NorbertHauriel** [comment]
Hi [vmaerten](https://github.com/vmaerten).

Then why aren't the required parameters evaluated first, before even trying to resolve them? Why would I ever want to move on to the task when it has missing dependencies?

**Comment by NorbertHauriel** [comment]
Hi vmaerten.

The use case is simple. Set MY_VAR to a space delimited list of words, then iterate on them. But MY_VAR is **REQUIRED**!
So if you do not provide the required MY_VAR, the implicit documentaton should be done by the "requires" feature. But instead, the template resolution front runs it, but why is this happening? It does not make sense to move forward when dependencies are missing.

Here is an example:

```
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range .MY_VAR | splitList " " }}
        echo {{.}}
      {{end}}
```


To call the task, the user gives something like this:
task MY_VAR="my words"

And the result is:
```
task: [default] 
  echo my

  echo words

my
words
```

**Comment by vmaerten** [comment]
Thank you for the explanation! I apologize for not fully understanding your issue initially.

You're absolutely right—in your case, which is valid, the message should be:
`task: Task "default" cancelled because it is missing required variables: MY_VAR`

Until this is addressed, you can use the following workaround by defining a default value:

```yml
version: 3
tasks:
  default:
    requires:
      vars: [MY_VAR]
    cmd: |
      {{range (default "" .MY_VAR) | splitList " " }}
        echo {{.}}
      {{end}}
```
