### ISSUE TITLE
Unable to use Requires to limit Wildcards

### ISSUE THREAD

**Issue by ionfury** [go-task/task#1955]
From the docs I expect to be able to use [requires](https://taskfile.dev/usage/#ensuring-required-variables-have-allowed-values) and [wildcard arguments](https://taskfile.dev/usage/#wildcard-arguments) together to limit the possible wildcards.  Below is an example, following from the initial wildcard PR https://github.com/go-task/task/pull/1489:

```yaml
---
version: "3"

tasks:
  start-*:
    desc: "Starts a service.  Options: web, db"
    vars:
      SERVICE: "{{ index .MATCH 0 }}"
    cmds:
      - echo "Starting {{.SERVICE}}"
    requires:
      vars:
        - name: SERVICE
          enum: ["web", "db"]
```

And the output:

```sh
❯ task start-a
task: Task "start-*" cancelled because it is missing required variables: SERVICE
```

```sh
❯ task start-web
task: Task "start-*" cancelled because it is missing required variables: SERVICE
```

Removing the `requires` block results in the following (correct) output:

```sh
❯ task start-web
task: [start-*] echo "Starting web"
Starting web
```

I would expect `requires` to validate that `SERVICE` is in `["web", "db"]`.  If this assumption or my implementation is incorrect, please forgive me.

- Task version: 
```sh
Task version: 3.40.1 ()
```
- Operating system:
```sh
ProductName:            macOS
ProductVersion:         14.4.1
BuildVersion:           23E224
```
- Experiments enabled: none
