### ISSUE TITLE
Task should fail if the status checks don't pass

### ISSUE THREAD

**Issue by alexec** [go-task/task#1956]
Consider this synthetic task:

```yaml
  download-ui-dependencies:
    cmds:
      - yarn
    status:
      - test -d node_modules
```

This task should only be successful if the status checks pass. I end up doing this:

```yaml
  download-ui-dependencies:
    cmds:
      - yarn
      - test -d node_modules
    status:
      - test -d node_modules
```

Would it be good to run the status checks after the task runs so we fail fast?

**Comment by trulede** [comment]
@alexec don't you want [preconditions](https://taskfile.dev/reference/schema/#precondition)?

Status is something slightly different, in-so-much that status means run or skip (so that a task only runs if status conditions are (not) satisfied.

**Comment by vmaerten** [comment]
@alexec , @trulede is right

status won't run the task if status conditions are not satified and it won't exit in error.

```yml
  download-ui-dependencies:
    cmds:
      - yarn
    status:
      - test -d node_modules
```
It'll run `yarn` if node_modules folder does not exist. If the folder exists, the task won't be ran

If you want to `fail` (IE: exit in error), you need to use preconditions : 

```yml
  download-ui-dependencies:
    cmds:
      - yarn
    preconditions:
      - test -d node_modules
```
