### ISSUE TITLE
special variable for absolute path of task directory

### ISSUE THREAD

**Issue by vmaerten** [go-task/task#1959]
### Discussed in https://github.com/go-task/task/discussions/1957

<div type='discussions-op-text'>

<sup>Originally posted by **lesomnus** December 14, 2024</sup>
Assume I run following taskfile at `/home/lesomnus/foo`:
```yaml
version: "3"

tasks:
  hello:
    dir: bar
    cmds:
      - echo $(pwd)
```
It will print  `/home/lesomnus/foo/bar`.
However, I believe it should be templated rather than executing `pwd`.

There was an issue about it at #525 but is closed as duplication of #215 but #215 does not state that.

Maybe I can:
```yaml
version: "3"

tasks:
  gen-proto:
    dir: proto
    vars:
      PWD:
        sh: pwd
    cmds:
      - echo {{.PWD}}
```
but it is too verbose.

Is there already a special variable for this?</div>
