### ISSUE TITLE
Declaring task dependencies using template

### ISSUE THREAD

**Issue by AkihikoITOH** [go-task/task#196]
Hello,

I've been using go-task since recently and I find it very handy.

I have a question.
Right now I have a task file which is basically like
```yaml
version: "2"

tasks:
  example:
    deps:
      - task: example-rb
        vars:
          DIR: dir1
      - task: example-go
        vars:
          DIR: dir2
      - task: example-rb
        vars:
          DIR: dir3
      - task: example-js
        vars:
          DIR: dir4

  example-rb:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Ruby specific task in {{.DIR}}"

  example-go:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Go specific task in {{.DIR}}"

  example-js:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Javascript specific task in {{.DIR}}"
```

and the result is
```
$ task -s example
Ruby specific task in dir1
Ruby specific task in dir3
Javascript specific task in dir4
Go specific task in dir2
```

Now, I'm having dozens more of directory-language combinations and I wonder if I can avoid having dozens more task dependencies, because it would be tedious and hard to grasp otherwise.

I tried the following so I only need to add items to the variable TARGETS.
```yaml
version: "2"

tasks:
  example:
    vars:
      TARGETS: |-
        dir1,rb
        dir2,go
        dir3,rb
        dir4,js
    deps: |
      {{ range .TARGETS | splitLines }}
      {{ $parts := split "," . }}
      - task: example-{{$parts._1}}
        vars:
          DIR: "{{$parts._0}}"
      {{ end }}

# Following part remains unchanged.
  example-rb:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Ruby specific task in {{.DIR}}"

  example-go:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Go specific task in {{.DIR}}"

  example-js:
    prefix: "{{.DIR}}"
    dir: "{{.DIR}}"
    cmds:
      - echo "Javascript specific task in {{.DIR}}"
```

However this results in
```
$ task -v example
yaml: unmarshal errors:
  line 11: cannot unmarshal !!str `{{ rang...` into []*taskfile.Dep
```

Is this kind of task declaration supposed to work? If so, what am I doing wrong?
If not, do you know any alternative ways?

Thank you very much!

--
```
Task version: 2.5.0
```
