### ISSUE TITLE
Issue with EXIT_CODE variable not available in deferred tasks referencing another task

### ISSUE THREAD

**Issue by NikitaCOEUR** [go-task/task#1966]
### Description

I am trying to configure a task that is used in a defer based on the EXIT_CODE generated when a command fails in my Taskfile. However, I am encountering an issue where the EXIT_CODE variable is only available in a defer that uses a command directly, but not in a defer that references another task.

## Steps to reproduce:
1. Generate the Taskfile : 
```yaml
# https://taskfile.dev

version: '3'

tasks:
  exit:
    cmd: echo {{.MESSAGE}}

  exit-with-exit-code:
    cmd: echo Defer to task with EXIT_CODE management {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}

  exit-one:
    cmds:
      - defer:
          task: exit
          vars:
            MESSAGE:
              sh: "echo Defer to task via vars with sh {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - defer:
          task: exit
          vars:
            MESSAGE: "Defer to task via classic vars {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - defer:
          task: exit-with-exit-code
      - defer: "echo 'Defer to cmd' {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - |
        exit 1
```
2. Execute this command :  `task exit-one`
3. This produces : 
```shell
task: [exit-one] exit 1

task: [exit-one] echo 'Defer to cmd' Failed with 1!
Defer to cmd Failed with 1!
task: [exit-with-exit-code] echo Defer to task with EXIT_CODE management Success!
Defer to task with EXIT_CODE management Success!
task: [exit] echo Defer to task via classic vars Success!
Defer to task via classic vars Success!
task: [exit] echo Defer to task via vars with sh Success!
Defer to task via vars with sh Success!
task: [exit-with-exit-code] echo Defer to task with EXIT_CODE management Success!
Defer to task with EXIT_CODE management Success!
task: Failed to run task "exit-one": exit status 1
```
5. But i expected : 
```shell
task: [exit-one] exit 1

task: [exit-one] echo 'Defer to cmd' Failed with 1!
Defer to cmd Failed with 1!
task: [exit-with-exit-code] echo Defer to task with EXIT_CODE management Failed with 1!
Defer to task with EXIT_CODE management Failed with 1!
task: [exit] echo Defer to task via classic vars Failed with 1!
Defer to task via classic vars Failed with 1!
task: [exit] echo Defer to task via vars with sh Failed with 1!
Defer to task via vars with sh Failed with 1!
task: [exit-with-exit-code] echo Defer to task with EXIT_CODE management Failed with 1!
Defer to task with EXIT_CODE management Failed with 1!
task: Failed to run task "exit-one": exit status 1
```

### Version

Task version: v3.40.1 (h1:Q/TjPh5SAI+XK2fBravDPZXNGm6mvnwrLJqCXfhZ3Wc=)

### Operating system

Debian 12

### Example Taskfile

```YAML
# https://taskfile.dev

version: '3'

tasks:
  exit:
    cmd: echo {{.MESSAGE}}

  exit-with-exit-code:
    cmd: echo Defer to task with EXIT_CODE management {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}

  exit-one:
    cmds:
      - defer:
          task: exit
          vars:
            MESSAGE:
              sh: "echo Defer to task via vars with sh {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - defer:
          task: exit
          vars:
            MESSAGE: "Defer to task via classic vars {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - defer:
          task: exit-with-exit-code
      - defer: "echo 'Defer to cmd' {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}"
      - |
        exit 1
```

**Comment by NikitaCOEUR** [comment]
Hey, thanks for the suggestion, but it doesn’t seem to work either:

```shell
$ task exit-one
task: [exit-one] exit 1

task: [exit] echo 'Success!'
Success!
task: Failed to run task "exit-one": exit status 1

**Comment by trulede** [comment]
OK, the code here is only operating on the `Cmd`.
https://github.com/go-task/task/blob/c5be67655543100c33607f8176e3dd21f323e374/task.go#L343

I think if the `EXIT_CODE` was also added to the cmd.Vars at the same point; in the case when cmd.Vars is available, i.e. a Task and not a command; then probably this would work like you expect.

**Comment by NikitaCOEUR** [comment]
That makes sense ! I will test that.

**Comment by NikitaCOEUR** [comment]
This issue is still present; is there any chance this will be fixed?

**Comment by NikitaCOEUR** [comment]
This issue is partially resolved — but sufficiently — as of release [3.43.1](https://github.com/go-task/task/releases/tag/v3.43.1)+ notably thanks to https://github.com/go-task/task/pull/2173.

The only missing part is when referencing a variable generated within a task — it's not made available unless it's explicitly declared under vars at the task level :
```yaml
# https://taskfile.dev

version: '3'

tasks:
  exit-with-exit-code:
    cmd: echo Defer to task with EXIT_CODE management {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}

  exit-one:
    cmds:
      - defer:
          task: exit-with-exit-code
      - |
        exit 1
```

EXIT_CODE is not available in deferred task. but We can easily solve it with : 

```yaml
# https://taskfile.dev

version: '3'

tasks:
  exit-with-exit-code:
    cmd: echo Defer to task with EXIT_CODE management {{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}

  exit-one:
    cmds:
      - defer:
          task: exit-with-exit-code
          vars:
            EXIT_CODE: "{{.EXIT_CODE}}"
      - |
        exit 1
```
