### ISSUE TITLE
Using variables in sources section results in invalid "is up to date"

### ISSUE THREAD

**Issue by korverdev** [go-task/task#1986]
### Description

I'm not sure if this is intended behavior or not, but couldn't find another issue on this so I wanted to at least raise the question.

Variables are seemingly ignored in the `sources` section, resulting in a bad checksum. To recreate, use the example Taskfile below and run the following commands:

```bash
task example
task example DIR=other_dir
```

Oh, and this project is awesome! Thanks for all the hard work!

### Version

v3.40.1

### Operating system

Ubuntu 24.04

### Example Taskfile

```YAML
version: "3"

example:
        vars:
            DIR: "packages"
        cmds:
            - echo "Ran"
        sources:
            - "{{.DIR}}"
```

**Comment by vmaerten** [comment]
Hello ! 
There are multiple issue in our example. First of all, you cannot override a variable like this. You need to use the `default` function like this 

```yml
vars:
  DIR: '{{default "packages" .DIR}}'
```
In our example, DIR is always 'packages'

The second thing is, we use https://github.com/mattn/go-zglob to match all **files** that match the patterm. I assume `packages`  is a directory so you need to add a wildcard like : 

```yml
vars:
  DIR: 'packages/*'
```

The final taskfile could be something like : 

```yml

version: "3"
tasks:
  example:
     vars:
       DIR: '{{default "packages" .DIR}}/*'
     cmds:
       - echo "Ran {{.DIR}}"
     sources:
            - "{{.DIR}}"
```

PS: please, be careful when providing Taskfile, your example is not correct, I cannot copy / past it because `tasks` as a key is missing
