### ISSUE TITLE
Support asterisk matching in aliases

### ISSUE THREAD

**Issue by NorbertHauriel** [go-task/task#1988]
### Description

Below is my feature request, see the comments inside the taskfile:
```
version: "3"

tasks:
  echo-*:
    aliases:
      - e* # should pass the .MATCH argument
    vars:
      TEXT: "{{index .MATCH 0}}"
    cmds:
      - echo {{.TEXT}}

  run-*-*:
    aliases:
      - r*-* # should pass the .MATCH arguments
      - r # should be illegal
      - r* # should be illegal
    vars:
      ARG_1: "{{index .MATCH 0}}"
      ARG_2: "{{index .MATCH 1}}"
    cmds:
      - echo {{.ARG_1}} {{.ARG_2}}

```
