### ISSUE TITLE
Colon in cmds fails yaml parsing

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#20]
Taskvars.yml:

```yaml
CONTEXT: /
```

Taskfile.yml:

```yaml
view:
  cmds:
    - echo 'context: {{.CONTEXT}}'
```

Produces:

```bash
$ task view
yaml: line 3: found unexpected end of stream
```

Taskfile.yml:

```yaml
view:
  cmds:
    - echo 'context: test'

```

Produces:

```bash
$ task view
yaml: unmarshal errors:
  line 3: cannot unmarshal !!map into string
```

**Comment by andreynering** [comment]
When a string constains a colon, YAML required you to quote this string. The following works:

```yml
view:
  cmds:
    - "echo 'context: {{.CONTEXT}}'"
  vars:
    CONTEXT: /
```
