### ISSUE TITLE
Wildcards & Fingerprinting Don't Work Together

### ISSUE THREAD

**Issue by ionfury** [go-task/task#2004]
### Description

I am attempting to use [wildcard tasks](https://taskfile.dev/usage/#wildcard-arguments) along with [fingerprinting](https://taskfile.dev/usage/#by-fingerprinting-locally-generated-files-and-their-sources) to create task runners for my [open tofu homelab modules](https://github.com/ionfury/homelab-modules/blob/main/.taskfiles/tofu/taskfile.yaml).  I am using nested wildcard tasks to be able to run [all tests](https://github.com/ionfury/homelab-modules/blob/62f06f8affcbd7726734f2d909a245dbac06779d/.taskfiles/tofu/taskfile.yaml#L8), [module tests](https://github.com/ionfury/homelab-modules/blob/62f06f8affcbd7726734f2d909a245dbac06779d/.taskfiles/tofu/taskfile.yaml#L18), or a [specific test](https://github.com/ionfury/homelab-modules/blob/62f06f8affcbd7726734f2d909a245dbac06779d/.taskfiles/tofu/taskfile.yaml#L29).  I am expecting the `.task/checksum` fingerprinting each unique invocation of the wildcard task, to prevent unnnessecary work.

However, the `.task/checksum` is only fingerprinting the _last_ invocation of the wildcard task.  Meaning that when running through a collection of wildcard tasks, the fingerprinting does not prevent any unnecessary work because a single file (`.task/checksum/tofu-test_-_-`) is being used to fingerprint multiple different invocations of the wildcard task.

I have created a simplified example of the issue [here](https://github.com/ionfury/homelab-modules/blob/taskfile-wildcard-issue-example/.taskfiles/example/taskfile.yaml).

Running `task copy` calls `task paste-*` on each item.  The `.task/checksum/paste--` file stores the fingerprint of each call, replacing the previous one.  This means that each call to `task copy` runs the full copy each time, even though the inputs and outputs have not changed.

I would imagine the correct behavior would be for `.task/checksum` to store the specific invocation of the wildcard task to prevent overwriting the checksum.

Please let me know if there is an issue in my implementation.  Thanks!

### Version

Task version: 3.40.1 ()

### Operating system

ProductName:            macOS ProductVersion:         14.4.1 BuildVersion:           23E224

### Example Taskfile

```YAML
# Needs additional local files created, see: https://github.com/ionfury/homelab-modules/blob/taskfile-wildcard-issue-example/.taskfiles/example/taskfile.yaml
---
version: "3"

tasks:
  copy:
    desc: Copys items from resources to outputs.
    vars:
      TASKS:
        sh: ls {{.ROOT_DIR}}/resources
    cmds:
      - for: { var: TASKS }
        task: paste-{{.ITEM}}
  
  paste-*:
    desc: Pastes an item in outputs.
    vars:
      ITEM: "{{index .MATCH 0}}"
    cmds:
      - touch {{.ROOT_DIR}}/outputs/{{.ITEM}}
    sources:
      - '{{.ROOT_DIR}}/resources/{{.ITEM}}'
    generates:
      - '{{.ROOT_DIR}}/outputs/{{.ITEM}}'
```
