### ISSUE TITLE
crlf line endings cause issues on windows

### ISSUE THREAD

**Issue by webuniverseio** [go-task/task#201]
- Task version
2.5.1

- OS
Windows 10

- Example Taskfile showing the issue
```
version: '2'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
```
Hi, thanks for your support. I have an issue with latest version when Taskfile.yml was created on windows & has `crlf` line endings. As a result of running `task -l` I'm getting following error
```
yaml: line 4: mapping values are not allowed in this context
```
Once I changed line endings to `lf` task started to work, I can run `task hello`.

Thank you.
