### ISSUE TITLE
docs: Mention arm64 for ARCH

### ISSUE THREAD

**Issue by jubr** [go-task/task#2016]
### Description

Hola, thanks for Task, it's awesome!

Perhaps worth also mentioning `arm64` explicitly in docs [#task-functions](https://taskfile.dev/reference/templating/#task-functions) for `ARCH`, now it only shows `arm`.

grtz, jubr

### Version

v3.40.1

### Operating system

arm64

### Example Taskfile

```YAML
tasks:
  test:
    vars:
      RUNTIME_ARCH: 'linux/{{ .ARCH }}'
```
