### ISSUE TITLE
Allow overriding of global variable default at the task level

### ISSUE THREAD

**Issue by luiavila** [go-task/task#2025]
### Description

Example situation:

By default, the global variable default should be used. If a task defines / attempts to override the default, it is currently not utilized.

``` yml
version: '3'

vars:
  MY_VAR: '{{.MY_VAR | default 123}}'

tasks:
  MY_TASK:
    vars:
      MY_VAR: '{{.MY_VAR | default 456}}'
    cmds:
      - echo "MY_VAR = {{.MY_VAR}}"
```

Current output:
``` text
> task MY_TASK
MY_VAR = 123

> task MY_TASK MY_VAR=789
MY_VAR = 789
```

**Comment by trulede** [comment]
The "default" is applying to the templating mechanism, which means that once the global var is evaluated then that global var is no longer undefined, and subsequent use of the template "default" will never be evaluated.

You can design your task around that behaviour in numerous ways. One of those is to do this:

```yaml
version: '3'

vars:
  G_MY_VAR: '{{.MY_VAR | default 123}}'

tasks:
  MY_TASK:
    vars:
      G_MY_VAR: '{{.MY_VAR | default 456}}'
    cmds:
      - echo "MY_VAR = {{.G_MY_VAR}}"
```

and gives output:
```bash
$ task MY_TASK
task: [MY_TASK] echo "MY_VAR = 456"
MY_VAR = 456
$ task MY_TASK MY_VAR=789
task: [MY_TASK] echo "MY_VAR = 789"
MY_VAR = 789
```

which solves the problem.
