### ISSUE TITLE
Idea: Add method / functionality to require all variables

### ISSUE THREAD

**Issue by luiavila** [go-task/task#2026]
### Description

Currently, tasks that utilize many variables causes a lot of redundant typing of the required variable

``` yaml
tasks:
  MY_TASK_W_LOTS_OF_OPTIONS:
    requires: [OPTION_A, OPTION_B, OPTION_C, OPTION_D, OPTION E, OPTION F ......]
    cmds:
      - make some_recipe A={{.OPTION_A}} B={{.OPTION_B}} C={{.OPTION_C}} D={{.OPTION_D}} E={{.OPTION_E}} F={{.OPTION_F}} .....
```

Desire is to create a global or task level option to require all variables

Possible solutions:
``` yaml
tasks:
  MY_TASK_W_LOTS_OF_OPTIONS:
    requires: "*"
    cmds:
      - make some_recipe A={{.OPTION_A}} B={{.OPTION_B}} C={{.OPTION_C}} D={{.OPTION_D}} E={{.OPTION_E}} F={{.OPTION_F}} .....
```
``` yaml
tasks:
  MY_TASK_W_LOTS_OF_OPTIONS:
    require-all: True
    cmds:
      - make some_recipe A={{.OPTION_A}} B={{.OPTION_B}} C={{.OPTION_C}} D={{.OPTION_D}} E={{.OPTION_E}} F={{.OPTION_F}} .....
```
