### ISSUE TITLE
Show allowed values when variable with set enum is missing

### ISSUE THREAD

**Issue by SanderKnape** [go-task/task#2027]
### Description

With a task like the following:

```yaml
version: '3'
tasks:
  deploy:
    cmds:
      - echo "deploying to {{.ENV}}"
    requires:
      vars:
        - name: ENV
          enum: [dev, beta, prod]
```

The following error will be shown when the required variable is missing:

`task: Task "deploy" cancelled because it is missing required variables: ENV`

When an `enum` is set like here, it would be great if the allowed values would be shown in the error. This way the user doesn't have to look into the Taskfile to see what values are allowed in situations where this isn't obvious.
