### ISSUE TITLE
passing environment variables to task via command directly on windows

### ISSUE THREAD

**Issue by LittleC** [go-task/task#203]
- Task version: master(installed via go)
- OS: windows
- Example Taskfile:
```yaml
version: '2'
env:
  CONFIG: Debug
print:
    cmds:
      - echo $CONFIG
```
For Mac, I could pass environment variables like this `CONFIG=Debug task print`,
but for windows, I have to do  `$env:CONFIG='Debug'; task print; Remove-Item Env:\CONFIG` in powershell, because `task print CONFIG=Release` will just parse that as `vars` rather than `env`.

I'm wondering if it is possible to provide a way to pass env variable directly in one command like
`task print $CONFIG=Debug VAR=test`, for which
- variable name start with a `$` will be recognized as env
- otherwise, treated as `vars` like current

Or any other ideas? Open for discussion.

**Comment by smyrman** [comment]
You can set the env in your Taskfile from variables (or environment when no variables are set) using:
```yaml
version: '2'
env:
  CONFIG: {{.CONFIG | default "Debug"}}
tasks:
  print:
    cmds:
      - echo $CONFIG
```

Then you should be able to run `task print CONFIG=Debug`.

**Comment by LittleC** [comment]
OK, that makes sense.
thanks a lot!

didn't know could write in this way
`  CONFIG: '{{.CONFIG | default "Debug"}}'`

**Comment by LittleC** [comment]
I have tried above approach, and generally it would work well.
But for task in dependencies, global env would not be shared.

For example,
```yaml
# https://taskfile.org

version: '2'

env:
  CONFIG: '{{.CONFIG | default "Debug"}}'

tasks:
  foo:
    deps: [bar]
    cmds:
      - echo $CONFIG Configuration for task foo
      - task: bar
        vars:
          CONFIG: "{{.CONFIG}}"
    silent: true

  bar:
    cmds:
      - echo $CONFIG Configuration for task bar
    silent: true
```

And when running `task foo CONFIG=Release`, the output would be
```
Debug Configuration for task bar
Release Configuration for task foo
Release Configuration for task bar
```

@smyrman do you have any means to work around this?

**Comment by LittleC** [comment]
IMHO, this may be caused by env is evaluated per time task is called?
As far as that one is defined as global env, my expectation is evaluating once and shared within all tasks.

**Comment by smyrman** [comment]
This looks like a bug to me. @andreynering?

From what I can tell, the variable is passed on to the specific task when passed on the CLI, and not to the global vars or env. In addition, I am surprised that the env is re-evaluated for each task -- is this intentional?

I tried a few different variants, this works, but defeats the purpose of a global `env`:
```yaml
# https://taskfile.org

version: '2'

env:
  CONFIG: '{{.CONFIG | default "Debug"}}'

tasks:
  foo:
    deps:
    - task: bar
      vars:
        CONFIG: '{{.CONFIG}}'
    cmds:
    - echo $CONFIG Configuration for task foo
    - task: bar
      vars:
        CONFIG: '{{.CONFIG}}'
    silent: true

  bar:
    cmds:
    - echo $CONFIG Configuration for task bar
    silent: true
```
```
$ task foo CONFIG=Release
Release Configuration for task bar
Release Configuration for task foo
Release Configuration for task bar
```
This does not:

```yaml
# https://taskfile.org

version: '2'

vars:
  CONFIG: '{{.CONFIG | default "Debug"}}'

tasks:
  foo:
    env:
      CONFIG: '{{.CONFIG}}'
    deps:
    - task: bar
    cmds:
    - echo $CONFIG Configuration for task foo
    - task: bar
    silent: true

  bar:
    env:
      CONFIG: '{{.CONFIG}}'
    cmds:
    - echo $CONFIG Configuration for task bar
    silent: true
```

```
ask foo CONFIG=Release
Debug Configuration for task bar
Release Configuration for task foo
Debug Configuration for task bar
```
