### ISSUE TITLE
Proposal: Ability to run a task / included taskfile, as a distinct user

### ISSUE THREAD

**Issue by hugo-ricateau** [go-task/task#2037]
### Description

It would be convenient to be able to run a specific task / included taskfile, as a distinct user: e.g. when using Homebrew in a multi-user environment, it must be invoked with its "owning" user, that definitely is distinct from the current one (according to the Homebrew's recommendation in this context).
I didn't find any previous request for such feature; I hope I didn't miss it.

This can already be achieved through
```yaml
version: 3

vars:
  USER:
    sh: echo ${USER:-$(whoami)}

tasks:
  target:
    cmds:
      - sudo --user={{.USER}} command0
      - ...
      - sudo --user={{.USER}} commandN
```
but rapidly becomes cumbersome with lots of tasks / commands; such a syntax would be of a great help for readability and maintainability:
```yaml
tasks:
  target:
    as: {{.USER}}
    cmds:
      - command0
      - ...
      - commandN
```

**Comment by MathieM** [comment]
Would be a great feature

**Comment by trulede** [comment]
@hugo-ricateau you can do this?

```yaml
version: 3

vars:
  USER:
    sh: echo ${USER:-$(whoami)}

tasks:
  target:
    cmds:
      - |
        sudo --login --user={{.USER}} 
        command0
        command1
        commandN
```

having Task do that with an `as` may not be viable (if you know otherwise please leave a note) and this seems reasonable.
