### ISSUE TITLE
example from official documentation does not work - .env files

### ISSUE THREAD

**Issue by eklunko** [go-task/task#2039]
### Description

Trying to reproduce this example from the doc:
https://taskfile.dev/usage/#env-files

I expect to see the following output:
`Using VALUE and endpoint testing.com`

I see the following:
`Using VALUE and endpoint`

Installation method: `npm install -g @go-task/cli`
npm version: 10.8.2
node version: v20.17.0
os version: Ubuntu 20.04.6 LTS under WSL in Windows 10

### Version

Task version: v3.41.0 (h1:giUddhe0XZLbEWIQ/MuTPipR9ek+teulIA5xf/2IHXg=)

### Operating system

Ubuntu 20.04.6 LTS (WSL in Windows 10)

### Example

```
# .env
KEYNAME=VALUE
```

```
# testing/.env
ENDPOINT=testing.com
```

```YAML
# Taskfile.yml
version: '3'

env:
  ENV: testing

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  greet:
    cmds:
      - echo "Using $KEYNAME and endpoint $ENDPOINT"
```

**Comment by vmaerten** [comment]
Hello !
There is a typo in the documentation: there is a dot at the end of `{{.ENV}}/.env.` that should not be there.

Using this Taskfile works as expected

```yml
# Taskfile.yml
version: '3'

env:
  ENV: testing

dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

tasks:
  greet:
    cmds:
      - echo "Using $KEYNAME and endpoint $ENDPOINT"
```
