### ISSUE TITLE
Add a "setup:" setting to allow running setup scripts before any command?

### ISSUE THREAD

**Issue by jooola** [go-task/task#204]
I'm looking for a tool that can run `source venv/bin/activate` and run the commands in that same shell. It is not cleanly doable using make, and so I tried Task.

It appears we can't do this using Task. Is there a way to have a workaround or add an option to run all commands in the same shell ?

**Comment by andreynering** [comment]
Hi @jooola,

Can you explain more why you think this'd be useful? Perhaps an example...

**Comment by jooola** [comment]
When developing a Python project within a Virtual environment with all its dependencies, we always need to activate this virtual environment in order to run project tasks like testing, linting, building.

To set up the environment by hand, we run the following commands (where `requirements.txt` lists all the dependencies):
```sh
python3 -m venv venv
source venv/bin/activate
pip -q install --upgrade -r requirements.txt
```

Since the `source` command is altering the shell to activate it, we need to stay in it to execute the next commands. So I suggested to allow to run all the commands within the same shell.

The option should also all to run all the dependencies in the same shell.

Sorry for my previous message, I clearly wasn't describing my problem enough.

**Comment by smyrman** [comment]
You can do this today as a multi-line command, but you need to somehow duplicate the setup of venv to each command, e.g. as a template variable.

**Comment by jooola** [comment]
It would be something like:
```yaml
vars:
  VENV: |-
    test -d venv || python3 -m venv venv
    source venv/bin/activate


tasks:
  setup:
    cmds:
      - |
        {{.VENV}}
        pip -q install --upgrade -r requirements.txt

```

**Comment by smyrman** [comment]
👍 

Remember to also add a `set -e` on of multi-line commands to ensure they exit on error.

```yaml
vars:
  VENV: |-
    test -d venv || python3 -m venv venv
    source venv/bin/activate


tasks:
  setup:
    cmds:
    - |
      set -e
      {{.VENV}}
      pip -q install --upgrade -r requirements.txt
```

**Comment by smyrman** [comment]
> But dependencies inheritance cannot work in this case, that was the point of chaining dependencies. 

No it can't; dependencies, or any other cmd, can never change the environment in task, which is what would be needed for that to work.

At an early stage of task, there was a `"set"` command, that could set the environment within a task, but it was deprecated.

**Comment by andreynering** [comment]
As @smyrman said, multi-line strings should solve this use case. The downside is that you have to concat the setup stage in each needed command.

Maybe we could add a `setup` flag to task/global to setup stuff before all commands?

```yaml
version: '2'

setup:
  - set -e
  - rbenv init

tasks:
  # ...
```

Sharing state between command calls for a single task would be possible, but it'd be likely confusing.

**Comment by stephencheng** [comment]
@andreynering https://github.com/direnv/direnv might be considered to achieve this? it actually load the sourced export values into its context. If so, can part of its code incorporated?

**Comment by andreynering** [comment]
@stephencheng Interesting idea, worth studying the possibility. Thanks for sharing.

**Comment by ProfessorManhattan** [comment]
This is ideal but while we're waiting on this feature is there a file like `~/.bashrc` that we can put functions in that we would like to be able to access globally from any task?

**Comment by andreynering** [comment]
@ProfessorManhattan Interesting idea, but no, we do not support that.

**Comment by ssbarnea** [comment]
I really like the idea to allow a configurable list of commands to run before each shell task, `set -e` being an obvious use case.

**Comment by andreynering** [comment]
Idea: just like the `setup:` proposal above, having a `cleanup:` setting (needs to think if it's the best name) to run _after_  each task could make sense as well.

**Comment by andreynering** [comment]
#1115 is a complement to this. Both should probably be implemented together.

**Comment by cweagans** [comment]
`cleanup` would be really great. My use case is that I need to do something like this:

```yaml
tasks:
  foo:
    cmds:
      - echo "do something"
    preconditions:
      - op document get "TLS Cert" --output=./test.crt --force && step certificate needs-renewal --expires-in 48h --bundle test.crt
```

This leaves a `test.crt` sitting around - I'll never want that after the task runs, so having some way to clean things like that up at the very end of `task` execution would be helpful! I'd definitely be able to use `setup:` as well.

**Comment by jubr** [comment]
@cweagans in the precondition you could solve that with sh logic and do something like:
```
preconditions:
  - >- 
    op document get "TLS Cert" --output=./test.crt --force;
    set +e;
    step certificate needs-renewal --expires-in 48h --bundle test.crt;
    ret=$?;
    rm -f test.crt;
    exit $ret;
```

**Comment by trulede** [comment]
There are lots of ways to solve the problems raised in this issue, and lots of solutions provided too! In general you want an approach like this:

```
version: '3'

tasks:
  setup:
    - |
      echo "FOO=foo" > session.txt
  default:
    deps:
      - task: setup
    cmds:
      - |
        source session.txt
        echo $FOO
      - defer:
          echo '{{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}'
```

Normally, that will get you what you need, and you can use the capabilities of Task to achieve that in especially efficient ways.

There are other issues tracking sharing a 'cmd' between tasks (an especially bad idea), and there is this PR #2346 that demonstrates how setup/cleanup mechanism might work (which sits unnoticed). I suggest to take up the discussion there, or open a fresh clean issue, since this one was resolved long ago.
