### ISSUE TITLE
Proposal: `defer:` availability at task level

### ISSUE THREAD

**Issue by hugo-ricateau** [go-task/task#2040]
### Description

I have similar use-cases as reported in this [feature request](https://github.com/go-task/task/issues/1082) (running post-processing tasks at the very end of the overall workflow), but I would like to propose a different approach for handling such case; as it may have a slightly different purpose / implementation, I created a distinct report, but close it if it seems like a duplicate.

The proposal would be to add support for the `defer:` keyword at task level, with the exact same behaviour as for commands; defining a symmetric to the `deps:` feature. For instance,
```yaml
version: 3

tasks:
  pre:
    internal: true
    run: once
    defer:
      - post
    cmds:
      - pre-cmd

  a:
    deps:
      - pre
    cmds:
      - a-cmd

  b:
    deps:
      - pre
    cmds:
      - b-cmd

  post:
    internal: true
    run: once
    cmds:
      - post-cmd
```
when invoked via `task a b`, would result in running `pre` then `a` then `b` and finally `post`.

For now, the proposed syntax has no effect.

**Comment by trulede** [comment]
Perhaps a new `run` option "defer", to suggest the task run at the end of a structured call graph. 

```yaml
tasks:
  pre:
    internal: true
    run: once
    cmds:
      - task: post
      - echo pre
 
  post
    internal: true
    run: defer
    cmds:
      - echo post

a:
    deps:
      - pre
    cmds:
      - echo a
```

If you are interested in hacking, I came up with this, which is a handy pattern for typical login/cmds/logout sequence:
<details>
```yaml
tasks:
  pre:
    internal: true
    run: once
    cmds:
      - echo "pre"

  post:
    internal: true
    run: once
    cmds:
      - echo "post"

  cmd:
    internal: true
    vars:
      MSG: '{{.MSG | default "foo"}}'
    cmds:
      - echo "message {{.MSG}}  (cmd)"

  a:
    cmds:
      - task: cmd
        vars:
          MSG: "hello from A"

  b:
    cmds:
      - task: cmd
        vars:
          MSG: "hello from B"

  run:
    cmds:
      - task: pre
      - for: { var: CLI_ARGS }
        task: '{{.ITEM}}'
      - task: post
```

```bash
$ task run -- a b
task: [pre] echo "pre"
pre
task: [cmd] echo "message hello from A  (cmd)"
message hello from A  (cmd)
task: [cmd] echo "message hello from B  (cmd)"
message hello from B  (cmd)
task: [post] echo "post"
post
```
</details>
