### ISSUE TITLE
Shopt globstar does not work

### ISSUE THREAD

**Issue by trallnag** [go-task/task#2043]
### Description

For me, shell option globstar does not work.

I followed this documentation: https://taskfile.dev/usage/#set-and-shopt

```
❯ task
task: [default] echo **/*.go
**/*.go
```

If I adjust it to just `echo **/*.go` the expansion works. So it is just globstar that is broken?

```
❯ task
task: [default] echo **/*.go
**/*.go
```

### Version

3.41.0

### Operating system

Linux

### Example Taskfile

```YAML
version: '3'

set: [pipefail]
shopt: [globstar]

tasks:
  default: echo **/*.go
```
