### ISSUE TITLE
Native support for piping stdout to stdin between commands

### ISSUE THREAD

**Issue by zan-xhipe** [go-task/task#2051]
### Description

I often find myself writing pipelines with various unix tools and it would be great if Task had native support for this.  Adds a new attribute for a task called `pipe` that is mutually exclusive with `cmds`.  It accepts an array of commands, same as `cmds` but it pipes `stdout` of each to `stdin` of the next. 

An alternative would be to have a `pipe: true` option to enable this behaviour on `cmds`.

It would look something like this.
```yaml
tasks:
  prepare:
    pipe:
      - aws logs filter-log-events --log-group-name {{.LOG_GROUP}} --filter-pattern REPORT --query 'events[*].message'
      - jq -R '.[]'
      - grep .
      - grep -v 'INIT_REPORT'
      - tr -du "[:alpha:]"
      - cut -f2-5
      - tr '\t' ','
```
