### ISSUE TITLE
TASKFILE_DIR resolved incorrectly in dynamic variables of included Taskfiles

### ISSUE THREAD

**Issue by Diaphteiros** [go-task/task#2057]
## Setup
```
./
├── Taskfile.yaml
└── common/
    ├── Taskfile.yaml
    └── foo.sh
```
#### Taskfile.yaml
```yaml
version: 3

includes:
  shared:
    taskfile: common

tasks:
  pwd:
    desc: Print the current working directory.
    cmds:
    - pwd
```
#### common/Taskfile.yaml
```yaml
version: 3

vars:
  foo:
    sh: '{{.TASKFILE_DIR}}/foo.sh'

tasks:
  pwd:
    desc: Print the current working directory.
    cmds:
      - pwd
```
#### common/foo.sh
The content of this file doesn't really matter.
```shell
#!/bin/bash
echo "foo"
```

## Actual Behavior
Calling `task shared:pwd` works as expected:
```
task: [shared:pwd] pwd
/var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.6yctrFQfZM/tasktest
```
However, calling any task from the root Taskfile sets `TASKFILE_DIR` to the root Taskfile's directory for variable resolution, leading to this error:
```
stat /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.6yctrFQfZM/tasktest/foo.sh: no such file or directory
task: Command "/var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.6yctrFQfZM/tasktest/foo.sh" failed: exit status 127
```

## Expected Behavior
`{{.TASKFILE_DIR}}` in the `common/Taskfile.yaml` file should always resolve to the `common` subdirectory, never to the directory of the including Taskfile. The current behavior makes it impossible for the included Taskfile to reference a file next to it (at least without knowing the relative path from including to included Taskfile).

### Version

v3.41.0

### Operating system

macOS (darwin/arm64)

### Example Taskfile

```YAML

```

**Comment by Diaphteiros** [comment]
Possibly related to #1684

**Comment by trulede** [comment]
@andreynering  This is a duplicate of #454 #2035 and others.

Cause of the problem; when task parses taskfiles all global vars are "merged" into a single set, then, when you run the `pwd` task it attempts to evaluate all dynamic variables using its value of TASKFILE_DIR, and not the value you might expect.

If you want this to work now, then you will have the either: change the path to be more explicit (i.e. `{{.ROOT_DIR}}/common/foo.sh`, or relocate the var to one of the tasks where it is used.

**Comment by trulede** [comment]
Right, so there are a few things going on here:

 TASKFILE_DIR is going to the the folder of the executing taskfile, keep that in mind.

The importED taskfile vars will be merged into the root taskfile vars, still as a templated variable (so dynamically resolved).

When you run a task in the importED taskfile the TASKFILE_DIR will be that of the importED taskfile ... works as _you_ expect.

When you run a task in the importING taskfile the TASKDILE_DIR will be that of the importING taskfile ... works as expected, but not as _you_expect.


Solution is to provide the importED taskfile vars with a path that will reliably evaluate. My suggestion would be a combination of ROOT_DIR and a global var COMMON_DIR.



But perhaps, rethink the approach? .dotenv files ,include vars ... really anything but what you were doing ;-)

Because I spend so-much-time-on-this .. here are the taskfiles I ended up with


```
version: 3

includes:
  shared:
    taskfile: common

#vars:
#  COMMON_DIR: common # also works.

tasks:
  pwd:
    desc: Print the current working directory.
    cmds:
    - pwd
    - echo foo={{.foo}}
    - echo bar={{.bar}}
```


```
version: 3

vars:
  COMMON_DIR: 'common' # works 
  foo:
    sh: 'echo {{.ROOT_DIR}}/{{.COMMON_DIR}}/foo.sh'
    #sh: 'echo {{.ROOT_DIR}}/common/foo.sh'  # also works
  bar: '{{.ROOT_DIR}}/{{.COMMON_DIR}}/foo.sh'

tasks:
  pwd:
    desc: Print the current working directory.
    cmds:
      - pwd
      - echo foo={{.foo}}
      - echo bar={{.bar}}
```
