### ISSUE TITLE
YAML schema does not recognize `silent` attribute for `defer` blocks

### ISSUE THREAD

**Issue by StoaferP** [go-task/task#2061]
### Description

I use the [Taskfile YAML schema with VS Code](https://taskfile.dev/integrations/#visual-studio-code) and found that it incorrectly reports `silent` as an invalid parameter for `defer` items (screenshot below).  This is definitely [valid behavior that was recently implemented](https://github.com/go-task/task/pull/1879/files).

![Image](https://github.com/user-attachments/assets/17b5c27c-fdf0-461d-9531-505593fa0bd9)

### Version

3.41.0

### Operating system

Ubuntu 22.04.4

### Example Taskfile

```YAML
version: '3'

tasks:
  stoaferp-defer-things:
    cmds:
      - defer: echo "this will always execute"
        silent: true
      - exit 1
      - echo "this will not execute"
```
