### ISSUE TITLE
Allow to use vars in matrix

### ISSUE THREAD

**Issue by DjinNO** [go-task/task#2065]
### Description

It is not possible to use variables in a matrix task now

```
version: '3'

vars:
  OS_VAR: ["windows", "linux", "darwin"]
  ARCH_VAR: ["amd64", "arm64"]

tasks:
  default:
    silent: true
    cmds:
      - for:
          matrix:
            OS: {{.OS_VAR}}
            ARCH: {{.ARCH_VAR}}
        cmd: echo "{{.ITEM.OS}}/{{.ITEM.ARCH}}"
```

```
err:  invalid keys in command
file: /Users/djinn/GIT/gitlab/gitops/installations/generator/Taskfile.yml:12:9
  10 |     silent: true
  11 |     cmds:
> 12 |       - for:
     |         ^
  13 |           matrix:
  14 |             OS: {{.OS_VAR}}
```

Correct me if I'm wrong

**Comment by pd93** [comment]
@DjinNO You are correct that it is currently not possible to pass variables into the matrix. You would need to define the variables statically:

```yaml
version: '3'

tasks:
  default:
    silent: true
    cmds:
      - for:
          matrix:
            OS: ["windows", "linux", "darwin"]
            ARCH: ["amd64", "arm64"]
        cmd: echo "{{.ITEM.OS}}/{{.ITEM.ARCH}}"
```

The error message you're getting is actually a little misleading and I've opened #2068 to address this. With the changes in that PR, you should see something like `err:  cannot unmarshal !!map into []interface {}`. This indicates that the values in a matrix need to be arrays and hence you wouldn't be able to using templating syntax to do what you want (templates always output strings).

If we support this going forwards, I imagine it would look something like this instead:

```yaml
version: '3'

vars:
  OS_VAR: ["windows", "linux", "darwin"]
  ARCH_VAR: ["amd64", "arm64"]

tasks:
  default:
    silent: true
    cmds:
      - for:
          matrix:
            OS:
              ref: OS_VAR
            ARCH:
              ref: ARCH_VAR
        cmd: echo "{{.ITEM.OS}}/{{.ITEM.ARCH}}"
```

However, this won't work currently.

**Comment by illia-weisser** [comment]
```
vars:
  ENVIRONMENTS_YML:
    sh: yq e '.environments' environments.yaml
  ENVIRONMENTS:
    ref: "keys ((fromYaml .ENVIRONMENTS_YML))"
  SERVICES:
    sh: find ./microservices -type f  -name "*" -exec basename {} \; | sed 's/\.[^.]*$//' | sed 's/\.[^.]*$//' | sort

tasks:
  generate-all:
    desc: Generate all manifests for all clusters and environments
    cmds:
      - for:
          matrix:
            ENVIRONMENT:
              ref: .ENVIRONMENTS
            SERVICE:
              ref: .SERVICES
        task: task:generate:chart
```

`matrix reference ".ENVIRONMENTS" must resolve to a list`

Should this work or do I need to create a ticket?
