### ISSUE TITLE
Expand task aliases

### ISSUE THREAD

**Issue by MetalArend** [go-task/task#2071]
### Description

```
tasks:
  do:*:
    internal: true
    aliases:
      - label: do:something
        desc: Do something
        list: true
        internal: false
```

Could we add a possibility to list aliases in the main task list?
