### ISSUE TITLE
Allow users to input variables interactively

### ISSUE THREAD

**Issue by andreynering** [go-task/task#2079]
### Description

We could probably use [Huh](https://github.com/charmbracelet/huh) for this.

**Comment by vmaerten** [comment]
Really good idea!
Do you want to make all of them interactive, or add a new `interactive: bool` flag?

**Comment by andreynering** [comment]
@vmaerten Not every variable. I think it makes sense that the user chooses which vars make sense to ask. Perhaps something like this:

```yaml
tasks:
  my-task:
    cmds:
      - input: MY_VAR
      - echo "Result: {{.MY_VAR}}"
```

or

```yaml
tasks:
  my-task:
    vars:
      MY_VAR: {input: true}
    cmds:
      - echo "Result: {{.MY_VAR}}"
```

**Comment by timrulebosch** [comment]
Could using the template engine work? Where a callback interface, from the template function to the UI, allows the retrieval of additional user input. The default UI would be a simple STDIN based prompt. So for example, chaining some template functions:

```yaml
tasks:
  my-task:
    vars:
      MY_VAR: '{{.MY_OTHER_VAR | prompt "foo"}}'  # prompt in "interactive-mode", with default presented to the user
      MY_VAR2: '{{.MY_OTHER_VAR | prompt "bar" | fail "VAR2 was not set"}}'  # mandatory, must provide
      MY_VAR3: '{{.MY_OTHER_VAR | prompt | default "fubar"}}'  # prompt no default, then fallback to  default
    cmds:
       - echo "Result: {{.MY_VAR}}"
```

In interactive mode, prompt returns the value from the callback, or if "Nil", then the "default" prompt value. Otherwise, in non-interactive-mode, prompt returns the "default" prompt value (so acts like default keyword).
