### ISSUE TITLE
Using `-d` option brakes path resolution within `includes` when `dir` is set

### ISSUE THREAD

**Issue by 0xn3va** [go-task/task#2080]
### Description

Hello team,

I tried to set the working directory using the `-d` option and include task file from another directory but Task incorrectly resolves a path for included task file. You can follow the next steps to reproduce the issue:

1. Create temp directory `cd $(mktemp -d)`
2. Add shared task file to `./include/common.yml`:

    ```yaml
    version: '3'
    tasks:
      work:
        cmds:
          - echo 'Hello World from Task!'
    ```

3. Add task file to `./Taskfile.yml`:

    ```
    version: '3'
    includes:
      common:
        taskfile: "include/common.yml"
        dir: "{{.DIR_PATH}}"
    tasks:
      default:
        cmds:
          - task common:work
    ```

4. Run the following command to confirm that everything working as expected when `-d` is not set:

    ```
    $ DIR_PATH="$(pwd)" task -t Taskfile.yml
    Hello World from Task!
    ```

5. Run the following command to reproduce the error:

    ```
    $ DIR_PATH="$(pwd)" task -d "$(mktemp -d)" -t Taskfile.yml 
    task: No Taskfile found at "/var/folders/yp/syl984812xsdsc7qv3zr7y4c0000gp/T/tmp.w6MZV1YF0H"
    task: Failed to run task "default": exit status 100
    ```

I tried to use absolute paths like `taskfile: "{{.DIR_PATH}}/include/common.yml"` but nothing worked.

### Version

Task version: 3.41.0 (pypi)

### Operating system

macos

### Example Taskfile

```YAML
# includes/common.yml
version: '3'
tasks:
  work:
    cmds:
      - echo 'Hello World from Task!'

# Taskfile.yml
version: '3'
includes:
  common:
    taskfile: "include/common.yml"
    dir: "{{.DIR_PATH}}"
tasks:
  default:
    cmds:
      - task common:work
```
