### ISSUE TITLE
Yaml anchor insertion is not correctly recognised, and falls back to error in default branch

### ISSUE THREAD

**Issue by MetalArend** [go-task/task#2083]
### Description

YAML anchors are not correctly recognised, so they end up in the [default](https://github.com/go-task/task/blob/fb273186019920119b439644d81cb3f57336dc94/taskfile/ast/var.go#L251) statement, and error out.

### Version

3.41.0

### Operating system

Ubuntu

### Example Taskfile

```YAML
version: '3'


tasks:
  foo:
    vars: &anchor
      FOO: true
  bar:
    vars:
      <<: *anchor
      BAR: true
```
