### ISSUE TITLE
Global vars can't use .CLI_ARGS special var as default value

### ISSUE THREAD

**Issue by angelmadames** [go-task/task#2090]
### Description

I wanted to use a global `vars:` key to default to the .CLI_ARGS special var.

```yaml
vars:
  ENV: '{{.ENV | default .CLI_ARGS}}'
```

And then use it in a task, so both of these examples work:

```shell
task debug -- dev  # Should use 'dev' as value for `ENV`
task debug ENV=dev # Should behave similarly as `-- dev`
```

The above behavior works if `vars:` is used directly in the task definition:

```yaml
tasks:
  debug:
    vars:
      ENV: '{{.ENV | default .CLI_ARGS}}'
    cmds:
      - echo '{{.ENV}}'

```

Only when using `vars:` globally `.CLI_ARGS` comes empty and doesn't work.

### Version

v3.41.0 (h1:giUddhe0XZLbEWIQ/MuTPipR9ek+teulIA5xf/2IHXg=)

### Operating system

macOS Sequioa 15.3.1 (24D70)

### Example Taskfile

```YAML
version: '3'

vars:
  ENV: '{{.ENV | default .CLI_ARGS}}'

tasks:
  debug:
    cmds:
      - echo '{{.ENV}}'
```
