### ISSUE TITLE
Version 3.42 breaks some variable usages inside go templates

### ISSUE THREAD

**Issue by vctls** [go-task/task#2106]
### Description

I have multiple taskfiles that use the following pattern to factorize global variables that are expensive to initialize:
```yaml
version: "3"
vars:
  FOO:
    sh: |-
      echo {{ if .TASK | contains "bar"}}baz{{end}}
tasks:
  bar:
    cmd: echo {{.FOO}}
```
This worked fine in 3.41.0:
```bash
❯ task bar
task: [bar] echo baz
baz
```

Now in version 3.42, I get the following error:
```bash
❯ task bar
template: :1:28: executing "" at <"bar">: invalid value; expected string
```
Which suggests that the `TASK` variable is not a string.  

But if I do this:
```yaml
version: "3"
vars:
  FOO:
    sh: |-
      echo {{.TASK}}
tasks:
  bar:
    cmd: echo {{.FOO}}
```
…then the value of the variable is printed:
```bash
❯ task bar
task: [bar] echo bar
bar
```
Not sure what's going on here.  
Maybe I'm using the variables in an unexpected way.

### Version

3.42

### Operating system

Ubuntu 22.04

### Example Taskfile

```YAML
version: "3"
vars:
  FOO:
    sh: |-
      echo {{ if .TASK | contains "bar"}}baz{{end}}
tasks:
  bar:
    cmd: echo {{.FOO}}
```
