### ISSUE TITLE
Incorrect Directory Path Formatting in Windows (ROOT_DIR Missing Slashes)

### ISSUE THREAD

**Issue by marcolongol** [go-task/task#2116]
### Description

When running the task CLI tool on Windows, the ROOT_DIR variable appears to return an incorrectly formatted path, missing the expected backslashes (\).

Steps to Reproduce:

    Create a Taskfile.yaml with the following content:

```yaml
version: '3'

tasks:
  default:
    - echo {{.ROOT_DIR}}
```

Run task from the extracted binary location:

    C:\Users\WDAGUtilityAccount\Downloads\task_windows_amd64>task

Expected Behavior:

The output should correctly print the full directory path with backslashes:

`C:\Users\WDAGUtilityAccount\Downloads\task_windows_amd64`

Actual Behavior:

The output is missing backslashes:

`C:UsersWDAGUtilityAccountDownloadstask_windows_amd64`

### Version

3.42.1

### Operating system

Windows

### Example Taskfile

```YAML
version: '3'

tasks:
  default:
    - echo {{.ROOT_DIR}}
```

**Comment by trulede** [comment]
@marcolongol it's possible that the backslash are consumed by the echo command, you might try:

```
- echo "{{.ROOT_DIR}}"
- echo '{{.ROOT_DIR}}'
- echo {{shellQuote .ROOT_DIR}}
- echo {{spew .ROOT_DIR}}
```

to gain an insight.

**Comment by Yorherim** [comment]
rewrite

```yaml
vars:
  ROOT_DIR: '$(pwd)'
  BIN_DIR: '{{.ROOT_DIR}}/bin'
```
