### ISSUE TITLE
the order of task under deps is random

### ISSUE THREAD

**Issue by sinlov** [go-task/task#2117]
### Description

The order of task under deps is random. Most of the time, the running order will affect the execution result.

```bash
task --experiments                                 
* GENTLE_FORCE:     off
* REMOTE_TASKFILES: off
* MAP_VARIABLES:    off
* ENV_PRECEDENCE:   off
```

### Version

3.41.0

### Operating system

linux, windows, macOS

### Example Taskfile

```YAML
version: '3'
silent: true

tasks:
  a:
    desc: "task a"
    internal: true
    cmds:
      - echo "a"

  b:
    desc: "task b"
    internal: true
    cmds:
      - echo "b"

  c:
    desc: "task c"
    internal: true
    cmds:
      - echo "c"

  tests.deps.sequence:
    desc: show deps sequence
    deps:
      - task: a
      - task: b
      - task: c
```

**Comment by pd93** [comment]
As described [in the docs](https://taskfile.dev/usage/#task-dependencies), `deps` are always run in parallel by design. If you want to call tasks serially, you should use `cmds` instead:

```yaml
version: 3

tasks:
  default:
    cmds:
      - task: a
      - task: b
      - task: c
```
