### ISSUE TITLE
task isn't sorting correctly in version 3.42.1

### ISSUE THREAD

**Issue by bartdorlandt** [go-task/task#2124]
### Description

I updated go-task to the latest version via homebrew

```
task --version
Task version: 3.42.1 (Homebrew)
```

I expected the listing to act the same as before. (using `--sort none`)

Instead the sorting is acting up, where the order is changed using the default, and when using `--sort none`. The `alphanumeric` is behaving as expected. 

> NOTE: order expected is [up, down, remove:volumes]

Output, plain task

```
❯ task
task: Available tasks for this project:
* down:                 Stop the ghost and db services
* up:                   Start the ghost and db services
* remove:volumes:       Remove the ghost and db services
task: Task "default" does not exist
```

task -l
```
❯ task -l
task: Available tasks for this project:
* down:                 Stop the ghost and db services
* up:                   Start the ghost and db services
* remove:volumes:       Remove the ghost and db services
```

task -l --sort none

```
❯ task -l --sort none
task: Available tasks for this project:
* down:                 Stop the ghost and db services
* up:                   Start the ghost and db services
* remove:volumes:       Remove the ghost and db services
```

task -l --sort alphanumeric

```
❯ task -l --sort alphanumeric
task: Available tasks for this project:
* down:                 Stop the ghost and db services
* remove:volumes:       Remove the ghost and db services
* up:                   Start the ghost and db services
```

Using shell fish.

### Version

3.42.1

### Operating system

Mac OS X 15.3.2 (24D81)

### Example Taskfile

```YAML
# https://taskfile.dev

version: '3'

tasks:
  # default:
  #   cmd: task -l --sort none
  #   silent: true

  up:
    desc: Start the ghost and db services
    cmds:
      - docker compose --env-file .env up -d --remove-orphans

  down:
    desc: Stop the ghost and db services
    cmds:
      - docker compose --env-file .env down

  remove:volumes:
    desc: Remove the ghost and db services
    cmds:
      - docker compose --env-file .env down --volumes
```
