### ISSUE TITLE
Interpolating env vars with variables does not work

### ISSUE THREAD

**Issue by ryanpodonnell1** [go-task/task#2128]
### Description

```sh
$ task -t ./Taskfile2.yaml example
task: [example] echo 'account_'
account_
```

```
task -t Taskfile2.yaml example TIER=dev
task: [example] echo 'account_'
account_
```

### Version

3.42.1

### Operating system

linux

### Example Taskfile

```YAML
version: "3"

vars:
  TIER: '{{ .TIER | default "dev"}}'


env:
  AWS_PROFILE: "account_{{ .TIER }}"


tasks:
 example:
  cmds:
  - echo '{{ .AWS_PROFILE }}'
```
