### ISSUE TITLE
Regression: character escaping ignored

### ISSUE THREAD

**Issue by NorbertHauriel** [go-task/task#2129]
### Description

Running the same task in two different versions produce different outputs, breaking previously working tasks.

v3.41.0  outputs this txt file content:
`/
`
v3.42.0 outputs this txt file content:
`//
`

### Version

v3.42.0

### Operating system

Linux

### Experiments Enabled

No

### Example Taskfile

```YAML
tasks:
  default:
    cmds:
      - |
        cat <<EOF > ./test.txt
        \\
        EOF
```
