### ISSUE TITLE
Imported task cannot call excluded task

### ISSUE THREAD

**Issue by mkantzer** [go-task/task#2135]
### Description

For the given files:

`Taskfile.yaml`:
```yaml
version: 3

includes:
  import:
    taskfile: import.yaml
    excludes:
      - excluded-task

tasks:
  test:
    cmds:
      - task: import:included-task
```

`import.yaml`
```yaml
version: 3

tasks:
  imported-task:
    cmds:
      - echo "howdy"
      - task: excluded-task

  excluded-task:
    cmd: echo "bazz"
```

Running `task test` returns:
```
task: [import:imported-task] echo "howdy"
howdy
task: Failed to run task "test": task: Task "import:excluded-task" does not exist
```

but when the `excludes` block is commented out, it returns:
```
task: [import:imported-task] echo "howdy"
howdy
task: [import:excluded-task] echo "bazz"
bazz
```

I'd expect `task test` to return the second result in both cases. I'm using the `exclude` to prevent `excluded-task` from showing up in things like autocomplete and `task --list-all`, but the internal workings of an imported system shouldn't change based on that.

### Version

3.41.0

### Operating system

macOS

### Example Taskfile

```YAML

```

**Comment by pd93** [comment]
@mkantzer Unfortunately, this is another consequence of the way we currently merge taskfiles when resolving includes. This is something that will eventually be solved when we move away from merging. However, there is a lot of work to do to get there.

In the meantime, if you have an internal task that you don't want to show up in `--list-all` or autocomplete, you could [mark it as internal](https://taskfile.dev/usage/#internal-tasks) by using `internal: true`. This will make it so that the task is not directly callable via the CLI which may or may not be desirable in your case.

I will leave this open for now so that we remember to add it as a test case when we remove AST merging.

**Comment by vmaerten** [comment]
Hello,
I’m a bit confused here because excludes was designed to work this way. It allows a Taskfile with conflicting tasks to be included when using flatten.

Like @pd93 said, mark the task as `internal` if that’s what you want—it won’t appear in` task --list-all` and won’t be callable from the CLI.

like this : 

`Taskfile.yaml`:
```yaml
version: 3

includes:
  import:
    taskfile: import.yaml

tasks:
  test:
    cmds:
      - task: import:included-task
```

`import.yaml`
```yaml
version: 3

tasks:
  imported-task:
    cmds:
      - echo "howdy"
      - task: excluded-task

  excluded-task:
    internal: true
    cmd: echo "bazz"
```

To me `internal` does what you want, and it's not the same behavior as `excludes`

To finish, I'd quote our doc : 

![Image](https://github.com/user-attachments/assets/e8bc7912-f89d-4d4f-b5c6-d2f86c9ef5bc)

Maybe we need to clarify that it won't be callable not only from the CLI but also from within a Taskfile.

We could change this behavior, but what would be the difference with `internal` in this case ?

Feel free to jump in @pd93
