### ISSUE TITLE
Perform variable expansion in precondition `msg` output.

### ISSUE THREAD

**Issue by benjamin-branchware** [go-task/task#2136]
### Description

Sometimes I would like to provide more meaningful output in `preconditions.msg`. For example, if I have a precondition that a task must be running in a MinGW-w64 environment, I may wish to print out what the `MSYSTEM` variable is:

`msg: "Error: When running on Windows, this task requires a MinGW-w64 environment. Current MSYSTEM: $MSYSTEM"`

Currently, the variable is not expanded.

**Comment by vmaerten** [comment]
Hello !

You can use the templating system : 

```yml

version: '3'

tasks:
  default:
    preconditions:
      - sh: exit 1
        msg: "When running on Windows, this task requires a MinGW-w64 environment. Current MSYSTEM: {{.MSYSTEM}}"
```

Running this : 
`MSYSTEM=linux task`
will output : 

```
task: When running on Windows, this task requires a MinGW-w64 environment. Current MSYSTEM: linux
task: precondition not met

```
