### ISSUE TITLE
Merging not working properly with yaml reference block

### ISSUE THREAD

**Issue by rfan-debug** [go-task/task#2154]
### Description

It seems the yaml reference block merging hasn't been resolved yet.

The following taskfile.yml code cannot inherit the variable `MAGIC` as long as there is another `vars` field defined in `rhel6`

```yaml
version: "3"
tasks:
  task_rhel7: &anchor
    cmds:
      - echo {{.VERSION}}
      - echo {{.MAGIC}}
    vars:
      VERSION: rhel7
      MAGIC: magic
  task_rhel6:
    <<: *anchor
    vars:
      VERSION: rhel6
```

Output:
```
task task_rhel6
task: [task_rhel6] echo rhel6
rhel6
task: [task_rhel6] echo
```
I'd expect the `task task_rhel6` echoes the `MAGIC` variable properly. 

Related issues:
1. https://github.com/go-task/task/issues/112
2. https://github.com/go-yaml/yaml/issues/410. It seems that the go/yaml merge issues won't be fixed since the repository has been archived.

### Version

3.42.0

### Operating system

MacOS 15

### Example Taskfile

```YAML

```
