### ISSUE TITLE
Task does not pass SIGQUIT to php-fpm

### ISSUE THREAD

**Issue by davidbarratt** [go-task/task#2155]
### Description

I'm having this problem with `php-fpm` on macos

Running 
```
 php-fpm --force-stderr --nodaemonize
```
on the command line works just fine and Command+C kills it as you would expect, but putting the command in a task causes it to fail (even if `interactive` is `true`)

It looks like this is because php-fpm [uses SIGQUIT](https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163) and that doesn't get propogated correctly.

It might be helpful if Taskfile were to allow users to configure the stop signal kind of like Docker's [STOPSIGNAL](https://docs.docker.com/reference/dockerfile/#stopsignal)? That's how they [fixed this problem over there](https://github.com/docker-library/php/blob/cabce86b7a0e3ccc79b46a4f393758ec3b3ef999/8.4/alpine3.21/fpm/Dockerfile#L256).

### Version

3.42.1

### Operating system

macOS

### Example Taskfile

```YAML
version: "3"
output: prefixed

tasks:
  nginx:
    internal: true
    cmd: nginx -c etc/nginx/nginx.conf -p $PWD

  php:
    internal: true
    cmd: php-fpm --force-stderr --fpm-config ./etc/php/php-fpm.conf

  dev:
    desc: |
      Runs a dev server.
    deps:
      - nginx
      - php
```
