### ISSUE TITLE
Remote task file cant load in Git Hub actions - error:  not trusted by user

### ISSUE THREAD

**Issue by joeblew999** [go-task/task#2163]
### Description

Here is a full reproduction.

CI Error:
https://github.com/joeblew999/pb-stack/actions/runs/14264412256/job/39982879685

Its a simple task call.

task: [bin] cd proj/todo-with-all && task go:bin
Building all ...
task: Taskfile "https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml" not trusted by user
task: Failed to run task "bin": exit status 104

This works fine from the laptop doing the exact same call.

### Version

version: v3.42.1 (h1:HOaFbZGLOrAy2V/dLsX2rGJZVG2Qx6268KUIAIXdNE4=)

### Operating system

darwin

### Experiments Enabled

Env Precedence, Remote Taskfiles

### Example Taskfile

```YAML
# https://taskfile.dev

# todo

version: '3'


# MUST have this ONLY in root for env variables to work.
#dotenv: ['.env', '{{.ENV}}/.env', '{{.HOME}}/.env']

includes:
  # base for devtime
  base: ./../../base.taskfile.yml

  git: ./../../git.taskfile.yml
  go: ./../../go.taskfile.yml
  #vscode: ./vscode.taskfile.yml

  remote:
    # binary needed: https://github.com/aquasecurity/trivy/releases/tag/v0.60.0
    # https://github.com/saydulaev/taskfile
    taskfile: https://raw.githubusercontent.com/saydulaev/taskfile/v1.4.3/Taskfile.yml

vars:
  BASE_SRC_NAME: todo
  TODO_GREETING: Hello, from todo project !
 
tasks:
  default:
    desc: todo print
    cmds:
      - echo "{{.TODO_GREETING}}"
    silent: true
  bin:
    cmds:
      - task go:bin
```
