### ISSUE TITLE
misleading feature: "generates" and checksum checker

### ISSUE THREAD

**Issue by viktorasm** [go-task/task#2181]
### Description

It's very misleading how `task.generates` feature works.

One would assume that the task will run if combined checksum of sources and outputs does not match sources/results of previous execution, e.g. having such definition

```yaml
sources:
   - openapi.yaml
generates:
   - client/go/**/*.go
```

.. One would expect that if some generated files are missing, or are unintentionally changed, this will cause task to rerun.

How it actually works with checksum checker:
* Checksum is calculated and checked for `sources`;
* For `generates` list, it's only verified that glob matches any files. 

This means that "generates" is only somewhat usable with absolute file names (globbing is basically useless).

Probably the best fix would be to actually include generated files into checksum calculation.

### Version

main branch

### Operating system

all

### Example Taskfile

```YAML

```

**Comment by ameergituser** [comment]
This is really one of those features that is REALLY required.  For us to live up to the "simpler than Make" statement. The basic feature of only executing when required needs to be supported.

My previous issue: #1741 

My last statement: https://github.com/go-task/task/issues/1741#issuecomment-2437013900

Other related issues: #1945

Related PR: #1816

**Comment by hanoii** [comment]
Also I think is useful if one can simple tell generates about a directory, i.e:

```yml
tasks:
  build:
    dir: web/theme
    cmds:
      - n auto
      - npm i -g yarn
      - yarn install
      - npx mix --production
    sources:
      - '*.lock'
    generates:
      - dist # or - dist/

```
