### ISSUE TITLE
task on windows returns wrong paths

### ISSUE THREAD

**Issue by joeblew999** [go-task/task#2183]
### Description

All the paths are wrong 

in windows on desktop and in GitHub actions.

tested on both Powershell and the old CMD, giving same results.

```sh

PS C:\Users\admin\go\src\github\joeblew99\pb-stack>

C:\Users\admin\go\src\github\joeblew99\pb-stack>

```

```sh


- task env
TASK_TEMP_DIR:
TASK_REMOTE_DIR:
TASK_OFFLINE:
FORCE_COLOR:

- task vars
CLI_ARGS:
CLI_FORCE: false
CLI_SILENT: false
CLI_VERBOSE: false
CLI_OFFLINE: false

The name of the current task:
TASK: base:default
The alias used for the current task, otherwise matches TASK:
ALIAS: base
TASK_EXE: C:/Users/admin/go/bin/task.exe
ROOT_TASKFILE: C:Usersadmingosrcgithubjoeblew99pb-stack
ROOT_DIR: C:Usersadmingosrcgithubjoeblew99pb-stack
TASKFILE: C:Usersadmingosrcgithubjoeblew99pb-stackbase.taskfile.yml
TASKFILE_DIR: C:Usersadmingosrcgithubjoeblew99pb-stack
TASK_DIR: C:Usersadmingosrcgithubjoeblew99pb-stack
USER_WORKING_DIR: C:Usersadmingosrcgithubjoeblew99pb-stack
CHECKSUM:
TIMESTAMP:
TASK_VERSION: v3.42.1
ITEM:
EXIT_CODE:
``` 

task file cmds:

```yaml

      - echo '- task env'
      - echo 'TASK_TEMP_DIR:'         {{.TASK_TEMP_DIR}}
      - echo 'TASK_REMOTE_DIR:'       {{.TASK_REMOTE_DIR}}
      - echo 'TASK_OFFLINE:'          {{.TASK_OFFLINE}}
      - echo 'FORCE_COLOR:'           {{.FORCE_COLOR}}
      - echo ''
      # https://taskfile.dev/reference/templating/#special-variables
      - echo '- task vars'
      - echo 'CLI_ARGS:'              {{.CLI_ARGS}}
      - echo 'CLI_FORCE:'             {{.CLI_FORCE}}
      - echo 'CLI_SILENT:'            {{.CLI_SILENT}}
      - echo 'CLI_VERBOSE:'           {{.CLI_VERBOSE}}
      - echo 'CLI_OFFLINE:'           {{.CLI_OFFLINE}}
      - echo ''  
      - echo 'TASK:'                  {{.TASK}}
      - echo 'ALIAS:'                 {{.ALIAS}}
      # The Task executable name or path.
      - echo 'TASK_EXE:'              {{.TASK_EXE}}
      # The absolute path of the root Taskfile
      - echo 'ROOT_TASKFILE:'         {{.ROOT_TASKFILE}}
      # The absolute path of the root Taskfile directory
      - echo 'ROOT_DIR:'              {{.ROOT_DIR}}
      # The absolute path of the included Taskfile.
      - echo 'TASKFILE:'              {{.TASKFILE}}
      # The absolute path of the included Taskfile directory.
      - echo 'TASKFILE_DIR:'          {{.TASKFILE_DIR}}
      # The absolute path of the directory where the task is executed.
      - echo 'TASK_DIR:'              {{.TASK_DIR}}
      # The absolute path of the directory task was called from.
      - echo 'USER_WORKING_DIR:'      {{.USER_WORKING_DIR}}
      # The checksum of the files listed in sources. Only available within the status prop and if method is set to checksum.
      - echo 'CHECKSUM:'              {{.CHECKSUM}}
      # The date object of the greatest timestamp of the files listed in sources. Only available within the status prop and if method is set to timestamp.
      - echo 'TIMESTAMP:'             {{.TIMESTAMP}}
      # The current version of task.
      - echo 'TASK_VERSION:'          {{.TASK_VERSION}}
      # The value of the current iteration when using the for property. Can be changed to a different variable name using as:.
      - echo 'ITEM:'                  {{.ITEM}}
      # Available exclusively inside the defer: command. Contains the failed command exit code. Only set when non-zero.
      - echo 'EXIT_CODE:'             {{.EXIT_CODE}}

``` 

### Version

latest

### Operating system

windows arm64, windows amd64

### Experiments Enabled

REMOTE_TASKFILES

### Example Taskfile

```YAML

```

**Comment by trulede** [comment]
#2116 #2129 possibly related issues?

**Comment by trulede** [comment]
If I had to guess, 

```yaml
version: '3'

vars:
  FOO: '{{.USER_WORKING_DIR}}'
  BAR: "bar/foo"
  FUBAR: '{{joinPath .FOO .BAR}}'

tasks:
  example:
    cmds:
      - echo 'FUBAR:' {{joinPath .FOO .BAR}}
      - echo 'FUBAR:' {{.FUBAR}}              ***** NOT OK
      - echo '{{.FUBAR}}'                           ***** OK
      - echo '{{spew .FUBAR}}'                  ***** internally, OK
      - echo 'FUBAR:' test\\foo\bar          ***** here, the problem is generated directly
      - echo 'FUBAR:' {{shellQuote .FUBAR}} **** This will FIX the problem
```

Windows:
```
task example
task: [example] echo 'FUBAR:' C:\users\trule\bar\foo
FUBAR: C:userstrulebarfoo
task: [example] echo 'FUBAR:' C:\users\trule\bar\foo
FUBAR: C:userstrulebarfoo
task: [example] echo 'C:\users\trule\bar\foo'
C:\users\trule\bar\foo
task: [example] echo '(string) (len=22) "C:\\users\\trule\\bar\\foo"
'
(string) (len=22) "C:\\users\\trule\\bar\\foo"

task: [example] echo 'FUBAR:' test\\foo\bar
FUBAR: test\foobar
task: [example] echo 'FUBAR:' 'C:\users\trule\bar\foo'
FUBAR: C:\users\trule\bar\foo
```
