### ISSUE TITLE
`{{.CLI_ARGS}}` is templated as an array instead of string.

### ISSUE THREAD

**Issue by romnn** [go-task/task#2190]
### Description

Consider this `taskfile.yaml`:

```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  test:
    cmds:
      - 'echo "arguments: {{.CLI_ARGS}}"'
```

**Before `v3.43.1`** this would print:
```
"arguments: "
```

**Now** it prints:
```
"arguments: []"
```

In my taskfiles, I used to always append `{{.CLI_ARGS}}` to a command such that users may add more arguments via `--`. Now this would need some sort of concatenation which I'm not sure how to achieve.

Is this expected behaviour or a regression?

Best, Roman

### Version

3.43.1

### Operating system

MacOS

### Example Taskfile

```YAML
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  test:
    cmds:
      - 'echo "arguments: {{.CLI_ARGS}}"'
```

**Comment by romnn** [comment]
## Update

As a workaround, or the new way to do this, this works for me:

```yaml
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  test:
    cmds:
      - |
         echo "arguments: {{ join " " .CLI_ARGS}}"
```
