### ISSUE TITLE
Regression: Builtin variables not resolved in included `vars` section

### ISSUE THREAD

**Issue by Diaphteiros** [go-task/task#2195]
### Description

Taskfile.yaml
```yaml
version: 3

includes:
  shared:
    taskfile: common/Taskfile_library.yaml
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/pkg/...'

tasks:
  print:
    desc: Print the code dirs.
    cmds:
    - 'echo "Code dirs: {{.ROOT_DIR}}/pkg/..."'
```

common/Taskfile_library.yaml
```yaml
version: 3

tasks:
  print:
    desc: Print the code dirs.
    cmds:
    - 'echo "Code dirs: {{.CODE_DIRS}}"'
```

With version `v3.42.0`:
```
task print
task: [print] echo "Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/..."
Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/...

task shared:print
task: [shared:print] echo "Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/..."
Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/...
```

With version `v3.43.*`:
```
task print
task: [print] echo "Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/..."
Code dirs: /var/folders/b8/g43jjlg51gs4h13yf49sjmjm0000gn/T/tmp.fjWVHCzUTO/pkg/...

task shared:print
task: [shared:print] echo "Code dirs: /pkg/..."
Code dirs: /pkg/...
```

As you can see, everything was working perfectly fine before and now the `ROOT_DIR` variable is resolved to the empty string in the `CODE_DIRS: '{{.ROOT_DIR}}/pkg/...'` line.

### Version

v3.43.*

### Operating system

macOS

### Experiments Enabled

_None_
