### ISSUE TITLE
Sources to support space seperated list of files

### ISSUE THREAD

**Issue by ameergituser** [go-task/task#2201]
### Description

This feature would allow taskfile to be easier and more intuative to use, and expland its use cases.

I would like to be able to use a space seperated list of files as a "sources" item. 

Example 1: Simple.

``` yaml

  task1:
    cmds:
      - <do stuff with FILES>
    sources:
      - ./file1.c ./file2.c

```
AND

``` yaml

  task1:
    cmds:
      - <do stuff with FILES>
    sources:
      - |
        ./file1.c
        ./file2.c

```

Example 2: Support task input vars.

``` yaml

  task1:
    requires:
      vars: [FILES]
    cmds:
      - <do stuff with FILES>
    sources:
      - '{{.FILES}}'

```
And Called like:

``` yaml

  parent-task:
    vars:
       SRC_FILES:
         sh: ls ./src/*.c
    cmds:
      - task: task1
        vars: {
          FILES: {{.SRC_FILES}}
        }

```
This would also apply to the generates sections as well.
