### ISSUE TITLE
USER_WORKING_DIR stops working in global tasks

### ISSUE THREAD

**Issue by snakeego** [go-task/task#2206]
### Description

Global tasks stop working in this scenario: [https://taskfile.dev/usage/#running-a-global-taskfile](https://taskfile.dev/usage/#running-a-global-taskfile). 
This version doesn't change the ⁠`USER_WORKING_DIR` variable; it always keeps the ⁠`$HOME` directory.

### Version

3.42.2

### Operating system

MacOS

### Example Taskfile

```YAML
version: "3"

tasks:
  pwd:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - pwd
```

**Comment by mbowman-nv** [comment]
Maybe a related datapoint...

Something changed in `v3.42.x -> v3.43.x` when using`USER_WORKING_DIR` in combination with `-d / --dir`

```yaml
version: "3"
silent: true
tasks:
  default:
    - echo "{{.USER_WORKING_DIR}}"
```

### Context

```
❯ go version
go version go1.24.2 linux/amd64

❯ pwd
/workspace

❯ tree .
.
├── some
│   └── nested
│       └── path
└── Taskfile.yml

❯ cd some/nested/path

❯ pwd
/workspace/some/nested/path
```
### v3.42.1 :white_check_mark:

**Test** 

```
❯ go install github.com/go-task/task/v3/cmd/task@v3.42.1
❯ task --version
Task version: v3.42.1 (h1:HOaFbZGLOrAy2V/dLsX2rGJZVG2Qx6268KUIAIXdNE4=)

❯ task
/workspace/some/nested/path

❯ task -d "/workspace"
/workspace/some/nested/path
```

**Expected**
```
/workspace/some/nested/path
/workspace/some/nested/path
```

**Actual**
```
/workspace/some/nested/path
/workspace/some/nested/path
```

### v3.43.2 :x:

```
❯ go install github.com/go-task/task/v3/cmd/task@v3.43.2
❯ task --version
3.43.2

❯ task
/workspace/some/nested/path

❯ task -d "/workspace"
/workspace
```

**Expected**

```
/workspace/some/nested/path
/workspace/some/nested/path
```

**Actual**

```
/workspace/some/nested/path
/workspace
```
