### ISSUE TITLE
fromYaml not defined

### ISSUE THREAD

**Issue by polds** [go-task/task#2217]
### Description

- What did you do?

Following the [Parsing JSON/YAML into map variables](https://taskfile.dev/usage/#parsing-jsonyaml-into-map-variables) section of the docs it recommends using the `fromYaml` template function to parse yaml.

- What did you expect to happen?

`fromYaml` should be able to read a YAML string.

- What happened instead?

I get this error:

> template: resolver:1: function "fromYaml" not defined

### Version

3.43.3

### Operating system

macos

### Example Taskfile

```YAML
version: '3'

tasks:
  read-yaml:
    vars:
      FILE:
        sh: cat config.yaml
      PARSED:
        ref: 'fromYaml .FILE'
    cmds:
      - echo {{ .PARSED }}
```

**Comment by pd93** [comment]
Probably an assumption made when creating the docs. For now you could use a tool like `yq` to convert from YAML to JSON and then use `fromJson`, but we should add this natively IMO.

@andreynering any objection to this going in slim-sprig? or would you prefer it directly in Task?

**Comment by polds** [comment]
Yeah, I did manage to get it to work going the `fromJson` path doing something like this:

```yaml
  helm:vendor-all:
    vars:
      FILE:
        sh: yq '.charts' charts/charts.yaml | yq -o=json
      CHARTS:
        ref: "fromJson .FILE"
    cmds:
    - for: { var: CHARTS, as: CHART }
      task: helm:vendor
      vars:
        NAME: '{{ .CHART.name }}'
        REPO: '{{ .CHART.repo }}'
        CHART: '{{ .CHART.chart }}'
        VERSION: '{{ .CHART.version }}'
```
