### ISSUE TITLE
Variable passed to an included taskfile task doesn't take precedence

### ISSUE THREAD

**Issue by szpn** [go-task/task#2218]
### Description

Hey, I came across an issue when using Taskfile,

Given the following file structure:
```
/
├── test
│   └── Taskfile.yml
└── Taskfile.yml
```

Taskfile contents:

**/test/Taskfile.yml**
```yaml
version: "3"

includes:
  global:
    taskfile: ../Taskfile.yml
    dir: ../
    flatten: true
```

**/Taskfile.yml**
```yaml
version: "3"

vars:
  USER: 'szpn'

tasks:
  test:
    cmd: |
      echo "Hello, USER: {{.USER}}"
```

##  Expected Behavior:
Running the task without passing `USER` works as expected from both `/` and `/test` directories - it uses the globally set variable `USER: 'szpn'`:
```
/ $ task test
task: [test] echo "Hello, USER: szpn"

Hello, USER: szpn
```
```
/test/ $ task test
task: [test] echo "Hello, USER: szpn"

Hello, USER: szpn
```

When passing a `USER` parameter, it should take precedence over the global variable, **regardless of which directory the command is run from**:
```
/ $ task test USER=my_user
task: [test] echo "Hello, USER: my_user"

Hello, USER: my_user
```
```
/test/ $ task test USER=my_user
task: [test] echo "Hello, USER: my_user"

Hello, USER: my_user
```

##  Actual Behavior:
Passing `USER=my_user` only works correctly when running from the root (`/`).  
When running from `/test`, the `USER` parameter is **ignored**, and the globa variable `USER: 'szpn'` is used:
```
/test/ $ task test USER=my_user
task: [test] echo "Hello, USER: szpn"

Hello, USER: szpn
```

### Version

3.42.1

### Operating system

macOS 15.0.1

### Experiments Enabled

None

**Comment by vmaerten** [comment]
Hello ! 
What is your use case for having a Taskfile in a parent folder that includes another Taskfile with `flatten: true` ?
If your goal is simply to be able to run the `test` task from within a subfolder, it's actually possible without needing an additional Taskfile.
You just need to delete the Taskfile in the test subfolder. Then, if you run `task test` from inside ./test, it will work automatically.

Regarding your issue: if you want to override a variable, you need to use the default function : 

```yml
version: "3"

vars:
  USERS: '{{.USERS | default "szpn"}}'

tasks:
  test:
    cmd: |
      echo "Hello, USERS: {{.USERS}}"

```

**Comment by szpn** [comment]
Hey,

I have some tasks defined inside a Taskfile in a subfolder, and I want those tasks to only be visible when working inside that subfolder. At the same time, I also want to have access to the tasks defined in the root directory's Taskfile.

I can't use the `default` function to set variables like `USER`, because it ends up pulling the value from system environment variables, which causes unexpected behavior.

For example, with the following setup:

**Taskfile:**
```yaml
version: "3"

vars:
  USER: '{{.USER | default "szpn"}}'

tasks:
  test:
    cmd: |
      echo "Hello, USER: {{.USER}}"
```

And a system environment variable set like this:
```
USER=xyzxyz
```

Running the task behaves incorrectly:
```
/test/ $ task test
task: [test] echo "Hello, USER: xyzxyz"

Hello, USER: xyzxyz
```
Instead of falling back to `szpn`, it ends up using the system's `USER` env variable, which is not what I want.

Hope that clarifies my use case a bit better!
