### ISSUE TITLE
Array variables don't work when used naively (`wrong type for value; expected string; got []interface {}`)

### ISSUE THREAD

**Issue by agirardeau** [go-task/task#2224]
### Description

Version: `v3.42.1`

Example task file:

```yml
version: '3'

vars:
  ARGS:
    - '1'
    - '2'
    - '3'

tasks:
  exec:
    cmds:
      - echo {{ join .ARGS ' ' }}
```

I expected this to run `echo 1 2 3`, printing `1 2 3`. Instead I get the following error:

```
template: :1:13: executing "" at <.ARGS>: wrong type for value; expected string; got []interface {}
```

### Version

v3.42.1

### Operating system

WSL

### Example Taskfile

```YAML
version: '3'

vars:
  ARGS:
    - '1'
    - '2'
    - '3'

tasks:
  exec:
    cmds:
      - echo {{ join .ARGS ' ' }}
```
