### ISSUE TITLE
Using `requires` with `vars` fails to show missing required variable name in error message

### ISSUE THREAD

**Issue by ToshY** [go-task/task#2228]
### Description

When using `requires` with `vars`, it fails to show which required variable is missing.

```shell
task: Task "database" cancelled because it is missing required variables:
```

Expected to see:

```shell
task: Task "database" cancelled because it is missing required variables: DB
```

### Version

3.43.3

### Operating system

Ubuntu 22.04.5 LTS

### Example Taskfile

```YAML
version: '3'

tasks:
  database:
    desc: Open database
    silent: true
    vars:
      DB: '{{.d}}'
      NAME: '{{.n}}'
    requires:
      vars:
        - DB
    cmds:
      - |
        echo "{{.DB}}-{{.NAME}}"
```

**Comment by vmaerten** [comment]
Hello
What command do you run ?  Because it works fine when I run `task database`

IE : DB and NAME are empty (define but empty)

![Image](https://github.com/user-attachments/assets/9922e280-81c3-4158-8d4b-df95a7ab7bc0)

**Comment by ToshY** [comment]
Hey @vmaerten 

I see I messed up the reproducer. My bad 🙁 I've updated the example below.

```yaml
version: '3'

tasks:
  database:
    desc: Open database
    silent: true
    vars:
      NAME: '{{.n}}'
    requires:
      vars:
        - DB: '{{.d}}'
    cmds:
      - |
        echo "{{.DB}}-{{.NAME}}"
```

> IE : DB and NAME are empty (define but empty)

Maybe my misunderstanding comes from the misuse of `vars` and `requires`. I want to use variables with a shortcut (like `{{.n}}` and `{{.d}}`), where some are required and some are not. In the above `NAME` is optional, but `DB` should be required, but I want to call it with `task database` / `task database d=1`, which should output `1-` (in `n` is not provided). 

Long story short: I cannot use shortcuts like `{{.d}}` for required variables?

**Comment by vmaerten** [comment]
requires.vars is a list of string, it does not accepte any values.
This is incorrect : 
```yml
    requires:
      vars:
        - DB: '{{.d}}'
```
This is correct : 
```yaml
    requires:
      vars:
        - DB
```

About what you are trying to achieve, you can do that : 

```yml
version: '3'

tasks:
  database:
    desc: Open database
    silent: true
    vars:
      DB: '{{.d}}'
      NAME: '{{.n}}'
    requires:
      vars:
        - d
    cmds:
      - |
        echo "{{.DB}}-{{.NAME}}"
```

You define two variables `DB` that will take value from `d` and NAME that will take value from `n`
And you also specify that `d` is required.
