### ISSUE TITLE
looping over files

### ISSUE THREAD

**Issue by sejo** [go-task/task#223]
Task version (go get--> master)
- OS: Debian 9.9

Is there a way to loop over files in a directory and run something like this (pseudo code):

for file in subdir/*.go
    GOOS=linux GOARCH=amd64 {{.GOBIN}}/govvv build subdir/$file -o releases/{{ sh: basename $file }}/$file-amd64

I'm  can't find this from the documentation.

**Comment by smyrman** [comment]
In a multiline taks you can use `sh` syntax to do that. Remember to adda `set -e` at the start.

```yaml
version: 2
tasks:
  foo:
    cmds:
    - |
      set -e
      for file in subdir/*; do
        echo $file
      done
```
