### ISSUE TITLE
`sources` don’t seem to be working in 3.43.3

### ISSUE THREAD

**Issue by chimbori** [go-task/task#2232]
### Description

```
———————————————————————————————————————————————————————————————[ 04:07:38 ]————
/…/BugReports/Taskfile $ cat Taskfile.yml
version: '3'

tasks:
  ls:
    desc: ls
    dir: '~'
    sources:
      - foo.txt
      - bar.txt
    cmds:
      - echo $PWD
      - for: sources
        cmd: echo {{ .ITEM }}
———————————————————————————————————————————————————————————————[ 04:07:40 ]————
/…/BugReports/Taskfile $ task ls -f -v
task: "ls" started
task: [ls] echo $PWD
/Users/manas
task: "ls" finished
———————————————————————————————————————————————————————————————[ 04:07:45 ]————
/…/BugReports/Taskfile $ task --version
3.43.3
———————————————————————————————————————————————————————————————[ 04:08:26 ]————
```

Expected: It should print out `foo.txt` and `bar.txt`

### Version

3.43.3

### Operating system

macOS, Linux

### Example Taskfile

```YAML
version: '3'

tasks:
  ls:
    desc: ls
    dir: '~'
    sources:
      - foo.txt
      - bar.txt
    cmds:
      - echo $PWD
      - for: sources
        cmd: echo {{ .ITEM }}
```
