### ISSUE TITLE
Checksum is not calculated anymore when `method: none`

### ISSUE THREAD

**Issue by maciej-lech** [go-task/task#2239]
### Description

```
❱ /nix/store/jn35gb9isnqzr9mfwhmig40c6iflmadz-go-task-3.41.0/bin/go-task test
task: [test] echo "a3e64c2be2ee99e18159e25340b9f632"
a3e64c2be2ee99e18159e25340b9f632
❱ /nix/store/sy2fx4azx6ny9115k1qxq210gcpdhr0c-go-task-3.43.2/bin/go-task test
task: [test] echo ""
```

I also tested 3.43.3 and it is also empty.

### Version

3.43.3

### Operating system

Linux

### Experiments Enabled

Env Precedence

### Example Taskfile

```YAML
---
version: "3"

tasks:
  test:
    sources:
      - ./test/**/*
    cmds:
      - echo "{{.CHECKSUM}}"
    method: none
```
