### ISSUE TITLE
Requires does not check if a variable is set

### ISSUE THREAD

**Issue by timrulebosch** [go-task/task#2243]
### Description

Requires does not check if a variable is set, it only checks is a variable is "present". As a result, variables which are set to "null/nil" will pass the required check.

### Version

3.43.2

### Operating system

Linux (WSL)

### Example Taskfile

```YAML
version: '3'
tasks:
  default:
    vars:
      A: null
      B: '{{.B}}'
    env:
      A: '{{.A}}'
      B: '{{.B}}'
      C: '{{.C}}'
    cmds:
      - echo "$A"
      - echo "$B"
      - echo "$C"
    requires:
      #vars: [A, B, C]
      vars: [A, B]
```

**Comment by timrulebosch** [comment]
The fundamental problem behind this is that a variable has no `nil` representation. This is apparently because the tempting system will raise errors in such cases ... and therefore any `nil` (`null` in yaml) value will be set to an empty string. Ok.

I've developed a fix for that, i.e. the requires feature checks for a "nil" value. That works ... however it introduces a conflict to #1962 and #1962 and #2033 ... which moves the requires check _before_ the task is compiled. Which means tasks like this fail with the fix I developed:

```yaml
  validation-var-dynamic:
    vars:
      FOO:
        sh: echo "one" ***** not evaluated until _after_ a task is compiled.
    requires:
      vars:
        - name: FOO
          enum: ['one', 'two']
```

@vmaerten Do you have any thoughts? As far as I can see, compiling a task is ... doing much more than tempting variables. And so that causes cases like:

```bash
require-before-compile:
    requires:
      vars: [ MY_VAR ]
    cmd: |
      {{range .MY_VAR | splitList " " }}
        echo {{.}}
      {{end}}
```

to fail (if task compile is moved _before_ requires checks). 

Ideally I would "detect" the `sh` portion, or compile variables _only_ before doing the requires check.

**Comment by timrulebosch** [comment]
I've figured out what was happening and updated the related PR.

**Comment by CJKay** [comment]
Both "requires defined" and "requires non-empty" are valid preconditions. Updating the default behaviour would be a breaking change, but could `requires` instead be expanded to support a constrained set of conditions? e.g.:

```yaml
requires:
  vars:
    - name: FOO
      condition: defined
    - name: BAR
      condition: non-empty
```

A more radical (but significantly more flexible) alternative might be to allow it to evaluate shell or boolean template expressions in the context before `vars` has been evaluated:

```yaml
requires:
  conditions:
    - sh: '{{hasKey . "FOO"}}'
      msg: "`FOO` variable is undefined"
    - sh: '{{not (empty .BAR)}}'
      msg: "`BAR` variable is empty"
```

Conceptually, this overlaps near-totally with `preconditions`, except that `requires` runs *before* all variables have been evaluated, whilst `preconditions` runs *after*.
