### ISSUE TITLE
Variable definitions are re-evaluated in deferred cmds

### ISSUE THREAD

**Issue by infogulch** [go-task/task#2244]
### Description

It seems that every time a `defer:` command is run, variable templates are re-evaluated. This is problematic when using nondeterministic variable definitions that include things like the `randInt` builtin. In addition, this breaks from the behavior of normal commands where all executions seem to share the same variable values.

For example, I would expect the example task to print the same path value 4 times, but instead it prints 2 of the same path then 2 more different paths (a total of 3 unique paths).

### Version

3.43.2

### Operating system

Windows

### Example Taskfile

```YAML
tasks:
  test:
    vars:
      DIR: '{{.ROOT_DIR}}/temp-{{randInt 1000000 9999999}}'
    cmds:
      - echo "{{.DIR}}"
      - defer: echo "{{.DIR}}"
      - defer: echo "{{.DIR}}"
      - echo "{{.DIR}}"
```
