### ISSUE TITLE
Task is running when there is no checksum stored, but status command returns 0

### ISSUE THREAD

**Issue by maciej-lech** [go-task/task#2251]
### Description

According to the docs for `status`  schema reference:

> A list of commands to check if this task should run. The task is skipped otherwise. This overrides method, sources and generates.

"This overrides method, sources and generates." indicates that `source` has more power over checksum/timestamp local state which make sense as it would handle the situation that you would like to check the state on a remote machine. (see example `Taskfile`)

Now, if the `.task/checksum/buid` is missing it executes the task always, despite the return code which doesn't make any sense and it is not what the documentation says.

### Version

3.43.2

### Operating system

Linux

### Experiments Enabled

Env Precedence

### Example Taskfile

```YAML
---
version: "3"

tasks:
  build:
    vars:
      TAG_PREFIX: myimage:1.0.0
    sources:
      - ./docker/**/*
    cmds:
      - docker build -t {{.TAG_PREFIX}}-{{substr 0 9 .CHECKSUM}} ./docker
      - docker push {{.TAG_PREFIX}}-{{substr 0 9 .CHECKSUM}}
    status:
      - docker manifest inspect {{.TAG_PREFIX}}-{{substr 0 9 .CHECKSUM}}
```

**Comment by vmaerten** [comment]
Hello ! 

It looks like the schema reference is not up to date. `Status` can be combined with the fingerprint mechanism.
You can find the relevant documentation [here](https://taskfile.dev/usage/#using-programmatic-checks-to-indicate-a-task-is-up-to-date).
For example:

```yml
version: '3'

tasks:
  build:prod:
    desc: Build for production usage.
    cmds:
      - composer install
    # Run this task if source files changes.
    sources:
      - composer.json
      - composer.lock
    generates:
      - ./vendor/composer/installed.json
      - ./vendor/autoload.php
    # But also run the task if the last build was not a production build.
    status:
      - grep -q '"dev": false' ./vendor/composer/installed.json
```

I'll update the schema reference!
