### ISSUE TITLE
Environment variables cannot reference other environment variables

### ISSUE THREAD

**Issue by bravely-beep** [go-task/task#2268]
### Description

After creating this `Taskfile.yml`:
```yaml
version: "3"

env: { FOO: foo }

tasks:
  print_foobar: 
    requires: { vars: [ $FOO ] }
    env: { FOOBAR: { sh: echo "$FOO"bar } }
    cmd: echo "$FOOBAR"
```
and running `task print_foobar`, I get the error:
> task: Task "print_foobar" cancelled because it is missing required variables: $FOO

### Version

3.39.2

### Operating system

NixOS

### Example Taskfile

```YAML
version: "3"

env: { FOO: foo }

tasks:
  print_foobar: 
    requires: { vars: [ $FOO ] }
    env: { FOOBAR: { sh: echo "$FOO"bar } }
    cmd: echo "$FOOBAR"
```

**Comment by CodeTroopers** [comment]
### Another taskfile example
```
version: "3"

dotenv:
  - .env

env:
  PORT: {{$PORT | default: 8080}}

tasks:
  echo: 
    cmd: echo $PORT
```

### Expected behavior
If .env contains PORT=9999
```
task: [echo] echo $PORT
9999
```
If .env contains nothing
```
task: [echo] echo $PORT
8080
```
