### ISSUE TITLE
`env.PATH` override not taking effect on Windows

### ISSUE THREAD

**Issue by superpluss** [go-task/task#2279]
### Description

---

### 📋 Description

When running a task on Windows and attempting to override the `PATH` environment variable in the `Taskfile.yml`, the change does not seem to take effect. Even if I explicitly prepend `{{.JAVA_HOME}}\bin` to `PATH`, the `java` command cannot be found during execution. It appears the modified `PATH` is not respected during task runtime.

---

### ✅ Expected Behavior

With the following `Taskfile.yml`:

```yaml
version: '3'

env:
  JAVA_HOME: 'C:\Program Files\Java\jdk-17.0.15'
  PATH: '{{.PATH}};{{.JAVA_HOME}}'

tasks:
  check:

    cmds:
      - echo $JAVA_HOME
      - echo $PATH
      - java -version
```

Expected output:

```text
task: [check] echo $JAVA_HOME
C:\Program Files\Java\jdk-17.0.15
task: [check] echo $PATH
C:\Program Files\Java\jdk-17.0.15\bin;...(rest of system PATH)
task: [check] java -version
C:\Program Files\Java\jdk-17.0.15\bin\java.exe
java version "17.0.15"
```

---

### ❌ Actual Behavior

Output shows that `PATH` is unchanged and `java` is not found:

```text
task: [check] echo $JAVA_HOME
JAVA_HOME=C:\Program Files\Java\jdk-17.0.15
task: [check] echo $PATH
PATH=C:\WINDOWS\system32;C:\WINDOWS;...(rest of system PATH)
task: [check] java -version
"java": executable file not found in $PATH
task: Failed to run task "check": exit status 127
```

---

### 💻 Environment Info

* OS: Windows 11 Pro 22H2
* Shells tested: PowerShell 5.1, CMD, Git Bash
* go-task version: `Task version: 3.32.0`

---

### 📌 Notes

* Running the equivalent manually in PowerShell or CMD using `set PATH=%JAVA_HOME%\bin;%PATH%` works as expected.
* Possibly `{{.PATH}}` is not resolving correctly or is being overwritten internally.

Would appreciate confirmation on whether this is a bug or if there's an intended way to pass a modified `PATH` on Windows. Thanks in advance!

---

You can submit this issue by visiting the [[go-task GitHub Issues page](https://github.com/go-task/task/issues/new)](https://github.com/go-task/task/issues/new) and pasting the above content into the issue description.

If you need further assistance with this or have other questions, feel free to ask!

### Version

3.43.3

### Operating system

Microsoft Windows 11 10.0.26100

### Experiments Enabled

Env Precedence

### Example Taskfile

```YAML
version: '3'

env:
  JAVA_HOME: 'C:\Program Files\Java\jdk-17.0.15'
  PATH: '{{.PATH}};{{.JAVA_HOME}}'

tasks:
  check:

    cmds:
      - echo $JAVA_HOME
      - echo $PATH
      - java -version
```
