### ISSUE TITLE
assignment to entry in nil map without top-level vars

### ISSUE THREAD

**Issue by Oneymus** [go-task/task#229]
```
GOARCH="amd64"
GOOS="darwin"
```

When assigning global variables via the CLI, if there is no top-level `vars` declaration, the application panics and does not provide a useful error message.

Taskfile:
```yml
version: '2'

tasks:
  testcover:
    desc: "runs unit tests and produces coverage artifacts"
    vars:
      TESTCMD: '{{.TESTCMD | default "go test"}}'
    cmds:
      - '{{.TESTCMD}} -race -timeout 1s -covermode=atomic -coverprofile coverage.out ./...'
      - go tool cover -html=coverage.out -o coverage.html
```

When assigning a global variable via the CLI, it fails:
```
→ task TESTCMD=gotest testcover                                       
panic: assignment to entry in nil map

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/go-task/task/cmd/task/task.go:141 +0xa0b
```

When assigning a task variable via the CLI, it succeeds (as expected):
```
→ task testcover TESTCMD=gotest                                       
gotest -race -timeout 1s -covermode=atomic -coverprofile coverage.out ./...
...
go tool cover -html=coverage.out -o coverage.html
```

The inverse does *not* produce similar behaviour.

Taskfile:
```yml
version: '2'

vars:
  TESTCMD: '{{.TESTCMD | default "go test"}}'

tasks:
  testcover:
    desc: "runs unit tests and produces coverage artifacts"
    cmds:
      - '{{.TESTCMD}} -race -timeout 1s -covermode=atomic -coverprofile coverage.out ./...'
      - go tool cover -html=coverage.out -o coverage.html
```

```
→ task TESTCMD=gotest testcover                                       
gotest -race -timeout 1s -covermode=atomic -coverprofile coverage.out ./...
...
go tool cover -html=coverage.out -o coverage.html

→ task testcover TESTCMD=gotest                                       
gotest -race -timeout 1s -covermode=atomic -coverprofile coverage.out ./...
...
go tool cover -html=coverage.out -o coverage.html
```
