### ISSUE TITLE
Task checksum is always the same value in v3.44.0

### ISSUE THREAD

**Issue by pastelmind** [go-task/task#2294]
### Description

On v3.44.0, Task fails to detect changes in source files because it computes incorrect checksums. When I examined the task checksum files generated in `.task/`, they always contained `99aa06d3014798d86001c324468d497f` regardless of `sources`.

The bug has been observed on the Windows (amd64) build of v3.44.0. I also tested the macOS (arm64) build of v3.44.0, and it computes checksums correctly. The Windows (amd64) build of the previous version on Winget (v3.43.2) also works fine.

### Version

v3.44.0

### Operating system

Windows 11 (amd64)

### Example Taskfile

```YAML
# https://taskfile.dev

version: "3"

tasks:
  default:
    sources:
      - input.txt
    cmds:
      - echo input.txt has changed
```

A reproduction is also available at https://github.com/pastelmind/go-task-bug-repro
