### ISSUE TITLE
sources option for deps tasks maybe w/ bug

### ISSUE THREAD

**Issue by frederikhors** [go-task/task#233]
If I have a Taskfile.yml like this:

```yml
version: "2"

tasks:
  start:
    deps: [server, assets]

  assets:
    sources:
      - assets/**/*.scss
    dir: assets
    cmds:
      - npm run sass

  server:
    sources:
      - "**/*.go"
    cmds:
      - go run ./cmd/app
```

I expect that if I update a `*.go` file it restart just the `server` task.

Now it relaunch both.

Am I wrong?
