### ISSUE TITLE
Variable precedence confusion

### ISSUE THREAD

**Issue by crewjam** [go-task/task#234]
Task version: 2.6.0 / darwin

The documentation states:

```
When doing interpolation of variables, Task will look for the below. They are listed below in order of importance (e.g. most important first):

Variables declared locally in the task
Variables given while calling a task from another. (See Calling another task above)
Variables declared in the vars: option in the Taskfile
Variables available in the Taskvars.yml file
Environment variables
```

So I would expect the following task file to emit "Howdy", but instead it emits "Hello"

```
version: '2'

tasks:
  print-greeting:
    cmds:
      - echo "{{.GREETING}}"
    vars:
      GREETING: Hello

  print-howdy:
    cmds:
      - task: print-greeting
        vars:
          GREETING: howdy
```

```
$ task print-howdy
echo "Hello"
Hello
```

```
task print-greeting
echo "Hello"
Hello
```

I'm not sure if this is a bug, that the docs are incorrect, or if I'm just confused.

As a side note, it seems that providing values on the command line causes a panic:

```
$ task GREETING=foo print-howdy
panic: assignment to entry in nil map

goroutine 1 [running]:
main.main()
	/home/travis/gopath/src/github.com/go-task/task/cmd/task/task.go:141 +0xa0b
```

**Comment by crewjam** [comment]
So re-reading the docs, the phrase "Variables declared locally in the task" was confusing, to me anyway. Would it be more clear to say "Variables assigned in the task definition" ?

**Comment by andreynering** [comment]
Hi @crewjam, thanks for opening this issue!

The panic bug was fixed here: 955359b073bfb1f6fb80e2bd9fb06debeb4242c0.

About your documentation question: I understand that Task is working correctly here, and documentation is correct, but indeed it was a bit confusing. I took your suggestion here: e414c1f7b053af03be956b4775e1cf0c2ec123d7.

The reason the precedence is as is, is to allow the task to work with the passed value, for example having a default:

```yaml
version: '2'

tasks:
 default:
   cmds:
     - echo "{{.MSG}}"
   vars:
     MSG: '{{.MSG | default "Hi!"}}'
```
