### ISSUE TITLE
Add interactive input system (feature++ awesomeness++++)

### ISSUE THREAD

**Issue by JulienBreux** [go-task/task#235]
Hi awesome team!

# Request

Possibility to declare interactive inputs. Yeah budy! No less no more! #humor

# Simple example

## File: `Taskfile.yaml`

```yaml
version: "2"

task:
  aTaskWithInput:
    inputs:
      - foo
      - bar
      - baz
```

## How to use?

```shell
$ task aTaskWithInput
$ foo
$ <input>
$ bar
$ <input>
$ baz
$ <input>
```

# Advanced example

## File: `Taskfile.yaml`

```yaml
version: "2"

task:
  aTaskWithInput:
    inputs:
      foo:
        required: true
      bar:
        default: "🍻"
        desc: "Do you love beer?"
      baz:
        validator: "([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))"
```

## How to use?

```shell
$ task aTaskWithInput
$ foo (Is required)
$ <input>
$ Do you love beer? (default: 🍻)
$ <input>
$ baz (must validate: "([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))")
$ <input>
```

# Feedback need!

👍 OMG! I want this now!
😕 I don't know guy, it's cool but I can leave without!
👎 Please... I've a lot of work!

# Implem' status
1. Fri 9 Aug: Started (https://github.com/JulienBreux/task/tree/features/inputs)
