### ISSUE TITLE
perhaps the checksum should consider the generated files too?

### ISSUE THREAD

**Issue by crewjam** [go-task/task#238]
It appears that the checksum method uses on the source files to determine if a task should run, but perhaps the generated files should be included.

Example:

Taskfile.yml:

```
version: '2'

tasks:
  thing:
    sources: ['foo']
    generates: ['thing']
    method: 'checksum'
    cmds:
    - cat foo > thing
```

```
$ cat test.sh
#!/bin/bash -ex
rm -rf thing .task
task thing
[ -e thing ]

rm thing
task thing
[ -e thing ]  # thing should exist

$ ./test.sh
+ rm -rf thing .task
+ task thing
cat foo > thing
+ '[' -e thing ']'
+ rm thing
+ task thing
task: Task "thing" is up to date
+ '[' -e thing ']'
```

I would rather like for *thing* to be regenerated if it has changed (or perhaps it would be sufficient to regenerate when it is deleted.
