### ISSUE TITLE
Validate variable via preconditions

### ISSUE THREAD

**Issue by juelsn** [go-task/task#241]
- Task version:  2.6.0
- OS: Windows execution via Git Bash
- Example Taskfile:

```
version: '2'

vars:
  VAR: '{{.VAR}}'

tasks:
  echo:
     preconditions:
      - sh: "[ -v '{{.VAR}}' ] || exit 1 "
        msg: "Variable {{.VAR}} is not set"
     cmds:
      - echo {{.VAR}}

```

Execution: 
$ task VAR=test echo
task: Variable $VAR is not set
task: precondition not met

Could you please help me why the check whether the VAR variable is set is not working?

**Comment by andreynering** [comment]
Hi @juelsn,

I did some testing and I think the problem is a bug with your shell script, which was always returning a non-zero status.

This seems to work for me:

```yaml
version: '2'

tasks:
  echo:
    cmds:
      - echo '{{.VAR}}'
    preconditions:
      - sh: "[ '{{.VAR}}' != '<no value>' ]"
        msg: "Variable .VAR is not set"
```

Let me know if you have further questions.
