### ISSUE TITLE
Incompatible types for comparison (boolean) #bug

### ISSUE THREAD

**Issue by JulienBreux** [go-task/task#242]
## 🤓 Context

- Task version: **2.6.0**
- OS: **Mac OS, 10.14.6 (18G87)**
- `Taskfile.yml`
```yml
version: '2'

vars:
  BOOL_VAR: true

tasks:
  test:
    cmds:
      - echo "{{ if eq .BOOL_VAR true }}TRUE{{ end }}" 
```

## ❌ Error

```shell
template: :x:y: executing "" at <eq .BOOL_VAR true>: error calling eq: incompatible types for comparison
```

## 🔗 Maybe linked
- https://github.com/go-task/task/issues/140
