### ISSUE TITLE
Add interpreted go code as an alternative to shell

### ISSUE THREAD

**Issue by ddtmachado** [go-task/task#243]
**This is a feature request**

Add integration with [Yaegi](https://github.com/containous/yaegi) to support interpreted go code on variables / environments and commands.

```
version: '2'

# Could require custom configuration for the interpreter
go:
  import:
    - "fmt"
    - "os"

env:
  MY_ENV:
    go: fmt.Println("Hello")

tasks:
  my-go-task:
    cmds:
      - go: |
        fmt.Println("MY_ENV:", os.Getenv("MY_ENV"))
```
I love the idea as it would open so many possibilities for complex scenarios like you could just import your packages and use your API to write or assist in tasks, without having to rely on command binaries.

But I may be completely off and this might not be feasible / doable on Task.dev, just let me know :)

**Comment by andreynering** [comment]
Hi @ddtmachado, and thank for opening this issue!

FYI: there was some discussion already about allowing plugging more interpreters into Task: https://github.com/go-task/task/issues/195#issuecomment-497140838.

A couple of comments on this proposal:

First of all, while Task is written in Go and it's more popular between Go devs, it's also used on other contexts. For example, it's also used for generic devops stuff (building Docker images, etc), and I've seen it being used on other languages projects (Python, etc). That said, why allow specifically Go but not, say, Python, Ruby, Lua or other languages with interpreters available in Go?

That said, the reason we use a [Shell interpreter](https://github.com/mvdan/sh) is to normalize the behavior between different operation systems (most notably Windows, which doesn't come with a Posix-like shell). Ideally, we wouldn't have any other interpreters shipped with Task since can you *already* can run other languages by running `go run script.go`, `python script.py`, `ruby script.rb`, etc. You just can't use Task templating features with them just yet.

So, the best proposal so far IMHO is @stephenprater's one [here](https://github.com/go-task/task/issues/195#issuecomment-502880603) to have something like this:

```yaml
interpreters:
  python: /usr/bin/env python
  ruby: bundle exec ruby
```

This way people would be able to plug whatever language they want into Task (but with the con of requiring it to be installed into the system).
