### ISSUE TITLE
does --watch sources support docker?

### ISSUE THREAD

**Issue by ItsLeeOwen** [go-task/task#244]
When running task --watch with `sources` in Taskfile.yml, I encounter the following err: `task: Failed to run task "api": context canceled` within the docker container.

I do not encounter this when running directly on host machine, which is a mac, or when running w/out `sources` defined in Taskfile.yml.

Dockerfile
```
FROM golang:1.12.9
...
ENV GO111MODULE=off
ENV BINDIR=/bin
RUN curl -sL https://taskfile.dev/install.sh | sh

CMD task api -w
```

Taskfile.yml
```
tasks:
  api:
    desc: build & run api service
    cmds:
      - go build -v -i -o /tmp/api -tags=local ./cmd/api
      - /tmp/api
    sources:
      - ./v2/pkg/**/*.go
```
