### ISSUE TITLE
Make task name available to the commands

### ISSUE THREAD

**Issue by marco-m** [go-task/task#252]
The use-case is to reduce as much as possible the boilerplate one is obliged to write. This allows also to reduce repetitions -> less bugs.

Consider having multiple tasks, all very similar one to the other, that change mostly in the target name. For example we have 3 tasks `prog1`, `prog2`, `prog3`:

```
tasks:
  prog1:
    cmds:
      - go build ./prog1
      - ... prog1
  prog2:
    cmds: 
      - go build ./prog2
      - ... prog2
  prog3:
    cmds: 
      - go build ./prog3
      - ... prog3
```

If the task name was available as a special template variable `{{task}}` (in the same spirit of `{{exeExt}}`, but dynamic), then one could rewrite the example above to something like:

```
tasks:
  prog1:
    cmds:
      - go build ./{{task}}
      - ... {{task}}
  prog2:
    cmds: 
      - go build ./{{task}}
      - ... {{task}}
  prog3:
    cmds: 
      - go build ./{{task}}
      - ... {{task}}
```

What do you think?

**Comment by andreynering** [comment]
It probably be easier to have a `.TASK` variable than have a `task` template function (since the return will be dynamic).

I think is easy enough to be worth the effort. 👍

**Comment by andreynering** [comment]
This is now implemented in the `v3` branch.

See 7373639f57e5e41d371268d75bd17fa83e711a08.

**Comment by marco-m** [comment]
Thanks @andreynering ! :-)

**Comment by marco-m** [comment]
What I especially like is that this opens the door to YAML anchors. I tested the below example and it works:

```yaml
# YAML anchor, see for example: https://learnxinyminutes.com/docs/yaml/
build: &build
  silent: true
  cmds:
    - go build {{.TASK}}

tasks:
  default:
    deps: [prog1, prog2, prog3]
  prog1:
    *build
  prog2:
    *build
  prog3:
    *build
```

@andreynering do you think it would make sense to add a similar example to the documentation? If yes, let me know, I will create a PR. I think that a lot of people who use YAML do not know about anchors and merges.
