### ISSUE TITLE
Change Go template behavior to output "" instead of "<no value>" when variable is unset

### ISSUE THREAD

**Issue by Ilyes512** [go-task/task#254]
When I use the fallowing `Taskfile.yml`:

```
version: "2"

tasks:
  example:
    cmds:
      - task: "template"
        vars:
          FOOBAR: "{{.FOO}}"

  template:
    silent: true
    cmds:
      - echo "{{.FOOBAR}}"
```

And run the fallowing task command: `$ task example FOO="Hello World"` I get the fallowing result: `Hello World`. But when I don't provide the `FOO` variable and execute this instead `$ task example` I expect to see no output (or a newline), except I get the fallowing output: `<no value>`.

I know that gotemplate can handle non-existent variables three ways. Here an excerpt:

```
"missingkey=default" or "missingkey=invalid"
	The default behavior: Do nothing and continue execution.
	If printed, the result of the index operation is the string
	"<no value>".
"missingkey=zero"
	The operation returns the zero value for the map type's element.
"missingkey=error"
	Execution stops immediately with an error.
```

At the moment it using the `default`. I think it would be nice to set it to `zero` instead? Link to [godoc Template.Option](https://golang.org/pkg/text/template/#Template.Option).

Task version: 2.7.0
OS: Macos 10.14.6

Tap @blacktoko
