### ISSUE TITLE
I want to set default current working directory in Taskfile.yml.

### ISSUE THREAD

**Issue by mitsuru793** [go-task/task#255]
My enviroment
```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G87
```

task version: 2.7.0

Please tell me the following.

I want to set default current working directory in Taskfile.yml.
The yml file is not on pwd, but on anthoer path.

```yaml
# https://taskfile.dev

version: '2'

tasks:
  hi:
    cmds:
      - pwd

```

```
❯ command task --taskfile a/Taskfile.yml hi
pwd
/Users/mitsuru/tmp/2019-10-12_01-11-51_go-task-dir/a
```

Expected
```
/Users/mitsuru/tmp/2019-10-12_01-11-51_go-task-dir
```

I found option --dir, but this couldn't be used with --taskfile.

```
❯ command task --taskfile a/Taskfile.yml --dir $(pwd)
task: You can't set both --dir and --taskfile
```

How do I change default pwd in Taskfile.yml?

I know dir property, but I can't use it to set it as pwd.
I must write 'deps' or 'dir' each 'tasks'.
I want to write easily. I want to use dir property as global.

[Working directory for deps and subtasks · Issue \#174 · go\-task/task](https://github.com/go-task/task/issues/174)
```yaml
# https://taskfile.dev

version: '2'

tasks:
  hi:
    dir: ~/project
    cmds:
      - pwd
  something:
    deps:
      - task: hi

```
