### ISSUE TITLE
Allow task cmds to use updated Taskvars

### ISSUE THREAD

**Issue by radTuti** [go-task/task#256]
I have a task that call a couple of other reusable tasks but I noticed that if a previous task updated the Taskvars.yml, the next tasks do not pick it up.

Example

```yml
version: '2'

tasks:
  main:
    cmds:
      - task: write-to-taskvars
      - task: use-updated-taskvars
      - task: :external-ref:do-something
```

With the example Taskfile above, the content written to `Taskvars.yml` is not visible to `use-updated-taskvars` and `:external-ref:do-something`

Alternatively I tried declaring the vars in `main` task like this:

```yml
version: '2'

tasks:
  main:
    cmds:
      - task: use-updated-taskvars
      - task: :external-ref:do-something
    vars:
      FIRST_VAR: hello
```
For the tasks `use-updated-taskvars` and `:external-ref:do-something`, `FIRST_VAR` still resolves to `<no value>` _i reckon this part may be related to_ #84 so i decided to abandon that for something else

Additionally I tried making `write-to-taskvars` a dependency for `main` assuming it will pick up the updated Taskvars (_as shown below_) but that did not work

```yml
version: '2'

tasks:
  main:
    deps: [write-to-taskvars]
    cmds:
      - task: use-updated-taskvars
      - task: :external-ref:do-something
```

Currently using a workaround of calling the tasks separately in command line i.e.
```sh
task write-to-taskvars
task main
```

Supporting Info:
- Task version: 2.7.0
- OS: linux ubutu 18.04
