### ISSUE TITLE
feature: support interpolation on other properties

### ISSUE THREAD

**Issue by automaticgiant** [go-task/task#26]
example:
```yaml
dep-shfmt:
  generates:
    - {{GOPATH}}/bin/shfmt
  cmds:
    - go get github.com/mvdan/sh/cmd/shfmt
```
