### ISSUE TITLE
Task identifier shorthand notation / aliases

### ISSUE THREAD

**Issue by aegershman** [go-task/task#268]
In order to allow shorthand notation for tasks, consider allowing a task to be referenced by multiple values. For example, and equivalent in `shell` would be...

```sh
#!/usr/bin/env bash

case "$1" in
dt | do | do-thing | do-the-thing )
  ...
;;
```

perhaps in a Taskfile.yml it _could_ be...

```yml
tasks:
  do-thing:
    cmds:
      - ...
    aliases:
      - dt
      - do
      - do-the-thing
```

Just an idea, just putting it out there. Feel free to close whenever, etc. Thanks for your time 👍

**Comment by andreynering** [comment]
Hi @aegershman,

That's kinda already possible, just more verbose:

```yaml
version: 2

tasks:
  do-thing:
    cmds:
      - ...

 dt:
    cmds:
      - task: do-thing

 do:
    cmds:
      - task: do-thing

 do-the-thing:
    cmds:
      - task: do-thing
```

I liked your idea though, and it's probably easy to implement.
