### ISSUE TITLE
executable file not found in $PATH (windows)

### ISSUE THREAD

**Issue by ubermanu** [go-task/task#272]
Hello,

When running a task on windows, it can't find the executable of basic sh commands

- Task version: 2.7.1
- Windows 10
- Installed using scoop

Example Taskfile.yml

```
version: '2'

tasks:
  default:
    cmds:
      - touch test.txt
```

Running default task it throws an error:

```
rm test.txt
"rm": executable file not found in $PATH
task: Failed to run task "default": exit status 127
```
Any idea?
