### ISSUE TITLE
Having preconditions without fail

### ISSUE THREAD

**Issue by soullivaneuh** [go-task/task#275]
In order to make a project dependencies update tools, I'm interested by the  `preconditions` options.

It allow me to run the different dependencies managers if the condition are met:

```yaml
version: '2'

silent: true

tasks:
  default:
    deps:
      - composer
      - npm

  composer:
    preconditions:
      - test -f composer.lock
    cmds:
      - composer update

  npm:
    preconditions:
      - test -f package-lock.json
    cmds:
      - npm update
```

But the way this option is working does not fit my needs. It fail immediately if one of the task as unmet condition:

```
❯ task
task: `test -f package-lock.json` failed
task: `test -f composer.lock` failed
task: precondition not met
❯ touch composer.lock
❯ task
task: `test -f package-lock.json` failed
task: precondition not met
```

I didn't find any option to solve this issue, so I guess it was designed for.

Would you consider an evolution about this?

Regards

**Comment by soullivaneuh** [comment]
I found a workaround using `ignore_error`:

```yaml
composer:
  ignore_error: true
  cmds:
    - test -f composer.lock && composer update

npm:
  ignore_error: true
  cmds:
    - test -f package-lock.json && npm update
```

But this is not ideal, because I won't have any feedback if the task really fails.
