### ISSUE TITLE
desc doesnt seem to support templatization

### ISSUE THREAD

**Issue by mxrss** [go-task/task#276]
If relevant, include the following information:
- Task version: Task version: 2.8.0
- OS: darwin
- Example Taskfile showing the issue

```

version: '2'

vars:
  Repo: blah
  Tag: confd
  Version: v0.16.0
  FullName: "{{ .Repo }}/{{ .Tag }}:{{ .Version }}"

tasks:
  container:build:
    desc: |
     This will build "{{ OS }}"
    cmds:
      - docker build . -t "{{ .FullName }}"
    silent: true

```

Variable interpolation works well, but it seems that desc does not support auto generating content. I am looking for this to try to make my tasks a little more generic.. 

{{ OS }} or other golang templates should be executed for desc (Description).
