### ISSUE TITLE
Task is not honouring the dir is when call go dep in a Taskfile.yml

### ISSUE THREAD

**Issue by kevinneufeld** [go-task/task#278]
### System and Task version information:
- Task version: `2.8.0`
- System-Version: `macOS 10.15.1 (19B88)`
   Kernel-Version: `Darwin 19.0.0`

## Description:
Migrated a make file to Taskfile to execute Terratest, but Task fails to download vendors with `dep ensure`; dep seems to think it is in the root directory with Taskfile, not honouring the `dir` flag of a `cd` to temp `.gopath/src/go-task-example` folder.

To reproduce the issue I have created a sample project [go-task-example](https://github.com/kevinneufeld/go-task-example) 

Steps from `test/src`:
- `make test` &  `make clean` 
- `task test` & `task clean`

The MakeFile:
```make
PACKAGE := go-task-example
GOEXE 	?= $(which go)
GOPATH  := $(CURDIR)/.gopath
GOBIN   := $(GOPATH)/bin
BASE    := $(GOPATH)/src/$(PACKAGE)
##PATH 	= $(PATH):$(GOBIN)

export TF_DATA_DIR ?= $(CURDIR)/.terraform
export TF_CLI_ARGS_init ?= -get-plugins=true
export GOPATH

.PHONY: all
## Default target
all: test

ifneq (,$(wildcard /sbin/apk))
## Install go, if not installed
$(GOEXE):
	apk add --update go
endif

ifneq ($(OS),Windows_NT)
## Install all `dep`, if not installed
$(GOBIN)/dep:
	@mkdir -p $(GOBIN)
	@curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
endif

## Prepare the GOPATH
$(BASE): $(GOEXE)
	@mkdir -p $(dir $@)
	@ln -sf $(CURDIR) $@
## init and download vendor dependencies to vendor/
base-vendor-init: $(BASE) $(GOBIN)/dep
	cd $(BASE) && dep init

## Download vendor dependencies to vendor/
$(BASE)/vendor: $(BASE) $(GOBIN)/dep
	cd $(BASE) && dep ensure

.PHONY : init
## Initialize tests
init: $(BASE)/vendor

.PHONY : test
## Run tests
test: init
	cd $(BASE) && go test -v -timeout 30m -run TestExamplesComplete

.PHONY : clean
## Clean up files
clean:
	rm -rf .gopath/ vendor/ $(TF_DATA_DIR) terraform.tfplan ../../examples/complete/terraform.tfstate ../../examples/complete/terraform.tfstate.backup
```

The Taskfile.yml
```yml
version: "2"

vars:
  PACKAGE: go-task-example
  CURDIR:
    sh: echo "$(PWD)"
  GOPATH_VAR:
    sh: echo "$(PWD)/.gopath"
  GOEXE:
    sh: which go
  GOBIN: "{{.GOPATH_VAR}}/bin"
  BASE: "{{.GOPATH_VAR}}/src/{{.PACKAGE}}"

env:
  TF_DATA_DIR: "./.terraform"
  TF_CLI_ARGS_init: "-get-plugins=true"
  GOBIN: "{{.GOBIN}}"
  GOPATH: "{{.GOPATH_VAR}}"
  PATH:
    sh: echo "{{.GOBIN}}:$PATH"

tasks:
  go-exe:
    desc: Is go installed
    cmds:
      - |
        echo "You need to install GO"
    status:
      - test -f {{.GOEXE}}

  go-bin-dep:
    desc: Download and install Golang Dep
    cmds:
      - mkdir -p {{.GOBIN}}
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    status:
      - test -f .gopath/bin/dep{{exeExt}}

  base:
    desc: "Create a symlink to of the current ./test/src to {{.BASE}}"
    deps: [go-exe]
    cmds:
      - |
        mkdir -p {{.GOPATH_VAR}}/src
        ln -sf {{.CURDIR}} {{.BASE}}
    status:
      - test -d "{{.BASE}}"

  base-vendor-init:
    desc: Initialize Dep to create and download Terratest project dependecies of Gopkg.toml does not exists
    dir: "{{.BASE}}"
    deps: [go-bin-dep]
    cmds:
      - dep init
    status:
      - test -f "{{.BASE}}/Gopkg.toml"

  base-vendor:
    desc: Dep esure, downloads all require go dependecies
    deps: [base, go-bin-dep]
    dir: "{{.BASE}}"
    cmds:
      - |
        echo ""
        export PATH=$GOBIN:$PATH
        echo "PATH='$PATH'"
        echo ""
        export GOPATH={{.GOPATH_VAR}}
        echo "GOPATH='$GOPATH'"
        echo ""
        echo "PWD='$PWD'"
        echo ""
        #cd {{.BASE}}
        dep ensure

  init:
    desc: Initialize terratest project environment
    deps: [base-vendor]

  test:
    desc: Run tests
    deps: [init]
    dir: .gopath/src/terraform-windows-application-cluster
    cmds:
      - go test -v -timeout 30m -run TestExamplesComplete

  clean:
    desc: Cleans up all files and foders inorder to run terratest
    cmds:
      - "rm -rf ./.gopath/ ./vendor/ ./.terraform terraform.tfplan ../../examples/complete/terraform.tfstate ../../examples/complete/terraform.tfstate.backup"
```

## Task output:
```Shell
task test
mkdir -p /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin
task: Task "go-exe" is up to date
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
mkdir -p /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src
ln -sf /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src/go-task-example

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5230  100  5230    0     0   100k      0 --:--:-- --:--:-- --:--:--  100k
ARCH = amd64
OS = darwin
Will install into /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.4
Fetching https://github.com/golang/dep/releases/tag/v0.5.4..
Fetching https://github.com/golang/dep/releases/download/v0.5.4/dep-darwin-amd64..
Setting executable permissions.
Moving executable to /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin/dep
echo ""
export PATH=$GOBIN:$PATH
echo "PATH='$PATH'"
echo ""
export GOPATH=/Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath
echo "GOPATH='$GOPATH'"
echo ""
echo "PWD='$PWD'"
echo ""
#cd /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src/go-task-example
dep ensure


PATH='/Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin:/opt/chefdk/bin:/Users/kneufeld/.chefdk/gem/ruby/2.6.0/bin:/opt/chefdk/embedded/bin:/opt/chefdk/bin:/Users/kneufeld/.chefdk/gem/ruby/2.6.0/bin:/opt/chefdk/embedded/bin:/opt/chefdk/embedded/bin:/usr/local/bin/pwsh:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/chefdk/bin:/Users/kneufeld/.chefdk/gem/ruby/2.6.0/bin:/opt/chefdk/embedded/bin:/usr/local/bin/pwsh:/Users/kneufeld/Documents/Development/go-workspace/bin:/usr/local/opt/go/libexec/bin:/opt/chefdk/gitbin:/Users/kneufeld/Documents/Development/go-workspace/bin:/usr/local/opt/go/libexec/bin:/opt/chefdk/gitbin:/opt/chefdk/gitbin'

GOPATH='/Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath'

PWD='/Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src/go-task-example'

/Users/kneufeld/Documents/Development/terraform/go-task-example/test/src is not within a known GOPATH/src
task: Failed to run task "base-vendor": exit status 1
```

## MAKE output:
```shell
make test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5230  100  5230    0     0  83015      0 --:--:-- --:--:-- --:--:-- 83015
ARCH = amd64
OS = darwin
Will install into /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.4
Fetching https://github.com/golang/dep/releases/tag/v0.5.4..
Fetching https://github.com/golang/dep/releases/download/v0.5.4/dep-darwin-amd64..
Setting executable permissions.
Moving executable to /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/bin/dep
cd /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src/go-task-example && dep ensure
cd /Users/kneufeld/Documents/Development/terraform/go-task-example/test/src/.gopath/src/go-task-example && go test -v -timeout 30m -run TestExamplesComplete
=== RUN   TestExamplesComplete
=== PAUSE TestExamplesComplete
=== CONT  TestExamplesComplete
TestExamplesComplete 2019-12-16T11:23:29-08:00 retry.go:72: terraform [init -upgrade=true]
TestExamplesComplete 2019-12-16T11:23:29-08:00 command.go:87: Running command terraform with args [init -upgrade=true]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Upgrading modules...
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: - label1 in ../..
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Initializing the backend...
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Terraform has been successfully initialized!
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: You may now begin working with Terraform. Try running "terraform plan" to see
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: any changes that are required for your infrastructure. All Terraform commands
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: should now work.
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: If you ever set or change modules or backend configuration for Terraform,
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: rerun this command to reinitialize your working directory. If you forget, other
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: commands will detect it and remind you to do so if necessary.
TestExamplesComplete 2019-12-16T11:23:30-08:00 retry.go:72: terraform [get -update]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:87: Running command terraform with args [get -update]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: - label1 in ../..
TestExamplesComplete 2019-12-16T11:23:30-08:00 retry.go:72: terraform [apply -input=false -lock=false -auto-approve]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:87: Running command terraform with args [apply -input=false -lock=false -auto-approve]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Outputs:
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1 = {
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "attributes" = "1-2-3"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "delimiter" = "-"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "id" = "namespace-stage-name-1-2-3"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "name" = "name"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "namespace" = "namespace"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "stage" = "stage"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: }
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_attributes = 1-2-3
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_id = namespace-stage-name-1-2-3
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_name = name
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_namespace = namespace
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_stage = stage
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: label1_tags = {
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "Key" = "Value"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "Name" = "namespace-stage-name-1-2-3"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "Namespace" = "namespace"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158:   "Stage" = "stage"
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: }
TestExamplesComplete 2019-12-16T11:23:30-08:00 retry.go:72: terraform [output -no-color -json label1]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:87: Running command terraform with args [output -no-color -json label1]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: {"attributes":"1-2-3","delimiter":"-","id":"namespace-stage-name-1-2-3","name":"name","namespace":"namespace","stage":"stage"}
TestExamplesComplete 2019-12-16T11:23:30-08:00 retry.go:72: terraform [destroy -auto-approve -input=false -lock=false]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:87: Running command terraform with args [destroy -auto-approve -input=false -lock=false]
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: 
TestExamplesComplete 2019-12-16T11:23:30-08:00 command.go:158: Destroy complete! Resources: 0 destroyed.
--- PASS: TestExamplesComplete (0.81s)
PASS
ok      go-task-example 0.914s
```

**Comment by andreynering** [comment]
Hi @kevinneufeld, thanks for opening this issue!

> To reproduce the issue I have created a sample project [go-task-example](https://github.com/kevinneufeld/go-task-example)

This repository is empty.

**Comment by kevinneufeld** [comment]
Apologies thought I did. It is there now.

**Comment by 2ffs2nns** [comment]
for a project I'm working on, the `dir:` directive plus a `cd {{.DIR}} &&` is required to get it to work when called from a `included` taskfile

ie
```
includes:
  project: ../Taskfile.yml
```
only way to get it to work when called as `task project:lint`

```
  lint:
    desc: 'lint tests'
    dir: my/dir
    cmds:
      - cd {{.DIR}} && terraform fmt -check -recursive
    silent: true
    vars:
      DIR: my/dir
```
