### ISSUE TITLE
Allow to reference abstract tasks in included Taskfiles

### ISSUE THREAD

**Issue by thomews** [go-task/task#279]
My use case is to reference generic global tasks definitions in different included common Taskfiles. As included Taskfiles can’t include other Taskfiles, it could be a solution to allow to reference abstract tasks in included Taskfiles instead. The abstract tasks could then be implementend in a global Taskfile which eventually would be included in the main Taskfile. 

Example: 

Main Taskfile:

````yaml

version: '2'

includes:

  # include some common stuff
  common: common-tasks.yml
  
  # include even more generic common stuff
  global: global-install-tasks.yml

tasks:

  main-task:
    cmds:
      - task: common:common-task

````

Taskfile: common-tasks.yml

````yaml

version: '2'

tasks:

  common-task:
    cmds:
      # call abstract task here
      - task: global:install

````

Taskfile: global-install-tasks.yml

````yaml

version: '2'

tasks:

  # implement abstract task here
  install:
    cmds:
      - echo "Performing global installation task"

````

As mentioned at the beginning I have multiple different variants of common-tasks.yml which all require the same global install task. Currently in need to copy and paste the same definition of the task "install" to every common tasks Taskfile. The concept of abstract tasks would avoid the need to redundantly define the same task again an again over multiple included Taskfiles.

**Comment by andreynering** [comment]
Hi @thomews,

You can call a global task by prefixing it with `:`. Example:

```yaml
# Taskfile to be included

version: '2'

tasks:
  something:
    cmds:
      # "install" is defined in the global Taskfile.yml
      - task: :install
```

Let me know if that works for you.
