### ISSUE TITLE
File globing not working anymore?

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#28]
Tasfile:

```yaml
create:
  cmds:
    - touch the-new-rpm.rpm

clean-rpm:
  deps:
    - create
  cmds:
    - rm *.rpm
```

Produces:

```bash
task clean-rpm
touch the-new-rpm.rpm
rm *.rpm
rm: cannot remove '*.rpm': No such file or directory
task: Failed to run task "clean-rpm": exit status 1
```

Does this not work anymore with the go native sh interpreter?

If so, it should probably documented somewhere.

**Comment by kevinburke** [comment]
I would add that Make also accepts wildcards in inputs in two forms - `*` and `?` - and losing those would disable useful classes of optimizations.

**Comment by andreynering** [comment]
Hi @zbindenren!

Are you using master or released version? Was that working before?

I just tried with current master and glob works, but gives the error if no file was found for that pattern.

Example: `rm *.txt` will works but fail if there's no `.txt` file.

I also tried on regular bash and the behavior is exactly the same, so I'd say that's expected?

---

@kevinburke You can open a new issue explaining in detail your proposal.

**Comment by zbindenren** [comment]
@andreynering I am using master.

```bash
[rz:~]↥ % go get -u -v github.com/go-task/task/cmd/task
github.com/go-task/task (download)



[rz:~]↥ 2s % cat Taskfile.yml
create:
  cmds:
    - touch the-new-rpm.rpm

clean-rpm:
  env:
    FILE: the-new-rpm.rpm
  deps:
    - create
  cmds:
    - ls ${FILE} && echo "file ${FILE} exists"
    - rm *.rpm


[rz:~]↥ % task clean-rpm
touch the-new-rpm.rpm
ls ${FILE} && echo "file ${FILE} exists"
the-new-rpm.rpm
file the-new-rpm.rpm exists
rm *.rpm
rm: cannot remove '*.rpm': No such file or directory
task: Failed to run task "clean-rpm": exit status 1

```

Can  you run the taskfile on a linux system?
```yaml
create:
  cmds:
    - touch the-new-rpm.rpm

clean-rpm:
  env:
    FILE: the-new-rpm.rpm
  deps:
    - create
  cmds:
    - ls ${FILE} && echo "file ${FILE} exists"
    - rm *.rpm
```
