### ISSUE TITLE
Running a bash script in Task in Gitbash on Windows causes unexpected error

### ISSUE THREAD

**Issue by nullorvoid** [go-task/task#280]
Hi,

I had some behavior I was not expecting using Task under Windows and git bash on a project that was originally on a Mac.

### System information
- Windows 10
- Task 2.8.0 (task_windows_amd64.zip extracted and added to PATH)

### Problem
I was expecting my .sh scripts to be able to run in the same way in Task or Git Bash but Task threw an error.

Example Task File
```
version: '2'

tasks:
  test:
    cmds:
      - ./test.sh
```

test.sh
```
#!/usr/bin/env bash

echo 'test'
```
Note: `#!/bin/bash` produced the same result

Executing from git bash `./test.sh` gives the output `test`

Executing from task `task test` gives the following error:
`task: Failed to run task "test": fork/exec D:\test\test.sh: %1 is not a valid Win32 application.`

### Workaround
The workaround I ended up with was to add `bash` to the command

Fixed Task File
```
version: '2'

tasks:
  test:
    cmds:
      - bash ./test.sh
```

Which then gives the correct output `test`.

Running the Task with just `./test.sh` works directly on a Mac but not under git bash on Windows. Is this a bug / limitation, or is there something I should have set up before?
