### ISSUE TITLE
Doesn't pass os signal to programs

### ISSUE THREAD

**Issue by kovetskiy** [go-task/task#288]
~There is a nasty bug: task doesn't pass signals to its children processes:~
```
version: '2'

tasks:
  a:
    cmds:
      - bash -c "trap 'echo EXIT' EXIT; sleep inf" 2>&1 | cat

```

~When I run `task a` and then hit `ctrl-c` my program (I actually have it in Go, but here bash does the same) I expect to see EXIT because my program should receive the same signal that was received by its parent (task), but it doesn't receive any signals in case when there is a pipe after program execution.~

FIXED: the same doesn't work in pure bash too
