### ISSUE TITLE
dependencies, file globbing, &c

### ISSUE THREAD

**Issue by kevinburke** [go-task/task#29]
One of the nice things about Makefiles is that it doesn't do unnecessary work. The way that you specify this is with target dependencies:

```make
public/index.html: sources/index.md
    markdown sources/index.md > public/index.html
```

If the mtime for index.md is newer than the mtime for index.html, Make runs the command. This is covered in the README for this project as far as I can tell.

A more useful property is, the files in directory X all depend on their equivalent in directory Y. For example, you have index.md, blog.md, about.md which all compile to their equivalents. If you were to do this:

```make
public/*.html: sources/*.md
    ...
```

That would work but it would recompile every Markdown file any time any file in sources/*.md updated. Instead what we want is to establish that 1:1 mapping, done this way:

```make
public/%.html: sources/%.md
	markdown $< > $@
```

**Comment by andreynering** [comment]
This is currently only partially supported.

[You can specify globbing in `sources` and `generates`][redo], but Task will rerun everything once any file change.

No way to do 1-to-1 file mapping yet.

[redo]: https://github.com/go-task/task#prevent-task-from-running-when-not-necessary

**Comment by smyrman** [comment]
In Makefiles, this feature is not _only_ to avoid necessary work, as it also allows templating tasks for use with different parameters.

E.g. if we where to produce a deb package for N binaries, it would be cool if there was a way to allow for templating / task reusability.

**Comment by smyrman** [comment]
Could a syntax like this work?
```yaml
template-task:
  args:
    - filename
  cmds:
    - markdown {{filename}}.md > {{filename}}.html
  sources:
    - {{filename}}.md
  generates:
    - {{filename}}.html
```

The template task may only be used in another task. E.g. like this:
```
using-template:
  cmds:
    - ^template-task filename=index
```

A more complex usage would want to call the template-task with either a list of input parameters, or maybe even somehow retrieve this list via a glob pattern!

**Comment by smyrman** [comment]
I guess the glob pattern _could_ be retrieved via a dynamic variable... `FILENAMES=$ls *.md | sed 's/\.md$//g'`. Of course, this might make it OS specific...

**Comment by smyrman** [comment]
Rather adding yet-another-keyword `args`, I guess we could also use the existing `vars`, the only difference being that vars might be set when running sub-tasks?

**Comment by andreynering** [comment]
@smyrman I liked the idea! Yes, I would use existing `vars` instead of `args`.

Could you please open another issue for task parameters?

**Comment by smyrman** [comment]
Done. Note that I might now be leaning towards adding args anyhow... Se #31 for why.

**Comment by andreynering** [comment]
@smyrman Thanks

**Comment by smyrman** [comment]
> That would work but it would recompile every Markdown file any time any file in sources/*.md updated. Instead what we want is to establish that 1:1 mapping, done this way:

```yaml
public/%.html: sources/%.md
	markdown $< > $@
```

I guess this is now possible via task parameters.
```yaml
build:
  deps:
    - cmd: tmpl/md2html:
      vars:
        NAME: index
    - cmd: tmpl/md2html:
      vars:
        NAME: about
    - cmd: tmpl/md2html:
      vars:
        NAME: blog

tmpl/md2html:
  cmds:
    - markdown sources/{{.NAME}}.md > public/{{.NAME}}.html
  sources:
    - sources/{{.NAME}}.md
  generates:
    - public/{{.NAME}}.html
```
