### ISSUE TITLE
Add global preconditions

### ISSUE THREAD

**Issue by tommyalatalo** [go-task/task#294]
It would be great to be able to set global preconditions to prevent running any tasks in a directory/repo if the precondition is not met. This would be a simple way to add a precondition to all tasks without having to add the same precondition to every task individually.

The use case for this is for example to enforce that a repository has been initialized somehow before allowing to run any other tasks, like setting up release targets for goreleaser or similar. In this example I would have the .goreleaser.yml contain a string like "INIT_PACKAGE" which should be replaced by the package name of the repository, and until that's done all tasks should fail (precondition greps for "INIT_PACKAGE"), and return the same message "This repository hasn't been initialized, please run 'task init'".

Obviously to be able to run the initial `task init` there needs to be a property to disable the global precondition for that specific task. So the Taskfile would end up something like this:

```
version: '2'

preconditions:
    - grep INIT_PACKAGE .goreleaser.yml
      msg: "this repository needs to be initialized, run 'task init' to continue"

tasks:
  build:
    desc: build go project
    cmds:
      - go build .
  
  init:
    desc: initalize repository
    cmds:
      - <do something>
    ignore_global_preconditions: yes
```

**Comment by andreynering** [comment]
Hi @tommyalatalo,

This seems like an useful feature request, but shouldn't be my priority for the near future, unless someone else decides to contribute with this.

**Comment by sylv-io** [comment]
Since #405 is a duplication, let me paste my workaround [[1](https://github.com/go-task/task/issues/405#issuecomment-935724197), [2](https://github.com/go-task/task/issues/405#issuecomment-935734215)] here too:

There is already a way to reuse preconditions by the use of YAML anchors:
```
tasks:

  task1:
    cmds:
      - "echo task1"
    preconditions:
      - &test-precondition
        sh: "[ 1 = 0 ]"
        msg: "One doesn't equal Zero, Halting"

  task2:
    cmds:
      - "echo task2"
    preconditions:
      - *test-precondition

  task3:
    cmds:
      - "echo task3"
    preconditions:
      - *test-precondition
 ```
However, the anchor have to be on the same YAML file.
Adding global preconditions would only reduce duplications, if they are used on multiple imported taskfiles.

Since we do not use strict YAML unmarshal, even this is possible:
```
preconditions:
  <<: &test-precondition
    sh: "[ 1 = 0 ]"
    msg: "One doesn't equal Zero, Halting"

tasks:

  task1:
    cmds:
      - "echo task1"
    preconditions:
      - *test-precondition

  task2:
    cmds:
      - "echo task2"
    preconditions:
      - *test-precondition

  task3:
    cmds:
      - "echo task3"
    preconditions:
      - *test-precondition
```

**Comment by altosys** [comment]
I'm aware of yaml anchors, but as you said yourself, it doesn't work across multiple taskfiles, and it requires a lot of duplication which is error prone.

**Comment by sylv-io** [comment]
> I'm aware of yaml anchors, but as you said yourself, it doesn't work across multiple taskfiles, and it requires a lot of duplication which is error prone.

sure, I understand. I prefer a proper solution for this issue, too. This is just a comment for anyone who is not aware of yaml anchors and are looking for a workaround solution.

**Comment by dark06** [comment]
I prefer to initially advocate for seeking a solution that doesn't rely on anchors.
If that's not possible, having a key to store anchors would be helpful to prevent syntax highlighting errors.

<img width="472" alt="image" src="https://github.com/go-task/task/assets/28400414/07115a84-b52d-4160-82c7-de8382269c6a">

**Comment by onedr0p** [comment]
I just came across a use-case that would have made my taskfiles so much more DRY, do not let the taskfile be run as root.

```yaml
preconditions
  - msg: must not be run as root
    sh: '[[ $LOGNAME != "root" ]]'
```

**Comment by firstmustburn** [comment]
I'll tack a comment onto this that if we're going to add `preconditions`, we should add `requires` as well.  I've got imported taskfiles that depend on global variables (from the importing taskfile), and I'd like to be able to ensure those are set at the taskfile level.  

If I can carve out a little time, I will try to make a PR for this, but I'm leaving a comment here for future me or in case someone else picks it up first.

Example use case:  
- `REMOTE_DOCKER_NAME_STUB` is common across many included taskfiles, so I want it to be defined at the top level.
- `REMOTE_DOCKER_IMAGE_NAME` is shared among tasks in *one* of the included taskfiles, so I want to define it once at the top of that taskfile.
- As a workaround, I can include `REMOTE_DOCKER_NAME_STUB` in the `requires` for each task, but this breaks the DRY.  If I change the way REMOTE_DOCKER_IMAGE_NAME is defined, I also have to go update all those tasks.

including file:
```yaml
vars:
  REMOTE_DOCKER_NAME_STUB: somerepo.example.com/argyle


includes:
  foo:
    taskfile: ./foo/Taskfile.yml
```

included file:
```yaml
vars: #alphabetical list
  REMOTE_DOCKER_IMAGE_NAME: "{{.REMOTE_DOCKER_NAME_STUB}}/myimagename:latest"

tasks:
  docker-build:
    desc: build the docker image
    requires:
      vars: [ REMOTE_DOCKER_IMAGE_NAME]
    cmds:
      - docker build -t "{{.REMOTE_DOCKER_IMAGE_NAME}}" ./src/
docker-push-remote:
    desc: push the pg-backup docker image to the 
    requires:
      vars: [ REMOTE_DOCKER_IMAGE_NAME]
    cmds:
      - docker push "{{.REMOTE_DOCKER_IMAGE_NAME}}"
```

desired included file:
```yaml
requires: [ REMOTE_DOCKER_NAME_STUB ]

vars: #alphabetical list
  REMOTE_DOCKER_IMAGE_NAME: "{{.REMOTE_DOCKER_NAME_STUB}}/myimagename:latest"

tasks:
  docker-build:
    desc: build the docker image
    requires:
      vars: [ REMOTE_DOCKER_IMAGE_NAME]
    cmds:
      - docker build -t "{{.REMOTE_DOCKER_IMAGE_NAME}}" ./src/
docker-push-remote:
    desc: push the pg-backup docker image to the 
    requires:
      vars: [ REMOTE_DOCKER_IMAGE_NAME]
    cmds:
      - docker push "{{.REMOTE_DOCKER_IMAGE_NAME}}"
```
