### ISSUE TITLE
How to use "&&" in templated commands

### ISSUE THREAD

**Issue by tommyalatalo** [go-task/task#297]
I'm trying to use commands from environment variables in conditional statements like in the simplified example below.

```
    env:
       CMD: echo three && echo four
    cmds:
      - echo one && echo two
      - >-
        {{ if true }}$CMD{{ end }}
```

The resulting output is 
```
one
two
three && echo four
```

The problem is that on the go-templated "&&" is not read as the shell "and" operator, but as more string arguments to the echo command. Is there some way to escape the "&&" to make this work? I really need to be able to chain commands this way. I'm not sure if this is a go-task issue or just general behavior of go-template.

**Comment by andreynering** [comment]
Hi @tommyalatalo,

By using `$CMD` instead of `{{.CMD}}` you're asking Bash to execute that env, and not using Task's templating. And executing that also doesn't work on pure Bash.

This does the trick:

```yaml
echo:
  env:
    CMD: echo three && echo four
  cmds:
    - echo one && echo two
    - '{{.CMD}}'
```
