### ISSUE TITLE
Dependencies are not run before all parts of a task description.

### ISSUE THREAD

**Issue by kevinkjt2000** [go-task/task#301]
Thanks for making such an easy to use task runner! This has become one of my new favorite tools to use. I spent some time today learning what order things are executed in, and found that dependencies are not always evaluated first.

Task 2.8.0

```yaml
version: "2"

output: prefixed

tasks:
  default:
    deps: ["dependency"]
    vars:
      something2:
        sh: "echo default var > messages.txt && sync"
    env:
      something:
        sh: "echo default env >> messages.txt && sync"
    cmds:
      - "echo default cmd >> messages.txt && sync"

  dependency:
    cmds:
      - "echo dep_cmd >> messages.txt && sync"
```

Monitor with `tail -F messages.txt` while running `task` over and over:
```
...
tail: messages.txt: file truncated
default var
default env
dep_cmd
default cmd
```

I was expecting (and I also realize that I would need to move the `>` to a different echo if this was the case):
```
...
tail: messages.txt: file truncated
dep_cmd
default var
default env
default cmd
```

This is especially important when using shell commands to read a value that can only be present after the dependency is finished. Mainly my use case is pulling information from Terraform state:
```yaml
vars:
  WEBSITE_BUCKET:
    sh: "terraform output website_bucket"
```
I can only use that after Terraform has deployed the S3 bucket to AWS.
