### ISSUE TITLE
Can you pass arguments to a task call

### ISSUE THREAD

**Issue by klauern** [go-task/task#304]
Is it possible to pass in and reference an argument that was passed-in for a task?

`task some-task <an argument passed-in>`

Where I could use `<an argument passed-in>` as a variable in a task definition?

```yaml
tasks:
  some-task:
    cmds:
    - sh: ./running-a-thing.sh {{.<an argument passed-in>}} # or however you could reference it.
```
