### ISSUE TITLE
Ability to forward command line arguments to task

### ISSUE THREAD

**Issue by mbertschler** [go-task/task#316]
I know there is a way to pass environment variables, but I would like to be able to pass arbitrary command line arguments to tasks. I imagine that it could work like this:

```yaml
version: '2'

tasks:
  list:
    cmds:
      - ls -l {{.Args}}
```

```bash
$ task list -a mydir
```

So that in the end the command `ls -l -a mydir` is executed. Is this something you would like to support?

**Comment by andreynering** [comment]
Hi @mbertschler,

If you take a look [at the documentation](https://taskfile.dev/#/usage?id=variables) you'll see that you can already set variables using the CLI, by using a syntax like:

```bash
task YOU_VAR=foobar your-task
```

Is that enough for your use case? If not, can you explain why?

**Comment by mbertschler** [comment]
Yes I have read the documentation on variables but I am talking about something else. An example usecase that I have right now is a webapp where I have a Javascript project in a subfolder. In order to not always `cd` in and out of the folder I would like to have a `yarn` task that can execute arbitrary yarn commands in this subfolder.

With a task like this
```yaml
  yarn:
    dir: web
    cmds:
      - yarn {{.ARGS}}
```
It currently needs to be called like this
```
task yarn ARGS="run myscript"
```
but I would prefer to just write the command like this for better usability:

```
task yarn run myscript
```

But I see now why task can't easily support that because it allows running multiple tasks in one call. What do you think about this?

**Comment by andreynering** [comment]
Hi @mbertschler,

The path I usually take is to declare your Yarn tasks into the Taskfile like this:

```yaml
version: '2'

tasks:
  myscript:
    dir: web
    cmds:
      - yarn run myscript
```

This way you'd get it even shorter:

```bash
task myscript
```

---

I know your proposal is valid, and it'd make some use cases easier, but I want to focus on other stuff at the moment.

I may back to this issue again in the future.

**Comment by mbertschler** [comment]
Okay I understand, for a small number of different commands this is feasible.
Thank you for this simple and fast tool 🙂

**Comment by talesmgodois** [comment]
I think this feature is very important. Is there someone working on it?

**Comment by vmaerten** [comment]
@talesmgodois 
You can already do it. ([docs](https://taskfile.dev/api/#special-variables))

```yml
version: 3

tasks:
  default:
    cmds:
      - echo "Args {{.CLI_ARGS}}"
```

and running : 
`task -- my_args`  will print you `Args my_args`
