### ISSUE TITLE
inherit vars from parent node

### ISSUE THREAD

**Issue by watano** [go-task/task#322]
```yaml
version: '3'

tasks:
  bakDir:
    cmds:
      - '{{.bakcmd}} --exclude-from=exclude_{{.name}}.txt {{.rootDir}} ./{{.name}}'
      - 'tar -zcf {{.name}}.tar.gz ./{{.name}}'
      - 'rm -rdf ./{{.name}}'
  myprojects:
    desc: backup {{.name}}
    vars: { rootDir: '../work/projects/myprojects/', name: 'myprojects' }
    cmds:
      - task: 'bakDir'
        vars: { rootDir: '{{.rootDir}}', name: '{{.name}}' }
```
In this case, task bakDir need two vars, but it can't inherit vars from task myprojects, so it need write a bad duplicate code like this: 
```yaml
vars: { rootDir: '{{.rootDir}}', name: '{{.name}}' }
```
If subtask vars can inherit from the parent task vars, it will have a clean code. the inherit list can like this `file vars -> task vars -> sub task vars`

**Comment by andreynering** [comment]
Hi @watano,

I think that this could cause some confusion. Task variables are supposed to be used only within the task itself.

We're going to do some improvements on v3 regarding variables, but I don't think this change will happen.

**Comment by watano** [comment]
I don't think it's confusing, it's like parsing the args for a cli program. it has this priority: environment variables -> configuration files -> command line parameters.
This feature simplifies the configuration file a lot, and although it adds some learning costs, I think it's worth it, and the task tool itself is for programmers or IT operations staff, who should be more familiar with this feature than confused.

**Comment by dolfelt** [comment]
@andreynering I think offering the option to pass all local vars down to a sub-task could be very useful for utility tasks.

```yaml
tasks:
  run:
    cmds:
      - task: build
        vars: { ACTION: do-work, HOST_IP: 127.0.0.1 }
  
  build:
    cmds:
      - task: template
        vars: { ACTION: "{{.ACTION}}" }
        inheritVars: true
  
  template:
    cmds:
      - echo "{{. | toJson}}" | dotemplate | {{.ACTION}}
```

This allows helper functions to be able to be arbitrarily customized from more than one layer away. Without the ability to inherit vars, the `HOST_IP` or any other custom var would be lost.
