### ISSUE TITLE
Question: dynamic var expansion?

### ISSUE THREAD

**Issue by chris-garrett** [go-task/task#323]
- Task version: 3 preview 3
- OS: macOS 10.15.3

content.txt
```
one two three
{{.A}} {{.B}} {{.C}}
```

Taskfile.yml
```
version: '3'


silent: true


tasks:

  expand1:
    cmds:
      - echo "{{.INPUT | replace "one" .A}}"
    vars:
      INPUT: |
        one two three
        {{.A}} {{.B}} {{.C}}
      A: aaa
      B: bbb
      C: ccc

  expand2:
    cmds:
      - echo "{{.CONTENT | replace "one" .A}}"
    vars:
      A: aaa
      B: bbb
      C: ccc
      CONTENT: 
        sh: cat ./content.txt
```

Is it possible to have CONTENT (dynamic var) be expanded like INPUT is?

**Comment by chris-garrett** [comment]
Actually, what I'm ultimately after is to pass a file through the go template parser using task vars/env as part of a build step.  

```
  make-version:
    sources:
      - src/version.template
    generates:
      - dist/version.json
```
