### ISSUE TITLE
Variables interpolation priority question

### ISSUE THREAD

**Issue by yaroslavbikov** [go-task/task#326]
Hey guys! I'm trying to understand the reason behind variables resolution priority and would be grateful if someone could give me some ideas.
In the example below I would intuitively expect that calling `t2` would result in output of `2`, but the resolution priority (as docs state) makes it `1`.
Could you think of a use case where the current resolution order makes sense? And as a consequence - in which cases would one declare vars at task level?
```
  t1:
    vars:
      V: 1
    cmds:
      - echo {{.V}}
  t2:
    cmds:
      - task: t1
        vars: {V: 2}
```

**Comment by andreynering** [comment]
Hi @yaroslavbikov,

For now, you could use `default` to accept an override while also falling back to a default value:

```yaml
vars:
  t1:
    vars:
      V: '{{default 1 .V}}'
    cmds:
      - echo {{.V}}
  t2:
    cmds:
      - task: t1
        vars: {V: 2}
```

The resolution order is something that was discussed before, but [although unlikely] it can be changed on v3.
