### ISSUE TITLE
Execute task dependencies sequentially

### ISSUE THREAD

**Issue by pztrn** [go-task/task#331]
I'm on macOS 10.14.6 and task 2.8.0.

I have a taskfile which installs gopherjs and golang version it requires:

```yaml
version: "2"

vars:
  GOPHERJS_GOLANG: "go1.12.16"
  GOPHERJS_GOLANG_ROOT: "{{.HOME}}/sdk/{{.GOPHERJS_GOLANG}}"
  GOPHERJS:
    sh: which gopherjs

tasks:
  prepare-gopherjs-go-step-1:
    desc: "Downloads and installs golang toolchain version suitable for gopherjs (step 1). WARNING: this is internal thing and SHOULD NOT be called manually!"
    cmds:
      - "{{.GO}} get golang.org/dl/{{.GOPHERJS_GOLANG}}"
      - "{{.GOPATH}}/bin/{{.GOPHERJS_GOLANG}} download"
    preconditions:
      - sh: test ! -f {{.GOPHERJS_GOLANG_ROOT}}/bin/go"
        msg: "{{.GOPHERJS_GOLANG}} installed"

  prepare-gopherjs-go-step-2:
    desc: "Downloads and installs golang toolchain version suitable for gopherjs (step 2). WARNING: this is internal thing and SHOULD NOT be called manually!"
    cmds:
      - "GOPATH={{.GOPHERJS_GOLANG_GOPATH}} {{.GOPHERJS_GOLANG_ROOT}}/bin/go get -u -v github.com/gopherjs/gopherjs"
    preconditions:
      - sh: test ! -f {{.GOPATH}}/bin/gopherjs
        msg: "GopherJS installed"

  prepare-gopherjs:
    desc: "Prepares gopherjs for using."
    deps: [prepare-gopherjs-go-step-1, prepare-gopherjs-go-step-2]
```

I was thinking that dependencies will be called sequentially, in that case step-1 will run before step-2, but for some reason I got followed output:

```
task: GopherJS installed
task: go1.12.16 installed
task: precondition not met
```

And, after couple of re-runs:

```
task: go1.12.16 installed
task: GopherJS installed
task: precondition not met
```

This punch me back to documentation, which states:

> If there is more than one dependency, they always run in parallel for better performance.

So I really have no ability to run them sequentially? Why? Can this mode be added?

**Comment by andreynering** [comment]
Hi @pztrn,

The reason why we don't have a flag for running deps sequentially is because you already can run tasks sequentially by moving it to `cmds:`:

```yaml
tasks:
  prepare-gopherjs:
    cmds:
      - task: prepare-gopherjs-go-step-1
      - task: prepare-gopherjs-go-step-2
```
