### ISSUE TITLE
v3: cleaning checksum for job that doesn't have them

### ISSUE THREAD

**Issue by kovetskiy** [go-task/task#333]
Hi, giving a try to v3:

```
version: '3'

tasks:
  a:
    cmds:
      - task: before_a
      - exit 1

  before_a:
    deps: [the_dep]
    cmds:
      - echo before a

  the_dep:
    cmds:
      - date > x.b
    generates:
      - '*.a'
    sources:
      - '*.b'
    method: checksum

```

Then run it like that:
```
task a -v
```
(verbose mode is required)

you will get `task: error cleaning status on error: remove .task/checksum/a: no such file or directory` which is odd because the task `a` doesn't use any checksum verifications.

**Comment by andreynering** [comment]
Hi @kovetskiy, thanks for reporting!

What happens is that in v3 `checksum` is now considered the default method. So, even with a Taskfile as simple as this it's already possible to reproduce:

```yaml
version: '3'

tasks:
  echo:
    - echo "Echo"
    - exit 1
```

I just fixed this problem in the v3 branch.
