### ISSUE TITLE
option to clear terminal in watch mode

### ISSUE THREAD

**Issue by jnoortheen** [go-task/task#335]
It will be very helpful to clear the console before every run when watch flag is active. Since running multiple commands pollute the space, it becomes hard to navigate and find the errors. 
Is it possible to have this option set inside yml file?

**Comment by andreynering** [comment]
Hi @jnoortheen, thanks for opening this issue!

I'm not sure how easy for hard this is, but I'll keep this issue open for discussion.

**Comment by jnoortheen** [comment]
I also don't have much knowledge working with terminal tools. But this seems redundant. For example the below command opens new window and exits with `ctrl+c` 
```
watch date
```

**Comment by NinoM4ster** [comment]
something like this seems to work alright for me:

```yaml
version: '3'

tasks:
  default:
    sources:
      - "SaveMe.txt"
    cmds:
      - clear
      - echo Your Command Here
```
`task -w`

https://user-images.githubusercontent.com/8485761/209571688-7ab49762-826c-454d-b8d9-afe2463b2fcc.mp4
