### ISSUE TITLE
v3: expansion doesn't work as expected

### ISSUE THREAD

**Issue by kovetskiy** [go-task/task#336]
I'm using latest version of v3 branch

Taskfile.yml
```
version: '3'

vars:
  root: 'x'
  exp: 'exp-{{.root}}'

tasks:
  test:
    desc: a
    cmds:
      - echo root is '{{.root}}'
      - echo but exp is '{{.exp}}'
```

Current output:
```
$ task test root=y
task: echo root is 'y'
root is y
task: echo but exp is 'exp-x'
but exp is exp-x

$ task root=y test
task: echo root is 'y'
root is y
task: echo but exp is 'exp-y'
but exp is exp-y
```

Expected: both variants should output the same — exp variable should be `exp-y` because `root` is `y`.
