### ISSUE TITLE
Add task pre and post operations (before, after)

### ISSUE THREAD

**Issue by fairbairn** [go-task/task#344]
Be great if there was a way to add post processing similar in concept to preconditions but a bit more flexible.

The goal is to be able to have pre- and post- operations surround a task sequence.
For example, the pre- would be the setup (much like a test runner), and the post- would be the cleanup.

It's conceivable it can be done with sequential tasks under cmds: , but it gets messy because of the added bash code to track exit codes, shove in variables, add ignore_errors (which you may or may not forget to add or remove at times), and test those to abort follow on tasks but not the cleanup task.

It would be cleaner to have a pre- and post- sequence that could surround the cmd, instead of writing nuance around cmd sequences or adding additional tasks.

Thinking something like...

```
task:
  example:
    before:
      - docker run -d --name server -p 8080:80 nginx
    cmds:
      - curl http://localhost:8080 | awk '{print}/error/{exit 1}'
      - echo "I may or may not get here"
    after:
      - docker rm server -f
```

To extend it further, you could conceivably have different flags that could determine which operations in after should/should not run depending on the eventual exit result (it could even be a number, or simply a success/failure) ...

```
after:
   - echo "Fires only if the cmds sequence failed"
   if_errors: true
   - echo "Fires if no error"
   if_errors: false
   - echo "Fires regardless"
   - echo "Send message to slack if we got a 25, as we know where that came from"
   if_error: 25
   
```
