### ISSUE TITLE
Completion file does not honor includes

### ISSUE THREAD

**Issue by ronvanderheijden** [go-task/task#346]
- Task version: 2
- OS: Mac (using zsh)

```yml
version: '2'

includes:
  docker: ./TaskfileDocker.yml
```

An example commands:
```bash
task docker:dev:build
```

But the regex `s/:/\\:/` only accepts `:` a single time.
