### ISSUE TITLE
More complex string manipulations in Taskfile.yml

### ISSUE THREAD

**Issue by huy-nguyen** [go-task/task#350]
I usually invoke an executable that takes a list of properties as argument:

```shell
my-commmand --properties PROPERTY_1:value-1,PROPERTY_2:value-2,PROPERTY_3:value-3
```

This is how I currently set up my Taskfile:

```yaml
version: "2"

vars:
  PROPERTY_1: value-1
  PROPERTY_2: value-2
  PROPERTY_3: value-3

tasks:
  my-task:
    cmds:
    - > 
      my-command
      --properties PROPERTY_1:{{.PROPERTY_1}},PROPERTY_2:{{.PROPERTY_2}},PROPERTY_3:{{.PROPERTY_3}}
```

This is difficult to read and the line with all the properties usually extends past the editor's right edge.
I don't know Go and I'm wondering if there's a way to simplify this setup. Is there a way to get the string:
```text
PROPERTY_1:value-1,PROPERTY_2:value-2,PROPERTY_3:value-3
```
from the mapping:
```yaml
  PROPERTY_1: value-1
  PROPERTY_2: value-2
  PROPERTY_3: value-3
```
either by using Task or Go's built-in functionality or by providing a user-written Go function? I've read through [Go's templating guide](https://golang.org/pkg/text/template/) but haven't found anything useful there.

If relevant, include the following information:
- Task version: 2.8.0
- OS: Mac 10.15.6
