### ISSUE TITLE
Diamond dependency executed multiple times

### ISSUE THREAD

**Issue by aidansteele** [go-task/task#355]
Hi,

If I have a task file like this:

```yaml
version: '2'

tasks:
  top:
    deps: [depA, depB]

  depA:
    deps: [depC]

  depB:
    deps: [depC]

  depC:
    cmds:
      - echo "hello world!"
```

And I execute the `top` task, it will end up echoing "hello world!" to the console twice. Would you consider addressing this as "out of scope" for `task`, or perhaps changing it to only run `depC` once might be backwards-incompatible? (Maybe users expect it to run twice)

The reason I ask is because I have a preference that `depC` only run once in this scenario. My imagination is lacking, but I can't imagine a scenario where you might actually want `depC` to run twice - but I won't discount the possibility.

I'd be happy to try attempt a PR to introduce functionality to only execute `depC` once, but I don't wish to waste your time with a PR that might not be helpful.

Thanks!
