### ISSUE TITLE
Respect ignore_error when calling another task from a command

### ISSUE THREAD

**Issue by shilangyu** [go-task/task#363]
- Task version: master
- OS: Linux

When calling `task other` with the following Taskfiles:

## this works, the error is ignored

```yaml
version: "3"

tasks:
  bad:
    cmds:
      - exit 1
  other:
    cmds:
      - cmd: task bad
        ignore_error: true
      - echo hello
```

## this does not work, nothing is printed

```yaml
version: "3"

tasks:
  bad:
    cmds:
      - exit 1
  other:
    cmds:
      - task: bad
        ignore_error: true
      - echo hello
```

**Comment by andreynering** [comment]
Hi @shilangyu, thanks for opening this issue!

This doesn't work because it was not originally intended to work like this. It may makes sense to respect that, though...

**Comment by marco-m** [comment]
@andreynering I stumbled upon this exact problem.
To me this is a bug, not an enhancement, for the following reason: adding ignore_error to a task has the effect that the task is _silently_ skipped and the user doesn't even understand what is going on :-)

**Comment by ivotron** [comment]
My 2c is that `ignore_error` should work the same way when invoking another task. In my case, the workaround I came up with is to create another task that includes `ignore_error: true` and add an `-ignore-error` prefix to its name, so:

```yaml
version: "3"

tasks:
  bad:
    cmds:
      - exit 1
  bad-ignore-error:
    ignore_error: true
    cmds:
      - exit 1
  other:
    cmds:
      - task: bad-ignore-error
      - echo hello
```

not ideal but gets the job done
