### ISSUE TITLE
Task Watch is unreliable and other helpers

### ISSUE THREAD

**Issue by dschissler** [go-task/task#368]
```Task version: 3.0.0```
```OS: Linux host 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

First off it would be good if there was a way to force the `cmds` part of a watched task to always fire the first time.  I've been able to work around this with my `always` task as a dependency hack.

Second, I found that the task watcher to be unreliable as it will simply stop working at some point.  I've been able to work around this by using the [reflex](https://github.com/cespare/reflex) tool.  So now I can run my dev environment with `task dev:watch` and `task -w dev`.  Since I have both styles available to me I'll continue experimenting to see if I can isolate the bug.

```yaml
version: '3'

vars:
  CMD_NAME: garage
  JS_SRC: web/raw/typescript
  JS_DST: build/web/javascript
  JS_ENTRIES:
    index
    signin

  dev:watch:
    cmds:
      - reflex --decoration=none --regex='(\.[a-z]+)$' --start-service task dev
    silent: true

  dev:
    deps: [always, build:script]
    cmds:
      - go run {{.CMD_NAME}}.go
    sources:
      - "**/*.go"
      - web/static/**
      - web/templates/**
    method: checksum

  build:script:
    deps: [build:prepare]
    cmds:
      - |
        for ENTRY in {{.JS_ENTRIES}}
        do
          deno bundle "{{.JS_SRC}}/${ENTRY}.ts" "{{.JS_DST}}/${ENTRY}.bundle.js"
        done
    sources:
      - web/raw/typescript/**/*
    method: checksum

  build:prepare:
    cmds:
      - install --directory build
      - install --directory build/web/{css,javascript}
    status:
      - test -d build
      - test -d build/web/css
      - test -d build/web/javascript
    silent: true

  always:
    cmds:
      - echo "Always run" >/dev/null
    status: [ 1 = 0 ]
    silent: true
```

**Comment by dschissler** [comment]
Sorry, this is just the `go run` built binary not being stopped.  So its a duplicate of #160

**Comment by dschissler** [comment]
I'm not stupid.  Its just that I just started go and I had too many moving pieces.  I should be able to solve this with a bit of PID code and some related bash work.  Ideally this would be handled crudely in Task so that a project could at least get going without needing to do the custom work.

**Comment by andreynering** [comment]
Hi @dschissler,

The watch feature definitely needs some love.

Thanks for opening this issue, it helps me to know what I need to improve, even if ended up being a duplicate.

**Comment by dschissler** [comment]
@andreynering Here is my Taskfile.  I'm posting the whole thing at the bottom and highlighting certain parts section-by-section so that you can see how I solved some of `task`'s short comings.  It has been a joy to work with Task, except for the watching/service part, which was a real drag.

First off I'll show you the unexposed `dev:actual` task:  It actually runs the program and checks that the javascript was made via `dev:preconditions`.  It also forces task to run via `dev:kill-server`. 

```yaml
  dev:actual:
    deps: [dev:kill-server, make:clean:generate, dev:preconditions]
    cmds:
      - go run {{.CMD_NAME}}.go
    sources:
      - "**/*.go"
      - web/static/**
      - web/templates/**
    method: timestamp
    silent: true
```

`dev:kill-server` uses `[ 1 = 0 ]` status check to always run.  I had to add a a few lines of pid file support to my server.  It would be nice if there was a way to always make a dependency trigger or at least if this pattern was shown in the documentation it might be enough.

```yaml
  dev:kill-server:
    cmds:
      - |
        if [[ -f /tmp/{{.CMD_NAME}}.pid ]]; then
          kill $(cat /tmp/{{.CMD_NAME}}.pid) >/dev/null 2>&1
          [[ $? -eq 0 ]] && sleep 0.2
        fi
        exit 0
    status:
      - "[ 1 = 0 ]"
    silent: true
```

`dev:watch-native` first builds the scripts and then calls the task via shell using the `-w` flag.  It would be nice if this was somehow built-in either via a `cmds:` `task:` key or in a task definition.  The problem with this method is that, well, it simply doesn't work all of the time.  There appears to be some great lag on the watching of the files, almost as if there is either an easy to trigger race condition happening or that its done not with inotify but rather a congested normal loop.  It is not even close to reliable enough to use for development.

```yaml
  dev:watch-native:
    desc: Start the dev server with watching reload using built-in Task watching
    cmds:
      - task: make:intermediate:script
      - task -w dev:actual
    silent: true
```

Finally the `default` task calls to `dev:actual` the same but rather uses the `reflex` tool to do the watching.  This works well, except, [sigh] the `reflex` command really doesn't get along with `deno bundle` as it keeps interrupting and failing, and so the script build cannot be part of the dependencies.  So I had to break it out like I did (after a lot of frustration).  This is the task that I use for development and after all of the work I can say that it works great.

```yaml
  default:
    desc: Start the dev server with watching reload using the reflex tool
    cmds:
      - task: make:intermediate:script
      - reflex --shutdown-timeout=50000ms --decoration=none --regex='(\.[a-z]+)$' --start-service=true task dev:actual
    silent: true
```

Complete

```yaml
version: '3'

vars:
  CMD_NAME: program_name
  SCRIPT_SRC: web/raw/typescript
  SCRIPT_DST: build/web/javascript

tasks:
  default:
    desc: Start the dev server with watching reload using the reflex tool
    cmds:
      - task: make:intermediate:script
      - reflex --shutdown-timeout=50000ms --decoration=none --regex='(\.[a-z]+)$' --start-service=true task dev:actual
    silent: true

  dev:watch-native:
    desc: Start the dev server with watching reload using built-in Task watching
    cmds:
      - task: make:intermediate:script
      - task -w dev:actual
    silent: true

  build:
    deps: [make:intermediate:generate]
    desc: Build the go binary
    summary: |
      Build the project

      This will generate the pkger.go file from all of the resources and
      then build the binary into the build directory.
    cmds:
      - go build -o build/bin/{{.CMD_NAME}} {{.CMD_NAME}}.go
    sources:
      - "**/*.go"
    method: timestamp


  ######################
  # dev support
  ######################

  dev:actual:
    deps: [dev:kill-server, make:clean:generate, dev:preconditions]
    cmds:
      - go run {{.CMD_NAME}}.go
    sources:
      - "**/*.go"
      - web/static/**
      - web/templates/**
    method: timestamp
    silent: true

  dev:preconditions:
    preconditions:
      - |
        ! find -- {{.SCRIPT_DST}} -prune -type d -empty | grep -q .
    silent: true

  dev:kill-server:
    cmds:
      - |
        if [[ -f /tmp/{{.CMD_NAME}}.pid ]]; then
          kill $(cat /tmp/{{.CMD_NAME}}.pid) >/dev/null 2>&1
          [[ $? -eq 0 ]] && sleep 0.2
        fi
        exit 0
    status:
      - "[ 1 = 0 ]"
    silent: true


  ######################
  # make build support
  ######################

  make:init:
    cmds:
      - install --directory build
      - install --directory build/bin
      - install --directory build/web/{css,javascript}
    status:
      - test -d build/bin
      - test -d build/web/css
      - test -d build/web/javascript
    silent: true

  make:intermediate:generate:
    deps: [make:intermediate:script]
    cmds:
      - go generate
    sources:
      - "web/**/*"

  make:intermediate:script:
    deps: [make:init]
    cmds:
      - |
        for ENTRY in {{.ENTRIES}}; do
          deno bundle "{{.SCRIPT_SRC}}/${ENTRY}" "{{.SCRIPT_DST}}/${ENTRY}"
          minify -o "{{.SCRIPT_DST}}/${ENTRY}" "{{.SCRIPT_DST}}/${ENTRY}"
        done
    sources:
      - web/raw/typescript/**/*
    generates:
      - build/web/javascript/**/*
    vars:
      ENTRIES:
        sh: echo $(find web/raw/typescript ! -path . -name '*' -printf '%P\n')
    method: timestamp
    silent: true


  ######################
  # make clean support
  ######################

  make:clean:
    deps: [make:clean:bin, make:clean:generate, make:clean:web]
    desc: Clean the build directory
    cmds:
      - rmdir build
    status:
      - test ! -d build

  make:clean:bin:
    cmds:
      - rm -fR {{.BIN_DIR}}
    status:
      - test ! -d {{.BIN_DIR}}
    vars:
      BIN_DIR: build/bin
    silent: true

  make:clean:generate:
    cmds:
      - rm -f {{.PKGER_FILE}}
    status:
      - test ! -f {{.PKGER_FILE}}
    vars:
      PKGER_FILE: build/pkged.go
    silent: true

  make:clean:web:
    cmds:
      - rm -Rf {{.WEB_DIR}}
    status:
      - test ! -d {{.WEB_DIR}}
    vars:
      WEB_DIR: build/web
    silent: true
```
