### ISSUE TITLE
Overriding vars in called task not working as expected

### ISSUE THREAD

**Issue by BeyondEvil** [go-task/task#376]
macOS Mojave 10.14.6

```bash
$ task --version
Task version: 2.8.1
```

```yml
version: "2"

silent: true

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the GO binary
    vars:
      GOOS: linux
    cmds:
      - echo {{.GOOS}}

  build-darwin:
    desc: Build the GO binary for macOS
    cmds:
      - task: build
        vars: {GOOS: "darwin"}
  
  build-linux:
    desc: Build the GO binary for Linux
    cmds:
      - task: build
        vars: {GOOS: "linux"}
```

Expected output:

```bash
$ task build
linux
$ task build-darwin
darwin
$ task build-linux
linux
```

Actual output:

```bash
$ task build
linux
$ task build-darwin
linux
$ task build-linux
linux
```

What am I doing wrong?

[Manual](https://taskfile.dev/#/usage?id=calling-another-task) says: "**Overriding** variables in the called task is as simple as informing `vars` attribute" (my emphasis)

**Comment by BeyondEvil** [comment]
Using the example and calling `write-file` generates: `task: Failed to run task "write-file": 1:19: > must be followed by a word`

**Comment by andreynering** [comment]
Hi @BeyondEvil,

That's by design. Your `build` task should probably be like:

```yaml
tasks:
  build:
    desc: Build the Go binary
    vars:
      GOOS: {{default "linux" .GOOS}}
    cmds:
      - echo {{.GOOS}}
```

As you was doing, you were always overriding whatever value is passed as argument by `linux`, because it was fixed in the task.
