### ISSUE TITLE
Passing a variable to a sub-task

### ISSUE THREAD

**Issue by smyrman** [go-task/task#38]
Somehow I would expect one of these to work:

```yaml
echo:
  cmds:
    - "echo {{.MYVAR}}"

default:
  vars:
    PLEASE: "awesome"
  cmds:
    - task: echo
      vars: {MYVAR: "{{.PLEASE}}"}
    - task: echo
      vars: {MYVAR: "$echo {{.PLEASE}}"}
    - task: echo
      vars: {MYVAR: "$echo $PLEASE"}
```

Especially with the new parameterised tasks, this would be an important aspect of composing chains of reusable tasks.
