### ISSUE TITLE
Automatically run included Taskfiles' default tasks without having to specify them

### ISSUE THREAD

**Issue by zx8** [go-task/task#381]
Given the following files/directories:

```
Taskfile.yml
foo/Taskfile.yml
```

And the following file content:

### `Taskfile.yml`

```yaml
version: '3'

includes:
  foo: ./foo/Taskfile.yml
```

### `foo/Taskfile.yml`

```yaml
version: '3'

tasks:
  default:
    deps:
      - foo

  foo:
    cmds:
      - echo foo
```

I would expect that running `task foo` from the root directory would run the _default_ task from the included Taskfile, yet to achieve the desired behaviour it is necessary to run `task foo:foo` and invoke the default task directly:

```sh
$ task foo
task: No tasks with description available
task: Task "foo" not found

$ task foo:foo
task: echo foo
foo
```

Not sure if this is a bug report or feature request, but what do you think about changing the behaviour to be more consistent with how `default` works for the root Taskfile?
