### ISSUE TITLE
Set / override environment variable when calling another task

### ISSUE THREAD

**Issue by lovromazgon** [go-task/task#386]
Would be nice to have the possibility to set ENV variables when calling another task. My use case is that I want to cross-compile a Go executable for a specific environment and I want to reuse an existing task.

Here is a simplified example of how I'd expect this to work:
```
version: '3'

tasks:
  build:
    desc: Build executable.
    cmds:
      - go build main.go

  build-linux:
    desc: Build executable for Linux
    cmds:
      - task: build
        env: {GOOS: "linux", GOARCH: "amd64"}
```

**Comment by andreynering** [comment]
Hi @lovromazgon,

For now, you can acomplish that by using interpolation like this:

```yaml
version: '3'

task:
  build-linux:
    - task: build
      vars: {GOOS: 'linux', GOARCH: 'amd64'}

  build:
    cmds:
      - go build .
    env:
      GOOS: '{{.GOOS}}'
      GOARCH: '{{.GOARCH}}'
```
