### ISSUE TITLE
Legitimate use-case of multi-level `includes`

### ISSUE THREAD

**Issue by LouisAmon** [go-task/task#390]
My company is specialised in infra-as-code and cloud automation.
A typical architecture we usually end up working with is as follows:

```bash
# Client-facing web platform
app/
    # Next.js application
    frontend/
    # Python infra-as-code (Pulumi)
    infra/
# Internal back-office
admin/
    frontend/
    infra/
```

As you can see here, we have 2 Python folders (each with their `virtualenv`) and 2 Next.js folders (using `yarn`)

In order to keep it DRY (Don't Repeat Yourself), I created a `common/taskfiles/python.yml` and a `common/taskfiles/yarn.yml` in my monorepo, and then I include those in the relevant taskfiles.

For example:
```
# app/infra/Taskfile.yml
version: "3"

includes:
  python: ../../common/taskfiles/python.yml

tasks:
  build:
    # I use the included Taskfile here
    deps: [python:install]
    cmds:
      - do something
```
This way, I ensure that every Python install uses the same tooling (checking the Python version, package manager, etc.), and the same thing goes for Next.js (Node version, yarn package manager, etc.) : it's the best way I found to avoid having drift between each install.

That's all fine and dandy, but I also need to coordinate my `infra` and my `frontend` for each of my platforms (`app` and `admin`).

So I end up having a Taskfile for that:
```
# app/Taskfile.yml
versions: "3"

# I'd like to do that, but can't :(
# includes:
#   frontend: ./frontend
#   infra: ./infra

tasks:
  deploy:
    # I'd like to do something like that
    # deps: [frontend:deploy, infra:deploy]

    # Instead, I have to do something like that
    deps: [deploy:frontend, deploy:infra]

  deploy:frontend:
    dir: ./frontend
    cmds:
      - task deploy

  deploy:infra:
    dir: ./infra
    cmds:
      - task deploy
```

The namespacing and log statements end up being messier than they could be, although it does work perfectly fine that way.

The main difficulty here are variables as it becomes kind of messy to know which tasks are called as subtasks (e.g. `task: subtask` and which are called from the shell directly `task subtask`) : variables should be passed differently in each scenario (`vars` vs environment variable).

This issue is the main reason why we're considering Buck or Pants as our build system, so I'd rather post the issue here for the community as it was literally written in the docs:

> Also, for now included Taskfiles can’t include other Taskfiles. This was a deliberate decision to keep use and implementation simple. If you disagree, open an GitHub issue and explain your use case. =)

**Comment by andreynering** [comment]
Hi @LouisAmon, thanks for opening this issue, and sharing your use case!

While we did that decision to make the first implementation simpler, and can change that in the future. I can't promise that it will happen, though.

**Comment by robbrit** [comment]
This would be extremely useful for us too, to be able to reference tasks in other directories easily. We're using a monorepo with directories split up across teams and often want to easily reference libraries shared across teams such as API clients, etc.

**Comment by tylermmorton** [comment]
I was trying to use task files in a very similar way until I discovered this limitation. Here is the hierarchy of my project
```
src/
src/Taskfile.yml
src/tasks/
src/tasks/builder.yml
src/project1/
src/project1/Taskfile.yml
src/project2/
src/project2/Taskfile.yml
```
Where the parent-most Taskfile imports tasks from `project1` and `project2`, while both `project1` and `project2` import tasks from common build tasks in `src/tasks/builder.yml`. The hope was to reduce task duplication by maintaining one set of builder tasks while also having a single point of entry Taskfile at the root of a multi-project monorepo. 

If you can point me in the right direction I'd be happy to help take a swing at a PR for this. It could greatly increase the flexibility of task.

**Comment by andreynering** [comment]
There's an attempt to address this at #656 if anyone is interested to test if it's working as expected.

**Comment by lukepighetti** [comment]
We have a situation where we'd like to generate an intermediary `Taskfile.packages.yml` based on the contents of a folder that contains a bunch of modularized packages which each have their own Taskfile. These packages are always changing, and this intermediary Taskfile would be consumed by the project root Taskfile. Very surprised to find out that this is not possible.

## package_a/Taskfile.yml
```yaml
version: "3"

tasks:
  clean: echo 'clean'
```

## Taskfile.packages.yml (generated)

```yaml
version: '3'

includes:
  package_a:
    taskfile: ../packages/package_a
    dir: ../packages/package_a
  package_b:
    taskfile: ../packages/package_b
    dir: ../packages/package_b
  package_c:
    taskfile: ../packages/package_c
    dir: ../packages/package_c
  package_d:
    taskfile: ../packages/package_d
    dir: ../packages/package_d
  package_e:
    taskfile: ../packages/package_e
    dir: ../packages/package_e
  package_f:
    taskfile: ../packages/package_f
    dir: ../packages/package_f

tasks:
  clean:
    deps:
      - 'task: package_a:clean'
      - 'task: package_e:clean'
      - 'task: package_f:clean'
      - 'task: package_d:clean'
      - 'task: package_c:clean'
      - 'task: package_b:clean'
  test:
    deps:
      - 'task: package_e:test'
      - 'task: package_d:test'
      - 'task: package_c:test'
      - 'task: package_b:test'
  analyze:
    deps:
      - 'task: package_b:analyze'
```


## Taskfile.yml

```yml
version: "3"

includes:
  packages: ./tasks/Taskfile.packages.yml

tasks:
  clean:
    desc: Run flutter clean on app and all packages
    cmds:
      - task: packages:clean
      - flutter clean
```
