### ISSUE TITLE
Inconsistent variable expansion

### ISSUE THREAD

**Issue by thomews** [go-task/task#393]
- Task version: 3.0.0
- OS: Windows 10 AMD64

I have a set of included task files which represent a composition of different variables. I also have one included generic task file and one main Taskfile which contains all includes. Task abcd in generic-tasks.yml is expected to always print A_B_C_D=A_B_C_D. With Task v2 this has been working as expected.  However, with Task v3.0.0 the result is random and not always consistent: 

```
$ cd main/
$ task generic:abcd
A_B_C_D=__C_D
$ task generic:abcd
A_B_C_D=___D
$ task generic:abcd
A_B_C_D=A_B_C_D
$ task generic:abcd
A_B_C_D=A_B_C_D
$ task generic:abcd
A_B_C_D=___D
$ task generic:abcd
A_B_C_D=A_B_C_D
$ task generic:abcd
A_B_C_D=_B_C_D
$ task generic:abcd
A_B_C_D=A_B_C_D
$ task generic:abcd
A_B_C_D=__C_D
```
[taskfiles.zip](https://github.com/go-task/task/files/5457247/taskfiles.zip)

Overview of files and structure:
```
|-vars-a.yml
|-vars-b.yml
|-vars-c.yml
|-vars-abcd.yml
|-generic-tasks.yml
|-main/
     |-Taskfile.yml
```

File: main/Taskfile.yml
```
version: '3'
includes:
  a: ../vars-a.yml
  b: ../vars-b.yml
  c: ../vars-c.yml
  abcd: ../vars-abcd.yml
  generic: ../generic-tasks.yml
vars:
  D: D
```

File: vars-a.yml
```
version: '3'
vars:
  A: A
```

File: vars-b.yml
```
version: '3'
vars:
  B: B
```
File: vars-c.yml
```
version: '3'
vars:
  C: C
```

File: vars-abdc.yml
```
version: '3'
vars:
  A_B_C_D: "{{.A}}_{{.B}}_{{.C}}_{{.D}}"
```

File: generic-tasks.yml
```
version: '3'
tasks:
  abcd:
    desc: print A_B_C_D
    cmds:
      - echo A_B_C_D={{.A_B_C_D}}
    silent: true
```
