### ISSUE TITLE
`includes` and backward compatibility with OS specific Taskfiles

### ISSUE THREAD

**Issue by mknapik** [go-task/task#397]
https://taskfile.dev/#/usage?id=directory-of-included-taskfile
I've tried to migrate from schema `2.6` to version `3.0`.
[The docs](https://taskfile.dev/#/usage?id=os-specific-taskfiles) claims OS specific Taskfiles can be substituted with `includes` and `{{OS}}`, however I find it difficulty adapting to the new format.

Here is my use case.

### `Taskfile.yml`

```yml
version: '2.6'
tasks:
  prerequisites:
    desc: 'Installs all external dependencies using OS package manager.'
    deps: [prerequisites:docker, prerequisites:prettier]
```

### `Taskfile_linux.yml`

```yml
version: '2.6'
tasks:
  prerequisites:docker:
    cmds:
      - sudo pacman -S --needed --noconfirm docker
    status:
      - command -v docker
  prerequisites:prettier:
    cmds:
      - yay -S --needed --noconfirm taskfile-git
    status:
      - command -v prettier
```

Linux package managers such as `apt` or `pacman` implement semaphores so
it's possible to run those tasks in parallel and benefit from quick task during subsequent runs (running multiple status commands in parallel).

### `Taskfile_darwin.yml`

AFAIK macOS's `brew` does not use any locks so running those tasks in parallel will fail. I can either overwrite `prerequisites` task in `Taskfile_darwin.yml` to check for deps in parallel or use `flock` cmd. Either way, overwriting `prerequisites` is necessary.

```yml
version: '2.6'

vars:
  LOCK: flock -w 600 .task.brew.lock

tasks:
  prerequisites:docker:
      - '{{.LOCK}} brew cask install docker'
    status:
      - command -v docker
  prerequisites:prettier:
    cmds:
      - '{{.LOCK}} brew install prettier'
    status:
      - command -v prettier
  prerequisites:flock:
    cmds:
      - brew tap discoteq/discoteq
      - brew install flock
    status:
      - command -v flock
  prerequisites:
    cmds:
      - task: flock
      - task: all
  prerequisites:all:
    deps: [docker, prettier]
```

### `Taskfile.yml`

```yml
version: '3.0'
includes:
  prerequisites: Taskfile_{{OS}}.yml
tasks:
  prerequisites:
    desc: 'Installs all external dependencies using OS package manager.'
    deps: [prerequisites:docker, prerequisites:prettier]
```

### `Taskfile_linux.yml`

```yml
version: '3.0'
tasks:
  docker:
    cmds:
      - sudo pacman -S --needed --noconfirm docker
    status:
      - command -v docker
  prettier:
    cmds:
      - sudo pacman -S --needed --noconfirm prettier
    status:
      - command -v prettier
```

This is more or less the same as in `2.6` (however, I cannot use tasks from `Taskfile.yml` inside the included one).

### `Taskfile_darwin.yml`

```yml
version: '3.0'

vars:
  LOCK: flock -w 600 .task.brew.lock

tasks:
  docker:
      - '{{.LOCK}} brew cask install docker'
    status:
      - command -v docker
  prettier:
    cmds:
      - '{{.LOCK}} brew install prettier'
    status:
      - command -v prettier
  flock:
    cmds:
      - brew tap discoteq/discoteq
      - brew install flock
    status:
      - command -v flock
  default: # this doesn't work
    cmds:
      - task: flock
      - task: all
  all:
    deps: [docker, prettier]
```

AFAIK there is no way to overwrite `prerequisites` task from the main file, isn't there?

## Workaround

Add dummy `flock` task in `Taskfile_linux.yml` and require it in `Taskfile.yml`.

### `Taskfile.yml`

```yml
version: '3.0'
includes:
  prerequisites: Taskfile_{{OS}}.yml
tasks:
  prerequisites:
    desc: 'Installs all external dependencies using OS package manager.'
    deps: [prerequisites:flock, prerequisites:all] # require `flock` even though it's not needed in Linux
  prerequisites:all:
    deps: [prerequisites:docker, prerequisites:prettier]
```

### `Taskfile_linux.yml`

```yml
version: '3.0'
tasks:
  docker:
    cmds:
      - sudo pacman -S --needed --noconfirm docker
    status:
      - command -v docker
  prettier:
    cmds:
      - sudo pacman -S --needed --noconfirm prettier
    status:
      - command -v prettier
  flock:
    status:
      - exit 0
```

### `Taskfile_darwin.yml`

```yml
version: '3.0'
vars:
  LOCK: flock -w 600 .task.brew.lock
tasks:
  docker:
      - '{{.LOCK}} brew cask install docker'
    status:
      - command -v docker
  prettier:
    cmds:
      - '{{.LOCK}} brew install prettier'
    status:
      - command -v prettier
  flock:
    cmds:
      - brew tap discoteq/discoteq
      - brew install flock
    status:
      - command -v flock
```

## Potential solution

Allow merging tasks

```yml
includes:
  does_not_matter:
    taskfile: Taskfile_{{OS}}.yml
    merge: true
```

## Summary

Do you have any other ideas how such functionality could be structured using currently available syntax?
