### ISSUE TITLE
Add method to call other tasks in parrallel

### ISSUE THREAD

**Issue by Nadock** [go-task/task#409]
Hi, I'm new to Taskfile so apologies if this duplicates an issue already - I had a look but I couldn't see this anywhere. Anyway, onto the actual idea, it would be useful to have a way of calling other tasks in parallel (like how dependencies work). 

Consider this use case I have atm: We want run a series of `docker-compose` commands in parallel, but if the Docker network does not exist running the compose commands in parallel creates a bunch of conflicting networks. The solution is to run `docker-compose up --no-start` first to ensure the network is created just once, then run the parallel tasks.

What I've done at the moment is something like this:
```yaml
tasks:
  parallel_compose:
    cmds:
      - cmd: docker-compose up --no-start
      - task: cfn:check:_

  parallel_compose_:
    deps:
      - compose_1
      - compose_2
      - ...
```

---

What would be nice is if we didn't have to create two tasks to achieve this, in my head it would look something like this:
```yaml
tasks:
  parallel_compose:
    cmds:
      - cmd: docker-compose up --no-start
      - task:
          parallel: [compose_1, compose_2, ...]
```
Where the compose `up` command would run, then the other compose tasks would run in parallel.
