### ISSUE TITLE
Allow interpolation in task names when calling another task?

### ISSUE THREAD

**Issue by sergeyberezansky** [go-task/task#410]
Hello, I am struggling to resolve task name based on variable

Having 2 different modes of task execution, and would like to support them both without making commands complicated
For this reason, tried to either separate the tasks into different include files,
or just create another tasks and then try to call them by name with variable expansion
Nothing works

Want, for example, to support local environment to work both with docker and minikube, and bring up the desired env according to env param.

```
# env installation_mode=docker

tasks: 
  install_database :
    cmds:
       - task: install_database_{{.installation_mode}}

  install_database_docker:
    - cmds:
      - docker run ...

  install_database_kube:
    - cmds:
     - kubectl apply...
```

Is this supported? What I am missing here?

**Comment by mknapik** [comment]
`{{.installation_mode}}` interpolates Taskfile variable which is not the same as shell env var.

The following config would use env vars:

```yaml
tasks:
  install_database_env_var:
    cmds:
       - echo "env_var install_database_${INSTALLATION_MODE}"
       - task: "install_database_${INSTALLATION_MODE}"
    preconditions:
      - test -n "${INSTALLATION_MODE}"

  install_database_docker:
    cmds:
      - echo "install_database_docker"

  install_database_kube:
    cmds:
     - echo "install_database_kube"
```
However, it doesn't work for me so I guess it's not supported.

You can work around the problem by using shell instead of `task` command:
```yaml
tasks:
  install_database_env_var:
    cmds:
       - echo "env_var install_database_${INSTALLATION_MODE}"
       - task install_database_${INSTALLATION_MODE}
    preconditions:
      - test -n "${INSTALLATION_MODE}"

  install_database_docker:
    cmds:
      - echo "install_database_docker"

  install_database_kube:
    cmds:
     - echo "install_database_kube"
```

```
$ env INSTALLATION_MODE=docker task install_database_env_var
task: echo "install_database_${INSTALLATION_MODE}"
install_database_docker
task: task install_database_${INSTALLATION_MODE}
task: echo "install_database_docker"
install_database_docker
```
