### ISSUE TITLE
Make using both `sources` and `status` work

### ISSUE THREAD

**Issue by drewsilcock** [go-task/task#411]
I have a build task that takes in variables to decide which platform to build for.

I'm trying to find some way to tell Task that the job is up-to-date using the standard sources checksum plus also checking whether the platform variables have changed.

I can get one to work at a time, but not both as the `status` commands seem to take precedence over the `sources` meaning if you specify commands for `status`, the `sources` are ignored.

Is there any way to have both the `sources` and `status` checked? Otherwise is there any way to add specific variables to the `sources` somehow? It might be I'm missing something obvious but I can't see a way of achieving this.

Many thanks in advance and thank you for the fantastic tool!

Here's a snippet of my `Taskfile.yml`:

```yaml
version: "3"

silent: true

vars:
  PROJECT_NAME: my-project

  VERSION:
    sh: echo "${VERSION:-$(git describe --tags --always 2> /dev/null)}"

  BUILD_TIME:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"

  PACKAGENAME:
    sh: go list 2> /dev/null || true

  LD_FLAGS: >
    -ldflags "-X '{{.PACKAGENAME}}/version.Version={{.VERSION}}'
    -X '{{.PACKAGENAME}}/version.BuildTime={{.BUILD_TIME}}'"

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build API executable for native platform platform specified by variables.
    cmds:
      - echo Building executable...
      - CGO_ENABLED="{{.CGO_ENABLED}}" GOOS="{{.GOOS}}" GOARCH="{{.GOARCH}}" go build {{.LD_FLAGS}}
      - echo "{{.GOOS}}-{{.GOARCH}}-{{.CGO_ENABLED}}" > .task/build-platform
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    status:
      - test -f .task/build-platform
      - "[ $(cat .task/build-platform) == \"{{.GOOS}}-{{.GOARCH}}-{{.CGO_ENABLED}}\" ]"
    generates:
      - "{{.PROJECT_NAME}}"

  build-linux:
    desc: Build Linux API executable.
    cmds:
      - echo Building Linux executable...
      - task: build
        vars:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
```
