### ISSUE TITLE
Should use labels to name checksum targets

### ISSUE THREAD

**Issue by adamwasila** [go-task/task#412]
Currently when single task is used to build different binaries, like in this example:

```
  build_target:
    label: "{{.TARGET}}"
    cmds:
      - go build -o {{.TARGET}} ./cmd/{{.TARGET}}
    sources:
      - "**/*.go"
    generates:
      - "{{.TARGET}}"

  build:
    desc: build all commands
    cmds:
      - task: build_target
        vars:
          TARGET: "{{.FIRST_APP}}"
      - task: build_target
        vars:
          TARGET: "{{.SECOND_APP}}"
```

It works perfectly except for caching which uses task name instead of label to generate hash of sources:

```
❯ tree .task
.task
└── checksum
    └── build_target
```

Fix should be quite trivial, just change https://github.com/go-task/task/blob/master/status.go#L80 `t.Task,` should become `t.Name(),` (aven't tested yet - maybe needs few more changes)

The only problem is that for some setups it will not be backward compatible, though for some other setups (like mine presented above) it is clearly broken right now. So, what you think, is it worth testing and publishing PR? Would you consider to merge such change?
