### ISSUE TITLE
Variable templating not handled when calling task via deps

### ISSUE THREAD

**Issue by smyrman** [go-task/task#42]
Given the following Taskfile:
```yaml
taskA:
  vars:
    A: null
    B: "42"
  cmds:
    - echo "{{.A}} {{.B}} {{.C}}"

taskB:
  vars:
    A: "taskB"
    B: "ignored"
    aha: "weee"
  deps:
    - task: taskA
      vars:
        A: "dep:{{.A}}"
        C: "{{.aha}}"
  cmds:
    - task: taskA
      vars:
        A: "cmd:{{.A}}"
        C: "{{.aha}}"

default:
  deps:
    - task: taskB
      vars: {A: "default"}
```

I would expect `task` to output:
```sh
task: No argument given, trying default task
echo "dep:default 42 weee"
dep:default 42 weee
echo "cmd:default 42 weee"
cmd:default 42 weee
```
Instead, we get:
```sh
task: No argument given, trying default task
echo "dep:{{.A}} 42 {{.aha}}"
dep:{{.A}} 42 {{.aha}}
echo "cmd:default 42 weee"
cmd:default 42 weee
```
