### ISSUE TITLE
Yaml alias syntax can not working on v3

### ISSUE THREAD

**Issue by komtaki** [go-task/task#424]
Yaml alias syntax can not working on v3.This syntax is working before v2.8.0.
Does v3 not support yaml alias syntax?

Best Regard.

- Task version: 3.1.0
- Operating System:

```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```

## Taskfile version 2

```yaml
version: '2'

.vars-yaml-alias: &vars-yaml-alias
  hogehoge: hogehoge

tasks:
  test:
    cmds:
      - echo '{{.hogehoge}}'
    vars:
      <<: *vars-yaml-alias
```

go-task v3.1.0 
```
$ task test
task: echo '<no value>'
<no value>
```

go-task v2.8.0
```
$ task test
echo 'hogehoge'
hogehoge
```

## Taskfile version 3

```
version: '3'

.vars-yaml-alias: &vars-yaml-alias
  hogehoge: hogehoge

tasks:
  test:
    cmds:
      - echo '{{.hogehoge}}'
    vars:
      <<: *vars-yaml-alias
```

go-task v3.1.0
```
$ task test
task: echo ''
```
