### ISSUE TITLE
Sources and status do not interoperate

### ISSUE THREAD

**Issue by timthesinner** [go-task/task#427]
- Task version: `3.2.0`
- Operating System: darwin

### Description

The sources and status checks do not seem to interoperate.  If status returns 0, in this case the docker image exists, task is  skipping the source checks. 

### Expectation 

I would expect a change to a listed source file OR a missing docker image to trigger a build.  
 
### Example Taskfile showing the issue

```yaml
tasks:
  build-dev:
    cmds:
      - docker buildx bake -f app_build/docker-bake.hcl -f app_build/docker-bake.override.hcl dev

    preconditions:
      - sh: "jq --version"
        msg: "You must have jq installed, https://github.com/stedolan/jq/wiki/Installation"
      - sh: "[ $(cat ~/.docker/config.json | jq -r '.auths | has(\"foo.dkr.ecr.us-east-1.amazonaws.com\")') == \"true\" ]"
        msg: "Docker is not logged into ECR, run task aws-login"

    status:
      # Check for the alerting-service:dev docker image, if it does not exist trigger a build
      - "[ ! -z \"$(docker image list --format \"{{\"{{\"}}json .{{\"}}\"}}\" | jq -s '.' | jq -c '.[] | select(.Repository == \"alerting-service\" and .Tag == \"dev\")')\" ]"

    method: checksum
    sources:
      - ./requirements.txt
      - ./Dockerfile
```
