### ISSUE TITLE
environment variable is not used in the "dir" and "vars" sections of tasks

### ISSUE THREAD

**Issue by viktorprogger** [go-task/task#431]
- Task version: 3.2.2
- Operating System: Ubuntu 20.04

### Example Taskfile showing the issue

```yaml
version: 3

env:
  PROJECTS_FOLDER: ../projects

tasks:
  test:
    dir: $PROJECTS_FOLDER/{{.WD}}
    cmds:
      - echo $PROJECTS_FOLDER/{{.WD}}

  subtest:
    cmds:
      - task: test
        vars:
          WD: project1
```

When I call `task subtest`, I see the next error:
> task: cannot make directory "/project1": mkdir /project1: permission denied

And if I remove `dir` from the `test` task, this command would echo `../projects/project1`.

As you can see, environment variable is not used in the `dir` section of the task. I think it should.

**Comment by viktorprogger** [comment]
It is also not expanded in the `vars` section. I tried to do these variants:
```yml
  subtest:
    cmds:
      - task: test
        vars:
          WD:
            sh: echo $PROJECTS_FOLDER/crm
```

```yml
  subtest:
    cmds:
      - task: test
        vars:
          WD: $PROJECTS_FOLDER/crm
```
