### ISSUE TITLE
Declared env vars do not take precedence over existing env vars

### ISSUE THREAD

**Issue by ahawkins** [go-task/task#436]
- Task version: 3.2.2
- Operating System: macOS

### Example Taskfile showing the issue

```yaml
version: "3"

env:
  DUMMY: "foo"

tasks:
  default:
    cmds:
      - echo "DUMMY=${DUMMY}"
```

### Example Behavior

```
$ task -s
DUMMY=foo
$ env DUMMY=placeholder task -s
DUMMY=placeholder
```

### Expectation

```
$ env DUMMY=placeholder task -s
DUMMY=foo
```

Outputs the value declared in the `Taskfile`.

Value declared in `env` is used for tasks irregardless to existing values. This used to work in a previous version, not sure where it stopped.
