### ISSUE TITLE
Global dynamic variables are set in wrong folder

### ISSUE THREAD

**Issue by tillhoff** [go-task/task#442]
- Task version: 3.2.2
- Operating System: Ubuntu 20.04

Since version 3.2.0 (and #384), task executes the dynamic variable commands (set with `sh: bash ...`) in the directory of the task they are used in. This is even the case if they are declared globally (-> not in a specific task).
Previously, they were executed in the current directory.

Intuitively, I'd say global variables should be set either in the current directory for global ones and variables which are set at task-level should be executed in the directory of the task.

I think it depends how one understands those dynamic variables: Are they intended to be used as "insert specified command here" or as variable which will be set at runtime? For me, `dynamic variable` means the latter.

Nevertheless, it was possible to use `VERSION: {sh: "bash {{ .PWD }}/scripts/version.sh"}` to still make it work somehow. (Instead of defining the relative path for each task where it is used)

### Example Taskfile showing the issue

```yaml
version: '2'

vars:
  VERSION: {sh: "bash scripts/version.sh"}

replace-versions:
    desc: Replace versions
    cmds:
      - |
          sed -i.bak -e "s#version: 0.0.0#version: {{.VERSION}}#g"
```
