### ISSUE TITLE
Add subcommands?

### ISSUE THREAD

**Issue by max-sixty** [go-task/task#443]
Currently I have some taskfiles that are growing fairly large, and thinking of a good way of grouping tasks. One approach is with different taskfiles, but it's not discoverable, and the syntax (`-t Taskfile-foo.yml`) isn't natural.

What do people think about enabling subcommands? e.g.

```yaml
version: '3'

tasks:
  # This is a subcommand.
  +hello:
    # These are tasks within the `hello` subcommand.
    hi: echo 'Hello World from Task!'
    ciao: echo 'Ciao Mondo from Task!'

  +goodbye:
    bye: echo 'Goodbye World from Task!'
    ciao:
      task: hello.ciao  # same as hello
```

Then `task hello hi`, `task hello ciao` would be subcommands of `task hello`, and same for `task goodbye`. 

I've seen the `+` syntax used elsewhere to avoid confusion between attributes and a hierarchy, but having `subcommands:` as another level could also work. Or just disallow keywords from being used as subcommands.
