### ISSUE TITLE
Run cmd from env: did not find expected '-' indicator

### ISSUE THREAD

**Issue by Antonboom** [go-task/task#450]
- Task version:
```
task --version
Task version: 3.0.1
```

- Operating System:

### Example Taskfile showing the issue

```yaml
version: '3'

silent: true

vars:
  APP: ./bin/some-backend

tasks:
  version:
    desc: Show app version.
    cmds:
      - {{.APP}} version
```
```
▶ task  version
yaml: line 11: did not find expected '-' indicator
```

But this works ok:
```yaml
    cmds:
      - "{{.APP}} version"
```

```
▶ task  version

release: "taskfile"
buildDate: "2021-03-17T12:33:34"
branch: "taskfile"
```
