### ISSUE TITLE
Included vars nor expanded in global vars

### ISSUE THREAD

**Issue by b4nst** [go-task/task#454]
- Task version: 3.2.2
- Operating System: macOS

### Example Taskfile showing the issue

_Taskfile.yml_
```yaml
# https://taskfile.dev

version: '3'

includes:
  msg: ./include.yml

vars:
  GREETING: '{{.MSG}}'

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - echo "{{.MSG}}"
```

_include.yml_
```yaml
# https://taskfile.dev

version: '3'

vars:
  MSG: Hello, World!
```

_output_
```shell
➜  task                                                                                                                                                                                                                                                                   
task: echo ""

task: echo "Hello, World!"
Hello, World!
```
