### ISSUE TITLE
Parsing of cli args in powershell (core) failed

### ISSUE THREAD

**Issue by kriegr** [go-task/task#464]
- Task version: 3.3.0
- Operating System: Microsoft Windows 10 Pro (10.0.19043 Build 19043)
- Shell: Powershell Core (7.1.3)

### Example Taskfile showing the issue

```yaml
# https://taskfile.dev

version: "3"

tasks:
  go:
    desc: "Run go"
    cmds:
      - go {{.CLI_ARGS}}
```

#### Expected
`go version go1.15.7 windows/amd64`

#### Actual
```
task: Available tasks for this project:
* go:   Run go
task: Task "version" not found
```
