### ISSUE TITLE
Single Quotes Around env breaks the parsing of the tasks with generic error

### ISSUE THREAD

**Issue by sheldonhull** [go-task/task#467]
- Task version: `Task version: 3.3.0`
- Operating System: macOS

```yaml
  docker_shell:
    desc: enter into the docker container manually to investigate and debug
    env:
      BUILDKIT_PROGRESS: '{{.BUILDKIT_PROGRESS}}'  <------ THIS LINE
    cmds:
      - docker run  --rm -it --entrypoint bash --env AWS_REGION={{.AWS_REGION}} -p 80:80/tcp {{.docker_container_name}}:latest

```

The line mentioned above fails when the quotes are removed with `task: can't unmarshal task value` resulting in lots of confusion and troubleshooting on task/cmd definitions.
Yaml generally is not supposed to quote string values if not required, so this either should be clearly indicated in the error content or support for not requiring quotes should be added. 

Considering linting tools often remove unrequired quotes, would be good to support this being parsed without the quotes, so that pre-commit and other tooling for yaml linting and formatting doesn't break.
