### ISSUE TITLE
Ability to run certain commands even if other commands have failed

### ISSUE THREAD

**Issue by mccolljr** [go-task/task#475]
As usual, I am loving this tool and I use it frequently. This has been a minor pain point (there is a work-around), but I would love to see a feature added which would reduce friction around cleaning up after a command or task.

The use case I've encountered is cleaning up test resources after running tests, regardless of whether or not the tests passed.

Here is a trimmed down version of something I have in a Taskfile currently:

```yaml
test:setup:
  - echo "set up docker containers"
test:run:
  - echo "execute tests"
test:cleanup:
  - echo "remove docker containers"
test:
  - |
     (task test:setup test:run);
     EXIT_CODE=$?;
     task test:cleanup;
     exit $EXIT_CODE;
```

It is clearly possible to achieve the desired result with the current implementation, but it's not ideal, since the cleanup doesn't run if I terminate execution with `CTRL-C` or if some other interrupt mechanism kills the task.

I also have nested task output because I call `task blah:blah` from the shell within a task, which doesn't hurt anything but can be kind of annoying with longer task names.

I'm not 100% sure what form the solution should take, but I have a couple of ideas:

### 1. `always` flag for commands

Allow commands (both `task: ...` and `cmd: ...` forms) to have a property `always` that can be set to `true` to indicate that the command should run even if a previous command within the same task has failed.

Example:

```yaml
test:
  - task: test:setup
  - task: test:run
  - task: test:cleanup
    always: true
```

### 2. `cleanup` for commands

Allow commands (both `task: ...` and `cmd: ...` forms) to accept a `cleanup` property which specifies one or more commands to be run as cleanup at the end of task execution (success or fail) once that command has been successfully executed. This is sort of analogous to `defer` in go, in the sense that once the top-level command is executed, successfully, the cleanup command is guaranteed to run regardless of whether or not the containing task succeeds or fails.

Example:

```yaml
test:
  - task: test:setup
    cleanup:
      - task: test:cleanup
  - task: test: run
```

I have opened a PR (#474) to show how option 1 might be implemented, but ultimately I'd love to find a solution that the maintainers feel fits best with the tool. As long as I can avoid using sub-shells and long sections of bash to ensure cleanup is run, I will be happy :)

**Comment by andreynering** [comment]
Regarding the syntax, I think `defer` could be interesting, to mimic Go's way:

```yaml
version: '3'

tasks:
  foo:
    cmds:
      - echo 'Hello'
      - defer: echo '!'
      - echo 'World'
```

The moment the reach `defer`, it'd be scheduled to run after the remaining commands of the task. In the Go's side we could use the real Go `defer` to accomplish that.

**Comment by kerma** [comment]
Another option would be to copy from Github Actions. Might be a bit more familiar than "defer" for people outside of go.

```yaml
tasks:
  foo:
    cmds:
      - task: work
      - task: notify
        if: {{ failure() }}
      - task: cleanup
        if: {{ always() }}
```

**Comment by mccolljr** [comment]
@andreynering I do like `defer`.


I'm wondering about semantics when there are multiple defers and one fails.

For a super contrived example:

```yaml
task:
    - defer: echo "hello again"
    - defer: exit 1
    - echo "hello"
    - exit 1
```

I think in this scenario, I'd want _both_ defers to run. In a more realistic scenario I could see a large task with several steps having a `defer` after steps that require cleanup. I would probably find it surprising that a failure in one of these cleanup actions would prevent the others from running

My personal preference would be to log an error for each deferred talk that fails, but ensure all are executed.

What are your thoughts?

@kerma I like your idea conceptually, but it seems difficult to implement correctly since nothing in the task structure itself tells us that it is special, and the current semantics are that processing stops at the first failed command. I'm having trouble envisioning a reliable way to go through and look for tasks that are to run on failure without actually evaluating their conditions and checking for a call to `failure()`
