### ISSUE TITLE
Running with --watch does not respect task directory when registering sources to watch

### ISSUE THREAD

**Issue by lpdyck** [go-task/task#484]
- Task version: v3.4.2
- Operating System: Windows

```yaml
version: '3'
dotenv: ['app/.env']

tasks:
  build-js:
    dir: app/js
    sources:
      - controllers/*.ts
      - application.ts
      - package.json
      - webpack.config.js
      - tsconfig.json
    cmds:
      - npm run webpack
```

When running the `build-js` task, Task correctly recognizes the sources for currency checks. However, when running it with the `--watch` flag, it gives an error `task: application.ts: file does not exist`. Looking at the code, the watch file globbing function does not respect the task directory (https://github.com/go-task/task/blob/master/watch.go#L131) while the internal status checker does (https://github.com/go-task/task/blob/master/internal/status/glob.go#L16).
