### ISSUE TITLE
Env variable used inside dir is not being expanded or used.

### ISSUE THREAD

**Issue by hfingler** [go-task/task#499]
- Task version: v3.4.3
- Operating System: Linux

### Example Taskfile showing the issue

I have a bunch of directories in a large project that I want to set as variables/envs so I don't have to keep moving up and down. Using env seems to be the best approach since I can't make vars work and I don't want to manually generate a dotenv.
This is cool because it seems included taskfile inherit these vars.

```
env:
  AVA_DIR:   {sh: "echo $(pwd)/vendor/ava"}
  <some other dirs>

ava-gen:
    dir: $AVA_DIR
    cmds:
      - echo yo $AVA_DIR
      - echo pwd $(pwd)
      - ./generate
```
When this task executes I see:

```
$ task ava-gen

task: [ava-gen] echo yo $AVA_DIR
yo /home/hfingler/project/vendor/ava
task: [ava-gen] echo pwd $(pwd)
pwd /home/hfingler/project
stat /home/hfingler/project/generate.py: no such file or directory
```

Is this a bug or am I doing something wrong? Can env variables be used in dir?

**Comment by estherlyoon** [comment]
I got env variables to expand using something like:
```
env:
  PWD: {sh: "pwd"}
  AVA_DIR: "{{.PWD}}/vendor/ava"

tasks:
  ava-gen:
    dir: "{{.AVA_DIR}}"
    cmds:
      - echo $(pwd)
```
