### ISSUE TITLE
source venv/bin/activate

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#512]
This is happening on an Alpine slim build so it's entirely possible that it is a problem with my config. But I figured I'd post it here just in case.

- Task version: Latest
- Operating System: Big Sur

The following errors out:

```
  python-requirements:
    cmds:
      - if ! type virtualenv &> /dev/null; then pip3 install virtualenv; fi
      - virtualenv venv
      - source venv/bin/activate
      - pip3 install -r requirements.txt
    sources:
      - requirements.txt
    preconditions:
      - sh: "test -f requirements.txt"
        msg: "The requirements.txt file is missing!"

```

With error: 

```
task: [common:python-requirements] if ! type virtualenv &> /dev/null; then pip3 install virtualenv; fi
task: [common:python-requirements] virtualenv venv
task: [common:_npm-ansibler] if ! type ansibler &> /dev/null; then npm install -g ansibler; fi
task: [common:nodejs-dependencies] npm install
task: Task "common:python-requirements" is up to date
task: [common:_npm-hbs] if ! type hbs &> /dev/null; then npm install -g hbs-cli; fi
task: [common:_npm-prettier] if ! type prettier &> /dev/null; then npm install -g prettier prettier-plugin-sh @megabytelabs/prettier-config @megabytelabs/prettier-config-ansible; fi
task: [common:_npm-prettier-package-json] if ! type prettier-package-json &> /dev/null; then npm install -g prettier-package-json; fi
task: [common:_npm-readme] if ! type readme &> /dev/null; then npm install -g @appnest/readme; fi
created virtual environment CPython3.9.5.final.0-64 in 718ms
  creator CPython3Posix(dest=/builds/megabyte-labs/ansible-roles/androidstudio/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
task: [common:python-requirements] source venv/bin/activate
task: Failed to run task "common:python-requirements": exit status 127
```

**Comment by ProfessorManhattan** [comment]
I tried using `. venv/bin/activate` as well

**Comment by SwitchedToGitlab** [comment]
@ProfessorManhattan try using the following command to use PIP inside the venv:

`venv/bin/python3 -m pip install -r requirements.txt`

This works for me. The issue that you're running into is that each task is run in it's own sub-shell. Dockerfiles have a similar issue and solution as well. 

To test this I used the following Taskfile...note that it is simplified for testing and readability.

```yaml
version: '3'

tasks:

  default:
    - task: create-venv
    - task: ls
    - task: install-packages
    - task: ls

  create-venv:
    cmds:
      - if ! type virtualenv &> /dev/null; then pip3 install virtualenv; fi
      - virtualenv venv

  ls:
    cmds:
      - ls venv/lib/python3.8/site-packages

  install-packages:
    cmds:
      - venv/bin/python3 -m pip install -r requirements.txt
```
### Output
⌬  task                              
task: [create-venv] if ! type virtualenv &> /dev/null; then pip3 install virtualenv; fi
task: [create-venv] virtualenv venv
created virtual environment CPython3.8.10.final.0-64 in 194ms
  creator CPython3Posix(dest=/home/sbrady/prj/dev/oci_images/app/vscode/python3/sandbox/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/sbrady/.local/share/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
task: [ls] ls venv/lib/python3.8/site-packages
_distutils_hack		  pip			pip-21.1.2.virtualenv  setuptools		    setuptools-57.0.0.virtualenv  _virtualenv.py  wheel-0.36.2.dist-info
distutils-precedence.pth  pip-21.1.2.dist-info	pkg_resources	       setuptools-57.0.0.dist-info  _virtualenv.pth		  wheel		  wheel-0.36.2.virtualenv
task: [install-packages] venv/bin/python3 -m pip install -r requirements.txt
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.3-py3-none-any.whl (35 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.3 idna-3.2 requests-2.26.0 urllib3-1.26.6
WARNING: You are using pip version 21.1.2; however, version 21.2.1 is available.
You should consider upgrading via the '/home/sbrady/prj/dev/oci_images/app/vscode/python3/sandbox/venv/bin/python3 -m pip install --upgrade pip' command.
task: [ls] ls venv/lib/python3.8/site-packages
certifi				    _distutils_hack	      pip		     __pycache__		setuptools-57.0.0.dist-info   _virtualenv.pth	      wheel-0.36.2.virtualenv
certifi-2021.5.30.dist-info	    distutils-precedence.pth  pip-21.1.2.dist-info   requests			setuptools-57.0.0.virtualenv  _virtualenv.py
charset_normalizer		    idna		      pip-21.1.2.virtualenv  requests-2.26.0.dist-info	urllib3			      wheel
charset_normalizer-2.0.3.dist-info  idna-3.2.dist-info	      pkg_resources	     setuptools			urllib3-1.26.6.dist-info      wheel-0.36.2.dist-info
```

Requirements.txt:
```
requests
```

Please update or re-open the issue if you believe this does not resolve it.


@andreynering I believe this issue can be closed.
