### ISSUE TITLE
Allow `sources` to run other tasks

### ISSUE THREAD

**Issue by dolfelt** [go-task/task#515]
When writing many commands we have a standard way of checking status for each. It would be nice to be able to write a task and use another task to check the status. For example:

```yaml
tasks:
  make:
    status:
      - task: check-file
        vars: { FILE: path/to/file.exe }
    cmds:
      - do command
```

From what I can tell `Status` is just an `[]string` rather than an `[]*Cmd`. https://github.com/go-task/task/blob/master/taskfile/task.go#L16

Thoughts on updating it to work more like `cmds`? What potential pitfalls might occur?

Thanks!
