### ISSUE TITLE
Passing Vars as Params to Task

### ISSUE THREAD

**Issue by mellena1** [go-task/task#52]
With the new 1.4 release and #32, is something like this supported?
```
some-task:
  cmds:
    - task: my-task
       vars: {var1: {{.VAR}}, var2: {{.OTHER_VAR}}}
  vars:
    VAR: $echo "hello"
    OTHER_VAR: $echo "hi" 

my-task:
  cmds:
    - cmd using var1 and var2
  vars:
    var1: val
    var2: val
```

The reasoning behind this is I'm obviously looking to do more intense commands than echoing a string as my values of VAR and OTHER_VAR. So I can compute my value once and pass it to all of the other tasks I'm running.

Thanks for your tool, it's really awesome!
