### ISSUE TITLE
Unexpected `env:` behavior

### ISSUE THREAD

**Issue by d3dc** [go-task/task#520]
- Task version: v3.6.0 (h1:RYrzgAOwuyvE6fR3xMaBzQseYKuE7xwQC4SRrpG4TRU=)
- Operating System: Alpine 3.14

### Example Taskfile showing the issue

```yaml
version: "3"

env:
  TEST: $pwd

cmds:
  default:
      - echo $pwd
      - echo $TEST
```

Task output:
```
task: [default] echo $pwd

task: [default] echo $TEST
/home/jenkins/agent
```

Putting a $ in an env variable will run it as a shell script.

**What?**

**Comment by d3dc** [comment]
For reference, here's what a regular shell does:
```
❯ TEST="$pwd"
❯ echo $pwd

❯ echo $TEST

```

**Comment by d3dc** [comment]
FWIW, this was a 1.4 feature that is nowhere to be documented.

```
v1.4.1 - 2017-07-15

Allow use of YAML for dynamic variables instead of $ prefix
VAR: {sh: echo Hello} instead of VAR: $echo Hello
```

**Comment by andreynering** [comment]
Hi @d3dc, thanks for opening this issue!

I think you made a mistake on your example Taskfile, specifically on the `echo $pwd` part. There's a `pwd` command and a `$PWD` env, but the `$pwd` env does not exist since envs are case sensitive.

```yaml
version: '3'

tasks:
  echo:
    env:
      TEST: {sh: pwd}
    cmds:
      - echo $TEST
      - echo $(pwd)
      - echo $pwd
      - echo $PWD
```

```shell
$ task echo
task: [echo] echo $TEST
/Users/andrey/Developer/andrey/task
task: [echo] echo $(pwd)
/Users/andrey/Developer/andrey/task
task: [echo] echo $pwd

task: [echo] echo $PWD
/Users/andrey/Developer/andrey/task
```

Regarding the ability to declare dynamic variables with `$`, that's deprecated and will be removed at some point. I recommend everyone to use `{sh: ...}`.
