### ISSUE TITLE
Interpolated variables should be factored into checksum

### ISSUE THREAD

**Issue by Porges** [go-task/task#548]
- Task version: v3.7.0 (h1:8dDFv12/Lxi6PHkYNIIm7N6v6oRGxePpLK67LuMh/Rs=)
- Operating System: Linux 2d7a33008788 5.10.43.3-microsoft-standard-WSL2 # 1 SMP Wed Jun 16 23:47:55 UTC 2021 x86_64 GNU/Linux

### Example Taskfile showing the issue

```yaml
version: '3.7'

run: when_changed

vars:
  VERSION: 1

tasks:
  generate-file:
    sources:
    - base.txt
    cmds:
    - <base.txt sed -e 's/VERSION/{{.VERSION}}/g' > versioned.txt
```

When changing `VERSION` from `1` to `2`, this should cause `generate-file` to re-run. At the moment it doesn’t because interpolated variables are not incorporated into the checksum.

**Comment by Porges** [comment]
Also, ideally, the task itself would be checksummed somehow, so that if I change the commands it will re-run.

**Comment by ghostsquad** [comment]
I found myself changing my task file, and later wondering how I was going to invalidate the cache automatically. It's not really just vars, it's actually the entire task definition. I imagine that you may want to checksum the output of `--dry-run` as part of the caching behavior, or at least some flag to enable or disable that.

I'm curious what people think about having the _default_ behavior include the task definition itself (and variable values) as part of the checksum, with a flag to disable 1 or both of those?

**Comment by ahus1** [comment]
@ghostsquad: +1 for making the task definition part of the checksum (not sure about interpolations as a new user yet). I admit that I'm new to task, still the first thing I did was adding `Taskfile.yaml` as one of the sources (which would build to much).

**Comment by ghostsquad** [comment]
For now, I'm including Taskfile.yml itself in `sources`. This is equivalent of using a sledge hammer when a rubber mallet would be sufficient.

**Comment by ahus1** [comment]
> This is equivalent of using a sledge hammer when a rubber mallet would be sufficient.

I know, and it wasn't fun. Next iteration was `task -f taskname`, but found that it also forces the dependencies of a task to run. 

Current iteration: a small script that extracts each task from the `Taskfile.yaml` and use that as a source: once the task changes, run the task again. Works OK for now. 

```
# Taskfile.yaml
tasks:
  split:
    desc: Split Taskfile to one-file-per-task for dirty checking
    run: once
    cmds:
      - bash -c ./split.sh
    sources:
      - Taskfile.yaml
      - split.sh
    silent: true

  ipchange:
    deps:
      - split
    cmds:
      # ...
    sources:
      - .task/subtask-{{.TASK}}.yaml
```

```
# split.sh
set -euo pipefail
yq --help > /dev/null
mkdir -p .task
rm -f .task/subtask-*.yaml
for i in $(yq -M e '.tasks | keys' Taskfile.yaml); do
   yq -M e ".tasks.${i}" Taskfile.yaml > .task/subtask-${i}.yaml
done
```

**Comment by andreynering** [comment]
Hi @ahus1,

Have you tried my suggestion done here? https://github.com/go-task/task/issues/548#issuecomment-941679515

I believe that's what you're are looking for.

**Comment by ahus1** [comment]
@andreynering - your suggestion will solve AFAIK the problem when a variable changes, as the labels changes with the variable. I don't know what will happen if the variable changes back to the old value: Would it then run again, or will the state with the old variable value / label name will be still there and it will not run?

This thread evolved form interpolating variables to also include the body of the task definition, so that whenever the definition changes, the task should run again. The variable/label approach doesn't cover that, so I looked for something else. So I came up with the idea to split the taskfile by tasks, and then use that as a "sources" element. I did some iterations with that, and it looks ok for me. although a bit verbose.

**Comment by ghostsquad** [comment]
I think what is realistically needed is a "cache key". I don't know what _else_ that `label` does. But generally, if we are able to derive our own "key" to tied to the task itself, that means that we can invalidate the cache arbitrarily.

**Comment by aminya** [comment]
I tried using `label: {{.TASK}}-{{.VARIABLE}}`, but still the task is incorrectly skipped. Is there a way to fix this issue? 
I have to disable the whole caching because of this bug

**Comment by dcecile** [comment]
My workaround is to add a silent command that does nothing except reference the used variables:

```yaml
      - cmd: 'true # /{{.WATCH}}/{{.RESTART}}/{{.MODE}}/{{.TEST}}/{{.NAME}}/{{.ARGS}}/'
        silent: true
```

So it seems like interpolated variables are factored in with 3.29.1? I think my issue was some of my other usages weren't factored in.

<details>
<summary>Other usages</summary>

```yaml
      - task: :watchman:client
        vars:
          WATCH: '{{.WATCH}}'
          RESTART: '{{.RESTART}}'
          MODE: executable
          COMMAND: build/target/{{.MODE}}/intertwine-{{.NAME | trimSuffix "-rs"}}{{if eq .TEST "true"}}-test{{end}} {{.ARGS}} {{.CLI_ARGS}}
```

</details>

**Comment by aminya** [comment]
I fixed this issue in 
https://github.com/go-task/task/pull/1401

It just needs addressing some comments otherwise it works as expected.

**Comment by reitzig** [comment]
FWIW: The docs say (emphasis mine):

> `when_changed` only invokes the task **once for each unique set of variables** passed into the task

As a newcomer, it was _quite_ surprising to me that changes in `vars` did not cause a re-run!

**Comment by FredrikAugust** [comment]
Hey! Are there any updates to this? I just ran into this, and as others have pointed out, it's a little confusing.

```yaml
      - for:
          var: APPS
        task: upgrade_app
        vars:
          APP: "{{ .ITEM }}"
          IMAGE: "{{ .IMAGE }}"
```

This was the offending code. Changes to `"{{ .ITEM }}"` did not cause a re-run. Fixed by setting `label: ` as others suggested:)
