### ISSUE TITLE
pwd -P produces incorrect output

### ISSUE THREAD

**Issue by amancevice** [go-task/task#553]
- Task version: Task version: v3.7.0 (h1:8dDFv12/Lxi6PHkYNIIm7N6v6oRGxePpLK67LuMh/Rs=)
- Operating System: macOS 11.5.1 (Big Sur)

### Example Taskfile showing the issue

Reproduce with the following steps:

```bash
mkdir ~/tmpdir
ln -s ~/tmpdir ~/tmplink
cd ~/tmplink
pwd -P
# => /Users/<user>/tmpdir
```

Using the following Taskfile:

```yaml
version: "3"
tasks:
  default:
    cmds:
      - pwd -P
```

Output is:

```bash
task: [default] pwd -P
/Users/<user>/tmplink
```
