### ISSUE TITLE
Use task variables within a go range template?

### ISSUE THREAD

**Issue by max-sixty** [go-task/task#566]
I'm sure I'm missing something obvious, but tried to figure it out without success for a few minutes.

Is it possible to access an external variable within a template? Here's an example

```yaml
    vars:
      env: '{{default "a b c d" .env}}'
      loc: '{{default "dc1" .loc}}'
    cmds:
      - |
        echo {{.loc}}                        # works 
        {{ range(split " " .env) }}
        echo {{.loc}}—{{.}}                  # fails
        {{- end}}
```

This fails, I think because it's attempting to get `loc` from the context within the `range`, which is just `a`.

Thanks for any ideas!
