### ISSUE TITLE
Allow "default" / "override" semantics for task variables (breaking change)

### ISSUE THREAD

**Issue by smyrman** [go-task/task#57]
I don't assume this is high priority atm., rather something to discuss. I want to propose changing the evaluation order for variables, and introduce default/override semantics when declaring variables. This still relates to changes made through #56.

# Why might this be needed?
I see some potential issues with the current _priority order_ for tasks:

> Variables given while calling a task from another. (See Calling another task above)
> Environment variables
> Variables declared locally in the task
> Variables available in the Taskvars.yml file

Especially the position of `Environment variables` could be very scary and error-prone to collision with values set  in `.bashrc` and similar. Especially if you tend to use _short_ variable names. I propose we deal with this by _replacing_ the documented priority order with a documented _evaluation order_, placing the environment first, accompanied by default/override semantics for variables so that variables are either set if not already set, or overwritten for each level.

# Other implementations
One of the common things in bash/make is to define a _default_ value for a variable through special syntax.

Makefile:
```Makefile
VAR ?= default
```

Bash:
```
VAR=${VAR:-default}
```

# How to implement this in task?
One of the things I like with `task` is that yaml allows a more explicit syntax over special syntax. Now that variables are a map (with "sh:" and "static:" keywords), maybe we could change the evaluation order slightly, and provide a new boolean keyword "ifAbsent". (I was also thinking about replacing "static" with "default" and "override", but then it would not be clear what do do with "sh" values.)

Example Taskfile.yml:
```yaml
 VAL1:
   static: hey
   ifAbsent: true
VAL2:
  sh: echo "hey"
  ifAbsent: true
```

Proposed new documented evaluation order:

1. environment variables
  - first level, ifAbsent value doesn't matter
  - skip template evaluation.
  - resolving of dynamic variables not relevant.
2. Taskvars.yml
  - ifAbsent default: false
  - template evaluation access uncompiled static values from 1 & 2
  - dynamic variables resolved _after_ template compilation
3.  Call
  - ifAbsent default: false
  - template evaluation access resolved values from 1 & 2, uncompiled static values from 3
  - dynamic variables resolved _after_ template compilation
4.  task
  - ifAbsent default: false 
  - template evaluation access resolved values from 1,2 and 3, uncompiled static values from 4
  - dynamic variables resolved _after_ template compilation

The order of 3/4 is a bit _weird_, but it's done to allow access to `Call` variables when compiling task templates. It also means that the task needs to `explicitly` allow variables to be overwritten via Call, environment variables or Taskvars, which I think makes sense. It's like local variables v.s. function parmeters in programming; you want to allow function parmeters to be specified by the caller, but _not_ local vars.

The semantics will be very simple. For each level, set the variable iff:
  - (variable not set) || !ifAbsent

**Comment by andreynering** [comment]
I agree with these changes.

I just dislike `ifAbsent` keyword. If we used it, it should be with underscore: `if_absent`.

Alternatives: `default: true`? `override: false`? (The later may not be clear and possible to implement because `true` shuld be the default).

**Comment by andreynering** [comment]
Maybe that should not be a thing, because one can use the Sprig lib [default function](http://masterminds.github.io/sprig/defaults.html) instead:

```yml
# Taskvars.yml
MY_VAR: '{{default "default_value" .MY_VAR}}'
```

These functions should be better documented on README.

**Comment by smyrman** [comment]
Yeah, I thought about using templates, but then we could no longer do this:
```yaml
# Taskvars.yml
VAR1: "test"
VAR2: "{{.VAR1}}"
```
Allowed by #56.

The PR allows this by giving access to uncompiled _static_ variables when compiling variable values, so the value of `MY_VAR` in your example would _always_ be `'{{default "default_value" .MY_VAR}}'` (as that would be the value of .MY_VAR on template compilation.

Not that we _have_ to have this feature, but it's pretty handy in many cases.

**Comment by smyrman** [comment]
Actually, the "feature" from #56 is pretty limited as it only works for static values with no tempaltes, so probably OK to remove.

**Comment by andreynering** [comment]
OK, keep that feature by now.

No matter how we decide to implement this, I think that feature should keep working.

I want to do some testing in master next week before we release the next version. So we'll have time to fix any issues.

**Comment by smyrman** [comment]
Another thing we could consider (for v2), is to use ordered variables like docker-compose allow through:
```yaml
    environment:
      - VAR1=docer-compose-val1
      - VAR2=docker-compose-val2
```
Then you could allow templated reuse + default semantics.
```yaml
  env:
    - "VAR1={{default task-val1 .VAR0}}"
    - "VAR2={{.VAR1}}-with-suffix"
```

PS! This relates to #76.

**Comment by smyrman** [comment]
A plausible good test-case for defaults found in one of our Taskfiles:
```yaml
tmpl/go-build-for-docker:
  # reusable task to build a static golang binary intended for Docker scratch images
  vars:
    SRC_DIR: cmd/{{.NAME}}          # default value, may be overriden
    TARGET_DIR: {{.NAME}}/build/bin # default value, may be overriden
```

I suppose with templating syntax, it would be:
```
  vars:
    - SRC_DIR={{ default "cmd/"+.NAME  .SRC_DIR }}
    - TARGET_DIR={{ default .NAME+"/build/bin" .TARGET_DIR }}

**Comment by smyrman** [comment]
I believe we can close this. Templating syntax works well enough in practice!

**Comment by saurabheights-ecr** [comment]
I used the above code pieces to set default value for variables using environment variables but it produces error.

Note, I am using taskfile version 3.
```
  test:
    cmds:
      - echo {{.ABC}}
    vars:
#      ABC: '{{default .ENV_TMP+"cmd/" .ABC}}'  # Fails with error template: :1: bad character U+002B '+'
#      ABC: '{{default "cmd/"+.ENV_TMP .ABC}}'  # template: :1: bad number syntax: "+.EN"
#      ABC: '{{default (print .ENV_TMP "def") .ABC}}'  # prints abcdef
```

and called task using `ENV_TMP=abc task test`

I figured it was using go-template syntax, so googled how to do string manipulation in go-template. If you agree, updating documentation on dynamic variables would help.
