### ISSUE TITLE
Inherit all/some tasks from included file

### ISSUE THREAD

**Issue by fgblomqvist** [go-task/task#572]
In my shared Taskfiles, I have two types of tasks:
* Ones that are primarily "utility" tasks that are meant to be used by other tasks
* Ones that are primarily first-degree tasks that are meant to be used by users

Right now I can include a Taskfile by doing something like (the extended format):
```
includes:
  shared:
    taskfile: ../../Taskfile.yml
```

However, in order for the user to be able to use the first-degree shared tasks I still have to redeclare them:
```
tasks:
  install: 
    - task: shared:install
```
This is tedious and can result in a lot of boilerplate.
Therefore, I think it would be handy to be able to directly inherit some/all of the tasks from an included file.

It could look like this:
```
includes:
  shared:
    taskfile: ../../Taskfile.yml
    inherit: true
```
or if you only want to inherit some of the tasks:
```
includes:
  shared:
    taskfile: ../../Taskfile.yml
    inherit: [install, test]
```

And then a user would be able to just call `task install` which would execute a task that would be equivalent to:
```
install:
  - task:
    - shared:install
```

However, inside the taskfile, you'd still have to use the namespace:
```
foo:
  - do things
  - task: shared:install
  - do more things
```

Any thoughts?

**Comment by tylermmorton** [comment]
Hi @fgblomqvist, thank you for the feature request. I could see it being useful to select which tasks are included from files. It could prevent polluting the task list if you have a utility Taskfile that you include in many of your other Taskfiles. 

```yml
includes:
  util:
    taskfile: "../util/Taskfile.yml"
    include: [clean, install]

tasks:
  setup:
    - task: util:clean
    - task: util:install
```

Are you also suggesting the ability to inline certain tasks to remove the parent namespace?
```yml
includes:
  util:
    taskfile: "../util/Taskfile.yml"
    include: [clean, install]
    inline: true

tasks:
  setup:
    - task: clean
    - task: install
```
