### ISSUE TITLE
escape template substitution for task params

### ISSUE THREAD

**Issue by conejo** [go-task/task#58]
I'm using gox to do parallel multiplatform builds, and it takes a parameter which is a text/template value describing the output location and name of the compiled binaries. I'm running into a problem because go-task wants to evaluate the template, and it just needs to be passed through.

buildall task:
`buildall:
  desc: Build 64bit versions for darwin, linux, and windows
  cmds:
          - gox -arch="amd64" -os="darwin linux windows"  -output="./build/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/hello-world/ `

output:
`$ task buildall
gox -arch="amd64" -os="darwin linux windows"  -output="./build/<no value>_<no value>_<no value>" ./cmd/hello-world/
`

how can I escape the template in the task above so the template isn't evaluated by task?

**Comment by smyrman** [comment]
As a hack, you can do this for now:
```yaml
mytask:
  vars:
    OUTPUT: "/build/{{.Dir}}_{{.OS}}_{{.Arch}}"
    ESC_OUTPUT: "{{.OUTPUT}}" # must be defined at same level as OUTPUT, e.g. both in the task, or both in Taskvars
  cmds:
    - gox -arch="amd64" -os="darwin linux windows" -output="{{.ESC_OUTPUT}}" ./cmd/hello-world/
```

@andreynering, do you have another idea for how we might solve this better? E.g. allow something like  `skip_template: true` on tasks/vars?

**Comment by smyrman** [comment]
Actualy, best option is probably to rely on golang template itself for escaping. Try
`{{printf "/build/{{.Dir}}_{{.OS}}_{{.Arch}}"}}` in your command!

**Comment by andreynering** [comment]
Hi @conejo

For now the workaround @smyrman said should work. For the future, we may discuss choosing other delimiters:

```yml
build:
  delims: ["${", "}"]
  cmds:
    - ...
```

I don't know gox well, but you can also have parallel builds with Task (all deps run in parallel):

```yml
build-all:
  deps:
    - task: build
      vars: {OS: windows, arch: 386}
    - task: build
      vars: {OS: windows, arch: amd64}
    - task: build
      vars: {OS: linux, arch: 386}
    - task: build
      vars: {OS: linux, arch: amd64}
    # others

build:
  cmds:
    - go build -o "dist/app_{{.OS}}_{{.ARCH}}
  env:
    GOOS: "{{.OS}}"
    GOARCH: "{{.GOARCH}}"
```

**Comment by conejo** [comment]
Thanks for the speedy assistance! The printf suggestion from @smyrman worked smoothly, and thanks @andreynering for giving me a different perspective and eliminating gox altogether.

**Comment by HeCorr** [comment]
P.S.: I searched a bit more and found a [slightly cleaner alternative](https://stackoverflow.com/a/38941123), but I would still rather be able to specify the delimiters.

```YAML
- "go list -f '{{`{{printf \"%10s\" .Name}}`}}: {{`{{.EmbedFiles}}`}}' {{.PKG}}/..."
```

**Comment by andreynering** [comment]
> is the `delims` feature planned to be implemented soon? Because I would really like to use it here.
> Or at the very least an option to use `${}` alternatively.

@HeCorr Not planned at the moment

**Comment by HeCorr** [comment]
> @HeCorr Not planned at the moment
I see. Thank you for replying!

**Comment by jubr** [comment]
Adding my $0.02: I'd also very much like to be able to use something like `delims: ["${", "}"]`!

This will allow you to get rid of a lot of `'` or `"` in your Taskfile.yml, since without stringification `{{` at the beginning of a value is yaml-interpreted as the start of two objects. It's an unfortunate coincidence that Go templating chose those delimeters.

```
tasks:
  helm:push:*:*:
    vars: 
      CHART: '{{index .MATCH 0}}'
      VERSION: '{{index .MATCH 1}}'
```
could then become:
```
delims: ["${{", "}}"]
tasks:
  helm:push:*:*:
    vars: 
      CHART: ${{index .MATCH 0}}
      VERSION: ${{index .MATCH 1}}
```

This might not seem much, but imagine all the other places where you suddenly do not have to stringify anymore! This can result in cleaner yaml files that are easier to write and read.

@Other Readers: If you agree, please 👍 as well, tnx!
