### ISSUE TITLE
Color doesn't work in prefixed output mode

### ISSUE THREAD

**Issue by cameronbrill** [go-task/task#583]
- Task version: 3.3.0
- Operating System: Mac OS Big Sur Version 11.5.2 (20G95)

### Example Taskfile showing the issue

```yaml
  frontend:start:
    deps:
      - task: f:styles
      - task: f:start
  f:start:
    dir: frontend
    cmds:
      - react-scripts start
  f:styles:
    dir: frontend
    cmds:
      - tsm src -w
```
where tsm is typed-scss-modules (https://github.com/skovy/typed-scss-modules)
