### ISSUE TITLE
Adding switch assignments

### ISSUE THREAD

**Issue by kendfss** [go-task/task#587]
Summary
---
In creating build systems it can be handy to tackle operating system sensitive commands using brief logic segments instead of multiple files. To that end I would like to propose a syntax for switching behaviour conditionally.
Note:
- This differs from status/preconditions because the goal here is to construct parameters as opposed to checking state/outcomes.

I guess it could be worth making variables from other files easy to access (if they aren't already)
Sorry for any errors (new to yaml), and/or if I missed this in the docs!

Here are some options

- Basic:
  ```yaml
  switch:
    trigger: {{.variable}}
    case1:
      match: {{variable}}
      return: {{variable}}
    case2:
      match: {{variable}}
      return: {{variable}}
    # ...
    caseN:
      match: {{variable}}
      return: {{variable}}
    else: # perhaps "failure" is a better term? "default" is taken, but perhaps could be reused. probably not worth the hassle though - down the line
      return: {{variable}}
  ```

- Using lists (instead)?
  ```yaml
  switch:
    trigger: {{.variable}}
    cases:
      - match: {{variable}}
        return: {{variable}}
      - match: {{variable}}
        return: {{variable}}
      # ...
      - match: {{variable}}
        return: {{variable}}
      - else: # perhaps "failure" is a better term? "default" is taken, but perhaps could be reused. probably not worth the hassle though - down the line
        return: {{variable}}
  ```

- Incorporating dynamism:
  ```yaml
  switch:
    trigger: {{.variable}}
    cases:
      - match: {{variable}}
        return:
          sh: cmd arg1 arg2 ... argN
      # ...
      - match: {{variable}}
        return:
          sh: cmd arg1 arg2 ... argN
      - failure:
        return:
          sh: cmd arg1 arg2 ... argN
  ```

Examples
---
- In the following example I am going to try to get the name of the current directory in a way that makes sense with respect to Linux, Darwin, and Windows (powershell).
  ```yaml
  vars:
    projname:
      switch:
        trigger: {{OS}}
        cases:
          - match: darwin
            return:
              sh: basename "$(pwd)"
          - match: linux
            return:
              sh: basename "$(pwd)"
          - else: #windows
              return:
                sh: [System.IO.Path]::GetFileName($(Get-Location))
  ```

- Or (perhaps less dubiously):
  ```yaml
  vars:
    projdir: "path/to/project/root"
    projname:
      switch:
        trigger: {{OS}}
        case1:
          match: darwin
          return:
            sh: basename {{.projdir}}
        case2:
          match: linux
          return:
            sh: basename {{.projdir}}
        fallback: #windows
          return:
            sh: split-path {{.projdir}} -leaf
  ```

Suppose you want to create manpages:
  ```yaml
  version: '3'

  tasks:
    docs:
      switch:
        target: {{OS}}
        case1:
          match: linux
          return:
            cmds:
              - sudo pandoc man_page.md -s -t man -o /usr/local/man/man1
              - mandb
        case2:
          match: darwin
          return:
            cmds:
              - sudo pandoc man_page.md -s -t man -o /usr/local/share/man/man1
   ```

- Perhaps the `cmds` should contain the `switch`?
  ```yaml
  tasks:
    docs:
      cmds:
        switch:
          # etc
  ```
