### ISSUE TITLE
Dynamic variables are being evaluated before dependencies are run

### ISSUE THREAD

**Issue by srohr-luther** [go-task/task#591]
- Task version: 3.9.0, 3.9.0
- Operating System: EndeavourOS, Windows Server 2019 Datacenter

While designing our build pipeline based on task I stumbled over the following issue. I would expect that any dependencies are executed before the task itself and that dynamic variables can be created from artifacts of those dependent tasks. At least from a user perspective it would make sense I think.

I added an example with preconditions which works as expected and I would expect dynamic variables behaving the same way.

### Example Taskfile showing the issue

```yaml
version: "3"

tasks:
  greeting:
    cmds:
      - echo "Hello World!" > greeting.txt
  default:
    deps: [greeting]
    cmds:
      - echo "$GREETING"
    env:
      GREETING:
        sh: head -n 1 greeting.txt
```
### Expected output

```txt
task: [greeting] echo "Hello World!" > greeting.txt
task: [default] echo "$GREETING"
Hello World!
```

### Actual output

```txt
head: cannot open 'greeting.txt' for reading: No such file or directory
task: Command "head -n 1 greeting.txt" failed: exit status 1
```

### Example Taskfile with preconditions

```yaml
version: "3"

tasks:
  greeting:
    cmds:
      - echo "Hello World!" > greeting.txt
  default:
    deps: [greeting]
    cmds:
      - cat greeting.txt
    preconditions:
      - test -f greeting.txt
```
