### ISSUE TITLE
Do not show label instead of task name in some places like `--list`

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#603]
- Task version: 3.9.0
- Operating System: Ubuntu

### Example Taskfile showing the issue

```yaml
---
version: '3'

vars:
  REPOSITORY_SUBTYPE: config
  REPOSITORY_TYPE: npm

tasks:
  one:
    cmds:
      - task: two
      - pip3 install ansible

  two:
    interactive: true
    label: three
    desc: Hey
    cmds:
      - poetry env info --path
      - poetry --help
      - source "$(poetry env info --path)/bin/activate"


```

When assigning a label to a task, the `task --list` is updated with the task with the new label. However, when you attempt to run the task by running `task [label_name]`, task fails to recognize the task.

Also, normally `task` alphabetizes the list shown in `task --list`. However, labeled items are not sorted alphabetically.

I propose that we:

1. Allow the user to run tasks by specifying their label name (e.g. `task label_name`)
2. Alphabetize the `task --list` with the label names included
