### ISSUE TITLE
Add Support for Hiding Entries from task --list

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#604]
I am using task for many different types of projects. At first I tried generating the Taskfiles for each individual project type but it quickly became confusing because I was using a templating engine and that interfered with YML parsers/autofixers as well as the Task VSCode plugin.

So, currently, I'm including all of my taskfiles which solves the issues. However, with this approach, when I run `task --list` I get shown items that have nothing to do with the current project. I propose that we add a new parameter called `when` or `label_when` that allows you to programmatically determine whether or not to print the item in `task --list`. I could probably handle this with an NPM wrapper script but it would be nice to see the feature incorporated in Task. I actually already hired a developer who supposedly programmed this feature --- the code is in this repository: https://github.com/Pranjalya/task

**Example:**
```
---
version: '3'

vars:
  PROJECT_TYPE: python

tasks:
  one:
    desc: One task
    when: {{eq .PROJECT_TYPE "nodejs"}}
    cmds:
      - echo Hey
```

In the example above, the task named `one` would be hidden from `task --list` since the `when:` option is falsey.
