### ISSUE TITLE
Incorporate a Prompt System

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#606]
Sometimes a task requires input from a user. For example, if we want to provide a wrapper for a long Docker command to launch a test environment in anyone of the 21 supported operating systems, we might want to prompt the user for which operating system they would like to run and let Task handle building the Docker command to run.

The most seamless approach I came up with to solving this was to incorporate the following library: https://github.com/AlecAivazis/survey. I had a developer create this feature and the code is here: https://github.com/Pranjalya/task/commit/3d0d70d01ddb0974ec93444f40f45bb9a28c5ef7

A sample `Taskfile.yml` might look something like this:

```
version: '3'

vars:
  VARIABLE: variable

tasks:
  prompt_test:
    prompt:
      type: MultiSelect
      message: What day is it? #notice how the 'message' key is lowercased even though survey requires it to be capitalized
      options:
        - msg: Sunday
        - Monday
        - msg:
            sh: date +%u # This should show today's full name as a possible answer
        - {{.VARIABLE}} # This should show the variable's name - Task currently processes all parts with Go template so just follow the same format
      validate:
        sh: '[[ "{{.ANSWER}} == "Tuesday" ]]'
      answer: # this should be an instance of a regular Task
        cmds:
          - echo {{.ANSWER}}
```

If we were to incorporate this, then it would also be trivial to open a prompt if the command `task` were entered by itself. This could help users new to a project start using task quicker. The feature is implemented on this fork: https://github.com/Pranjalya/task
