### ISSUE TITLE
shellQuote fails when passed an emptry string

### ISSUE THREAD

**Issue by justafish** [go-task/task#609]
- Task version: 3.9.0
- Operating System: Linux

### Example Taskfile showing the issue

```yaml
version: '3'
tasks:
  blah:
    cmds:
      - |
        {{}}
        if [ "" == {{shellQuote .test}} ] || [ {{shellQuote .test}} == "true" ]; then
          echo "Yes"
        fi
```

- `task test="true" blah` outputs `Yes`
- `task test="" blah` outputs `Yes` fails
   ```
   [blah] 1:4: == must be followed by a word
   [blah] 1:18: not a valid test operator: true
   [blah] 1:18: true must be followed by a word
   ```

**Comment by duckbrain** [comment]
As a workaround for bash, you could prefix your string with double quotes to concatenate an empty string.

```yaml
version: '3'
tasks:
  blah:
    cmds:
      - |
        if [ "" == ""{{shellQuote .test}} ] || [ ""{{shellQuote .test}} == "true" ]; then
          echo "Yes"
        fi
```

```
$ task test="" blah
task: [blah] if [ "" == "" ] || [ "" == "true" ]; then
  echo "Yes"
fi

Yes
$ task test="test" blah
task: [blah] if [ "" == ""test ] || [ ""test == "true" ]; then
  echo "Yes"
fi
```
