### ISSUE TITLE
`env` appears broken as values are set with extra square braces

### ISSUE THREAD

**Issue by smyrman** [go-task/task#61]
Minimal Taskfile.yml:

```yml
default:
  env:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: "0"
  cmds:
    - echo "GOOS='$GOOS' GOARCH='$GOARCH' CGO_ENABLED='$CGO_ENABLED'"
```

First, ensuring that task is up-to-date:
```sh
 % go get -u -v github.com/go-task/task/cmd/task
github.com/go-task/task (download)
```

When running task, I get extra curly braces and a space around the env value (`{`,` }`):
```sh
% task                                         
task: No argument given, trying default task
echo "GOOS='$GOOS' GOARCH='$GOARCH' CGO_ENABLED='$CGO_ENABLED'"
GOOS='{linux }' GOARCH='{amd64 }' CGO_ENABLED='{0 }'
```

I would have expected the following instead:
```sh
% task                                         
task: No argument given, trying default task
echo "GOOS='$GOOS' GOARCH='$GOARCH' CGO_ENABLED='$CGO_ENABLED'"
GOOS='linux' GOARCH='amd64' CGO_ENABLED='0'
```
