### ISSUE TITLE
Dynamic variable execution environment does not inherit globally set environment variables

### ISSUE THREAD

**Issue by kerma** [go-task/task#630]
It may be as designed, but it's been bugging me for a while and creates quite a bit of confusion. So if nothing else, I'll document the behavior here.

See the following example:

```yaml
version: '3'
env:
  NAME: "giselle"
tasks:
  default:
    vars: 
      person:
        sh: echo $NAME
    cmds:
      - echo "Hello $NAME"
      - echo "Hello {{ .person }}"
    silent: true
```
Output:
```
Hello giselle
Hello
```

That makes dynamic variables a bit useless in places where you need to pass auth or other relevant info via env.
