### ISSUE TITLE
when_changed does not work as intended

### ISSUE THREAD

**Issue by rfc2119** [go-task/task#637]
- Task version: v3.9.2 (h1:lej66zb32AL491eELVc9JK7Hey8l4AtyBaQ1pJ4Iu7E=)
- Operating System: Arch Linux

### Example Taskfile showing the issue

This example is copied straight from the [documentation](https://taskfile.dev/#/usage?id=limiting-when-tasks-run)
```yaml
version: '3'

tasks:
  default:
    cmds:
      - task: generate-file
        vars: { CONTENT: '1' }
      - task: generate-file
        vars: { CONTENT: '2' }
      - task: generate-file
        vars: { CONTENT: '2' }

  generate-file:
    run: when_changed
    deps:
      - install-deps
    cmds:
      - echo {{.CONTENT}}

  install-deps:
    run: once
    cmds:
      - sleep 5 # long operation like installing packages
```

### Indented behavior/output
```
$ task -v generate-file
task: "generate-file" started
task: "install-deps" started
task: [install-deps] sleep 5
task: "install-deps" finished
task: [generate-file] echo 1
1
task: "generate-file" started
task: "install-deps" started
task: [install-deps] sleep 5
task: "install-deps" finished
task: [generate-file] echo 2
2
task: "generate-file" finished
```
### Actual output
```
$ task -v generate-file
task: "generate-file" started
task: "install-deps" started
task: [install-deps] sleep 1
task: "install-deps" finished
task: [generate-file] echo 

task: "generate-file" finished
```
