### ISSUE TITLE
Env var doesn't work at start of string, but does in the middle

### ISSUE THREAD

**Issue by ambis** [go-task/task#642]
- Task version: 3.9.2
- Operating System: macOS 12.1

When a global `vars` value starts with a dollar/variable, task fails. I have tried escaping it with $$ and \\$ but no help.

### Example Taskfile showing the issue (version that works)

```yaml
version: '3'
vars:
  FOO: "does work ${FOO}"
tasks:
  default:
    cmds:
      - echo {{.FOO}}
```

When you run the above taskfile:

```
FOO=yes task -t Taskfile.works.yml
task: [default] echo does work ${FOO}
does work yes
```

### Example Taskfile showing the issue (version that does NOT work)

```yaml
version: '3'
vars:
  FOO: "${FOO} <- does not work"
tasks:
  default:
    cmds:
      - echo {{.FOO}}
```

When you run the above taskfile:

```
FOO=nowork task -t Taskfile.nowork.yml
open /tmp/-: no such file or directory
task: Command "{FOO} <- does not work" failed: exit status 1
exit 1
```

My usecase which fails:

`TAG: "${CI_REGISTRY_IMAGE}:latest"`

**Comment by ambis** [comment]
My current workaround:

```yaml
vars:
  CI_REGISTRY_IMAGE:
    sh: echo "${CI_REGISTRY_IMAGE}"
  TAG: "{{.CI_REGISTRY_IMAGE}}:latest"
```
