### ISSUE TITLE
Vars lazily evaluated since 3.10?

### ISSUE THREAD

**Issue by minitauros** [go-task/task#646]
- Task version: v3.10
- Operating System:

I assume that since 3.10 the vars defined in `vars` are lazily evaluated. We are running into some minor issues because of the following.

### Example Taskfile showing the issue

```yaml
version: '3'
silent: false
vars:
  PWD: $(pwd)
tasks:
  before:
    desc: Task in 3.9
    cmds:
      # {{.PWD}} = "/x/y/z"
      - echo "{{.PWD}}" 
      # {{.PWD}} = "/x/y/z"
      - echo '{{.PWD}}'
  after:
    desc: Task in 3.10
    cmds:
      # {{.PWD}} = "/x/y/z"
      - echo "{{.PWD}}"
      # {{.PWD}} = "$(pwd)"
      - echo '{{.PWD}}'
```

In other words, it looks like since 3.10 the value in `vars` is being copied literally into the placeholder instead of being evaluated first. This causes a few of our pipelines to break, because now instead of receiving a directory name as a value, they literally receive the string `$(pwd)` as a value.

I don't know if this needs a fix, because we can also replace our single quotes by double quotes and it'll still get evaluated correctly. But maybe it's good to know that this happened.
