### ISSUE TITLE
Grouped output with GitHub Actions friendly begin/end markers

### ISSUE THREAD

**Issue by janslow** [go-task/task#647]
Hi, thanks for the awesome project!

I was wondering if you'd consider supporting a variant of the `group` output, but also emitting a `::group::$TASK` line before the group and `::endgroup::` after it, so that [GitHub Actions will group all the output for a single task and allow it to be collapsed](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#grouping-log-lines).

For example, if there's a Taskfile like this:

```yaml
# Taskfile.yml
output: github_actions
tasks:
  default:
    cmds:
      - "echo 'Hello, World!'"
```

I'd expect `task default` to emit the following:

```bash
::group::default
Hello, World!
::endgroup::
```

Alternatively (as a non GitHub Actions-specific solution), adding support for custom begin/end markers, e.g.,

```
# Taskfile.yml
output:
  group:
    begin: '::group::%s'
    end: '::endgroup::'
```

I'm happy to put together a PR for this, if you'd consider reviewing it.

**Comment by kerma** [comment]
Thanks for the report @janslow ! Can you provide a more complex example where the same could not be achieved with just echoing the required output in the commands list?

```yaml
tasks:
  default:
    cmds:
      - echo "::group::default"
      - "echo 'Hello, World!'"
      - echo "::endgroup::"
```

Any reason why this won't work?

**Comment by janslow** [comment]
> Any reason why this won't work?

Mainly because you probably only want this behaviour when running in CI (e.g., I currently set `--output=group` in CI, because I want `interleaved` when running locally).

Additionally, it's going to make the tasks much more complex (because there's build and output logic mixed together) and (on larger taskfiles) a developer could forget to add one/both of those commands.

**Comment by janslow** [comment]
That seems like it would prevent the use of Task dependencies and other features of Taskfile.

For example, 

```yaml
tasks:
  default:
    vars:
       TAG:
          sh: "git log -n 1 --format=%h"
    deps:
      - prerequisites
    cmds:
      - echo 'Hello, {{ .TAG }}'
  prerequisites:
    cmds:
      - echo 'Downloading Prerequisites'
  ci:default:
    env:
       TAG:
          sh: echo "$GITHUB_SHA"
    cmds:
      - echo "::group::default"
      - task: default
         vars:
            TAG: 
              sh: echo "$GITHUB_SHA"
      - echo "::endgroup::" 
```

Would output:

```
::group::default
Downloading Prerequisites
Hello, 1.2.3
::endgroup::
```

Rather than:

```
::group::prerequisites
Downloading Prerequisites
::endgroup::
::group::default
Hello, 1.2.3
::endgroup::
```

It seems like you'd need to have two independent taskfiles to use this approach.

**Comment by andreynering** [comment]
Hi @janslow,

I didn't know GitHub Actions had this feature. Do other CI systems support something similar as well?

I think I like the idea of having this possibility. Not specifically to GitHub Actions but customizable to potentially include other use cases as well, as you suggested:

```yaml
output:
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'
```

In theory this would not be complex to implement, and I'd say a PR is welcome.
