### ISSUE TITLE
Can redirect kubectl stdout to file

### ISSUE THREAD

**Issue by varac** [go-task/task#649]
Hi, 
first of all, thanks for this, I am relieved that I can hopefully stop using Makefile, finally!

I'm trying to redirect stdout to a file and it works with echo, but not with kubectl:

```
❯ task        
task: [default] echo "hi" > /tmp/test.txt
task: [default] kubectl create configmap test --dry-run=client -o yaml > test2.txt
error: write /dev/stdout: permission denied
task: Failed to run task "default": exit status 1
```

Any ideas why this happens ?

- Task version: 3.10.0
- Operating System: PopOS 21.10 (Ubuntu-based)

### Example Taskfile showing the issue

```yaml
version: '3'
tasks:
  default:
    cmds:
      - echo "hi" > /tmp/test.txt
      - kubectl create configmap test --dry-run=client -o yaml > test2.txt
```
