### ISSUE TITLE
Allow global variables in Taskfile.yml

### ISSUE THREAD

**Issue by javipolo** [go-task/task#66]
It would be cool to have global variables defined inside the Taskfile, so we dont need to necesary tamper with two files

It could be an special section just for variables, like:

```
global_vars:
    hello: 'world'
    foo: 'bar'
    
hola:
    cmds: 
        - echo Hello {{.hello}}
```

/enhancement

**Comment by zbindenren** [comment]
I like that idea. With that it would be possible to overwrite them by GOOS.

**Comment by andreynering** [comment]
@zbindenren That should be already possible with, e.g.: `Taskvars.yml` and `Taskvars_windows.yml`.

I think we'll have to introduce an alternative layout with `tasks` in a deeper level to solve this + import of Taskfiles (#54)

```yml
# Taskfile.yml

import:
  - "another/dir"
  - "Another_taskfile.yml"

vars:
  FOO: bar
  BAR: baz

tasks:
  build:
    cmds:
      - go build ...
```

I'd prefer to keep everything in the root level, but that not clear and easy.
