### ISSUE TITLE
"default" task from included taskfile should be executed when no task name is provided

### ISSUE THREAD

**Issue by ankushg** [go-task/task#661]
I really like the behavior that
> If you omit a task name, “default” will be assumed.

Unfortunately, it doen't seem to play well with included taskfiles.

For example, if I have a root `Taskfile.yml` with the following contents:
```yaml
version: '3'

includes:
  main: .taskfiles/main.yml
```

and `.taskfiles/main.yml`:
```yaml
version: '3'

tasks:
  default:
    - task: build
    - task: assets

  build:
    cmds:
      - go build -v -i main.go

  assets:
    cmds:
      - minify -o public/style.css src/css
```

I would like to run something like `task main`  and have it automatically run `task main:default`

Currently though, I need to explicitly run `task main:default`
