### ISSUE TITLE
Dotenv file changes are not reflected in upcoming tasks

### ISSUE THREAD

**Issue by Saare** [go-task/task#663]
- Task version: Task version: v3.10.0 (h1:vOAyD9Etsz9ibedBGf1Mu0DpD6V0T1u3VG6Nwh89lDY=)
- Operating System: OSX 12.1

### Example Taskfile showing the issue

```yaml
version: '3'

dotenv: ['.env']

tasks:
  create-env:
    cmds:
      - echo MYVAR=my_value > .env

  do-it:
    deps: [create-env]
    cmds:
      - echo $MYVAR
```

Reprod:
```bash
% task do-it
task: [create-env] echo MYVAR=my_value > .env
task: [do-it] echo $MYVAR

% task do-it
task: [create-env] echo MYVAR=my_value > .env
task: [do-it] echo $MYVAR
my_value
```

NOTE that it also happens when the tasks are not dependent on each other, but called sequentially:
```yaml
    cmds:
      - task: create-env
      - echo $MYVAR
```
