### ISSUE TITLE
"includes" path does not resolve {{.HOME}} variable

### ISSUE THREAD

**Issue by piotrkardasz** [go-task/task#670]
- Task version: v3.10.0
- Operating System: Ubuntu

### Example Taskfile showing the issue

```yaml
version: '3'

includes:
  action:
    taskfile: "{{.HOME}}/common/Taskfile.yml"
```

I would like to include Taskfile from the home folder but I am getting an error

```
stat /common/Taskfile.yml: no such file or directory
```

When I put `taskfile: "/home/username/common/Taskfile.yml"` it working correctly it looks like a `.HOME` and variables are not resolved in this case
