### ISSUE TITLE
Feature Request: `include` to support remote files via https, git

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#672]
I would like to include remote task files like a library. Support for git as well as HTTP would be cool, allowing for `@<git-ref>` syntax for the ability to pin to a specific revision.

Allowing for private access should be allowed as well. SSH would handle itself (as it can be configured with `~/.ssh/config`, but for HTTPS, you may need ways to support various auth mechanisms.

**Comment by andreynering** [comment]
Hi @ghostsquad, thanks for opening this issue.

This was asked before, but I decided against it due to the complexity it would bring to the codebase, specially with regard to caching of these included files.

**Comment by ghostsquad** [comment]
Here's the implementation using Taskfile itself. I don't think this is very complicated. 

> `Taskfile.yaml`

```yaml
includes:
  dummy:
    taskfile: .task/inc/DummyTaskfile.yaml
    optional: true

tasks:
  inc:install:
    dir: .task/inc
    env:
      TARGET: DummyTaskfile.yaml
      DL_URL: https://gist.githubusercontent.com/ghostsquad/92ff69dbae49aad86f8db27703b8ce92/raw/8f442d1a1cde3a854650c58d15f2520e3678f68c/DummyTaskfile.yaml
      SHA256SUM: 0766de3abe477a20602a81e758f8a221e5fad2563bde25503de72e5a256b3eb8
    cmds:
      - mkdir -p .external-taskfiles
      - curl -SLO $DL_URL -o $TARGET
      - sha256sum $TARGET
      - echo "$SHA256SUM *$TARGET" | sha256sum -c -
    status:
      - test -f DummyTaskfile.yaml
      - echo "$SHA256SUM *$TARGET" | sha256sum -c -
    # OR
    #sources:
    #  - ../../Taskfile.yml
    #generates:
    #  - DummyTaskfile.yaml
```

> `.gitignore`

```.gitignore
# external taskfiles
/.external-taskfiles
```


I suppose now that this is in the public eye, yes, this pattern could be repeated, abstracted into cleaner/simpler "function" tasks. But hopefully you can see that this actually isn't very hard or complex at all.

This is very common pattern when creating docker files.

Here's some links in that regard:
https://docs.sysdig.com/en/docs/sysdig-secure/scanning/manage-scanning-policies/dockerfile-gate-and-triggers-deep-dive/
https://gitlab.com/gitlab-org/cluster-integration/helm-install-image/-/merge_requests/5/diffs#6651ddff6eb82c840ced7c1dddee15c6e1913dd4_21_7

@andreynering would you mind if this issue was either re-opened or should I start a discussion instead?
