### ISSUE TITLE
Template a file to destination

### ISSUE THREAD

**Issue by megakoresh** [go-task/task#673]
Hello, maybe I just couldn't find how to do it, but I would like to have a feature that could template a file to some destination. Right now we can only template under the `cmd` field, so all I can do for now is this:

```yaml
version: "3"

tasks:
  vars:
    HELLO: world
  cmds:
    - |
      cat <<EOF > destination.txt
      Hello {{ .HELLO }}
      EOF
```

But for large files it's impractical. It would be really good if we could supply a source template file and go-task would template it to destination. It doesn't have to be part of the Taskfile spec. For example adding a task command would work too - e.g.

```sh
task --template source.tpl > destination.txt
```

This may be actually even better than making a separate field in taskfile because it's more versatile. Then in taskfile I could simply write

```yaml
version: "3"

tasks:
  vars:
    HELLO: world
  sources:
    - source.tpl
  cmds:
    - task --template source.tpl > destination.txt
```

I think it fits the overall idea of go-task quite well and it would be really nice to use this tool for templating various configurations. Right now we need to use separate tool for that (ansible) which is quite painful to set up compared to go-task.

**Comment by tylermmorton** [comment]
Hi @megakoresh! I've run into a similar problem on another project and have been working on a tool separate from task. I hope its not completely inappropriate for me to plug it here. https://github.com/knitcodegen/knit

```yml
version: '3'

tasks:
  generate:
    cmds:
      - |
         knit generate \
           --input="vars.yml" \
           --template="source.tpl" > destination.txt
    sources:
      - vars.yml
    generates:
      - destination.txt
```
