### ISSUE TITLE
Skipping echo in the cmds incase of special characters

### ISSUE THREAD

**Issue by najamkhn** [go-task/task#684]
- Task version: v3.11.0 (h1:eCcCe1cKyta4YnGQYLo2FriPS9h7fFS8XBVW6QvWEV4=)
- Operating System: Mac OS v11.6.1 (20G224)

### Example Taskfile showing the issue

```yaml
version: '3'

env:
  LANG: 'en'
  COUNTRY: 'gb'

tasks:
  build:
    cmds:
      - echo "hello"
      - echo "parse: ${LANG}"
      - echo $COUNTRY    
    silent: true
```

## Output: 
```
hello
gb
```

## Expected Output:
```
hello
parse: en
gb
```

**Comment by andreynering** [comment]
Hi @najamkhn,

This is an YAML parse problem. You need to quote that command in single quotes:

```yaml
version: '3'

env:
  LANG: 'en'
  COUNTRY: 'gb'

tasks:
  build:
    cmds:
      - echo "hello"
      - 'echo "parse: ${LANG}"'
      - echo $COUNTRY    
    silent: true
```
