### ISSUE TITLE
Feature: OS specific task files with resulting overwrite

### ISSUE THREAD

**Issue by zbindenren** [go-task/task#7]
Hi

The following could be a nice feature:

Let's say we have 3 Task files in our repository:

# Taskfile.yml
```yaml
build:
  cmds:
    - go build -v -i main.go
assets:
  cmds:
    - ls
```

# Taskfile_windows.yml
```yaml
assets:
  cmds:
    - dir
```

# Taskfile_darwin.yml
```yaml
build:
  cmds:
    - go build -v -i main.go
only_darwin:
  cmds:
    - do darwin stuff here
```

This should result to following tasks:

# Linux
```yaml
build:
  cmds:
    - go build -v -i main.go
assets:
  cmds:
    - ls
```

# Windows
```yaml
build:
  cmds:
    - go build -v -i main.go
assets:
  cmds:
    - dir
```

# MacOS
```yaml
build:
  cmds:
    - go build -v -i main.go
assets:
  cmds:
    - ls
only_darwin:
  cmds:
    - do darwin stuff here
```

What do you think?

With #2 and this I could ditch our cmake file :-)

**Comment by andreynering** [comment]
I have a slighly different idea. I'm thinking of using [Go's template engine](https://golang.org/pkg/text/template/) inside commands, so one could have conditions and loops inside tasks:

```yml
dosomething:
  cmds:
    - {{if eq .GOOS "windows"}}windows-command{{else}}unix-command{{end}}
```

Thoughts?
