### ISSUE TITLE
Dynamic Variable when result contains a semicolon

### ISSUE THREAD

**Issue by BayerSe** [go-task/task#706]
- Task version: 3.12.0
- Operating System: Ubuntu 20.04

### Example Taskfile showing the issue

```yaml
version: '3'
tasks:
  default:
    vars:
      var:
        sh: echo "1;2"
    cmds:
      - echo {{ .var }}
```

Hi all,

I would like to use the dynamic variable approach to query a [connection string](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net) that contains semicola. Unfortunately, this seems to be a problem, the output is truncated at the first semicolon. 

In the MWE above, the output is 
```sh
task: [default] echo 1;2
1
"2": executable file not found in $PATH
task: Failed to run task "default": exit status 127
```
instead of the expected 1;2.

Is this a bug or intended behavior? If this is intended, is there some workaround?

Thanks for your help and this great tool!
Sebastian
