### ISSUE TITLE
Cannot programmatically generate dependencies for a task

### ISSUE THREAD

**Issue by postlund** [go-task/task#707]
- Task version: v3.12.0 (h1:viFy8kdDZ2iTcpTuxzzJCeKtTGt9U+5iXMVIpLjvIro=)
- Operating System: Linux 5.10.16.3-microsoft-standard-WSL2

### Example Taskfile showing the issue

I want to programmatically generate `deps` in a task based on the content of a variable, but it seems to be some problems when converting the string to a list. Here is a basic example:

```yaml
version: '3'

env:
  DEPS: "foo bar"

tasks:
  default:
    deps: {{ splitList " " .DEPS }}
    cmds:
      - echo default

  foo:
    cmds:
      - echo foo

  bar:
    cmds:
      - echo bar
```
Which generates this error:

```shell
$ ./build
yaml: unmarshal errors:
  line 8: cannot unmarshal !!map into []*taskfile.Dep
```

I assume something like this should work?
