### ISSUE TITLE
sources to support reading an `ignore`, and looking at the opposite of what's ignored

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#709]
I found myself writing this:

```yaml
  docker:bake:
    deps:
    - docker:create-multiarch-builder
    # this should match what's in .dockerignore
    sources:
    - ./cmd/**/*
    - ./internal/**/*
    - ./proto/**/*
    - ./testdata/**/*
    - ./go.*
```

with a `.dockerignore` file of:

```
*
!cmd/
!internal/
!proto/
!testdata/
!go.*
```

and thought, wouldn't it be nice if...
