### ISSUE TITLE
Task should not exit on interrupt for interactive tasks

### ISSUE THREAD

**Issue by amancevice** [go-task/task#710]
- Task version: v3.12.0 (h1:viFy8kdDZ2iTcpTuxzzJCeKtTGt9U+5iXMVIpLjvIro=)
- Operating System: macOS 12.3.1 (Monterey)

### Example Taskfile showing the issue

```yaml
version: "3"
tasks:
  console:
    desc: Open IRB console
    interactive: true
    cmds:
      - bundle exec irb
```

Executing a keyboard interrupt (^C on macOS) causes Task to fail the task and exit the IRB session whereas I would expect IRB to handle the interrupt until it's exited

```bash
$ task console
task: [console] bundle exec irb
irb(main):001:0> ^C
task: signal received: interrupt
irb(main):001:0> task: Failed to run task "console": context canceled
$ 
```
