### ISSUE TITLE
Print global vars (without an explicit task to do so)

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#711]
Sometimes it's very nice to be able to store variables in 1 location (such as in a taskfile), and be able to re-use them programmatically else where. Currently, if I wanted to manage a variable in task, and use it in another script or github action or something, I'd write this:

```yaml
vars:
   FOO: bar

tasks:
   vars:get:foo:
      cmds:
      - echo '{{.FOO}}'
```

and call with `task vars:get:foo`

I feel this could be simplified with something like

```
task -var foo
```
