### ISSUE TITLE
Stuck in deadlock with up-to-date "run once" task

### ISSUE THREAD

**Issue by postlund** [go-task/task#715]
- Task version: v3.12.0 (h1:viFy8kdDZ2iTcpTuxzzJCeKtTGt9U+5iXMVIpLjvIro=)
- Operating System: Linux 5.10.16.3-microsoft-standard-WSL2

### Example Taskfile showing the issue
I have a quite large project where I manage to end up in a deadlock every time I try to run task. It seems to be related to a `run: once` task that other tasks depend on. **This happens when I run with `-C X` where X < 4 in my case**. I suspect that If I add more "apps" I will eventually end up in this situation when running with all my cores as well.

I've managed to condense my layout into this:

```yaml
version: "3"

tasks:
  do_something:
    run: once
    status:
      - "true"

  prepare_env:
    cmds:
      - task: do_something

  app1:
    deps: [prepare_env]

  app2:
    deps: [prepare_env]

  default:
    deps: [app1, app2]
```

Running this example ends up in deadlock about one in ten times I run it (my larger repo ends up in deadlock every time, as I mentioned). I'm pretty sure it has to do with timing.

Example of a successful run:

```shell
$ ../work/task -v -C 1
task: "default" started
task: "app2" started
task: "app1" started
task: "prepare_env" started
task: "prepare_env" started
task: "do_something" started
task: status command true exited zero
task: Task "do_something" is up to date
task: skipping execution of task: do_something
task: "prepare_env" finished
task: "prepare_env" finished
task: "app2" finished
task: "app1" finished
task: "default" finished
```
And with deadlock:

```shell
$ ../work/task -v -C 1
task: "default" started
task: "app1" started
task: "app2" started
task: "prepare_env" started
task: "prepare_env" started
task: "do_something" started
task: skipping execution of task: do_something
```
