### ISSUE TITLE
Weighted tasks for better concurrency control

### ISSUE THREAD

**Issue by postlund** [go-task/task#716]
It's possible to control how many tasks that `task` itself runs concurrently via `-C`. A problem however is that the command(s) of a task may spawn any number of threads or processes, meaning one task actually represents several "tasks". One example is calling `make -j` which tells make to use one process per available CPU. Assume we have a machine with eight cores and we run eight tasks in parallel, each calling `make -j`, that would mean 64(!) processes running at the same time. I'm hitting a similar situation in my CI environment and it totally tanks my runner.

My suggestion is to allow a `weight` value (or similar) for a task which is used to calculate number of running tasks. An simple example:

```yaml
version: "3"

tasks:
  a:
    weight: 2
    cmds:
      - make -j

  b:
    weight: 2
    cmds:
      - make -j

  default:
    deps: [a, b]
```
Running `task -C 2` would run either `a` or `b` but not both concurrently. I would say that it should be OK to over schedule once, e.g. if task `a` above had a weight value of 1, then both would run concurrently even if total weight would be three (but no other task would scheduled until one of them finishes). This could however be a hard vs soft limit setting too.

**Comment by AntoinePrv** [comment]
I found this issue looking for a clever way to set the number of CPU for `make` as well.
My idea was be to have a special `{{.CPU}}` value dynamically set by `task`.

```yaml
tasks:
  a:
    cmds:
      - make -j {{.CPU}}

 b:
    cmds:
      - make -j {{.CPU}}
```
Depending on other commands `task` would decide to allow more or less CPUs to each of them.
For instance with 4 CPUs `task a` would use them all, but `task --parallel a b` could split them 2 and 2.

**Comment by MarioSchwalbe** [comment]
Hi, I'm also running C++ build systems (`meson`) on my CI with task. Since, they already build in parallel what is the actual benefit of any more parallelization within task? I simply run tasks sequentially doing the equivalent of (instead of `deps`):
```yml
tasks:
  default:
    cmds:
      - task: a
      - task: b
```
