### ISSUE TITLE
Dynamic variables on Windows appear to include trailing carriage return

### ISSUE THREAD

**Issue by siggimoo** [go-task/task#717]
- Task version: v3.11.0
- Operating System: Windows 2019

### Example Taskfile showing the issue

```yaml
version: "3"

vars:
  DYNAMIC:
    sh: aws sts get-caller-identity --query Account --output text
  STATIC: "{{.DYNAMIC}}.bar"

tasks:
  vars:
    cmds:
      - echo DYNAMIC = {{.DYNAMIC}}
      - echo STATIC = {{.STATIC}}
```

On *nix systems the above Taskfile produces the following (correct) output:
```
task: [vars] echo DYNAMIC = <account>
task: [vars] echo STATIC = <account>.bar
DYNAMIC = <account>
STATIC = <account>.bar
```

On Windows it produces the following:
```
task: [vars] echo DYNAMIC = <account>
task: [vars] echo STATIC = <account>
.bar
DYNAMIC = <account>
STATIC = <account> .bar
```

While I have not confirmed this, it appears to be the result of [this TrimSuffix call](https://github.com/go-task/task/blob/b65935d6cf9791557adc8b1363ebde88d1d399b8/internal/compiler/v3/compiler_v3.go#L154) only removing `\n`. That's sufficient on *nix systems but not on Windows, where the line suffix is `\r\n`. This leaves a trailing carriage return character after the output of the command, and that can lead to various failures down the line.

I recommend adding the following immediately after the above-mentioned line:
```
result = strings.TrimSuffix(result, "\r")
```

**Comment by siggimoo** [comment]
I've been able to confirm this is indeed the issue. Forking the repo and adding the suggested line resolves the problem.

**Comment by ghostsquad** [comment]
Can you submit a PR?

**Comment by siggimoo** [comment]
Already tried. Said I didn't have permission to do so.

**Comment by ghostsquad** [comment]
You can always submit a PR from a fork.

**Comment by andreynering** [comment]
Hi @siggimoo,

Thanks for reporting, fixed at 1acd59c7d6f5e8aefca5d4c57e25bacc27fdd20f.

**Comment by cr1cr1** [comment]
There is still this issue on windows when calling subshell with commands that output CRLF.

The workaround is to pipe through `dos2unix`

```yaml
version: "3"

tasks:
  default:
    env:
      EXPECTED: "hello world"
    set:
      - "x"
    cmds:
      - |
        ACTUAL=$(echo "[\"$EXPECTED\"]" | jq -r '.[]' | dos2unix)
        [[ "$ACTUAL" == "$EXPECTED" ]]
      - |
        ACTUAL=$(echo "[\"$EXPECTED\"]" | jq -r '.[]')
        [[ "$ACTUAL" == "$EXPECTED" ]]
```

```bash
task -v
task: "default" started
task: [default] ACTUAL=$(echo "[\"$EXPECTED\"]" | jq -r '.[]' | dos2unix)
[[ "$ACTUAL" == "$EXPECTED" ]]

+ dos2unix
+ jq -r .[]
+ echo '["hello world"]'
+ ACTUAL='hello world'
task: [default] ACTUAL=$(echo "[\"$EXPECTED\"]" | jq -r '.[]')
[[ "$ACTUAL" == "$EXPECTED" ]]

+ jq -r .[]
+ echo '["hello world"]'
+ ACTUAL=$'hello world\r'
task: Failed to run task "default": exit status 1
```
