### ISSUE TITLE
Allow status to be defined as shell

### ISSUE THREAD

**Issue by krzwiatrzyk** [go-task/task#719]
Right now I can only check if file or directory exists for a `status`. However, I would like to check if binary is alredy installed in the system or not (and exit code will tell if task should be run or not)

For example:
```
    status:
      - command -v my-binary >> /dev/null
```

I can do something similar with `preconditions` however it is not possible with `status`

**Comment by ghostsquad** [comment]
Please provide a minimal `Taskfile.yml` that demonstrates the problem and also the error you get.

**Comment by krzwiatrzyk** [comment]
So Taskfile.yaml I would like to work is:
```
version: 3

tasks:
  install-figlet:
    cmds:
    - sudo apt-get install figlet -y
    status:
    - command -v figlet >> /dev/null
```

And... it seems it works. But with some commands I don't understand why not. in example following one:
```
  GNU nano 4.8                                                                       Taskfile.yaml                                                                                 
version: 3

tasks:
  install-figlet:
    cmds:
    - sudo apt-get install figlet -y
    status:
    - return 0              
```
will always execute task, despite status returns exit code 0
