### ISSUE TITLE
Env replacement is not working properly 

### ISSUE THREAD

**Issue by pekhota** [go-task/task#732]
- Task version: v3.11.0 (h1:eCcCe1cKyta4YnGQYLo2FriPS9h7fFS8XBVW6QvWEV4=)
- Operating System: macOs Monterey 12.3 M1

### Example Taskfile showing the issue

```yaml
version: '3'

dotenv: ['.env'] # IS_AUTH_SERVICE_ENABLED=true

env:
  PARENTPATH:
    sh: echo "$(pwd)/.."
  COMPOSEPATH:
    sh: echo "$(pwd)"
  AUTHSERVICEPATH:
    sh: echo "{{.PARENTPATH}}/authorization-service"
  AUTH_SERVICE_COMPOSE_FILE:
    sh: if [ "{{.IS_AUTH_SERVICE_ENABLED}}" = "true" ];              then echo ":{{.AUTHSERVICEPATH}}/docker-compose.yml";               else echo ""; fi
  COMPOSE_FILE:
    sh: echo "{{.COMPOSEPATH}}/docker-compose.yml{{.AUTH_SERVICE_COMPOSE_FILE}}"

tasks:
  test:
    cmds:
      - echo "{{.COMPOSE_FILE}}"
```

Actual result: /Users/alex/tmp/docker-compose.yml
Expected result: /Users/alex/tmp/docker-compose.yml:/Users/alex/tmp/../authorization-service

**Comment by pekhota** [comment]
During our discussion on Discord, we've found that it can be related to the parallel execution of env variables. So I'd like to make a feature request to add an option 'deps' for env variables that have `sh` option set. Also, we discussed that dotenv variables can be loaded after the env variables from taskfile.yml. To solve this I suggest adding deps here as well. 
For example:
```
env:
  PARENTPATH:
    sh: echo "$(pwd)/.."
  COMPOSEPATH:
    sh: echo "$(pwd)"
  AUTHSERVICEPATH:
    sh: echo "{{.PARENTPATH}}/authorization-service"
  AUTH_SERVICE_COMPOSE_FILE:
    sh: if [ "{{.IS_AUTH_SERVICE_ENABLED}}" = "true" ];              then echo ":{{.AUTHSERVICEPATH}}/docker-compose.yml";               
else echo ""; fi
    **deps: ['.env']**
  COMPOSE_FILE:
    sh: echo "{{.COMPOSEPATH}}/docker-compose.yml{{.AUTH_SERVICE_COMPOSE_FILE}}"
    **deps: ['AUTH_SERVICE_COMPOSE_FILE']**
```
What to you think? Thanks!
