### ISSUE TITLE
multilevel schema validation

### ISSUE THREAD

**Issue by mkyc** [go-task/task#757]
- Task version: 3.12.1
- Operating System: Mac OS ARM

### Example Taskfile

```yaml
version: '3'

includes:
  lalala:
    taskfile: ./lalala/Taskfile.yml
    dir: ./lalala
```

Current [schema](https://json.schemastore.org/taskfile.json) is saying that `"required": ["version", "tasks"]` and that is not entirely true. `tasks` is not required (presented example works) and in multilevel include scenario this is going to be quite normal to have `Taskfile.yaml` just organising parts of directories tree.
