### ISSUE TITLE
"Runners" like docker/podman/shell/etc

### ISSUE THREAD

**Issue by endigma** [go-task/task#763]
In a taskfile, being able to define an environment for the command to run in would be useful. This could be something like:

```yml
tasks:
    setup:
        runner:
            container:
                runtime: podman
                image: ubuntu:latest
                mounts:
                 - "./app:/app"
                wd: "/app"
                ... other flags turned into opts
            # shell: zsh / python3 / node / etc repls
        cmds:
            - ... commands
 ```
 
 I know this is possible by just inlining this sort of thing or moving it into scripts, but I still think it would be a valuable addition.
