### ISSUE TITLE
ENV vars are not usable within other env var declarations

### ISSUE THREAD

**Issue by ghost** [go-task/task#793]
- Task version: 3.13.0
- Operating System: linux

```yaml
version: "3"
env:
  CGO_ENABLED: 0
  DISTDIR:
    sh: 'echo $(pwd)/dist'
  MODULE_NAME:
    sh: "cat ./go.mod | head -n 1 | sed 's/module//'"
  VERSION:
    sh: git describe --tags || printf "dev"
  COMMIT:
    sh: git log --format="%H" -n 1 || true
  BRANCH:
    sh: git branch --show-current
  PRJ_NAME:
    sh: basename ${MODULE_NAME}
tasks:
  prj:
    cmds:
    - echo $PRJ_NAME
```

With the above yaml there it gives an error when running the prj task. The reason is that the variable MODULE_NAME was not evaluated before executing the basename cmd.
Currently they are not evaluated one by one, but all together, I think.
As maps by nature don't have a specific ordering it cannot be guaranteed that they are evaluated in the correct order.
Therefore I would suggest to make the env declarations in a list, similar like kubernetes does it.
example:

```ỳaml
version: "3"
env:
- CGO_ENABLED=0
- DISTDIR=$(echo $(pwd)/dist)
```
Then the env vars should be evaluated one by one and can be set in a map that can then be used in the tasks for variable substitution (sprig...)

This approach would also allow combining and overriding env vars.

**Comment by krystian-panek-wttech** [comment]
I see also other problem:

```
env:
  JAVA_HOME:
    sh: cat java_home.txt


tasks:
  app:build:
    env:
      OTHER_APP_VERSION:
        sh: cd ../other-app && mvn help:evaluate -Dexpression=project.version -q -DforceStdout 
    cmd: 
       mvn clean package -Dother.app.version=$OTHER_APP_VERSION
```

looks like env vars defined in the root `env` section are not visible in task-level `env` section but they should be I suppose? :)

to make the snippet above work I needed to inline APP_VERSION directly to the `cmd` .. :/
