### ISSUE TITLE
why running deps when task would not run ( is up to date )?

### ISSUE THREAD

**Issue by sascha-andres** [go-task/task#8]
@andreynering The issue to discuss dependency handling

Maybe a switch to enforce running dependencies or two classes of dependencies ( `run always` and `run if required` ) could be a valid choice.

**Comment by andreynering** [comment]
I'd expect dependencies to always run. This because one can have a task that which the source is the target of another task (a dependency).

Think in this scenario:

- One task concatenate multiple `.js` files in a single `bundle.js` file and minify it.
- Another task uses a toll li e [fileb0x](https://github.com/UnnoTed/fileb0x) to embed `bundle.js` in a Go app.

Taskfile would be something like this:

```yml
assets:
  deps: [bundlejs]
  cmds:
    - fileb0x fileb0x_file.yaml
  sources:
    - public/bundle.js
  generates:
    - fileb0x/ab0x.go

bundlejs:
  cmds:
    - gulp
  sources:
    - src/**/*.js
  generates:
    - public/bundle.js
```

This this scenario, if I change a `.js` file on `src` folder, I'd expect both tasks to run, first `bundlejs` and then `assets`. If the file don't change, Task will just they are up-to-date.

But an options to change this behavior may be a good thing.
