### ISSUE TITLE
Redirect is messing up order

### ISSUE THREAD

**Issue by sandboxcom** [go-task/task#807]
- Task version: Task version: v3.13.0 (h1:H1LzM7Ac2Ixz26086sgN7xxueXHcjVwy7qt9BrboiTs=)
- Operating System: Linux k8s-0 5.4.0-1085-azure #90~18.04.1-Ubuntu SMP Fri Jun 10 18:32:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Example Taskfile showing the issue
```
---
version: '3'

tasks:
  present:
    vars:
      ANSWER:
        sh: whiptail --menu "Comes first:" 7 40 1 "I'm first " "I'm first" 3>&1 1>&2 2>&3
    cmds:
      - echo "And I shouldn't be last"
      - echo "pre {{.ANSWER}} post"
      - echo "But I'm last"
    silent: true
```
