### ISSUE TITLE
Flag to test if task(s) are up-to-date

### ISSUE THREAD

**Issue by smyrman** [go-task/task#81]
It would be nice if there was a `--status` flag avaialble in task that would check if one or more tasks are up-to-date and returned non-zero to the shell if one or more of them are not. There are many use-cases for this.

One case where it would be particular useful is when nesting Taskfiles via cmd calls:

Taskfile.yml
```yaml
default:
  deps:
    - sub/task1

sub/task1:
  dir: sub
  cmds:
    - task task1
  status:
    - task --status task1
```
sub/Taslfile.yml:
```yaml
task1:
  cmds:
    - cp file1.txt file2.txt
  sources:
    - file1.txt
  generates:
    - file2.txt
```

The main case for testing if _multiple_ tasks within a Taskflie are up-to-date would mostly be for completion (since it's possible to give multiple tasks on the command line) but it could also be relevant in CIs. E.g.

```
task --status generate-pkg1 generate-pkg2
```
