### ISSUE TITLE
"probably an cyclic dep or infinite loop" on huge graphs

### ISSUE THREAD

**Issue by alex65536** [go-task/task#820]
If the graph is large, you can get the following error:

```
task: maximum task call exceeded (100) for task: probably an cyclic dep or infinite loop
```

The reasons are as follows:
https://github.com/go-task/task/blob/bf9cd7625bdc9510a309b09a3b47b0fd4b23ac8e/task.go#L110-L112
So, if we try to execute the task >= 100 times, then we crash.

The issue is that `RunTask` is executed once from each of the dependencies:
https://github.com/go-task/task/blob/bf9cd7625bdc9510a309b09a3b47b0fd4b23ac8e/task.go#L200-L206
but we increment the counter before checking if the task is already running or finished. Such check is done below, in `startExecution`:
https://github.com/go-task/task/blob/bf9cd7625bdc9510a309b09a3b47b0fd4b23ac8e/task.go#L300-L327

So, if there is a task on which 100 other tasks depend, then the graph will fail with an error.

Moreover, if you read `startExecution` carefully, then it would appear that the error has nothing to do with cyclic deps. The simplified algorithm is as follows:
```go
RunTask(task) {
  if (hashes.contains(task)) {
    // wait for task
    return;
  }
  hashes.insert(task);
  // iterate over deps
  // run commands
}
```

So, even for cyclic dependency, the task will be executed once (though, it will eventually stuck waiting for itself).

**Comment by q0rban** [comment]
Running into this when running a task on ~150 files using the new `for` command option.

**Comment by q0rban** [comment]
Here's an example Taskfile.yml to replicate this:

```yaml
version: 3

tasks:
  default:
    vars:
      ITEMS:
        sh: echo {1..101}
    cmds:
      - for: { var: ITEMS }
        task: process-item
        vars:
          ITEM: '{{.ITEM}}'

  process-item:
    cmds:
      - echo {{.ITEM}}
```

What would be ideal in my mind is for Task to count the number of items that is in the for loop and only throw an error if it is called more than that number.

In addition, a parameter on the task to configure this limit would be desirable:

```yaml
version: 3

tasks:
  default:
    vars:
      ITEMS:
        sh: echo {1..101}
    cmds:
      - for: { var: ITEMS }
        task: process-item
        vars:
          ITEM: '{{.ITEM}}'

  process-item:
    max-call-count: 101
    cmds:
      - echo {{.ITEM}}
```
