### ISSUE TITLE
{{.TASK}} remains in task listing

### ISSUE THREAD

**Issue by MarioSchwalbe** [go-task/task#825]
### Versions

- Task version: v3.14.0
- Operating System: Mac OS X 10.15.7

### Example Taskfile showing the issue

```yaml
version: '3'

tasks:
  DoesNotWork:
    desc:  DoesNotWork
    label: '{{.TASK}}'
    cmds:
      - echo "PARAM = '{{ .PARAM | trim }}'"

  DoesWork:
    desc:  DoesWork
    label: '{{.TASK}}'
    cmds:
      - echo "PARAM = '{{ .PARAM | default "" | trim }}'"
```

Run:
```sh
$ task -l
task: Available tasks for this project:
* {{.TASK}}: 	DoesNotWork
* DoesWork: 	DoesWork
```

Notes:
- Both tasks are intended to be called from the command-line but also embedded within other tasks by passing their task name as variable `TASK`.
- The task `DoesNotWork` fails if run without the parameter (which is expected):
  ```sh
  $ task DoesNotWork
  template: :1:27: executing "" at <trim>: invalid value; expected string
  ```
  The task `DoesWork` would work due to the provided default.

However, this should not affect the output of `task -l`. Or is this a hidden feature to validate the correctness of tasks? Like: If it looks like `{{.TASK}}`, some default is missing.
