### ISSUE TITLE
Paths are not correctly resolved when using "dir"

### ISSUE THREAD

**Issue by Nantero1** [go-task/task#828]
- Task version: v3.14.1 (h1:myTmEIbMbQx2D+g5lJvnbSqX531HmxiaQuefAqz8ISA=)
- Operating System: 46 ~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022

Since minor version v3.14.1 we have problems to chdir into the correct directory using the following setup. Version 3.14.0 had no issues.

### Example Taskfile showing the issue

Directory structure:
```
/home/user/git/repo/projectname/Taskfile.yaml
/home/user/git/repo/.Taskfiles/Generic.yaml
```

`Taskfile.yaml`:
```yaml
# https://taskfile.dev

version: "3"

vars:
  project: "projectname"

includes:
  generics:
    taskfile: "../.Taskfiles/Generic.yaml"

tasks:
  default:
    cmds:
      - task -l
    silent: true
```

`Generic.yaml`:
```yaml
version: "3"

vars:
  gitBase:
    sh: git rev-parse --show-toplevel

tasks:

  plan:
    desc: Example on strange "dir" variable templating
    dir: "{{.gitBase}}/{{.project}}"
    cmds:
      - pwd
      - echo "{.gitBase}{.project} {{.gitBase}}/{{.project}}"
      - echo "{.gitBase} {{.gitBase}}"
```

### Expected behaviour

When using task version v3.14.0, the current dir is correct:

```bash
cd /home/user/git/repo/projectname/
task generics:plan
```
output:
```bash
task: [generics:plan] pwd
/home/user/git/repo/projectname/home/user/git/repo/projectname
task: [generics:plan] echo "{.gitBase}{.project} /home/user/git/repo/projectname"
{.gitBase}{.project} /home/user/git/repo/projectname
task: [generics:plan] echo "{.gitBase} /home/user/git/repo"
{.gitBase} /home/user/git/repo
```

### Actual behaviour

When using task version v3.14.1, the current dir is wrong:

```bash
cd /home/user/git/repo/projectname/
task generics:plan
```
output:
```bash
task: [generics:plan] pwd
/home/user/git/repo/projectname/home/user/git/repo/projectname
task: [generics:plan] echo "{.gitBase}{.project} /home/user/git/repo/projectname"
{.gitBase}{.project} /home/user/git/repo/projectname
task: [generics:plan] echo "{.gitBase} /home/user/git/repo"
{.gitBase} /home/user/git/repo
```

Please see the weird double path `/home/user/git/repo/projectname/home/user/git/repo/projectname` after the pwd command, **see the first line**.
Other command are only for debug purposes and show that the templating works for these other commands.

**Comment by lucasfcnunes** [comment]
I was planning to report the same thing. Thanks!

**Comment by andreynering** [comment]
Hi @Nantero1 and @lucasfcnunes,

I just took quite some time debugging this issue, and it's a bit tricky to fix. I'll write it here to help myself when I back to this.

The source of the problem is that you're using a value in `dir:` that starts with a template like `{{.DIRECTORY}}`.

There's a place in the code where the Taskfile dir in joined with the task dir like this:

`/path/to/project` + `sub/dir` = `/path/to/project/sub/dir`

There's an exception: if the task dir is already absolute (starts with `/` in linux/mac or `C:/` in Windows) the joining is skipped.

The problem is that interpolation only happen in a later stage, so it's failing to detect that `{{.DIRECTORY}}` holds an absolute path, so it'll be joined like:

`/path/to/project/{{.DIRECTORY}}` which will be later expanded as `/path/to/project/path/to/project`.

While this is not fixed, you can change `dir` to have a relative path like `../../`

**Comment by clintmod** [comment]
Working on a react native project where I was trying to "run in this dir" and this just bit me.  What an ugly little bug.  There's so much about this project that has promise but there so much about this project that just pisses me off.  I'm going to fork it and just fix all the stupid shit and call it go-task-that-doesnt-fucking-suck. Fuck

**Comment by davinkevin** [comment]
To fix that "issue", I did this: 

```
tasks
  foo:
    dir: /$TMPDIR/{{.COMPONENT_NAME}}
```

The trick is to start with `/` even if `$TMPDIR` contains the `slash`… it's a way to say "force absolute". It's tricky and a bit ugly, but it works for now. 

A better solution (like "if it starts with `$` or `{{`, then it's absolute…) is still welcome 😇

**Comment by brettinternet** [comment]
I was able to get this to work for my absolute path in the subtask file:

```
tasks:
  foo:
    dir: "/./{{.DIRECTORY}}/subpath/in/my/repo"
    cmd: pwd
```

**Comment by neptaco** [comment]
I encountered an issue where paths were duplicated in `vars:`. Using `/` at the beginning didn't work on Windows. Instead, I was able to avoid the problem by changing to a relative path as shown below:

```
vars:
  TARGET_DIR: '{{relPath .TASKFILE_DIR .USER_WORKING_DIR}/App'
```


Additionally, the behavior changed depending on whether `taskfile:` was used in the `includes:` configuration.
Example that worked without issues:

```
includes:
  ef: dotnet/Taskfile.ef.yaml
```

Example where the path was duplicated:
```
includes:
  ef:
    taskfile: dotnet/Taskfile.ef.yaml
```

**Comment by dpritchett** [comment]
Still hitting this in `v3.48.0`. Templated `dir:` values get treated as relative even when they resolve to absolute paths.

```yaml
# parent/Taskfile.yaml
version: '3'
includes:
  child:
    taskfile: ../child/Tasks.yaml
    dir: .
```

```yaml
# child/Tasks.yaml
version: '3'
vars:
  MYDIR: "/home/me/project"
tasks:
  test:
    dir: "{{ .MYDIR }}"
    cmd: pwd
    # expected: /home/me/project
    # actual:   /home/me/project/home/me/project
```

Hardcoded `dir: "/home/me/project"` works fine — the issue is only with templated values.

We worked around it by making all command paths absolute in `vars:` (avoiding `dir:` entirely) and adding a load-time guard to catch relative paths early:

```yaml
vars:
  _REQUIRE_ABSOLUTE:
    sh: 'case "{{ .MYDIR }}" in /*) ;; *) echo "MYDIR must be absolute" >&2; exit 1;; esac'
```
