### ISSUE TITLE
Parentheses not allowed in templates

### ISSUE THREAD

**Issue by smyrman** [go-task/task#83]
In Go, this is a legal template `{{.B | default (print "prefix/" .A)}}`

However, when run through task, the template will result in an error from something that appears to be shell script validation:

Taskfile.yml:
```yaml:
mytask:
  vars:
    B: '{{.B | default (print "prefix/" .A)}}'
  cmds:
    - 'echo {{.B}}'
```
```
$ task mytask
echo {{.B | default (print "prefix/" .A)}}
task: Failed to run task "mytask": 1:13: "foo(" must be followed by )
```

https://github.com/go-task/task/blob/e23a6dc9f16e759bd0a7082c83f937077814e50a/vendor/mvdan.cc/sh/syntax/parser.go#L379
  

Task version:
```
it log -n1
commit e23a6dc9f16e759bd0a7082c83f937077814e50a (HEAD -> master, origin/master, origin/HEAD)
Author: Andrey Nering <andrey.nering@gmail.com>
Date:   Wed Jan 3 15:12:40 2018 -0200

```
