### ISSUE TITLE
Shell pipes and multiline yaml strings

### ISSUE THREAD

**Issue by Zebradil** [go-task/task#834]
- Task version: v3.14.1 (h1:myTmEIbMbQx2D+g5lJvnbSqX531HmxiaQuefAqz8ISA=)
- Operating System: x86_64 GNU/Linux 5.18.16-arch1-1

### Example Taskfile showing the issue

```yaml
version: '3'

tasks:
  ok:
    # ok.txt contains "foo bar"
    cmds:
      - >
        echo foo \
          bar \
        > ok.txt
  ok2:
    # outputs "baz bar"
    cmds:
      - >
        echo foo \
          bar \
        | sed 's/foo/baz/'
  fail:
    # outputs nothing
    # fail.txt is empty
    cmds:
      - >
        echo foo \
          bar \
        | sed 's/foo/baz/' \
        | tee fail.txt
  ok-again:
    # outputs "baz bar"
    # ok-again.txt contains "baz bar"
    cmds:
      - |
        echo foo \
          bar \
        | sed 's/foo/baz/' \
        | tee fail.txt

```

There is a clue in the output of go-task:

```
task: [ok] echo foo \
  bar \
> ok.txt

task: [ok2] echo foo \
  bar \
| sed 's/foo/baz/'

task: [fail] echo foo \
  bar \
| sed 's/foo/baz/' \ | tee fail.txt

task: [ok-again] echo foo \
  bar \
| sed 's/foo/baz/' \
| tee fail.txt
```

Notice:
- the last lines of the `fail` task are joined together;
- the multiline string marker is `>` for every task except `ok-again`, where it's `|`.

Expected behaviour:
1. Ideally, `>` joins all lines together as per yaml standard. So that `\` is not needed in the end of every line.
2. Lines stay separated or get joined consistently, regardless of the string content.
