### ISSUE TITLE
Wrong shell execution directory for task-local variables

### ISSUE THREAD

**Issue by MarioSchwalbe** [go-task/task#839]
- Task version: Task version: v3.14.1 (h1:myTmEIbMbQx2D+g5lJvnbSqX531HmxiaQuefAqz8ISA=)
- Operating System: Ubuntu 22.04, Mac OS X, Windows 10

### Example Taskfile showing the issue

We need 2 taskfiles. The primary taskfile contains.
```yml
version: '3'

includes:
  top:
    taskfile: Util.yml
    dir:      .

  sub:
    taskfile: Util.yml
    dir:      subdir

tasks:
  default:
    cmds:
      - task: top:Setup # Comment this line to make it work.
      - task: sub:Setup
```

`Util.yml` is:
```yml
version: '3'

tasks:
  Setup:
    vars:
      WORK_DIR:
        sh: pwd
    cmds:
      - echo "{{.WORK_DIR}}"
      - pwd
```

Running this setup results in:
```sh
$ task
task: [top:Setup] echo "/home/mario/GoTask/Bugs/ExecDir"
/home/mario/GoTask/Bugs/ExecDir
task: [top:Setup] pwd
/home/mario/GoTask/Bugs/ExecDir
task: [sub:Setup] echo "/home/mario/GoTask/Bugs/ExecDir"
/home/mario/GoTask/Bugs/ExecDir
task: [sub:Setup] pwd
/home/mario/GoTask/Bugs/ExecDir/subdir
```

### Explanation

If running task in `/home/mario/GoTask/Bugs/ExecDir` the task `top:Setup` must be executed in that directory and the local variable `WORK_DIR` also contains the same path. This work. However, in case of `sub:Setup` to be executed in a subdirectory `subdir` as per the inclusion directive, the value of `WORK_DIR` is wrong. It still points at the top-level directory rather than the actual execution directory. In my opinion both invocations of `pwd` should return consistent results.

I needed something like that, because `meson` wants the installation prefix (`--prefix`) to be an absolute path, so I decided to make it absolute by obtaining the working directory and prepending it if necessary.

**Comment by toddlerya** [comment]
I also encountered the same problem

**Comment by totahuanocotl** [comment]
I think, rather than this be about the execution directory, it is about some sort of caching/sharing of the variable.

If you change the primary and util taskfiles to the following:
Taskfile.yml:
```
version: '3'

includes:
  top:
    taskfile: Util.yml

  sub:
    taskfile: Util.yml

tasks:
  default:
    cmds:
      - task: top:Setup # Comment this line to make it work.
      - task: sub:Setup
```
Util.yml
```
version: '3'

tasks:
  Setup:
    vars:
      WORK_DIR:
        sh: mktemp -d
    cmds:
      - echo "{{.WORK_DIR}}"
```

Expected output:
```
task: [top:Setup] echo "/tmp/tmp.<random_1>"
/tmp/tmp.random_1
task: [sub:Setup] echo "/tmp/tmp.<random_2"
/tmp/tmp.random_2
```

Actual output:
```
task: [top:Setup] echo "/tmp/tmp.UGcNjYyBwl"
/tmp/tmp.UGcNjYyBwl
task: [sub:Setup] echo "/tmp/tmp.UGcNjYyBwl"
/tmp/tmp.UGcNjYyBwl
```

Both task executions have the same value, whether I would have expected each invocation to generate its own value.
