### ISSUE TITLE
Unable to use env and vars in the same task definition

### ISSUE THREAD

**Issue by filbotblue** [go-task/task#843]
# Information

- Task version: (installed by RPM)

```bash
> task --version
Task version: v3.12.0 (h1:viFy8kdDZ2iTcpTuxzzJCeKtTGt9U+5iXMVIpLjvIro=)
```

- Operating System: Fedora Silverblue 36 and Toolbox

```bash
> cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Container Image)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
```

### Example Taskfile showing the issue

```yaml
---
# https://taskfile.dev
version: '3'

tasks:
  foobar:
    desc: Use both vars and env in a single task.
    cmds:
      - echo {{.FOO}} {{.BAR}}
    vars:
      FOO: Fizz
    env:
      BAR: Buzz
...
```

# Output

When using the YAML file above, I get the following

```bash
> task foobar
task: [foobar] echo Fizz
Fizz
```

The second part of this is missing. However, if I place the `env` section at the root level of the YAML file, it works as expected.
