### ISSUE TITLE
Taskfile schema fits multiple variants error

### ISSUE THREAD

**Issue by mriegler** [go-task/task#847]
- Task version: 3.12.1
- Operating System: macos x64

Using the current schema complains that multiple variants fit the same file.

This was caused by #757 because using the schema from before that commit works fine.

### Example Taskfile showing the issue

```yaml
# https://taskfile.dev

version: '3'

# Just here for convenience
includes:
  devops:
    taskfile: "./devops/Taskfile.dist.yaml"

tasks:
  default:
    cmds:
      - stuff

```
