### ISSUE TITLE
cannot use vars with sources\generates

### ISSUE THREAD

**Issue by aCLr** [go-task/task#856]
- Task version: 3.14.1.r21.g421cb52-1
- Operating System: archlinux, core 5.19.5

### Example Taskfile showing the issue

```yaml
version: '3'


tasks:
  gen:
    sources:
      - {{.SRC}}
    generates:
      - {{.GEN}}
    cmds:
      - echo "{{.SRC}}"
      - echo "{{.GEN}}"

  gen:foo:
    cmds:
      - task: gen
        vars:
          SRC: sss
          GEN: ggg
```

When I call `task gen:foo` it proceses errors:
```
yaml: unmarshal errors:
  line 7: cannot unmarshal !!map into string
  line 9: cannot unmarshal !!map into string
```

**Comment by andreynering** [comment]
Hi @aCLr,

This is a YAML parse issue. You need to quote `{{.SRC}}` and `{{.SRC}}` to avoid fix this:

```yaml
version: '3'


tasks:
  gen:
    sources:
      - '{{.SRC}}'
    generates:
      - '{{.GEN}}'
    cmds:
      - echo "{{.SRC}}"
      - echo "{{.GEN}}"

  gen:foo:
    cmds:
      - task: gen
        vars:
          SRC: sss
          GEN: ggg
```
