### ISSUE TITLE
Specify minimum required task verison.

### ISSUE THREAD

**Issue by sdemura** [go-task/task#872]
While the `version:` key is nice to specify the Taskfile schema version, it would be nice to have some option to define a _minimum_ required task version to run a task.

For example, a recent change introduced `.ROOT_DIR`, which is incredibly handy for how I leverage task for my team, but many of my devs are stumbling over that as they haven't bothered to upgrade task yet.

I propopse that in in taskfiles, the `version:` key be expanded to check for minimum task version.

Example:

```
version: 3
``` 

would be compatible with all 3.x taskfile releases, but...

```
version: 3.15.2
```

would cause `task` to exit non-zero if the task version isn't _at least_ 3.15.2.

**Comment by q0rban** [comment]
I came here looking for this feature as well.

I have a workaround  that works for my use case, but it's not the prettiest:

```yaml
# Specify your desired major version
version: 3

vars:
    TASK_MINOR_VERSION:
        # Store the current minor version of task in an environment variable
        sh: echo "{{.TASK_VERSION}}" | awk -F. '{print $2}'

tasks:
    default:
        preconditions:
            # Ensure we have at least version 3.28
            - sh: 'test {{.TASK_MINOR_VERSION}} -ge 28'
```
