### ISSUE TITLE
cannot unmarshal !!seq into struct { Sh string }

### ISSUE THREAD

**Issue by kovan** [go-task/task#875]
- Task version: Task version: v3.15.2 (h1:Swi9lMSrTM4a1UhXFe3SiHef6q+EY/WHfjQGj6yvtMc=)
- Operating System: Ubuntu 22.04

### Example Taskfile showing the issue

```yaml
version: '3'

tasks:
    build:
        cmds:
            - true
        vars:
            BRANCH:
                - sh: git branch --show-current
```

That is basically a copy-paste from the usage guide of the website.

I get the following error:

```
yaml: unmarshal errors:
  line 11: cannot unmarshal !!seq into struct { Sh string }
```

How to solve this?

Thank you for your time.
