### ISSUE TITLE
ROOT_DIR and escaping issues on Windows

### ISSUE THREAD

**Issue by postlund** [go-task/task#876]
- Task version: Task version: v3.15.0 (h1:k1s4CXeADCJyRt8tR67XC+gusYR0BL6d/r3AIOeE98c=)
- Operating System: MINGW64_NT-10.0-19044

### Example Taskfile showing the issue
Running this example on Windows (in my case via msys in Git bash):

```yaml
version: "3"

tasks:
  default:
    cmds:
      - echo {{.ROOT_DIR}}
```

Produces this output:
```
task: [default] echo C:\git\myrepo
C:gitmyrepo
```

The path is technically correct of course, but escaping kinda ruins `ROOT_DIR` when used as a variable. Maybe it should be escaped into c:\\\\git\\\\myrepo on Windows?

**Comment by pd93** [comment]
@postlund There is a `shellQuote` function made available via the [templating engine](https://taskfile.dev/usage/#gos-template-engine) for this kind of situation:

```yaml
version: "3"

tasks:
  default:
    cmds:
      - echo {{.ROOT_DIR | shellQuote}}
```

```
> task default
task: [default] echo 'C:\git\myrepo'
C:\git\myrepo
```

Please let me know if it works for you.
