### ISSUE TITLE
More powerful sources and generates patterns

### ISSUE THREAD

**Issue by masaeedu** [go-task/task#88]
I have a task that needs to re-run whenever any tracked file in the entire folder changes (I use git to track what is a "tracked file"). I wanted to use `**/*` as the pattern, but obviously this doesn't work without tweaking, because the task will pick up changes in the build artifacts that the task itself produces.

The simplest approach would just be to allow for:

```
sources:
  sh: <given filenames on stdin, exit or stdout line determines whether it is an input>
```

I could also make do with something like `sources: { include: [...], exclude: [...] }`.

PS: Just wanted to thank you for this amazing tool. I really like that you have sparse, minimal feature set that composes in powerful ways (e.g. recursive invocation).

**Comment by masaeedu** [comment]
In case you're curious why I need such a thing, here's my `Taskfile.yml`:

```yml
## Tasks

build_server:
  desc: Build the server code
  dir: server
  cmds:
  - dotnet build

build_client:
  desc: Build the client code
  dir: client
  cmds:
  - yarn && yarn build

build:
  desc: Build everything
  cmds:
  - task: run_in_docker
    vars: { TASK: build_server, IMAGE: microsoft/dotnet }
  - task: run_in_docker
    vars: { TASK: build_client, IMAGE: node }





## Utilities

run_in_docker:
  deps: 
  - build_gotask
  - task: upload_volume
    vars: { VOL: app, DIR: . }
  cmds:
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v app:/code -w /code {{.IMAGE}} ./bin/task -ws {{.TASK}}

# Hackery to work around lack of volume support for remote Docker instances
upload_volume:
  sources: [./client/**/*.js, ./server/**/*.cs, ./Taskfile.yml]
  generates: []
  method: checksum
  cmds:
  - test -e ./lock && exit 0 || echo "building"
  - echo "" > ./lock
  - docker create --name helper -v {{.VOL}}:/x busybox > /dev/null
  - docker cp {{.DIR}}/. helper:/x > /dev/null
  - docker rm helper > /dev/null
  - rm ./lock

# Build gotask binary
build_gotask:
  cmds:
  - docker run --rm golang bash -c "go get -u -v -ldflags '-linkmode external -extldflags -static' -a github.com/go-task/task/cmd/task && cat /go/bin/task" > ./bin/task
  status:
  - test -e ./bin/task
```

**Comment by andreynering** [comment]
Just an thought on the syntax, if someone want to implement it.

I think along with `sh:`, we should allow `not:` (or maybe `!`?):

```yml
sources:
  - **/*
  - not: *.exe
```

Or alternatively (?):

```yml
sources:
  - **/*
  - !*.exe
```

**Comment by masaeedu** [comment]
Sorry, was just cleaning out some old issues. Just noticed you're still tracking this for the next release.

**Comment by trulede** [comment]
I've implemented a PR #2671 which allows `sources` to take an array as an input. That array can be generated by a template string, that that template string could be set by a `sh` command. Like this:

```yaml
version: '3'

method: none

vars:
  GLOB_STRING: 
    sh: 'echo "foo.txt bar.txt"'

tasks:
  default:
    cmds:
      - task: string
  string:
    sources:
      - '{{splitList " " .GLOB_STRING}}'
    cmds:
      - echo "== {{.TASK}} =="
      - for: sources 
        cmd: echo {{.ITEM}}
```

@masaeedu its 8 years later, what do you think?
