### ISSUE TITLE
Throw error on Taskfiles with nonexistent YAML keys

### ISSUE THREAD

**Issue by kovan** [go-task/task#883]
The task was not executing, and I was sitting there for a while, testing this, testing that, nothing. Very strange I thought. After a (long) while, I realised I was writing with incorrect syntax. Like this:

I had:

```yaml
    backend-master:
        - deps: [build-backend, unittests-backend]
        - cmds:
            - task:  push-backend
```

And the correct syntax was:

```yaml
    backend-master:
        deps: [build-backend, unittests-backend]
        cmds:
            - task: push-backend
```

Notice the spare dashes at "deps" and "cmds" in the first case?. That was it. But I got no error or warning message, just the task would not execute. So I thought a syntax check  for the taskfile would be nice. That is my feature request.

Other than that really great tool, I use it daily, thank you.

And thank you for your time reading this.
Regards.
