### ISSUE TITLE
Unable to override vars at task level

### ISSUE THREAD

**Issue by ssbarnea** [go-task/task#888]
- Task version: 3.16
- Operating System: macos

### Example Taskfile showing the issue

```yaml
# this task will print apples instead of expected oranges
version: 3
vars:
  FOO: apples
tasks:
  subtask:
    cmds:
      - echo {{.FOO}}
  default:
    vars: # this vars do not override the global ones
      FOO: orages
    cmds:
      - task: subtask
        # vars: here would work as expected
```

Despite that the documentation suggests that there are 3 ways to override the vars, apparently none work for task leve, and we cannot even see one example of variable overriding inside the main test file from https://github.com/go-task/task/blob/master/testdata/vars/v3/Taskfile.yml -- all the vars are uniquely defined inside the file, which means that the overriding order is not tested by it.

We have at least these levels of vars:
- **global** (defined in root)
- **task** level (specific on a single tag)
- **command** level (specific to a single command)
- **passed** level, the level that applies when you call a task with arguments, probably should take precedence.

My expectation is that `passed` > `command` > `task` > `global`, but apparently I was not able to make the `command` level to work.

Temporary I could probably make use of YAML anchors in order to force taskfile to "inherit" the vars from the task level, still this should not be needed.

**Comment by prologic** [comment]
I came here looking for an answer to a similar puzzle I have. I have this `Taskfile.yml`:

```yaml
version: '3'

tasks:
  hello:
    desc: Print "Hello World!"
    cmds:
      - echo "Hello {{ .NAME }}!"
    vars:
      NAME: World
```

I expect to be able to override the variable `NAME`like this:

```console
$ task hello NAME=James
task: [hello] echo "Hello World!"
Hello World!
```

But sadly this does not seem to work 😢

**Comment by andreynering** [comment]
Hi @prologic,

You have to use `default` as explained above by Pete. It makes variables overridable.

As the original question by @ssbarnea was also answered above, I'm closing this. If you happen to still have questions, let us know.

**Comment by prologic** [comment]
@andreynering I _think_ we're missing a subtle point here. It seems only possible to override variables declared globally and not at a task level. This is counter intuitive to me 😢 The following example `Taskfile.yml` works with the following usage(s):

```yaml
version: '3'

vars:
  NAME: "World"

tasks:
  hello:
    desc: Print "Hello World!"
    cmds:
      - echo "Hello {{ .NAME }} !"
    vars:
      NAME: '{{ .NAME | default "World" }}'
```

```console
$ task hello
task: [hello] echo "Hello World !"
Hello World !
$ task hello NAME=James
task: [hello] echo "Hello James !"
Hello James !
```

But the following does not:

```yaml
version: '3'

tasks:
  hello:
    desc: Print "Hello World!"
    cmds:
      - echo "Hello {{ .NAME }} !"
    vars:
      NAME: 'World'
```

Yes you can do what has been suggested as (IMO) work-arounds here, but IMO the title of the issue still remains. It is not possible to override a task-level variable (only a global).
