### ISSUE TITLE
Capturing output as a variable.

### ISSUE THREAD

**Issue by huxoll** [go-task/task#89]
I'm working to port a make-based build to task.  I have a need to take action based on the output of a task command.

Basically, a build step generates a unique name that I need to record and then use in following steps.  The closest I've come is the following:

```yaml
deploy-app:
  cmds:
    - command-to-deploy.sh {{.NAME}} >> {{.TMPFILE}}
    - |
      DEPLOY_NAME=`cat {{.TMPFILE}} | grep -e ^NAME | cut -s -d' ' -f 4`
      echo "Deployed {{.NAME}} as $DEPLOY_NAME"
      echo "$DEPLOY_NAME" > app-deploy
    - rm {{.TMPFILE}}
  vars:
    TMPFILE: { sh: mktemp -t deploy-app }
```
I want to port away from make to get rid of some of the shell that's embedded in a make file, and this would be much better if a variable can receive the output of a command.

I also tried to do this with dynamic variables, but it looks like variables are not interpreted during dynamic variables?  E.g. 
```yaml
vars:
  OUTPUT: {sh: command-to-deploy.sh {{.NAME}} }
```
doesn't work.
