### ISSUE TITLE
Allow adding task name aliases

### ISSUE THREAD

**Issue by xavier-sanna** [go-task/task#891]
It would be great to be able to add task name aliases.

For instance, I have this task named: `api:prisma:migrate`
I would like to add a shortened alias `a:p:m` and be able to run the task with both notations.

```
tasks:
  api:npm:install:
    alias: a:n:i
    cmds:
      -  docker-compose exec api sh -c 'npm install {{.CLI_ARGS}'
```

It could even be a list of aliases, and not constraint the user to a single naming alterrnative.
```
tasks:
  api:npm:install:
    aliases:
      - a:n:i
      - npmi
      - etc
    cmds:
      -  docker-compose exec api sh -c 'npm install {{.CLI_ARGS}'
```
