### ISSUE TITLE
cannot use rm command to delete a file

### ISSUE THREAD

**Issue by a0v0** [go-task/task#892]
- Task version: latest
- Operating System: Windows 11

### Example Taskfile showing the issue

```yaml
gen:docker:
    desc: Generate Dockerfile
    cmds:
      - rm -f Dockerfile
```
Error I am getting:

```
"rm": executable file not found in $PATH     
task: Failed to run task "gen:api": exit status 127
```

Though If i use `rm -f Dockerfile` in vscode terminal everything works fine. Only not able to use it with Taskfile

**Comment by JohnHardy** [comment]
I have the same use-case as you, there is a little conversation about this ongoing in discord at the moment about the ways this can be worked around / resolved:

* https://discord.com/channels/974121106208354339/1028716829981544559/1028716829981544559 
* https://discord.com/channels/974121106208354339/974121514184085555/1029020102655483975

**Comment by a0v0** [comment]
seems will take quite a time

**Comment by a0v0** [comment]
For now this did the work

```
gen:docker:
    desc: Generate Dockerfile
    cmds:
      - '{{if eq .OS "Windows_NT"}}powershell{{end}} rm -r Dockerfile'

```

**Comment by JohnHardy** [comment]
That's a great workaround for now👍

```
vars:
  # Workaround
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'

  clean:
    cmds:
      - '{{.SHELL}} rm -r ./builds/'
      - '{{.SHELL}} rm -r ./packs/'
```

Tagging https://github.com/go-task/task/issues/197
