### ISSUE TITLE
Add VCS_ROOT variable

### ISSUE THREAD

**Issue by sdemura** [go-task/task#898]
On top of ROOT_DIR and TASKFILE_DIR being immensely useful, it would be awesome to have a built in VCS_ROOT variable.

I can usually get around this in my taskfiles by defining my own:
```
vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel
```

But this falls apart if trying to use that variable in includes. For example:
```
includes:
  foo: '{{.GIT_ROOT}}/.tasks/bar.yml`

vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel
```

**Comment by andreynering** [comment]
Hi @sdemura,

I don't plan do implement this at the moment. I think `ROOT_DIR` is what most people need, and people can always create a custom variable (as your example).

**Comment by dstadelm** [comment]
Actually I think that would be low hanging fruit but there is a workaround for those who need this feature

What I've done (using git)

```yaml
vars:
  VCS_ROOT:
    sh: git rev-parse --show-toplevel
  DOC_ROOT: '{{.VCS_ROOT}}/doc'
```
