### ISSUE TITLE
An `output:` cmd

### ISSUE THREAD

**Issue by max-sixty** [go-task/task#900]
I frequently want to update the user with the status of the task, from the taskfile. For example:

```yaml
    cmds:
      ...
      - cmd: echo "✅ Success! setup-dev complete! 😇🚀"
        silent: true
```

There's some awkwardness with using `echo` though:
- It's inline with the other output, which is sometimes quite verbose. We can use emojis to try and highlight it. But ideally it would be a different color, or some other semantic difference.
- We always want `silent: true`

So the question / proposal is to instead have something similar to [output syntax](https://taskfile.dev/usage/#output-syntax) but as a task:

```yaml
    cmds:
      ...
      - output: ✅ Success! setup-dev complete! 😇🚀
```

...which would then print in a different color, or with a prefix, or whatever ideas people have.

Clearly this isn't a problem that makes `task` otherwise unusable — it would be a small QoL feature. But I wanted to raise regardless, in the case that others agree it would be positive.

Thanks as ever!
