### ISSUE TITLE
Enable globstar by default

### ISSUE THREAD

**Issue by pd93** [go-task/task#909]
As per the discussions on [Discord](https://discord.com/channels/974121106208354339/1035164287695589457) and in #908, we should consider enabling `shopt -s globstar` by default for shell commands. This will enable functionality like this:

```yaml
tasks:
  default:
    cmds:
      - echo ./**
```

without having to do this:

```yaml
tasks:
  default:
    cmds:
      - shopt -s globstar && echo ./**
```
