### ISSUE TITLE
Tilde evaluation mangles output

### ISSUE THREAD

**Issue by masaeedu** [go-task/task#91]
I'm trying to use recursive invocation of `task` to define some platform specific utility tasks like so

```yml
dl:
  cmds:
  - |
    powershell - <<'EOF'
      $ProgressPreference='SilentlyContinue'
      iwr -UseBasicParsing {{.URL}} -OutFile {{.TARGET}}
    EOF

tempdir:
  cmds:
  - |
    powershell - <<'EOF'
      [io.path]::GetTempFileName() | % { rm $_; mkdir $_ -ea 0 > $null; echo $_ }
    EOF

tempfile:
  cmds:
  - |
    powershell -Command 'echo "$([io.path]::GetTempFileName()).{{.EXT}}"'
  vars:
    EXT: tmp

extract:
  cmds:
  - |
    powershell -Command "Expand-Archive {{.TARGET}} -DestinationPath {{.DESTINATION}}"

dl_archive:
  cmds:
  - |
    set -e
    export URL="{{.URL}}"
    export TARGET=`EXT=zip task -s tempfile`
    export DESTINATION=`task -s tempdir`

    echo $URL
    echo $TARGET
    echo $DESTINATION

    task dl && task extract
```

I can see from the `echo` output that the variables are being set correctly, and the first recursive invocation (`task dl`) works, but things go south from there:

```
PS > task -s dl_archive URL=https://github.com/go-task/task/releases/download/v1.4.4/task_windows_amd64.zip
https://github.com/go-task/task/releases/download/v1.4.4/task_windows_amd64.zip
C:\Users\asaeeduddin\AppData\Local\Temp\tmp4ECF.tmp.zip
C:\Users\asaeeduddin\AppData\Local\Temp\tmp520B.tmp
powershell - <<'EOF'
  $ProgressPreference='SilentlyContinue'
  iwr -UseBasicParsing https://github.com/go-task/task/releases/download/v1.4.4/task_windows_amd64.zip -OutFile C:\Users\asaeeduddin\AppData\Local\Temp\tmp4ECF.tmp.zip
EOF

"-DestinationPath C:\Users\asaeeduddin\AppData\Local\Temp\tmp520B.tmpl\Temp\tmp4ECF.tmp.zip

-DestinationPath : The term '-DestinationPath' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:2
+  -DestinationPath C:\Users\asaeeduddin\AppData\Local\Temp\tmp520B.tmp
+  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-DestinationPath:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

task: Failed to run task "extract": exit status 1
task: Failed to run task "dl_archive": exit status 1
```

The command for the second recursive task invocation has not been interpolated properly, and has somehow been mangled into:

```
"-DestinationPath C:\Users\asaeeduddin\AppData\Local\Temp\tmp520B.tmpl\Temp\tmp4ECF.tmp.zip
```

I haven't been able to distill this into a simpler repro unfortunately.
