### ISSUE TITLE
Support user input at runtime

### ISSUE THREAD

**Issue by ebr** [go-task/task#92]
It would be great to pause and wait for user input, for subsequent use in the script:

```
test:
  cmds:
    - read name
    - echo "hi ${name}"
```

```
$ task test 
read name
task: Failed to run task "test": exit status 127
```

I also tried moving the `read` command to Taskvars, but still no luck. I suspect this is because execution of go-task does not allocate a TTY? Is there any way to do this currently?

**Comment by andreynering** [comment]
I never thought about this possibility, and I don't know why it doesn't work. I'll think about it.

**Comment by andreynering** [comment]
This currently possible as follows:

```yml
read:
  cmds:
    - |
      echo "Type value of FOO:"
      read FOO;
      echo "You said: ${FOO}";
  silent: true
```

And for allowing `read` in variables, I don't know if that makes sense. One can pass parameters to tasks using environment variables or the special syntax:

```sh
task foo BAR=baz
```

**Comment by tommyknows** [comment]
Hi, 
Stumbled upon this issue while trying to work out the exact same thing.
I want to ask the user for input for a few variables that are going to be used throughout the Taskfile.

Obviously, as you noted, something like this panics:
```yaml
vars:
  MY_VAR:
    sh: read
```

At the same time, I can't use this:
```yaml
env:
  MY_VAR: "{{.MY_VAR}}"
tasks:
  get-vars:
    cmds:
      - {{if not .MY_VAR}}read MY_VAR; export MY_VAR{{end}}
  show-vars:
    cmds:
      - echo {{.MY_VAR}}
```

Is there any way to export variables from the `cmds` to the taskfile?
