### ISSUE TITLE
`&` at the end of `cmd` doesn't run the command in background

### ISSUE THREAD

**Issue by Mussabaheen** [go-task/task#928]
> Thanks for your bug report!
>
> Before submitting this issue, please make sure the same problem was
> not already reported by someone else.
>
> Please describe the bug you're facing. Consider pasting example

when using `&` at the end of a command doesn't make it a background task.

> Taskfiles showing how to reproduce the problem.
 ```
 run:
    cmds:
      - task: build
      - echo "Running server..."
      -  ./{{.APP_NAME}} > out.txt &
      - echo "Server running..."
```

- Task version:
latest
- Operating System: macOS and Linux

**Comment by Mussabaheen** [comment]
ok so, I found the problem basically the task ends before the server can start may be we should add the support for `disown` in this

**Comment by pd93** [comment]
This appears to be an issue with [mvdan/sh](https://github.com/mvdan/sh). See replication steps below:

`service.sh`:

```bash
#!/bin/bash
for i in {1..5}; do sleep 1s && echo "$i"; done
```

`> bash -c "./service.sh > out.txt &"`:

Creates the file `out.txt` and appends the numbers 1..5 as a background process

`> gosh -c "./service.sh > out.txt &"`:

Does nothing :/

**Comment by Mussabaheen** [comment]
I think the problem is that the parent task ends and it forces the child process created using `&` to end as well.

**Comment by pd93** [comment]
I don't think this is to do with Task. As I said, this problem also exists when executing your command directly with `gosh` (the interpreter used by Task).

Also, if we write a Taskfile like this:

```yaml
version: '3'

tasks:
  sleep-5s-bg:
    cmds:
      - sleep 5s &

  ps:
    cmds:
      - ps
```

and then run

`> task sleep-5s-bg`
`> task ps`

```shell
task: [ps] ps
    PID TTY          TIME CMD
...
 416575 pts/1    00:00:00 task
 416583 pts/1    00:00:00 sleep
```

You can see that the task executes `sleep` in the background and exits, but if you check `ps`, the sleep process is still running (i.e. Task is not killing the process when it exits).

This appears to only be a problem with combining [redirection](https://www.gnu.org/software/bash/manual/html_node/Redirections.html) (`> somefile`) with [job control](https://www.gnu.org/software/bash/manual/html_node/Job-Control.html) (`&`)

**Comment by Chi-teck** [comment]
I was able to reproduce the issue without using redirection.

This task does start dolphin by some reason.
```yaml
dolphin:
  cmds:
   - 'dolphin . &'
```

The workaround is appending some dummy command to the main one.
```yaml
dolphin:
  cmds:
   - 'dolphin . &'
   -  ':'
```

**Comment by toddpi314** [comment]
Ran into this starting up an express process in the background. 
Adding something like `sleep 10` after the `&` works, but it seems to be relative to the OS-level process setup time.

**Comment by pyrho** [comment]
I also ran into this issue, but none of the workarounds seem to work _consistently_ (adding a dummy `:` task, or adding a `sleep 5`).

**Comment by matzeeable** [comment]
I was just about to create my first task and stumbled across this problem. I have now actually invested 2 hours to find the error, as I never thought that it was due to the task file or the interpreter. Unfortunately, the workaround with `:` does not work for me. I just checked the docs, but could not find something like this: Is there an option to disable `mvdan/sh` and use `/bin/bash` or `/bin/sh` directly?

**Comment by q0rban** [comment]
Would it be possible to `defer` a call to `wait` with the pid of the command? Trying to think of how you would get the pid to the wait command though.

**Comment by q0rban** [comment]
> I couldn't get the pid without using a sub-subshell (not sure why?)

Okay, I discovered the reason we can't get the pid: mvdan/sh#221

> This library is written in Go, so it can't spawn sub-processes.

**Comment by cr1cr1** [comment]
It works if you run in bg both the subcommand and the subshell, followed by sleep:

```bash
task test_bg
task: [test_bg] bash -c 'sleep 10 & echo "PID $!"'& sleep 1
[test_bg] PID 4213

ps -fp 4213
UID     PID    PPID  TTY        STIME COMMAND
cri    4213       1 cons1    12:33:17 /usr/bin/sleep
```

See https://github.com/go-task/task/issues/162

**Comment by leobenkel** [comment]
what is the solution to spawn a disowned process ?

**Comment by JonZeolla** [comment]
@leobenkel this worked for me:

```yaml
  start-ollama:
    cmds:
      - bash -c 'nohup ollama serve >/dev/null 2>&1 &'
```

**Comment by Andrew99xx** [comment]
I think this needs to be implemented as feature

**Comment by q0rban** [comment]
I wonder if now that https://github.com/mvdan/sh/issues/221 is in, if this is easier now.

**Comment by rrrodzilla** [comment]
> [@leobenkel](https://github.com/leobenkel) this worked for me:
> 
>   start-ollama:
>     cmds:
>       - bash -c 'nohup ollama serve >/dev/null 2>&1 &'

omfg @JonZeolla  thank you. I've been busting my head on this all day.

**Comment by trulede** [comment]
@rrrodzilla @Mussabaheen @q0rban you might want to try with the latest version of Task. Its I little hard to pin down the exact failing scenario from this issue, but I found this worked:

```yaml
version: '3'

tasks:
  run:
    cmds:
      - echo "Running server..."
      - tail -f Taskfile.yml > out.txt &
      - echo "Server running..."
      - sleep 1
      - ps
```

For me, the tail command remains running.
