### ISSUE TITLE
Command-level dir (cd)

### ISSUE THREAD

**Issue by MadL1me** [go-task/task#941]
# Problem

Very often, when we use __Taskfile__, we want to call commands from some directive, required for this commands.

# Current Solution

Currently, we can do this this way:

```yaml
tasks:
  create:
    cmds:
      - |
        cd "dir1/dir2/dir2
        pwd
        echo "Hello"
        cd ..
        echo "Hello"
        pwd
```

The problem with this solution, is that we can't use cmd properties (like __*ignore_errors*__ or *vars*) for each command separately. We run whole job as one command, so we can't use other feature for taskfile.

The second way we can do this, is by making multiple task commands: 

```yaml
tasks:
  create:
    cmds:
      - task: hello1
      - task: hello2
   
  hello1:
    dir: 'dir1/dir2/dir2'
    cmds:
      - echo "Hello" && pwd
  
  hello2:
    dir: 'dir1/dir2'
    cmds:
      - echo "Hello" && pwd
```

But this is not ideal way either, because we create new sub-commands only to call them from one another "parent" command, so we making redurant task commands we can avoid creating.

# Proposal

We can implement *command-level* __dir__ definition, like ignore_errors for command:

```yaml
tasks:
  foo:
    cmds:
      - cmd: echo "Hello from" && pwd
        dir: "directory"
```  

There is a different ways to do it thought. We can save current __dir__ if we assume command are sequential, as we do __cd__. 
There is some questions about the api. First of all, its about __dir__ relativeness. We can make:
- dir always relative to the parent (task __dir__) (1)
- dir relative to last command dir (2)

(1) Example:
```yaml
# dir: src
tasks:
  foo:
    cmds:
      - cmd: echo "Hello from" && pwd # Hello from src/directory
        dir: "directory"
      - cmd: echo "Hello from" && pwd # Hello from src/directory2
        dir: "directory2" 
```  
        
(2) Example:
```yaml
# dir: src
tasks:
  foo:
    cmds:
      - cmd: echo "Hello from" && pwd # Hello from src/directory
        dir: "directory"
      - cmd: echo "Hello from" && pwd # Hello from src/directory/directory2
        dir: "directory2" 
```  

And then: 
- dir as _cmd_ child (3)
- dir as _cmds_ child (4)

(3) Example:
```yaml
# dir: src
tasks:
  foo:
    cmds:
      - cmd: echo "Hello from" && pwd # Hello from src/directory
        dir: "directory"
      - cmd: echo "Hello from" && pwd # Hello from src/directory/directory2
        dir: "directory2" 
``` 

(4) Example:
```yaml
# dir: src
tasks:
  foo:
    cmds:
      - dir: "directory"
      - echo "Hello from" && pwd # Hello from src/directory
      - dir: "directory2" 
      - echo "Hello from" && pwd # Hello from src/directory/directory2
``` 

So as you can see, there is 4 variations: we need to chose (1) or (2), with (3) or (4).

I think best combination down there is "(2) + (4), because it seems to me, that in many use cases you want to run multiple commands in one dir change. Also, in this variation, __dir__ would be semantically familiar to console __cd__ command: 

```yaml
# dir: src
tasks:
  foo:
    cmds:
      - dir: "directory"
      - echo "Hello 1" 
      - echo "Hello 2" 
      - echo "Hello 3" 
      - dir: ".."
      - echo "Hello 4" 
      - echo "Hello 5" 
``` 

We can name this "cd" as command, to make this more semantically correct: 

```yaml
# dir: src
tasks:
  foo:
    cmds:
      - cd: "directory"
      - echo "Hello 1" 
      - echo "Hello 2" 
      - echo "Hello 3" 
      - cd: ".."
      - echo "Hello 4" 
      - echo "Hello 5" 
``` 

In case of having task-level dir, with __cd__ we will start moving relative to task-level dir:

```yaml
# dir: src
tasks:
  foo:
    dir: "directory1"
    cmds:
      - cd: "someDir2" # directory1/someDir2 
      - echo "Hello 1"
      - echo "Hello 2" 
      - echo "Hello 3" 
      - cd: "someDir3" # directory1/someDir2/someDir3
      - echo "Hello 4"
      - echo "Hello 5" 
```

**Comment by MadL1me** [comment]
I would be happy to implement this myself, if you need help, after we establish the api

**Comment by sdemura** [comment]
```
# dir: src
tasks:
  foo:
    dir: "directory1"
    cmds:
      - cd: "someDir2" # directory1/someDir2 
      - echo "Hello 1"
      - echo "Hello 2" 
      - echo "Hello 3" 
      - cd: "someDir3" # directory1/someDir2/someDir3
      - echo "Hello 4"
      - echo "Hello 5" 
  ```

For sake of discussion, that feels a little icky. Bash variables defined in in commands don't propagate down, so why should cd? 

The first example seems far more idiomatic Task, imo.
```
# dir: src
tasks:
  foo:
    cmds:
      - cmd: echo "Hello from" && pwd # Hello from src/directory
        dir: "directory"
      - cmd: echo "Hello from" && pwd # Hello from src/directory2
        dir: "directory2" 
```

**Comment by pd93** [comment]
See previous discussion: https://github.com/go-task/task/discussions/940#discussioncomment-4205672

I tend to agree with @sdemura. As I've previously said, I think having a `dir` keyword at `cmd` level makes sense, but propagating directories over multiple commands seems to go against the way that most task runners (and Task) work and could be confusing.

To accomplish what you want to do without having to specify the directory for every command, I would be inclined to either:
- Make a separate script in `bash` or `sh` and call it from Task.
- Create multiple tasks which you can give different directories and then combine them as I illustrated in the discussion linked above.

**Comment by trulede** [comment]
Some things are so easy to do with shell commands ... I would just do this:

```
# dir: src
tasks:
  foo:
    cmds:
      - cmd: cd directory; echo "Hello from" && pwd # Hello from src/directory
      - cmd: cd directory2; echo "Hello from" && pwd # Hello from src/directory2
```
