### ISSUE TITLE
Show variables in terminal

### ISSUE THREAD

**Issue by arielsrv** [go-task/task#944]
I would like the terminal shows internal variables

This 

```shell
user@imac pets-api % task build
task: [build] mkdir -p $BUILD_FOLDER/..
task: [build] go build -v $SOURCE_FOLDER/$ENTRY_POINT.go
```

For it

```shell
user@imac pets-api % task build
task: [build] mkdir -p build/..
task: [build] go build -v build/main.go
```

**Comment by pd93** [comment]
Task already resolves _internal_ variables and environment variables. i.e. Ones that use the templating engine. For example:

```yaml
version: "3"

vars:
  FOO: foo

env:
  BAR: bar

tasks:
  default:
    cmds:
      - echo {{.FOO}}
      - echo {{.BAR}}
      - echo $BAR
```

```
❯ task
task: [default] echo foo
foo
task: [default] echo bar
bar
task: [default] echo $BAR
bar
```

What you're asking is for task to resolve _shell_ variables and I don't think this is a good idea. The purpose of that line of output is to display the command that was run in the shell. Resolving the variables could be misleading and make things difficult to debug.

If you want the output to print the _resolved_ variables, why not just use templating instead? e.g.

```yaml
tasks:
  default:
    cmds:
      - echo "go build -v {{.SOURCE_FOLDER}}/{{.ENTRY_POINT}}.go"
```
