### ISSUE TITLE
Use sources as variable

### ISSUE THREAD

**Issue by NVolcz** [go-task/task#948]
For a task, is the list of files specified in sources available for commands so it can be used as a variable?
I have a script that that I would like to pass the list of sources available to:
```
version: '3'

tasks:
  test:
    cmds:
      - echo {{.sources}}
      - ./test/shellcheck.sh {{.sources}}
    sources:
      - *.sh
```
Alternatively if it was possible to use vars for sources:
```
version: '3'

tasks:
  test:
    cmds:
      - echo {{.sources}}
      - ./test/shellcheck.sh {{.sources}}
    vars:
      SCRIPTS:
        sh: find . -iname '*.sh' -not -path './cygwin/*' | xargs echo
    sources:
      - {{.BASH_SCRIPTS}}
```

**Comment by Cheekie25** [comment]
Hello.

Task seems great but I'm very surprised this is not yet possible for a tool that aims to replace GNU Make.
So many of my Make recipes use $^ variable and I don't see any way to migrate to Task before this is implemented.

Do you have any workaround when you need to pass the whole list of sources to a command of a rule at the same time (and not one by one which I saw is possible with the for keyword) ?

Thanks

**Comment by LuckyJosh** [comment]
I was just wandering about this (just like @Cheekie25, I often use/used the (cryptic) shorthand notation in make).
I guess it would make sense to add the variable `TASK_SOURCES` but I thought of a "workaround" that seems 
actually  less error prone[1]:

Defining the source and generated files as variables first
and then add the variables in `sources/generates` respectivly.

My minimal working example:
```yaml 

version: '3'
tasks:
  default:
    vars:
      src_file_a: file-a.txt
      src_file_b: file-b.txt
      src_file_c: file-c.txt
      gen_file_ab: "file-ab.txt"
      gen_file_bc: "file-bc.txt"

    sources:
      - "{{.src_file_a}}"
      - "{{.src_file_b}}"
      - "{{.src_file_c}}"
    generates:
      - "{{.gen_file_ab}}"
      - "{{.gen_file_bc}}"
    method: timestamp

    cmds:
      - cat {{.src_file_a}} {{.src_file_b}} >> {{.gen_file_ab}}
      - cat {{.src_file_b}} {{.src_file_c}} >> {{.gen_file_bc}}
```
[1] The variable `TASK_SOURCE` would probably just be an array, so the position of the source files in the list would matter. This workaround names each source so it is not dependent on the order.
The best of both worlds would be if you could define `sources/generates` as associative arrays, i.e. the `sources/generates` 
would define variables without the extra step through `vars`.
