### ISSUE TITLE
`include` interpolation doesn't support dynamic variables

### ISSUE THREAD

**Issue by fatmcgav-depop** [go-task/task#951]
Follow on from #942 

We have a use-case where we would like to use "dynamic" variables as part of the path for an included Taskfile. 

e.g.
```yaml
---
version: "3"

vars:
  MODULE_NAME:
    sh: jq -r .module_name cookiecutter.json

includes:
  # Support running tasks defined in the generated template module
  generated:
    taskfile: './cookiecutter-temp/{{ .MODULE_NAME }}'
    dir: './cookiecutter-temp/{{ .MODULE_NAME }}'
    optional: true
```

Note that #943 added support for "static" variables, this ask is specifically for `dynamic` variable support. 
Also see https://github.com/go-task/task/issues/942#issuecomment-1341300056

**Comment by pd93** [comment]
Thanks for creating the issue. Since the current docs only mention using static variables, I'm going to categorise this as an enhancement and we can add something to the docs to explicitly say this is supported once its resolved.

**Comment by iwittkau** [comment]
This could also improve the security aspects of #1317:

```yaml
vars:
  GITHOST_TOKEN:
    sh: security find-generic-password -s "Git host token" -w

includes:
  compose: https://git:{{.GITHOST_TOKEN}}@example.com/shared/taskfiles.git//Tasks.yaml?ref=main
```

On macOS you can store tokens in the Keychain using the `security` CLI.  
On GNOME-based Linux distributions you can do something similar with `secret-tool`.

**Comment by stephenpope** [comment]
This would fully unblock usage of remote tasks for general usage. We provide a list of useful tasks in each repo that devs can use to speed up their day-to-dayt workflows.. 

Having to ask devs to do `TOKEN=$(gh auth token) task` when just running a task really breaks the simple workflow which `task` is really useful for.

Even if the variable was scoped so it was less dynamic/global and only needed to be evaluated in the current block would be fine e.g.

```yaml
includes:
  enviroment:
    vars:
      GH_TOKEN:
        sh: gh auth token
    taskfile: https://{{.GH_TOKEN}}@raw.githubusercontent.com/repo/path/to/task.yml
    aliases: ["env"]
```
