### ISSUE TITLE
Allow customising 'init'

### ISSUE THREAD

**Issue by 4x0v7** [go-task/task#952]
Almost every time I init a new Taskfile, I set `default:` to `task -a`
I find it quite useful when starting a project for the default task to be listing all tasks

Perhaps I slightly modified default Taskfile could be:

```yaml
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default: task -a

  hello:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
```

As a bonus, it hints new users to the fact that tasks can be defined in the shortened form (without `cmds:`)
