### ISSUE TITLE
'interval' directive in Taskfile.yaml has no effect

### ISSUE THREAD

**Issue by radcool** [go-task/task#969]
- Task version: 3.19.0 (or manual build from commit [c7d9efe](https://github.com/go-task/task/commit/c7d9efebf9e6ef6d94f3efeae12f7d8d6e53e65b))
- Operating System: Linux

Given this `Taskfile.yaml`:
````
# https://taskfile.dev

version: '3'

interval: 500ms

tasks:
  default:
    sources:
    - test_watch.txt
    cmds:
      - ksuid > test_watch.txt
````

Running:
````
task -w -I 500ms
````
executes the task every 500ms, as expected. However, running:
````
task -w
````
runs it every *5 seconds*, ignoring the `interval: 500ms` directive.

I think that this section:
````
if e.Interval != "" {
	watchIntervalString = e.Interval
} else if e.Taskfile.Interval != "" {
	watchIntervalString = e.Taskfile.Interval
}
````
in [watch.go](https://github.com/go-task/task/blob/e4158dc5e465a28bfeaa927ce9adb1cf352ea4aa/watch.go) will always match on the first "if" statement since `e.Interval` will always be set to **5s** by default if not specified on the commandline due to:
````
pflag.StringVarP(&interval, "interval", "I", "5s", "interval to watch for changes")
````
in [task.go](https://github.com/go-task/task/blob/e4158dc5e465a28bfeaa927ce9adb1cf352ea4aa/cmd/task/task.go).
