### ISSUE TITLE
bash select in task

### ISSUE THREAD

**Issue by sherlant** [go-task/task#986]
Hello,
i try to add a select bash in a task, and this doesn't work.
version of task : 3.17.0

Taskfile:
```yaml
---
version: '3'

tasks:
  test:
    interactive: true
    cmds:
      - |
        select build in build/*; do
          echo $build
          break
        done
```

result :
```bash
$ task test        
task: [test] select build in build/*; do
  echo $build
  break
done

build/toto
```

result when launched by bash :
```bash
$ select build in build/*; do
          echo $build
          break
        done
1) build/toto   2) build/vault  
?# 2
build/vault
```

thx

**Comment by pd93** [comment]
Looks like this might be a bug in the shell interpretter that we're using. If I run the following:

```shell
gosh -c 'select build in build/*; do
  echo $build
  break
done'
# build/toto
```

I get the same result as you. In the meantime, you can use the following workaround by invoking `bash` directly:

```yml
---
version: '3'

tasks:
  test:
    interactive: true
    cmds:
      - |
        bash -c 'select build in build/*; do
          echo $build
          break
        done'

```
