### ISSUE TITLE
Filepath without extension template function (`trimExt`)

### ISSUE THREAD

**Issue by W4RH4WK** [go-task/task#988]
I am not super familiar with Go's template functions, but while there is `base`, `dir`, `ext`, and `trimSuffix`, I am unable to strip an unknown file extension from a path.

To be more concrete: I am using a variable containing a filepath as parameter for a task.
The task is a conversion step that yields a file with the same filepath, except for the extension.

Here, the input would be `assets/my_texture.png` and the output would be `assets/my_texture.dds`.
I'd except a template function along the lines of `trimExt`, but so far I haven't found anything like it.

```yaml
  texture:albedo:
    cmds:
      - tools/texconv.exe -nologo -f BC7_UNORM -srgbi -y assets/{{.NAME}}
    sources:
      - assets/{{.NAME}}
    generates:
      - assets/{{.NAME | trimExt}}.dds
```
