### ISSUE TITLE
Fingerprinting for task that calls internal tasks

### ISSUE THREAD

**Issue by timbmg** [go-task/task#992]
- Task version: 3.20.0 
- Operating System: macos 12.6.1
```yml
version: '3'

tasks:

  gen-files:
    cmds:
      - echo "bar" > ./bar.beta.txt
      - echo "baz" > ./baz.beta.txt
    generates:
      - ./bar.beta.txt
      - ./baz.beta.txt

  alpha:
    cmds:
      - task: beta
        vars:
          FOO: bar
      - task: beta
        vars:
          FOO: baz
  
  beta:
    internal: true
    cmds:
      - cat "{{.FOO}}.beta.txt"
    sources:
      - ./{{.FOO}}.beta.txt

  gamma:
    deps: [alpha]
    cmds:
      - cat ./bar.beta.txt

  beta-external:
    cmds:
      - cat "bar.beta.txt"
      - cat "baz.beta.txt"
    sources:
      - ./bar.beta.txt
      - ./baz.beta.txt

  gamma-external:
    deps: [beta-external]
    cmds:
      - cat ./bar.beta.txt
```

I think the fingerprinting for subtasks is not working correctly. First, I generate some files (`task gen-files`). Next, when running `task gamma`, I would expect that `alpha` triggers running `beta` twice. However, when running it again, since the source of beta has not changed, it should not run the `beta` task, right? When running gamma-external, this fingerprinting works. However, when calling via `alpha` it does not.

**Comment by andreynering** [comment]
Hi @timbmg,

That happens because checksum is always saved in the same file: `.task/checksum/beta`, independent of the arguments.

What you should do is to add a `label:` attribute to make it different depending on the relevant arguments:

```yaml
beta:
  internal: true
  cmds:
    - cat "{{.FOO}}.beta.txt"
  sources:
    - './{{.FOO}}.beta.txt'
  label: beta-{{.FOO}}
```

You'll now notice you'll have different checksum files for each: `.task/checksum/beta-bar` and `.task/checksum/beta-bar`, and it'll work as you expect.
