### ISSUE TITLE
Vars don't get properly propagated with two levels of `included` nesting

### ISSUE THREAD

**Issue by gsantoro** [go-task/task#996]
Hello,
thanks for the amazing tool that Taskfile is. I have a bit of advanced use case, so bear with me.

I am facing an issue with the current setup:
- I have three Taskfiles: A, B, C
- A includes B and calls B:up
- B includes C and calls C:up
- C has a variable that I want to be overridable: `C_VARIABLE: '{{.C_VARIABLE | default "localhost"}}'`

this is the content of A.Taskfile.yml:

```yaml
version: '3'

includes:
  B: 
    taskfile: ./B.TaskFile.yml

tasks:
  up:
    cmds:
      - task: B:up
```

this is the content of B.Taskfile.yml:

```yaml
version: '3'

vars:
  B_VARIABLE: b

includes:
  C: 
    taskfile: ./C.TaskFile.yml
    vars:
      C_VARIABLE: "{{.B_VARIABLE}}"

tasks:
  up:
    cmds:
      - echo "B_VARIABLE {{.B_VARIABLE}}"
      - task: C:up
```

and this is the content of C.Taskfile.yml

```yaml
version: '3'

vars:
  C_VARIABLE: '{{.C_VARIABLE | default "localhost"}}'

tasks:
  up:
    cmds:
      - echo "C_VARIABLE {{.C_VARIABLE}}"
```

If I run the following command it behaves as expected. Meaning that when B:up calls C:up, it overrides the variable C_VARIABLE with the content of B_variable=b

```bash
➜ t -t B.Taskfile.yml up
task: [up] echo "B_VARIABLE b"
B_VARIABLE b
task: [C:up] echo "C_VARIABLE b"
C_VARIABLE b
```

if instead I run the same up task from A

```bash
➜ t -t A.Taskfile.yml up
task: [B:up] echo "B_VARIABLE b"
B_VARIABLE b
task: [B:C:up] echo "C_VARIABLE localhost"
C_VARIABLE localhost
```

the C_VARIABLE is not overridden but it uses the default value instead.

This is not what I was expecting

```bash
➜ t -t A.Taskfile.yml up
task: [B:up] echo "B_VARIABLE b"
B_VARIABLE b
task: [B:C:up] echo "C_VARIABLE b"
C_VARIABLE b
```

Am I doing something wrong? Do I have wrong expectations or is this a bug?

- Task version: v3.20.0
- Operating System: MacOS arm64 architecture

**Comment by acls** [comment]
I have the same issue, which I reduced to the following three task files:

```yml
# ./Taskfile.yml
version: '3'

includes:
  foo:
    taskfile: ./foo/Taskfile.yml



# ./foo/Taskfile.yml
version: '3'

includes:
  bar:
    vars:
      N: '3'
      PREFIX: 'prefix-'
    taskfile: ./Taskfile.include.yml



# ./foo/Taskfile.include.yml
version: '3'

vars:
  N: '{{.N | default "1"}}'

env:
  N_ENV: '{{.N}}'

tasks:
  baz:
    cmds:
      - echo N {{.N}}
      - echo PREFIX {{.PREFIX}}

```

When running from the top level,  the specified variables aren't used:

```
$> task foo:bar:baz
task: [foo:bar:baz] echo N 1
N 1
task: [foo:bar:baz] echo PREFIX 
PREFIX
```

But when running from the second level, they are used:

```
$> cd foo
$> task bar:baz
task: [bar:baz] echo N 3
N 3
task: [bar:baz] echo PREFIX prefix-
PREFIX prefix-
```
