### ISSUE TITLE
dotenv not working at task level

### ISSUE THREAD

**Issue by DjinNO** [go-task/task#997]
dotenv file **.env**:
```VAR=test```

Taskfile.yml:
```
version: "3"
silent: true
tasks:
  test:
    dotenv: [".env"]
    cmds:
    - echo $VAR
```

Result:
`nothing`

With global dotenv works good

Task version: master
Operating System: Arch Linux

**Comment by pd93** [comment]
I am not able to reproduce this. Also running Arch on master and your example works fine for me:

```
├── .env
└── Taskfile.yml
```

```ini
# .env
VAR=test
```

```yaml
# Taskfile.yml
version: "3"
silent: true
tasks:
  test:
    dotenv: [".env"]
    cmds:
    - echo $VAR
```

Outputs:

```
❯ task test                       
test
```

Are you sure your copy of `master` is up to date? I would recommend installing a release and trying again.

**Comment by DjinNO** [comment]
Interesting. I have go-task-bin-3.20.0-1, tried reinstalling, didn't help. At the same time, in a container with ubuntu - it works

**Comment by endorama** [comment]
Me and a colleague stumbled upon this issue today. Using the provided example we have been able to **reproduce** this issue on task `v3.15.2` and `v3.20.0` but **not** on `v3.21.0`.

**Comment by pd93** [comment]
@endorama That's interesting.. I don't believe there were any changes in `v3.21.0` that would effect this, so I'm not sure why you'd be able to repro in `v3.20.0`, but not latest. Are you able to provide a reproduceable sample for `v3.20.0`?

Otherwise, I might close this until someone is able to repro again since it isn't currently effecting anyone in the latest release.

**Comment by pd93** [comment]
Closing this for now. If anyone is able to repro this, please feel free to leave a comment and we can reopen.

**Comment by MattiasMartens** [comment]
I have this exact issue on arm64, taskfile version 3.30.1.

local taskfile:

```
# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  default:
    dotenv: [".env"]
    cmds:
      - echo {{.MYVAR}}
```

Output: "foo". But comment out the top-level dotenv clause and "foo" does not print.

**Comment by c-s-w** [comment]
@pd93 I'm testing it with these files: https://gist.github.com/c-s-w/7ae4e3c9b87e3e3735b05fd2a6aea542

**Comment by pd93** [comment]
@andreynering What's the expected behaviour here? The docs do not mention that you should be able to use variables defined in a `dotenv` via the templating engine (`{{.MYENVVAR}}`). Instead, it says you should use `$MYENVVAR` which is what the OP was reporting - This still works for me.

However, if I set `dotenv` at a global level, the variable will be in the templating engine. This seems to be rather inconsistent and confusing.

**Comment by c-s-w** [comment]
@pd93 Having the variables available via the templating engine allows the usage of `requires`, which doesn't work with .e.g. `$MYVAR`.

**Comment by MattiasMartens** [comment]
Here is a slightly more verbose repro of what I am now understanding is four different cases.
```
version: 3

# Un-comment the lines below for file-wide .env
# dotenv:
#   - .env

tasks:
  default:
    dotenv:
      # Task-specific .env
      - .env
    cmds:
      - "echo By template: {{.MY_VAR}}"
      - "echo By env: $MY_VAR"
 ```

Output on my machine (arm64, 3.32.0):
```
By template:
By env: foo
```

Output with file-wide .env un-commented:
```
By template: foo
By env: foo
```

**Comment by tuwid** [comment]
Same issue on mac on version Task version: v3.35.1 
with a `.env.development` and `.env.staging` 
with similar contexts 

```
CLUSTER_NAME=staging
AWS_ACCOUNT_ID=xxxxxxxx
AWS_REGION=eu-north-1
```

```
version: '3'

silent: false
dotenv: ["./.env.{{.ENV}}"]

tasks:
  set-context:
    desc: "Set the Kubernetes context based on the environment"
    cmds:
      - echo For env {{.ENV}} we got $AWS_REGION $CLUSTER_NAME $AWS_ACCOUNT_ID
      - "kubectl config use-context arn:aws:eks:$AWS_REGION:$AWS_ACCOUNT_ID:cluster/$CLUSTER_NAME"
      - "echo 'Using context: arn:aws:eks:$AWS_REGION:$AWS_ACCOUNT_ID:cluster/$CLUSTER_NAME for environment: {{.ENV}}'"

```

getting the following
```
> task -v ENV=staging set-context
task: "set-context" started
task: [set-context] echo For env staging we got $AWS_REGION $CLUSTER_NAME $AWS_ACCOUNT_ID
For env staging we got
```
